/**
 * @fileOverview High-depth verbatim synthesis for Personal Year 4/7 and Zodiac Intersections.
 */
export const INTERSECTION_SYNTHESIS: Record<string, string> = {
  "4_harm": "Personal Year 4's systematic foundation-building meets the Harm year's concealed erosion: while Rahu drives you to build structures, the Harm year's hidden adversary dynamics are quietly undermining what you build before it can be completed. This is the configuration where workaholism is most dangerous — the compulsive Year 4 building impulse creating elaborate structures that the Harm year's concealed forces are simultaneously destabilizing. The specific risk: trusted colleagues or business partners with hidden agendas at precisely the moment when you are most invested in collaborative structural projects. Year 4 foundation work should be primarily solo or with your most thoroughly verified relationships during this year. Avoid large structural financial commitments that depend on others' reliability.",
  "4_clash": "Personal Year 4's discipline meets the Direct Clash's maximum elemental friction: while you are trying to establish stability, the environment is forcing rapid transformation. This creates an atmosphere of high pressure where structural resistance leads to fracture. The key is proactive adaptation: instead of defending outdated structures, use the Year 4 discipline to build new ones better suited to the changed landscape. Forcing Year 4 stability in a Clash year is like building on a fault line; success requires acknowledging the seismic activity and engineering accordingly.",
  "4_destruction": "Personal Year 4's structural focus meets the Destruction year's rupture: established systems and institutional arrangements are revealed as fundamentally incompatible with your new foundational requirements. This is a year of necessary clearing where structural redundancy is eliminated. What feels like loss is actually the clearing of ground so that Year 4's genuine building can proceed without being obstructed by the weight of what is already broken. Focus on system simplification and reinforcing what is most essential.",
  "4_ben-ming": "Personal Year 4's foundation-building meets the Ben Ming Nian's amplification of native traits: your characteristic patterns are magnified, making the Year 4 structural work both more powerful and more prone to distortion. If you are naturally industrious, this combination can lead to extreme productivity; if you are prone to rigidity, it can produce structural inertia. The year requires deliberate self-correction and the use of red protective elements to balance the intensified resonance.",
  "4_neutral": "Personal Year 4's foundation-building discipline proceeds in a Neutral year — neither amplified by alliance support nor undermined by conflict energy. This allows Year 4's structural work to proceed primarily through your own effort and discernment rather than through environmental support or resistance. The advantage: your Year 4 foundations this year reflect your genuine capacity rather than exceptional circumstances in either direction. The discipline you build during a neutral Year 4 is the most authentic measure of your actual developmental state and the most reliable foundation for the years that follow.",
  "7_harm": "Personal Year 7's introspection and refinement meets the Harm year's hidden adversaries: while Ketu pulls you inward toward silence and self-knowledge, the Harm year's concealed dynamics may attempt to undermine your social or professional standing while your attention is withdrawn. This creates a specific risk of professional isolation or the erosion of reputation through others' hidden agendas. Maintain robust documentation and verification systems even while pursuing your inner retreat. Do not allow your meditative focus to become total negligence of external safeguards.",
  "7_clash": "Personal Year 7's requirement for stillness meets the Direct Clash's forced movement: the soul's call for retreat is challenged by the world's demand for action. This is the cycle's most spiritually stressful intersection — an inner lake being buffeted by hurricane winds. The solution is the 'Hermit in the Marketplace': maintaining your inner lake's stillness even while being forced to move and respond to external disruption. Forcing external results in this configuration leads to exhaustion; success comes through moving with the clash without surrendering your inner silence.",
  "7_destruction": "Personal Year 7's refinement meets the Destruction year's rupture: the cutting away of the inessential is accelerated by external failure or the collapse of structures you were already questioning. This is a powerful, if painful, clearing of spiritual baggage. What falls during a Year 7/Destruction year was likely the greatest obstacle to your genuine inner knowing. Accept the rupture as a clarifying force that reveals the indestructible beneath the temporary.",
  "7_ben-ming": "Personal Year 7's introspection meets the Ben Ming Nian's amplification: your intuitive and psychic faculties are at their cycle peak, but so is your vulnerability to emotional overwhelm. The self-review of the 12-year cycle coincides with the self-review of the 9-year cycle, creating a profound 'identity audit.' Use the red protective measures to ground the high-voltage spiritual energy being activated. This is a rare window for genuine metamorphosis, provided you maintain a grounding routine.",
  "7_alliance": "Personal Year 7's spiritual depth is supported by an Alliance year: mentors and teachers appear with precisely the wisdom your Year 7 study requires. Retreats and spiritual communities provide exceptional nourishment, and your inner work receives collective affirmation. This is the optimal window for advanced study, psychological integration, and the cultivation of specialized knowledge that will define your authority in Year 8.",
  "7_neutral": "Personal Year 7's introspection and refinement meets the environment's current frequency in a Neutral year — neither supported nor obstructed by environmental forces. Success is a pure reflection of your genuine effort and developmental state. This allows for an undistorted encounter with your own inner reality, free from the distractions of exceptional external favor or challenge. The insights gained in a neutral Year 7 are your most authentic and stable inner resources."
};
