// src/lib/new-astrology/aquarius.ts

export const aquarius = {
  "Aquarius/Rat": {
    description: `“Onward and upward” should be the motto of this completely idealistic and experimental character. Aquarius the individualist married to the aggressive and charming Rat character affords us a being of immense personal magnetism and derring-do. On the one hand, the Aquarian born Rat seeks to accumulate material possessions. On the other, this person cares less about tangibles than I do about Eskimo fertility rites. He’s a bohemian with a bourgeois streak. A hippie sophisticate. He wants to be free and unencumbered. But he cannot stand to be alone. He wants to ride a black stallion on the beach in the wind, but he’s not mad about horses. A contradictory nature full of excellent intentions, the Aquarius/Rat somersaults through life, stopping only to exhibit the fruits of his immense talent here and there as he tumbles along.

Aquarians want to be different. They have vision and are tolerant. Rats have lots of personal appeal and long to wield power. Of course, in this duo, the Rat is neutralized by the altruistic Aquarian, who tells him to get his mitts off the power switch until such time as man will love man and no wars will be fought. The effect is startling. Real force emanates from within this person. Watch him try to take over the reins in a given situation. He can strike a deal, even a slightly shady deal. Then, suddenly out of nowhere, he may back down. Under the influence of Aquarius, the Rat’s cupidity deflates. Good-bye, trickery. Hello, freedom and love.

As the Aquarius/Rat thinks he wants to see around corners toward a better world, he will frequently become involved in spiritual searches for truth and equilibrium. The Aquarian is first a thinker. The Rat, too, is cerebral. Both signs are borderline neurotic. So, rather than looking for stability on travelled paths, they are attracted by the cosmic, the extra-sensory and supernatural methods of mind control. Aquarian Rats are forever taking courses in ESP, EST, Hatha, Mudra and Zen. They want to depart from the humdrum, avoid having to live a bourgeois routine existence. They long to find peace through spiritual enlightenment.

No matter the degree of clear thinking attained by this character, he or she is nonetheless always a Rat. Rats sooner or later cleave to the middle-class life. Rats are acquisitive and driven by a thirst for power. Aquarius may force the Rat to a clear mountain stream but he cannot make him drink. This essential disagreement causes further loss of security for our native. He makes rash moves and grows moody and distant. Emotions are not his favorite province, so how can he say he’s sorry? How can he adapt to the workaday world with its stringent and inhuman demands? Why is life so stiflingly boring?

Well, as this offbeat subject will be the first to tell you, “The answer is blowing in the wind.” Other people never live up to the Aquarius/Rat’s high standards. He is often disappointed by the failure of group efforts and hurt by the selfishness of intimates. Yet he watches even himself fall short of the mark. Then he is really desolate and confused. Where did he go wrong? Although “application of derrière to seat of chair” is one of my stock bits of advice, I dare advance it here more particularly. Aquarian Rats must learn to slow down, to feel their way instead of trying to “think” their way, to sit still long enough for the lead to set between those ears. They mustn’t dabble in mind-altering substances or freaky movements unless there is a concrete and earthbound reason to do so. Sailing off into space without a seatbelt is a very dangerous business.`,
    love: `As the Aquarius/Rat mixes fancy with charisma and neurosis with nervousness, you can imagine the troubled waters of emotion at work here. This person will be both attractive and vulnerable. The attractiveness shows. The vulnerability hides. His or her emotional needs will be best met by coupling with solid citizen types who are willing to tether their Aquarius/Rat firmly to earth. Of course, square peg drudges hardly excite this rabid metaphysician. It’s a dilemma.

If you love an Aquarius/Rat, don’t fence him or her in. But do tie your loved one down. I know this sounds contradictory, but think of Aquarius/Rats as morning glories. For morning glories to thrive, their feet must be firmly planted in the shade and their heads constantly exposed to the brightest sunlight. That’s how you have to treat your Aquarius/Rat. Let him or her feel as free as a hot air balloon, but keep the lines drawn taut and don’t take any nonsense. Your Aquarius/Rat will love you all the more for caring.`,
    compatibilities: `Oxen like to be with you. They are inspired by your rapacity and swift dispatch. Choose an Ox from Gemini (born May 21 - June 20 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), Libra (born September 23 - October 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), or Sagittarius (born November 22 - December 21 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) if you want to be sure of compatibility. The same western astrological signs lend you their Dragons on a silver platter. This time it’s you doing the admiring. Aries (born March 21 - April 19 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), Libra (born September 23 - October 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Sagittarius (born November 22 - December 21 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) bestow Monkeys on your lifestyle. They too bring you joy—and good advice. Don’t be led down the aisle by Taurus/Horses (born April 20 - May 20 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026), Leo/Horses (born July 23 - August 22 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) or Scorpio/Horses (born October 23 - November 21 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026), and get out of the way of Leo/Rabbits (born July 23 - August 22 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and Scorpio/Roosters (born October 23 - November 21 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029).`,
    homeAndFamily: `Although erratic when flying loose in the world, the Aquarius/Rat somehow does not display this eccentricity at home. Here, in the privacy of his abode, the Aquarius/Rat decorates tastefully, simply and with a spareness that hints at his or her penchant for Oriental thought. Too much material wealth makes the Aquarius/Rat nervous. If he is flashy or showy, it will be in his dress. At home, things will be kept simple and elegant.

This person is a remarkably good parent. You see, kids have a tethering influence on Aquarius/Rats. For that security the Aquarius/Rat parent is grateful, and in his turn stretches the parental role as far as it will go. He or she gets very involved with kids’ activities and feelings. The Aquarius/Rat discusses everything in greatest detail with his children, and imparts a world view of broad scope to his kids long before they are old enough to leave the nest.

The Aquarius/Rat child is, most of all, interesting. He may be slightly daredevil and will surely be drawn to the unusual. Again, the role of intimates (in this case parents) is to focus the terrestrial aspect of this subject. Never allow his or her attraction to the otherworldly to overcome the attachment felt for family. The talented and intelligent Aquarian Rat child must be hitched to a solid post but never hobbled.`,
    profession: `Of course, as for all Aquarians who struggle with the emotional side of life, work is health. If this sometimes cranky and irrepressible Rat subject is able to fix his or her attention on one professional passion, authentically ingenious projects can be realized. The Rat/Aquarian has such a unique perception and is so close to madness and extraterrestrial thought at all times that if these qualities are applied to earthly pursuits, the result is unbeatable. But watch that freaky side. This person can go bonkers in a wink if allowed too much leeway.

The Aquarius/Rat is more of a creative than a bossy type. He or she will be glad to try to run an office or shop. But the result will never be spectacular—competent, but not fabulous. The same goes for employment. This person’s strength is in his or her individuality and personal approach to problems of at least cinemascopic proportion. Punching time clocks just won’t do.

Some possible professions for the Aquarian Rat are: politician, artist, journalist, genius, designer, musician, film maker, hair stylist, actor, writer – and other creative pursuits too numerous to mention.`,
  },
  "Aquarius/Ox": {
    description: `A strong-minded and loving bully, the Aquarian born in Ox years is destined to a lifetime of slog and struggle uphill against his own unwillingness to conform. Oxen, as you know, always think that the road to happiness is through retirement from the hub of popular activity. Oxen want to be left alone in the country somewhere. Aquarius is more affable, outgoing, flexible, less tundra-like than the Ox. Their marriage can be a rocky one.

Basically, the Ox does not agree with his flighty Aquarian side. And the Aquarian? Well, he sort of doesn’t give a damn. Aquarius is the out-of-thisworld fantasy person whose spirit is almost as monumentally elastic as the Ox’s is rigid. The cool-headed Aquarian who never gets lost in trivial emotion is here suddenly confronted by his own tendency toward bigotry and stick-in-the-mudism. The result? Grumpy moods. Suppressed anger. Bitterness. Feigned apathy about almost everything and everybody. The image, then, is one of a fiercely productive person who appears not to give two hoots. His “like it or lump it” attitude lives very close to the feisty surface. This person cannot hide his latent belligerence.

What saves our character from stewing for too long in his own acrid juice is a razor sharp sense of humor. The Aquarius/Ox is a great storyteller, a stunning performer, and a laugh-a-minute companion. He benefits from an excellent memory for detail, and can grip your attention for hours with just one anecdote about his gay cousin from Australia who rides a unicycle. Ordinarily boring stories become jewel-studded tales from the Arabian Nights. When the eloquence of the Ox meets with Aquarius’s originality of thought, the result is Scheherazade.

Too, the Aquarian profits from being brought to earth by his Ox side. Oxen of no matter what persuasion know how to apply the work ethic. Aquarians long to be free and roam about dreaming up the undreamed-of. This person will never stop working until he or she drops. Work, for the Aquarius/Ox, no matter how thankless or routine, represents salvation. Work keeps one from flying too close to the sun.

The Aquarius/Ox doesn’t bother with social approval. He cares not for judgments coming from people he considers beneath him anyway. This character blazes his own trails in life by slow and sure methods, keeping the zippy Aquarian mind operating at full tilt and never letting up on the elbow grease for a second. Of course, people become inflamed at this creature’s brutish determination. But as they are almost never as dutiful and laborious as he, they must concede Aquarius/Ox the victor, hands down all around. Despite the Aquarius/Ox’s uncanny talent for work, he or she will surprise you by exhibiting a silly side. The Aquarius/Ox loves to have fun. He or she will cook and decorate and stay up trimming trees till four A.M. for the sake of communal joy. The self-sacrificing person he or she is, although it doesn’t carry over much into the world at large, will animate many a soirée and fill many little hearts with delight. The Aquarius/Ox’s imagination for surprises and goodies is enormous, and it is generous, too.`,
    love: `The Aquarius/Ox has a difficult private life. First of all, being Aquarian, he needs mental stimulation and finds himself quickly bored. Then the homeloving Ox side rears his head and says, “I want to settle down. I’m tired of being so insecure. Too bad about your need for intellectual clearheadedness. I want a home.” So they get a home, and maybe a child or two. But before you know it, all they can think of is that old mental stimulation again. The ups and downs of Aquarian Ox love life are epic. And the Aquarius/Ox doesn’t seem to mind. He is often able to live without much sex and to drown whatever sorrows or regrets he might have in work. If you are attracted to one of these extraordinary people, you will first have to realize that no matter how much you count, you will never take first place over either Aquarius/Ox’s children or his work. This person is addicted to the love of his family and is a workaholic as well. Sex and affection, tenderness and romance, are secondary to this person’s wellbeing. He or she will have affairs and be a competent lover. But they are not sentimental. They hate syrupy sweet billings and cooings and don’t have time for Valentines.`,
    compatibilities: `You’re a fool for Snakes. Their very style drives you mad with desire. Stick to Aries (born March 21 - April 19 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025), Gemini (born May 21 - June 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025), Libra (born September 23 - October 22 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) or Sagittarius/Snakes (born November 22 - December 21 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025). They are the most likely to stick to you. Gemini, Libra and Sagittarius/Roosters also attract you. You are drawn to their frank, open ways. Taurus/Dragons (born April 20 - May 20 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), Leo/Dragons (born July 23 - August 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Scorpio/Dragons (born October 23 - November 21 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) exact too much from your patience. Taurus/Tigers (born April 20 - May 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Leo/Tigers (born July 23 - August 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) don’t turn you on. Leo/Goats (born July 23 - August 22 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) and Scorpio/Goats (born October 23 - November 21 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) are not good either. And whatever you do, don’t take up with a Scorpio/Monkey (born October 23 - November 21 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) or a Taurus/Horse (born April 20 - May 20 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026).`,
    homeAndFamily: `The Aquarius/Ox’s home is very comfortably furnished. As they are traditionalists and love art, they will own quality objects and care much for the welfare of such items. They are not showy people, so the furnishings will be sober yet welcoming. There may be some gold pieces sewn into the green velvet armchair, so mind the lumps under your seat. Aquarius/Oxen are shrewd with money, and know how to keep what they earn. Between sweat of brow and merchant’s hand spans an eternity. Their money motto: “You’ve got it. Keep it.”

Aquarian Oxen make fabulous parents. They know how to allow for fancy and imagination in their kids, and yet they always have the best-mannered and the nicest children around. First of all, Aquarius/Oxen crave the company of kids, and little kids love them right back. They know how to teach children as well as to delight them. They spoil them, but they also make them obey. It’s miraculous the way Aquarius/Oxen can handle children. Not having kids would be a terrible shame for this loving, caring, sweet, parental type.

The Aquarius/Ox child will seem dreamy and idealistic. He or she will of course be loquacious, but only when telling a story. Otherwise he may not be terribly communicative. This tyke should be offered lots of security. He doesn’t take well to brusque changes in personnel at home. He will love spectacle and enjoy being taken to shows and plays. Don’t try to force him or her into groups. These people don’t function well in hierarchies.`,
    profession: `Aquarius/Oxen are very manual people. They can fix anything, build anything, and are inventive to boot. As this subject is also expedient and practical, there are few labors that he or she cannot undertake and achieve at. The Aquarius/Ox is thorough and conscientious. He or she will be attracted by high salaries and able to adhere to routines. These folks are socially conscious, too. They often end up working for the betterment of mankind in international organizations and foundations.

The Aquarius/Ox boss will not be contradicted. You work for him. He calls the shots. You get your pay and keep your comments to yourself. If she likes you, you’ve got a friend (and a banker) for life. But if she doesn’t, pack it in. You’ll never penetrate her iron curtain of disdain. As an employee this person will perform duties with exceptional ability and perseverance. He or she will be slow. And he or she will basically not give a damn what you think. But the work will get done—and it will be done better than if you did it yourself. If you have hired such a person, give him his head about his work. You cannot tell him how to do anything. He always knows best.

Some jobs for this behemoth of diligence are: farmer, boat-builder, cabinetmaker, nursery school teacher, physical therapist, TV repairman, professor, counselor, activist.`,
  },
  "Aquarius/Tiger": {
    description: `A more speculative Tiger than we already know is personified by this clearthinking, zigzag personality. Aquarius lends Tiger vision. Tiger congeals some of the free-floating mental jelly that characterizes Aquarians. This combination sign provides the world with many innovators. Aquarius/Tigers go crazy for modern methods. They are purveyors of all sorts of new ways of accomplishing old tasks. They are into everything from the dernier cri computer setup for pet training to obscure relaxation techniques developed by astronauts in zero gravity.

Aquarius/Tigers like to stay young. For this reason they don’t often get married early and settle down to raise a family. Not that the Aquarius/Tiger is especially promiscuous, but his sexual adventures do smack of the miscellaneous. He is erratic, and even addicted to change for its own sake. Count on the Aquarian Tiger to switch domiciles whenever he feels the urge. Take him or her with you on holiday to the Alps and the next day you may wake up and find him/her gone. Aquarius/Tigers hate to be confined— even for fun! Spontaneity is the Aquarius/Tiger’s favorite play-thing. This person lives to be impetuous. He or she spends far too much energy dashing hither and thither in too many directions at once. Many times the Aquarius/Tiger is disappointed by the results. He’s exhausted. Yet where is the booty? Who took the achievement? This person must learn to slow down and consider the alternatives to racing ahead of time. He ought to think more and dash less. Otherwise, he will spend much of his life in a state of confused jitters.

As Aquarius/Tigers are not terribly balanced people, they are sometimes influenced by oddball cult-mongers. They may take up with a crazy religious group or involve themselves in shady activities for the thrill of it. What is urgently important for natives of this sign is that they cultivate wiser souls than themselves, who will guide them and know how to put their genius to best use. Of course, the Aquarian Tiger sometimes rebels against wisdom or measure. He or she itches to try something entirely different, to leap from the beaten path onto the moving sidewalk of excitement. Staying straight and acting sane is the cross this person must learn to bear with dignity. Otherwise, he or she cannot produce for the world as it truly exists. Freakiness doesn’t pay.

In all of this brouhaha, the Aquarian born Tiger manages to maintain very high ideals. He or she believes, nay, knows what is right and best for the people he or she loves and cares about. This Tiger longs to help his family and to comfort his friends. But often, the practical wherewithal just isn’t there. Aquarius/Tigers are not what you would call selfish, exactly. They often entertain complex schemes and carry them out most effectively. But those same schemes tend to take all the Aquarius/Tiger’s time and since something has to give, both family and friends are given short shrift. There is a certain genius in Aquarius/Tigers. This genius must be pampered and ministered to. The Aquarian Tiger is his own best publicity agent. If you aren’t sure whether or not the next Aquarius/Tiger person you meet is marvelous, ask him. He will be the first to assure you that he is.`,
    love: `Long-lasting passion is difficult to maintain – even for this zany character. You may stand by and watch him or her go up in flames over a lover for a matter of months or even years. So long as there are elements of honeymoon left in the relationship, Aquarius/Tigers take delight in romance. But don’t ask them to tie the knot. Don’t even mention marriage. Steer clear of jewelry store windows and take back streets to avoid churches, temples and justices of the peace. It is rare, but if he or she does marry, the average shelf life of wedlock for this heady person is about three weeks.

If you love one of these dashing creatures, you must not expect anything eternal from your relationship. Aquarius/Tigers are mavericks. Their pattern is to step in puddle after puddle just to test the water. Your heart will be fast broken should you put your hopes where your head should be. Be a good audience and never ask them to settle down. They cannot tolerate being caged in.`,
    compatibilities: `Dogs and you see eye to eye. There’s complicity between you, and real sympathy on a human level. Try picking a Dog person from out the signs of Aries (born March 21 - April 19 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030), Gemini (born May 21 - June 20 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030), Libra (born September 23 - October 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) or Sagittarius (born November 22 - December 21 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030). Horses, too, understand you. They won’t stand by you as faithfully as Dogs but they may give you better advice. Try Horses from Gemini (born May 21 - June 20 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026), Libra (born September 23 - October 22 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) and Sagittarius (born November 22 - December 21 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). Shun Taurus/Rabbits (born April 20 - May 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and Leo/Rabbits (born July 23 - August 22 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), Virgo/Oxen (born August 23 - September 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) and Scorpio/Oxen (born October 23 - November 21 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), Taurus/Goats (born April 20 - May 20 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) and Scorpio/Goats (born October 23 - November 21 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027)—and run when you meet a Taurus/Snake (born April 20 - May 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025). Your intuitions collide with disastrous results.`,
    homeAndFamily: `The Aquarius/Tiger will have a home. The fact that these people tend to like motion for its own sake doesn’t mean they don’t want a place of their own. The decor here will be simple and comfortable enough, but there will probably not be any studied refinement about the place. A medieval Spanish chest may be open to display the latest laser beam music player. Or a fancy modern kitchen may cook everything by robot while Aquarius/Tiger sits reading Hegel in his favorite gadget armchair with the built-in bar. As for clothes, I’d guess sober and classical, with very occasional flights of fancy. The Aquarius/Tiger parent is not terrifically patient with the tumult of children. This person, if he ever had any, might treat his children as equals. He or she will expect the kids to live up to his standards rather than the opposite. No goo-goo and gaga baby talk for these people. They respect their children as adults. Unfortunately, not all kids want to be treated like grownups when they are only three years old.

The Aquarius/Tiger child is impressive. He or she will behave in a very clear-cut manner. There is no need for subterfuge when you know flat out what you want. This kid is interested in everything new. Electronics and science, modern literature and new ways of riding a bike will capture his attention. No matter how you raise this child, you should try to show him the value of wisdom, and the wisdom of taking advice from people more experienced than himself. He or she will always buck the system. But sometimes the results are very interesting.`,
    profession: `Inventive in the extreme, and gifted with a certain genius for seeing through walls, the Aquarius/Tiger can be well employed in jobs requiring a different view of old methods. No matter what this person attempts, he or she will bring to it a sense of innovation and exaggerated free-thinking. Once their madcap ideas are toned down for actual use and application, they can be smashing. Give this character an office or laboratory of her own and let her experiment till the cows come home. Money? Never heard of it. This boss will be scatty, unpredictable… and annoyingly changeable. He likes acclaim and will react well to flattery. As an employee this person will prove brilliant as an idea person. But nine to five? I’m not so sure. Perhaps the happiest Aquarius/Tigers are those who work on their own, applying their genius and modern notions to creating artistry.

Some occupations for Aquarius/Tigers are: philosopher, writer, inventor, hairdresser, fashion designer, politician, masseur, acupuncturist, psychiatrist, computer nerd.`,
  },
  "Aquarius/Rabbit": {
    description: `Here is your true to life, one hundred percent virgin intellectual. The Aquarian Cat accumulates knowledge for the fun of it. He is curious about everything, and makes indiscriminate studies of practically everyone he comes in contact with. It doesn’t matter whether the subject is edifying or not, Aquarius/Cat wants to know all about it in goriest detail. He’s fascinated by knowledge, facts, information, learning, erudition—and experience. He or she spends a lifetime leaping from book to book, from museum to museum, and from discipline to other discipline. It’s what Cats born in Aquarius like to do—know more.

They are not particularly competitive in their quest for savvy. The Aquarius/Cat really needs to know more just for the sheer pleasure of acquiring facts. However, he or she may have a smarty-pants side that with a little practice they would do well to eliminate altogether. It is lovely to know scads of interesting things, to recall passages from great poetry, even to be able to recite whole scenes from Shakespeare. But knowledge (especially someone else’s) can be very boring. Aquarius/Cats tend to pedantry. When they flaunt their information ad nauseam, Aquarius/Cats are patently annoying.

Better to apply this knowledge to practical exploits. The concrete use of understanding ought to be the goal. But here is where the Cat born Aquarius begins to falter. This person cannot decide what he or she wants most out of life. They are perpetually seeking outlets of acceptable magnitude and scope in order to apply their huge bank of smarts. The Aquarius/Cat suffers from a condition I like to call “too much choice.” He can do almost anything he wants, so he rarely knows what he wants.

This character operates a lot on hunches. He or she will possess a very specialized and refined vision of others. Aquarius/Cat can locate a specific flaw or a need in a person’s character through pure insight. Perhaps this gift comes from the Aquarius/Cat’s odd way of studying everyone he meets. But it seems spookier than that. Aquarius/Cat is the one who says, “Hey, you didn’t tell me that Jane was divorcing Frank.” Your mouth drops open. That was classified information. “How did you know?” you ask the Aquarian Cat, who waits, licking his chops. “Just guessing,” he’ll tell you with that Cheshire smile.

One striking thing about Aquarius/Cats is their apparently carefree nature. These people appear to be totally without hang-ups or complexes. They travel a lot, and they find human contact a breeze. Aquarius/Cats are always picking up new friends and enthusing over how perfectly delightful and terrifically interesting So-and-so is. They are awash in friends. Actually, however, they are quite conservative underneath and worry about their effect on others. The Aquarius/Cat is less of a free spirit than even he believes.

For a Cat subject, the Aquarian is adventurous. He does things normal Cats wouldn’t hear of. He takes up kooky hobbies like being a magician or learning to dance the flamenco. He doesn’t fancy danger, mind you. But the Aquarius/Cat is easily seduced by the arcane. If it’s unusual, he or she will try it at least once.

The most striking quality in this person is his or her desire to undertake projects or great designs. The Aquarius/Cat never imagines himor herself in some lowly, underling, hack job making a living and waiting to retire. No. Aquarius/Cats only imagine themselves as grand experimenters with challenges. The Aquarius/Cat is born to rise above the average herd. He doesn’t even bother to detest mediocrity. He doesn’t recognize it. He sees only lofty, cosmic images and leaves the petty, scruffy side of life to those of less elevated aspirations.`,
    love: `The Aquarius/Cat will want to live as half of a couple in marriage and have children. As she will be the emissary-to-the-world type, she will surely seek a calm and sensitive partner who comprehends her need for attention and comfort. These people eschew harshness in partners, as they don’t like conflict and avoid it at all costs. The Aquarius/Cat is looking for an intellectual equal who knows how to be entertained—a nice, open-minded person who will laugh at the Aquarius/Cat’s jokes.

Should you have chosen to love an Aquarius/Cat, I wish you well. This person will never bore you. Sometimes you may want to turn off the plethora of information spilling forth from their mouths. But mostly this person is steady and oh, so respectable. Aquarian Cats are fairly eventempered, too, and only ever-so-slightly neurotic.`,
    compatibilities: `You’ll be happiest with Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Libra (born September 23 - October 22) or Sagittarius (born November 22 - December 21) partners born in Pig years (1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031). Aries, Gemini, Libra and Sagittarius proffer their Goat subjects (born 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) for your pleasure too. You can also count heavily on Librans born in Dog years (1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030). Taurus/Rats (born April 20 - May 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), Leo/Rats (born July 23 - August 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) and Scorpio/Rats (born October 23 - November 21 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) are not tuned to your channel. Taurus/Roosters (born April 20 - May 20 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) and Leo/Roosters (born July 23 - August 22 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) never notice you, nor you them. And Scorpio/Horses (born October 23 - November 21 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) are on their own trip, which does not include you.`,
    homeAndFamily: `Home for this character will be a useful place in which to read comfortably and house his or her family intelligently. Most everything about the Aquarius/Cat’s exterior appearance is classical. The decor should be sane and refined, but not ornate or showy. Aquarius/Cat is a hearth sign. This person will be drawn to coziness and a propitious ambience for gabbing. The Aquarian born Cat is a tiny bit of a snob. Look for sheets made from the finest cottons, hand-embroidered pillow slips and elegant thirsty, big bath towels.

The Aquarius/Cat parent is slightly eccentric, in that he or she will want to start children learning a mite too early. As their goal is always to know more, they feel kids, too, should benefit from floods of knowledge. For this purpose they spend lots of time with their little ones, poring over alphabet books and guiding pudgy little patties through writing exercises. As for tenderness, the Aquarius/Cat is a tad distant with kids. Head in the clouds time.

This child Cat born in Aquarius gives no trouble to his or her folks as long as he or she is occupied twenty-four hours a day. This kid is bright. You have to feed his vacuum-cleaner mind with knowledge. The choice is vast. He may want to learn hieroglyphics or voodoo. You just stand by ready to pay for all the lessons, please. Watch this child’s diet, too. He or she may tend to snack while reading all those tomes.`,
    profession: `You cannot expect this grand person to be willing to work in a garage and like it. I can practically guarantee that the Aquarius/Cat’s job choice will involve the use of brains first and brawn second. Not that the Aquarius/Cat is precious or even that skittish about physical labor. But repeating the same gesture over and over dulls the vivified sensors of this person’s active mind. He wants challenge. And what’s more, Aquarian Cats want money—lots of it. They are close with their wealth and do not spend lavishly on others. Whatever job they have, they will often think of exchanging it for something even more enormous and complex.

The Aquarius/Cat is a natural authority but does not take his position seriously. He or she will not be the domineering type. After all, if you are so darned terrific in your own head, what is there left to prove? I am not suggesting that Cats born in Aquarius are haughty. But they emanate a certain superiority of affect. They won’t be bossy, but rather so there as to be unavoidably dominant. These people make fine employees for empires that need to hire kings and queens, governments looking for chancellors, universities head hunting a new president even for secret service agencies looking for top level spies.

Some jobs that might go well with the Aquarius/Cat nature are: head of state, prime minister, historian, psychoanalyst, politician, novelist, double agent, performer (stars only need apply), preacher, oil magnate, shipping magnate, professor, Trust Fund manager.`,
  },
  "Aquarius/Dragon": {
    description: `“I know” and “I preside” were walking across the bridge. One of them fell in. Who was left? That’s correct! No matter which way you look at this character, he’s right up there in the top twenty. You see, Aquarius/Dragon always takes over. Nothing can stop him, as he both knows and presides better than everybody else. There is a driving, steady quality to this personality. No matter what he or she does it will be accomplished with flourish and style. Aquarius/Dragons are know-it-alls, yet circumspect about showing it. They are family-oriented and respect social conventions. This person’s nature is both hard-nosed and unswayable. Once he has declared something, it’s impossible to change his mind. Aquarius/Dragons give off severity rays. They are powerhouses who will stoop to anything in order to conquer their prey.

Aquarius/Dragons want things done their way. They hate competition. They are capable of enormous hoaxes to get control over others. When the Aquarius/Dragon is looking for followers, anything goes: poetry, humor, logic, charisma, noise, favors, money and so on. Of course, what I call hoax may really be charm and diplomacy, but whatever you call it, this character uses liters of it daily. He really lays it on. He is polite and well spoken. He is proper and mannerly. Frankly, I think he’s a bit much. But you cannot take away the fact that the Aquarius/Dragon is enormously successful. This subject is an organizer. He is sharp-minded and goes straight to the point. Other, more fiery, self-involved Dragons sometimes miss the mark because of their uppity egos. The Dragon born Aquarius doesn’t have that problem. Aquarius lends clarity to the dynamic Dragon. This person is a cool customer. People are attracted to his air of protectiveness and his earnest desire to please.

Despite his gift for achieving easy glory, the Aquarius/Dragon remains a worrier, Inside an outer shell of self-confidence, this subject gnaws at himself about eventualities. He is a shade pessimistic about the future. He does not like to lose control. Therefore, whatever is out of his hands, as yet unformed and uncertain, troubles this mistrustful character. He may become frantic and even neurotic over events that seem to be shifting away from his sphere of influence.

In worldly matters this niggling dread can be useful. It keeps the Aquarian Dragon on his toes. But in the personal realm, where romance or sentiment is concerned, this feeling of impending loss panics the soul of our hero and threatens to develop into real hysteria. When emotions are at stake, Aquarius/Dragon loses his cool in seconds. He is vastly sentimental and not always secure about his place in the heart of the loved one. His apparent calm then serves as a cover for this bottomless pit feeling of possible loneliness that stalks the Aquarius/Dragon’s private hell. He cannot be alone.

The Aquarius/Dragon is never intentionally mean or petty. His pleasure is in serving as control center. He wants to be mother, boss, chief, owner, handler, manager and everything else. His aim is to protect and to serve. He or she wants to watch things grow, to improve or to allow to flower elements over which he or she has this famous control. As the Dragon born in Aquarius is not particularly creative himself, his objective in love or friendship or even in work situations is to implement improvement. Aquarius/Dragons don’t mind running the show from the wings.`,
    love: `In romantic situations, the Aquarius/Dragon is ruthless for power. He wants to get and keep a lover forever. Of course, his desire for emotional dominion has nothing to do with evil or wickedness. The Aquarius/Dragon wants to help a loved one to realize his or her own dreams. The happier the loved one is, the happier the Aquarius/Dragon will be. There is however a potential for blind jealousy. Should you be in the clutches of an Aquarius/Dragon, I suggest you never mention the name of another possible lover or mistress in his fragile, incendiary presence. These folks suffer immense anxiety about losing you. Don’t play with their delicate heartstrings. You will be afforded much mental leeway in your couple, but if you stray, your giant green Dragon will first fly into a rage, then melt into a puddle of sobbing green goop.`,
    compatibilities: `Aries/Tigers (born March 21 - April 19 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Gemini/Tigers (born May 21 - June 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) are fun for you. So are Libra/Rats (born September 23 - October 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) and Sagittarius/Rats (born November 22 - December 21 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032). Gemini (born May 21 - June 20), Libra (born September 23 - October 22) and Sagittarius (born November 22 - December 21) Monkeys (born 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) provide fascinating company and keep you on your toes. You might also be attracted to an Aries/Rooster (born March 21 - April 19 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029). The reciprocity quotient is low, but the game’s a treat. Taurus/Dogs (born April 20 - May 20 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030), Leo/Dogs (born July 23 - August 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Scorpio/Dogs (born October 23 - November 21 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) don’t approve of you. And Taurus/Monkeys (born April 20 - May 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) find you too much of a challenge.`,
    homeAndFamily: `The home of the Aquarius/Dragon tends to favor the practical over the aesthetic. Although this person is sensitive to beauty and reacts positively to artistic creation, the interior of his or her home will not necessarily indicate a search for loveliness. This is a practical person. The ovens will work well and the sinks will be ample.

As these persons are family-responsible in the extreme, they will probably not only assist parents and siblings but will also want to have children of their own. They are reliable parents, and even have a bit of a Pygmalion streak. In lieu of being creative themselves, they wish to shape and mold human beings as though they were dolls. They will care for their offspring, worry, fret, cook, sew, earn, comfort, protect, teach—you name it. They do it in spades!

Little Aquarius/Dragon kids also fret a lot. They are concerned about their own futures and worry that parents may not be well or happy. They take on lots of personal guilt for what happens at home, and must be reasoned with about assuming too much responsibility. They are good workers in school and very attached to their family unit’s strength. Sometimes as young adults they leave home for a while to test their iconoclastic secrets. But rebellion in the case of clear-thinking Aquarius/Dragons doesn’t go very far. Parents who have an Aquarian Dragon child should think twice about divorce. Schism is hard on this clinging nature’s nerves.`,
    profession: `Talented for organizing anything from office structures to personnel duties, the Aquarius born Dragon can function in most any job requiring leadership and equanimity. This person is clever and moderate with money, and knows how to increase his earnings through investment. He is usually a serious student and will begin achieving in the real world at a young age. The Aquarius/Dragon is a natural boss. People like and respect his opinions. He is very diplomatic, remember? He is peripatetic by nature, too, and can work comfortably at different rungs of the hierarchal ladder. The Aquarius/Dragon is destined for a long-term job as well as personal commitment. He will not be tempted to change careers on a whim.

Employment is no problem for this highly employable character. He’ll do anything on his way up—sweep, push a pencil, run elevators—but he won’t have to do any menial job for long, as his superior executive talents are recognized soon enough.

The Aquarius/Dragon may enjoy the following jobs: householder, stockbroker, banker, vice-president in charge of investments, company director, personnel manager, hospital administrator, librarian, writer.`,
  },
  "Aquarius/Snake": {
    description: `Sunshine incarnate, the Snake born in Aquarius has the double luck to be able to think clearly and to intuit things with rare finesse. This “up” person is firmly planted in reality, yet manages to keep smiling. He is a natural optimist and stubborn about maintaining that image. The Aquarius/Snake never bothers to want what he knows he cannot have. Nonetheless, he is avid for what he desires and can get. By this I mean that the Serpent born in Aquarius is chillingly lucid. He or she will attempt to seduce and conquer others for the sheer excitement of the dance. But before attempting to seduce or entice, enchant or charm, this person will know well ahead precisely what his chances are. Snakes born in Aquarius do not play losing games.

This sureness of self is, of course, part of the charm of the Snake/Aquarius. He is never without a slew of hot spots in his life, wherein occur the most exorbitant variety of events. He tries everything new; he leaps about from lair to lair like Santa Claus, bringing joy and good will to every life he touches. He is not really materially generous, nor is this person attracted to ownership of tangibles. The Aquarius/Snake doesn’t care about the concrete. In fact, he’d rather not own anything at all to take care of or dust. The plush and sensuous inner life of this utterly charismatic creature goes on without interference from the outside. His adventures and dreams, his travels and his plans, all take place inside the head. Aquarius/Snake is the day dreamer of the double zodiac.

If someone yells at this character because she is late and lazy and forgets dates and is careless about facts, Aquarius/Snake takes a mental trip. She just drifts off. While the scolder stands there railing away, Aquarius/Snake basks in the imaginary sunshine of a desert island—all alone without a soul for company or interference. To Aquarius/Snakes what is real is what they declare to be real. The rest is fantasy.

These clever people can work very hard at complicated and difficult jobs. They can also perform breakthrough experiments, and create beautiful art. The Aquarius/Snake’s imagination is fertile, and his sense for saying or doing the proper thing at the proper time (not for social advancement or out of respect for manners) is infallible.

The Aquarius/Snake is the kindest of Snakes. He or she will be charitable, and feel pity for the sorrows and pain of others. She is not so empathetic as she is sympathetic and willing to help in a practical way. Having a Snake born in Aquarius for a friend is enviable. They are caring and loving, generous with their time, and truly good-hearted. They not only take in strays but they keep them warm and fed for however long is necessary. Also, the lucid Aquarius/Snake knows how to let go gracefully. When he has fixed the wounded bird’s wing and he can fly alone, Aquarius/Snake takes him outside and lets him go. No rewards wanted. No thanks either, other than the pleasure Aquarius/Snake gets from performing a charitable act. This Snake is not looking for glory, applause, or recognition for heroism.

The Aquarian Snake is eccentric and slightly outrageous. He or she will definitely lean to irresponsibility and have a running battle with laziness. Too, all Snakes fabulate. This one may only fib to make someone feel better. But lies come easily to this slippery sort. Lies, and a temptation to truancy. Not that any great criminals were ever born under this sign combination. But the temptation to be marginal is very strong.`,
    love: `The Aquarius/Snake knows how to control his emotions with cold, logical reason. He is first a thinker, then a sensor and finally he allows himself to feel. Feeling is not of primary urgency and will not take precedence over reason. Moreover, with such a mosaical life structure, this person cannot help getting involved with more than one person at a time. He or she will be promiscuous but jealous of mates.

Should you love an Aquarius/Snake, let me give you some advice. Don’t ever tie him or her down. Don’t ask for account of time spent away from you. Give out no information at all on your own private affairs. Keep things mysterious and shrouded in secrecy. The Aquarius/Snake is a sucker for enigma. Keep him guessing and he’ll slide along after you forever. Don’t try to corral him. It’s fatal. He’ll move off like an eel, never to be heard from again.`,
    compatibilities: `Gemini (born May 21 - June 20), Libra (born September 23 - October 22) and Sagittarius (born November 22 - December 21) Oxen (born 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) make the safest partners for you. Wisdom and cool headedness being some of your highest priorities, you settle well with Oxen. Aries (born March 21 - April 19), Libra (born September 23 - October 22) and Sagittarius (born November 22 - December 21) Roosters (born 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) make you a bit more nervous and insecure, but they are fun and you do share a good giggle from time to time. Aries/Rabbits (born March 21 - April 19 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) can be stimulating to your cultural side. You won’t last long with Taurus/Pigs (born April 20 - May 20 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031), Leo/Pigs (born July 23 - August 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) or Scorpio/Pigs (born October 23 - November 21 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031). They’re onto your game and you to theirs. Boredom. Taurus/Tigers (born April 20 - May 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Leo/Monkeys (born July 23 - August 22 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) amuse you, but you prefer stargazing to earthly pursuits and so will ultimately clash.`,
    homeAndFamily: `The Aquarius/Snake doesn’t care much for interiors. He wants them to function and be attractive, but he doesn’t really want to have to check up on them and worry about whether they are despoiled or robbed. His is a cerebral, not a material, nature. What this character does care about is how comfortable the people he loves and cares for and protects are. He will go out of his way to house loved ones properly, building them a bathtub in their bedroom if they think it’s fun, tearing out walls to make room for another family member. The Aquarius/Snake dresses sexily and has garish tastes.

Family is everything to this humane and self-sacrificing person. She will look after aging parents and call on old people in homes. He will take his kids to the ice rink, the roller rink, the circus, and every other possible point of interest imaginable and wait patiently for them to finish playing. These people are exaggeratedly infatuated with their offspring but they still manage to make them behave. They dream about how wonderful it would be if their whole family were happy and healthy. Aquarian Snakes would do almost anything to see their dream come true.

The Aquarian Snake child is close to perfect. He or she will care intensely for family unity. He will be sunny and optimistic and cute. His talents for philosophy and metaphysics should be educated and encouraged. This person needs sound instruction and a secure home lifeotherwise he or she may really end up on that fictional desert island. They are over-imaginative and need lots of reassurance and love. Without it, they could be attracted to a life of petty crime or dissolution. The Aquarius/Snake’s backbone must be tenderly imposed from without by means of a code of behavior demanded by family and home life.`,
    profession: `Usually, Aquarian Snakes have brilliant imaginative and philosophical minds. They are adventurous and reasonable. They like to feel free within a structure. As they are curious about everything, and are both manual and artistic, there are few creative doors they cannot open.

Aquarius/Snakes would have to be persuaded to be the boss of any enterprise, big or small. These people prefer the wings to the stage. They like to manipulate others and to toy with their emotions and thoughts, but they are not authoritarian for the sake of wielding control. They will work well in groups if necessary, but they will show only the tiniest part of themselves to each group involved. Their greatest joy is in helping others. They work best on their own, at their own speed, while their imagination transports them to tropical parts unknown.

Some careers they might want to try are: social worker, undercover policeman, lawyer, diplomat, preacher, political activist, travel agent.`,
  },
  "Aquarius/Horse": {
    description: `This character is a visionary who loves to gallop. The Aquarius/Horse never sits still long enough to hear the end of a sentence. He’s always off and running to the next exciting project or adventure. The Aquarian born in Horse years is an impetuous soul whose agile mind wants to be first in line for everything new. From trendy clothes to modern music, from fad diets to far-out lifestyles, this person is a real ground-breaker. He or she is attracted to anything that smacks of innovation.

The Aquarius/Horse is not a particularly practical person. He is too impatient to deal with details, and far too taken with himself and his own ideas to listen to the needs of others. If there is a bandwagon to jump on, you can be sure the Aquarius/Horse will be the first aboard. This person’s visionary qualities are often dissipated through lack of discipline. The Aquarius/Horse has a million brilliant ideas. He or she can imagine schemes and dream up plans in the twinkling of an eye. The problem lies in application. This person doesn’t stick to anything long enough to see it through to success.

In this sign, impatience is the key word. The Aquarius/Horse cannot wait for results. If the going gets tough, this person gets going—to the next project. The Horse’s natural selfishness and the Aquarian’s tendency to neurosis combine to create a personality whose charm is in its spunk and whose Achilles’ heel is in follow-through.

Of course, the Aquarius/Horse is popular. He or she is cheerful and seems to be ever on the lookout for a good time. This person’s very presence at a gathering ensures its success. He is a natural leader and loves to take the initiative. If there is a task to be accomplished, the Aquarius/Horse will be the first to volunteer. But don’t count on him to be there when the job is done. The Aquarius/Horse is a starter, not a finisher.

The Aquarius/Horse is also very independent. He doesn’t take kindly to authority and is forever getting into trouble for insubordination. This person needs to be free to express his or her individuality, and will go to great lengths to avoid being hemmed in by rules or regulations. The Aquarius/Horse is a rebel with a cause—his own.`,
    love: `In love, the Aquarius/Horse is as fickle as the wind. This person falls in and out of love with alarming frequency. The Aquarius/Horse is attracted to the idea of love, but when it comes to the nitty-gritty of commitment, he or she often bolts. This person needs a partner who is as free-spirited as he is, someone who can keep up with his pace and not demand too much emotional security.

If you love an Aquarius/Horse, be prepared for a wild ride. Don’t try to tie this person down or expect constant devotion. The Aquarius/Horse needs space to roam and will resent any attempts to curb his freedom. Keep things light and exciting, and you might just keep his attention for a while.`,
    compatibilities: `You’ll find good company with Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Libra (born September 23 - October 22), or Sagittarius (born November 22 - December 21) Dogs (born 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030). They share your love of freedom and can match your pace. Gemini and Libra/Tigers also make great partners, as they’re as adventurous as you are. Avoid Taurus (born April 20 - May 20), Leo (born July 23 - August 22), or Scorpio (born October 23 - November 21) Rats (born 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), as their need for control clashes with your independent streak. Taurus and Scorpio/Oxen are too stubborn for you, and Leo/Monkeys are too self-absorbed to notice your sparkle.`,
    homeAndFamily: `The Aquarius/Horse’s home is a reflection of his eclectic tastes. You’ll find a mix of modern gadgets, trendy decor, and perhaps a few unfinished projects scattered about. This person loves to entertain and will often host lively gatherings, but don’t expect a spotless or overly organized home. The Aquarius/Horse is too busy chasing the next big idea to worry about housekeeping.

As a parent, the Aquarius/Horse is enthusiastic but inconsistent. He or she will inspire their children with grand ideas and exciting plans but may struggle with the day-to-day responsibilities of parenting. The Aquarius/Horse parent needs a partner who can provide structure and stability for the kids.

The Aquarius/Horse child is a bundle of energy and ideas. This kid will be constantly on the move, dreaming up new games and adventures. Parents should encourage this child’s creativity but also teach the value of perseverance and discipline, as the Aquarius/Horse child is prone to abandoning projects when they lose their initial appeal.`,
    profession: `The Aquarius/Horse excels in careers that allow for creativity and independence. This person is not suited for routine or repetitive tasks, as they quickly lose interest. Jobs that involve innovation, leadership, or breaking new ground are ideal. The Aquarius/Horse is a natural entrepreneur, always ready to launch the next big thing.

As a boss, the Aquarius/Horse is inspiring but impatient. He or she will motivate the team with big ideas but may get frustrated if results don’t come quickly. As an employee, this person is a whirlwind of energy and ideas but may struggle with authority and routine. The Aquarius/Horse is best suited for freelance or project-based work, where they can set their own pace and pursue their passions.

Some career possibilities include: entrepreneur, inventor, advertising executive, fashion designer, event planner, motivational speaker, travel writer.`,
  },
  "Aquarius/Goat": {
    description: `This is a highly sensitive and creative soul. The Aquarius/Goat combines the visionary qualities of Aquarius with the whimsical and artistic nature of the Goat. This person is a dreamer who loves to explore new ideas and create beauty in the world. However, the Aquarius/Goat can be impractical and absent-minded, often losing track of time and responsibilities while lost in their own world.

The Aquarius/Goat is a true eccentric, with a unique perspective that sets them apart from the crowd. This person is tolerant and charitable, always ready to lend a helping hand or support a worthy cause. However, their tendency toward neurosis and thoughtlessness can make them seem aloof or unreliable at times. The Goat’s dependence clashes with Aquarius’s need for independence, creating an internal tug-of-war that can lead to indecision or inconsistency.

Despite these quirks, the Aquarius/Goat is a deeply caring individual who wants to make a difference in the world. This person is often drawn to artistic or humanitarian pursuits, where they can express their creativity and compassion. The Aquarius/Goat is not particularly ambitious in a traditional sense but is driven by a desire to create something meaningful and lasting.`,
    love: `In love, the Aquarius/Goat is a romantic at heart but can be unpredictable. This person craves emotional connection but also needs freedom to explore their own interests. The Aquarius/Goat is attracted to partners who share their creative and idealistic nature but may struggle with commitment if they feel trapped or smothered.

If you love an Aquarius/Goat, be patient with their absent-mindedness and give them room to breathe. Encourage their creative pursuits and show appreciation for their unique perspective. A partner who can balance their need for independence with a steady emotional presence will win their heart.`,
    compatibilities: `You’ll find harmony with Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Libra (born September 23 - October 22), or Sagittarius (born November 22 - December 21) Pigs (born 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031), who share your love of beauty and creativity. Libra and Sagittarius/Rabbits also make great partners, as they appreciate your whimsical nature. Avoid Taurus (born April 20 - May 20), Leo (born July 23 - August 22), or Scorpio (born October 23 - November 21) Oxen (born 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), as their practical nature clashes with your dreamy disposition. Taurus/Rats (born April 20 - May 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) and Scorpio/Dogs (born October 23 - November 21 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) are too controlling for your free spirit, and Leo/Dragons (born July 23 - August 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) are too domineering to suit your sensitive soul.`,
    homeAndFamily: `The Aquarius/Goat’s home is a haven of creativity and comfort. Expect an eclectic mix of art, books, and quirky decor that reflects their unique personality. This person loves to create a warm and inviting atmosphere but may struggle with keeping things organized or tidy.

As a parent, the Aquarius/Goat is nurturing and imaginative, always ready to engage their children in creative play or artistic projects. However, they may need a more practical partner to handle the mundane aspects of parenting, as they can be forgetful or inconsistent.

The Aquarius/Goat child is a dreamer who needs encouragement to pursue their creative talents. This child may struggle with structure and discipline, so parents should provide gentle guidance while allowing room for self-expression. A supportive and loving home environment is essential for this sensitive soul to thrive.`,
    profession: `The Aquarius/Goat shines in careers that allow for creativity and self-expression. This person is not suited for rigid or highly structured environments, as they need freedom to explore their ideas. Artistic or humanitarian fields are ideal, as they allow the Aquarius/Goat to make a positive impact while indulging their creative side.

As a boss, the Aquarius/Goat is kind and inspiring but may lack the organizational skills needed to manage effectively. As an employee, this person is a creative force but may struggle with deadlines or routine tasks. Freelance or project-based work suits the Aquarius/Goat best, allowing them to work at their own pace and pursue their passions.

Some career possibilities include: artist, musician, writer, graphic designer, social worker, nonprofit organizer, teacher.`,
  },
  "Aquarius/Monkey": {
    description: `The Aquarius/Monkey is a clever and inventive soul with a knack for improvisation. This person combines the visionary qualities of Aquarius with the cunning and wit of the Monkey, creating a personality that is both brilliant and unpredictable. The Aquarius/Monkey is always thinking ahead, planning new schemes, and finding creative solutions to problems. However, their tendency toward self-involvement and deceit can make them seem untrustworthy at times.

This person is a natural entertainer, with a quick wit and a charming demeanor that draws people in. The Aquarius/Monkey loves to be the center of attention and will go to great lengths to keep the spotlight on them. Their originality and independence make them stand out, but their impish nature can sometimes lead to trouble, as they’re not above bending the truth to get what they want.

The Aquarius/Monkey is driven by a desire to innovate and explore new possibilities. This person is not content with the status quo and is always looking for ways to shake things up. However, their tendency to be self-absorbed can make it difficult for them to form deep, lasting connections with others.`,
    love: `In love, the Aquarius/Monkey is charming and flirtatious but can be hard to pin down. This person loves the thrill of the chase but may lose interest once the initial excitement fades. The Aquarius/Monkey needs a partner who is intellectually stimulating and can keep up with their quick wit and ever-changing interests.

If you love an Aquarius/Monkey, be prepared for a relationship full of surprises. Don’t take their occasional deceit too personally—it’s often just their way of keeping things interesting. Keep them engaged with new experiences and intellectual challenges, and you’ll have a loyal, if somewhat unpredictable, partner.`,
    compatibilities: `You’ll find great chemistry with Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Libra (born September 23 - October 22), or Sagittarius (born November 22 - December 21) Dragons (born 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), who share your love of adventure and innovation. Gemini and Libra/Rats also make exciting partners, as they can match your wit and cunning. Avoid Taurus (born April 20 - May 20), Leo (born July 23 - August 22), or Scorpio (born October 23 - November 21) Snakes (born 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025), as their intensity clashes with your playful nature. Taurus/Pigs (born April 20 - May 20 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) and Scorpio/Goats (born October 23 - November 21 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) are too serious for your lighthearted spirit, and Leo/Oxen (born July 23 - August 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) are too stubborn to keep up with your quick pace.`,
    homeAndFamily: `The Aquarius/Monkey’s home is a lively and eclectic space, filled with gadgets, books, and conversation pieces. This person loves to entertain and will often host gatherings that are full of laughter and lively debate. However, their home may be a bit chaotic, as they’re more focused on ideas than on keeping things tidy.

As a parent, the Aquarius/Monkey is fun and engaging but may struggle with consistency. This person will delight their children with creative games and stories but may need a more grounded partner to handle the practical side of parenting.

The Aquarius/Monkey child is a whirlwind of energy and ideas, always ready to try something new. This child needs parents who can encourage their creativity while teaching them the value of honesty and responsibility, as their impish nature can sometimes lead them astray.`,
    profession: `The Aquarius/Monkey thrives in careers that require quick thinking and creativity. This person is not suited for routine or repetitive tasks, as they need constant stimulation and the freedom to explore new ideas. Jobs that involve problem-solving, innovation, or performance are ideal for the Aquarius/Monkey.

As a boss, the Aquarius/Monkey is charismatic and inspiring but may be prone to micromanaging or changing plans on a whim. As an employee, this person is a valuable asset for their creativity and resourcefulness but may struggle with authority or sticking to a schedule. Freelance or entrepreneurial roles suit the Aquarius/Monkey best, allowing them to shine without constraints.

Some career possibilities include: comedian, actor, marketer, inventor, public relations specialist, startup founder, writer.`,
  },
  "Aquarius/Rooster": {
    description: `The Aquarius/Rooster is a vibrant and outspoken character, blending the visionary qualities of Aquarius with the bold and enthusiastic nature of the Rooster. This person is a natural performer, with a flair for the dramatic and a knack for drawing attention. The Aquarius/Rooster is confident, candid, and always ready to share their opinions, often with a touch of eccentricity that makes them unforgettable.

However, the Aquarius/Rooster’s tendency toward pedantry and bossiness can make them seem overbearing at times. This person loves to be in control and may struggle with compromise, as they’re convinced their way is the best. The Rooster’s conservatism clashes with Aquarius’s progressive ideals, creating a personality that is both forward-thinking and surprisingly traditional in some ways.

The Aquarius/Rooster is driven by a desire to make an impact, whether through creative pursuits, intellectual endeavors, or social reform. This person is resilient and not easily discouraged, always ready to bounce back from setbacks with renewed enthusiasm. However, their egoism and need for validation can sometimes overshadow their charitable and tolerant side.`,
    love: `In love, the Aquarius/Rooster is passionate and expressive but can be demanding. This person wants a partner who admires their confidence and can keep up with their dynamic personality. The Aquarius/Rooster is loyal but needs constant reassurance and attention, which can be exhausting for a less assertive partner.

If you love an Aquarius/Rooster, be prepared to stroke their ego and give them the spotlight they crave. Encourage their big ideas and be patient with their occasional bossiness. A partner who can match their enthusiasm and share their vision will have a devoted and exciting companion.`,
    compatibilities: `You’ll find great partners in Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Libra (born September 23 - October 22), or Sagittarius (born November 22 - December 21) Snakes (born 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025), who appreciate your flair and share your vision. Gemini and Libra/Dragons also make exciting matches, as they can keep up with your energy and enthusiasm. Avoid Taurus (born April 20 - May 20), Leo (born July 23 - August 22), or Scorpio (born October 23 - November 21) Rabbits (born 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), as their reserved nature clashes with your outspoken personality. Taurus/Rabbits and Scorpio/Pigs are too sensitive for your candid approach, and Leo/Goats are too whimsical to match your drive.`,
    homeAndFamily: `The Aquarius/Rooster’s home is a showcase of their personality—bold, stylish, and a bit over-the-top. Expect dramatic decor, vibrant colors, and a space designed to impress. This person loves to entertain and will go all out to make their home a hub of social activity, though they may be particular about how things are arranged.

As a parent, the Aquarius/Rooster is enthusiastic and involved, always ready to cheer their children on and push them to excel. However, their bossy streak can make them overly controlling, and they may need to learn to give their kids more freedom.

The Aquarius/Rooster child is a confident and outspoken little star, always ready to take center stage. This child needs parents who can channel their energy into productive pursuits and teach them the value of humility and cooperation, as their cockiness can sometimes rub others the wrong way.`,
    profession: `The Aquarius/Rooster excels in careers that allow them to shine and take charge. This person is not suited for behind-the-scenes roles, as they need to be seen and heard. Jobs that involve leadership, performance, or public speaking are ideal for the Aquarius/Rooster, who thrives on attention and influence.

As a boss, the Aquarius/Rooster is inspiring but demanding, expecting their team to match their high standards. As an employee, this person is a powerhouse of energy and ideas but may clash with authority figures who don’t appreciate their candidness. The Aquarius/Rooster is best suited for roles where they can lead and innovate without too many constraints.

Some career possibilities include: public speaker, politician, actor, director, marketing director, fashion editor, motivational coach.`,
  },
  "Aquarius/Dog": {
    description: `The Aquarius/Dog is a complex and thoughtful character, blending the visionary qualities of Aquarius with the loyal and watchful nature of the Dog. This person is a dreamer with a strong sense of duty, always ready to stand up for what they believe in. The Aquarius/Dog is intelligent and observant, with a knack for seeing through facades and getting to the heart of matters. However, their tendency toward cynicism and worry can make them seem distant or overly critical at times.

This person is fiercely independent but also deeply loyal to those they care about. The Aquarius/Dog is driven by a desire to make the world a better place, often dedicating themselves to causes or ideals that align with their vision. Their eccentricity and originality set them apart, but their unsociable streak can make it hard for them to connect with others on a deeper level.

The Aquarius/Dog is a natural protector, always ready to defend their loved ones or stand up for the underdog. However, their self-righteous streak can sometimes lead to conflicts, as they’re not afraid to speak their mind or call out what they see as injustice.`,
    love: `In love, the Aquarius/Dog is loyal and devoted but can be hard to get close to. This person needs a partner who respects their independence and shares their ideals. The Aquarius/Dog is not overly romantic but shows their love through actions rather than words, often going out of their way to support their partner.

If you love an Aquarius/Dog, be patient with their occasional aloofness and give them space to pursue their interests. Show them that you share their values, and you’ll earn their unwavering loyalty. Avoid being overly emotional or clingy, as this can make the Aquarius/Dog feel trapped.`,
    compatibilities: `You’ll find strong connections with Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Libra (born September 23 - October 22), or Sagittarius (born November 22 - December 21) Tigers (born 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034), who share your independent spirit and love of adventure. Gemini and Libra/Horses also make great partners, as they can keep up with your dynamic nature. Avoid Taurus (born April 20 - May 20), Leo (born July 23 - August 22), or Scorpio (born October 23 - November 21) Dragons (born 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), as their domineering ways clash with your need for freedom. Taurus/Snakes (born April 20 - May 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Scorpio/Monkeys (born October 23 - November 21 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) are too manipulative for your straightforward nature, and Leo/Rats (born July 23 - August 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) are too controlling to suit your independent streak.`,
    homeAndFamily: `The Aquarius/Dog’s home is a blend of practicality and eccentricity, with a focus on comfort and functionality. This person values their personal space and may have a dedicated area for their hobbies or causes. Their home is a sanctuary where they can retreat from the world, but it’s also a place where they welcome those they trust.

As a parent, the Aquarius/Dog is protective and nurturing but may struggle with being overly critical or worried. This person will instill strong values in their children and encourage them to think for themselves, but they may need to work on being more emotionally open.

The Aquarius/Dog child is a thoughtful and observant little soul, always watching and learning from the world around them. This child needs parents who can nurture their independence while providing a stable and supportive home environment to counter their tendency toward worry.`,
    profession: `The Aquarius/Dog excels in careers that allow them to make a difference and use their sharp intellect. This person is not suited for roles that require blind obedience or routine tasks, as they need freedom to explore their ideas and challenge the status quo. Jobs that involve analysis, advocacy, or reform are ideal for the Aquarius/Dog.

As a boss, the Aquarius/Dog is fair and inspiring but can be overly critical or demanding. As an employee, this person is hardworking and reliable but may clash with authority figures who don’t share their vision. The Aquarius/Dog is best suited for roles where they can work independently or lead with a purpose.

Some career possibilities include: journalist, lawyer, activist, researcher, counselor, environmentalist, policy analyst.`,
  },
  "Aquarius/Pig": {
    description: `The Aquarius/Pig is a refined and generous soul, combining the visionary qualities of Aquarius with the sincere and cultured nature of the Pig. This person is a dreamer who loves the finer things in life, from art and music to good food and company. The Aquarius/Pig is charitable and tolerant, always ready to help others and embrace different perspectives. However, their naiveté and tendency toward luxury-seeking can sometimes lead them astray.

This person is driven by a desire to create beauty and harmony in the world. The Aquarius/Pig is highly creative and has a natural appreciation for culture, often immersing themselves in artistic or intellectual pursuits. Their sincerity and gallantry make them a beloved friend and companion, but their hot-temperedness and credulity can make them vulnerable to manipulation.

The Aquarius/Pig is a true eccentric, with a unique perspective that sets them apart from the crowd. They are independent but also crave connection, often surrounding themselves with a diverse group of friends who share their love of beauty and ideas. Their thoughtlessness and neurosis can sometimes make them seem unreliable, but their heart is always in the right place.`,
    love: `In love, the Aquarius/Pig is romantic and passionate but can be overly idealistic. This person dreams of a perfect love and may be disappointed when reality doesn’t match their vision. The Aquarius/Pig needs a partner who shares their love of culture and beauty and can provide a grounding influence to counter their naiveté.

If you love an Aquarius/Pig, indulge their romantic side and share in their love of the arts. Be honest and straightforward, as they value sincerity above all else. Be patient with their occasional temper flares and help them see through manipulative people who might take advantage of their trusting nature.`,
    compatibilities: `You’ll find great partners in Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Libra (born September 23 - October 22), or Sagittarius (born November 22 - December 21) Goats (born 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027), who share your love of creativity and beauty. Gemini and Libra/Rabbits also make wonderful matches, as they appreciate your cultured nature and eccentric charm. Avoid Taurus (born April 20 - May 20), Leo (born July 23 - August 22), or Scorpio (born October 23 - November 21) Snakes (born 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025), as their cunning ways clash with your sincere heart. Taurus/Dragons (born April 20 - May 20 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Scorpio/Roosters (born October 23 - November 21 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) are too intense for your gentle soul, and Leo/Dogs (born July 23 - August 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) are too critical to match your idealistic nature.`,
    homeAndFamily: `The Aquarius/Pig’s home is a luxurious and inviting space, filled with beautiful objects and artistic touches. This person loves to create a warm and welcoming atmosphere, often hosting elegant dinners or cultural gatherings. Their home is a reflection of their refined tastes, though their love of luxury can sometimes lead to overspending.

As a parent, the Aquarius/Pig is loving and nurturing, always ready to encourage their children’s creativity and individuality. However, their hot-temperedness can make them unpredictable, and they may need a more grounded partner to provide stability.

The Aquarius/Pig child is a dreamer with a love of beauty and culture. This child needs parents who can nurture their artistic talents and provide gentle guidance to help them navigate their naive and trusting nature. A supportive and loving home environment is essential for this sensitive soul to thrive.`,
    profession: `The Aquarius/Pig excels in careers that allow them to express their creativity and connect with others. This person is not suited for rigid or highly competitive environments, as they need freedom to explore their ideas and indulge their love of beauty. Jobs that involve art, culture, or helping others are ideal for the Aquarius/Pig.

As a boss, the Aquarius/Pig is generous and inspiring but may struggle with practical details or managing conflicts. As an employee, this person is a creative and hardworking team player but may be overly trusting or sensitive to criticism. Freelance or artistic roles suit the Aquarius/Pig best, allowing them to shine without constraints.

Some career possibilities include: art curator, interior designer, musician, writer, chef, cultural historian, philanthropist.`,
  },
};
