// src/lib/new-astrology/aries.ts

export const aries = {
  "Aries/Rat": {
    description: `Who is that Aries I saw you with? It’s not just any old Aries. That’s an Aries/Rat, the cleverest, wiliest, and most loquacious of Aries alive.

Rats are sociable. Aries are affable. Put the two together and you come up with personality plus. Blend the Rat’s inimitable charisma with the dauntless self-assurance of Aries and, well, see for yourself. This person is vitality incarnate.

Plans and projects boil over in the lives of Aries/Rats. On the desk in the den there are plans for a new wing on the old new wing, which Aries/Rat has drawn up in a fine deft hand. In the workshop there are four-scale model villages Aries/Rat has designed and will present to the city council for possible use as housing projects. Upstairs, next to the bed, sits a thick notebook full of Aries/Rat’s first novel. Down in the kitchen you will find the fridge overflowing with carefully wrapped planned meals for the week. It is impossible to keep up with this subject. Don’t try.

But don’t sit around and look unbusy either. Aries/Rats cannot tolerate idleness in others. They are kindly and will assist their loved ones in enterprises of all variety, but they will not invest time or funds in your plan while you lie on the couch for ten days watching your toenails grow. Aries/Rats love a challenge. They are not afraid to take off into a strange cold land by themselves. They could open the market for humidifiers in the Amazon basin. Aries/Rats inspire confidence. They are not just good salespeople. But they are brilliant at the trappings that go with selling: expensive business lunches, gifts for the executives’ wives, champagne delivered to your hotel room and truffles for breakfast. Who could resist such openhandedness?

As for open-mindedness, well, that’s another story. Aries/Rats, despite their amiability and charm, are slightly on the old-fashioned side—especially where the fashion concerns a member of their family. Call it hypocrisy. Aries/Rats may enjoy a wild “social” life, rife with lovers and thick with intrigue, but they prefer that their mates and kinder remain straight arrows all the way down the line. “Do as I say, not as I do.”

Aries/Rat is a nervous type. If he appears calm and exudes peacefulness, it’s forced and false. Neuroses are always a simmer in the background. Life is never nearly so terrific as Aries/Rat likes to make it appear. Aries/Rats are impatient and sizzling with the spirit of “let’s get going.” They hate to be late and never waste time.

Aries/Rat wants power. But he is not willing to take the heat that goes with the dominion over others. The Aries/Rat character is that of a slightly naïve monarch. The Aries/Rat character lends itself to ruling. But to be a boss you must also be a meany, play policeman, enforce rules and regulations. On the whole, subjects don’t “like” those who lead them. Aries/Rat, although position appeals to him or her, will not be able to be put up with being hated. The loneliness of sovereignty would kill Aries/Rat. If he were king or she were queen who would they talk to?

Aries/Rat is in a hurry. Lending a quick nervous mind to so many different plans and projects causes this person to wax edgy and grow persnickety at times. Aries/Rat is efficient. Why does the rest of the world have to be so indolent, so uninvolved, so free from worry and care? How dare they take the time to smell the roses? There is no time. It’s already scheduled for a meeting, an errand, a buying spree, a committee luncheon or a ceremony. Aries/Rats don’t give poetry much quarter. They can’t. They really are too busy being busy.

Aries benefits from being born in Rat years. The added Rat guile gives the Ram a better chance of success. With a dose of Rat wisdom thrown in, the excessive Aries will be curtailed. Aries/Rat knows how to fight. But unlike other Aries subjects, he will never stoop to street scrappings or conscious vulgarity. The Aries/Rat is after bigger quarry than a mere physical victory. Aries/Rat wants moral triumphs—and lots of money to go with them.`,
    love: `In the beginning, Aries/Rat never has much trouble with love. The young Aries/Rat is energetic, attractive and wily enough to seduce and conquer easily. Moreover, the younger they are, the more flexible and gentle Aries/Rats allow themselves to be. So parties and dancing, dates galore and even some social drinking will play a big part in the Aries/Rat’s early adult life.

But middle age, work, responsibility, kids, social status and the necessity to acquire material wealth has a toning-down effect on this subject. Aries/Rats mellow backward. That is, they start off tender and gentle, funny and silly, and by middle age take every love affair as seriously as Hiroshima. This reversal in the fun-in-love pattern stems from the grown-up Aries/Rat’s unhealthy preoccupation with doing the right thing. Where most people loosen up as they grow into their thirties and forties, the Aries/Rat tightens, stiffens and panics. Am I old? Am I ugly? Should I diet? Will I be attractive enough? As an adult, the Aries/Rat is plagued by self-doubt in love. For this reason, when an Aries/Rat of a certain experience falls in love, you can hear the thud for a thousand miles around. Beware of the elder Aries/Rat who adores you, calls you thirty times a day and sends you so many flowers you’ll wake up one day and think you’re already in a coffin…wreaths of roses, baskets of posies, truckloads of gladiolas. It’s love, Aries/Rat style.`,
    compatibilities: `You ought to go looking for a Gemini/Dragon (born May 21 - June 20 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or Gemini/Ox (born May 21 - June 20 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), a Leo/Dragon (born July 23 - August 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or Leo/Ox (born July 23 - August 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), or even a rollicking Sagittarius/Monkey (born November 22 - December 21 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) whose antics will be sure to keep you on your toes. Aquarians of the Pig (born January 20 - February 18 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) or even Dog (born January 20 - February 18 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) persuasion will lighten your spirits and never bore you. Stay away from Cancer/Rabbits (born June 21 - July 22 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and Cancer/Horses (born June 21 - July 22 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) and avoid Capricorns born in Horse (1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) or Tiger (1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) years. You don’t see eye to eye on important subjects—like money! Librans will beguile you. But don’t bank on a Libra to keep you on the straight and narrow. Avoid all Horses. They, too, attract you like mad. But, for Rat people, Horses are eventual poison.`,
    homeAndFamily: `Oh, to have an Aries/Rat parent! Talk about involved—this person digs in with both hands and lives vicariously everything the children do, from their first drool to their final wave as they go off to college. Mother Aries/Rat makes clothes for her children and costumes for the school play. She bakes cookies for the Sunday School bazaar and volunteers to direct and produce the kids’ senior play. Father Aries/Rats heft their kids over rocks and rills at age two just to get them out into nature, teach them about birds—and to show them all the property they will inherit one day. As a parent, Aries/Rat is wonderful, responsible and lovingly strict.

As sister and brothers Aries/Rats are not so laudable. They tend to be critical of their siblings and feel superior to them. Aries/Rat might be the one to take on the raising of a nephew or niece because the child is difficult at home, or because of illness or divorce. But don’t think that Aries/Rat charity is free. The Aries/Rat will never let you forget how “good” he has been.

Aries/Rat children are great fun. They are energetic in the extreme, but they usually are not naughty or unruly. Aries/Rat kids love taking part in sports or other extracurricular activities. They will be popular and work well in class. At home, they must be reminded to take time away from hobbies to do homework. They will be talented for art. This must be encouraged. Never humiliate an Aries/Rat child. You will not be forgiven.`,
    profession: `It’s hardly necessary to tell you that Aries/Rats are incurably ambitious. They like to work—on anything and everything. They are always gifted for their profession. They take joy in planning and organizing, finding things out and even in filling out boring administrative forms. Success arrives at Aries/Rat’s doorstep without any apparent effort being made to attract it. Aries/Rat is not interested in living poorly or in feeling inferior to his neighbors and coworkers. Therefore, Aries/Rat, who has energy to expend anyway and never shirks chores, is a natural achiever.

If I had to hire someone and I had to choose among several candidates I’d look for the Aries/Rat in the lot. They are not only vibrant and intelligent, but they are loyal to any cause they take up. You couldn’t ask for a more committed employee. You might, however, be surprised at the cost of this commitment to your monthly payroll. Aries/Rats do not work for peanuts. They do wonderful jobs at whatever they do, so it’s probably worth it. But if you’re looking for a bargain basement sales manager, don’t hire an Aries/Rat. They never give up until they have earned “enough” money, which is about one million more than is “enough” for me or you. Aries/Rats like luxury and are not afraid to go after it.`,
  },
  "Aries/Ox": {
    description: `The powerful Aries/Ox can wither a mountain in a half-hearted shrug. This is a mighty combination, doomed to achievement. The stalwart Aries character sallies forth into the world full of vigor and hope at a tender age. The Ox, solid and diligent, carries young Aries, head high, sword drawn, slowly but surely toward serious, demanding goals. Aries/Oxen are winners. But Aries/Ox is about as subtle as a ten-ton truck in a mud slide. His accomplishments are many. But his friends may be few.

People don’t hate the Aries/Ox, but this tender-hearted behemoth cannot communicate with ease. Shy? Yes. And reserved and even forbidding. The Aries/Ox can be an eloquent raconteur. But he just cannot make small talk with the grocer. Aries/Oxen are clumsy. Expression, for Aries/Oxen, depends instead on a tangible physical result. And I don’t mean sports scores. The Aries/Ox must be allowed to put his shoulder to the wheel, apply elbow grease, pitch in and get things done, solve real problems. Through deeds, Aries/Ox can shine.

Of course our urban-worshiping world of today gives little opportunity for exhibitions of brute force. Gone are the days when a homely young woman who could carry babies and bucketfuls of water in the same load up the steepest hill was preferred over her weak beautiful fairy princess sister. Nowadays people are rewarded for their grasp of the artificial. The girl with the prettiest makeup job is luckier in love than the industrious Cinderella who takes in laundry to help her widowed mother. Our modern hero is the chap with the zippy sports car and the plastic smile. The one in the toothpaste commercials.

So it is that Aries/Ox becomes disenchanted with life and its superficialities. Where are the values of yesteryear? wonders the disgruntled Aries/Ox, embittered and finally alienated. I shall move to the country. I’ll get an unlisted address. Who needs this phony baloney world?`,
    love: `No ideal love is too ideal, no miraculous fidelity more faithful than that which Aries/Ox offers a mate. Aries/Oxen love with quiet compact passion. This is a forceful lover on whom you can count for security. You cannot, however, count on Aries/Ox for imaginative loving. He won’t go out of his way just to please or seduce you. Remember that sex is of secondary importance to the Aries/Ox. First comes achievement (or disgruntlement, depending on the stage). Syrupy poetry makes Aries/Ox want to puke. Aries/Ox will take his or her love straight up without so much as a lemon twist. Oh yes, thanks, maybe an ice cube or two. What appeals to Aries/Ox partners are qualities like folksiness and hominess and coziness and earnestness. Fill their beds with hot water bottles and dab essence of vanilla behind your ears. Eschew frippery. To turn on an Aries/Ox you needn’t gild the lily. Just get out there in the woods and start gathering nuts and berries. A love affair with an Aries/Ox saves on perfume and coiffure costs. Buy her a garbage disposer for her sink, a new sump pump for Christmas, and Aries/Ox will give years of trouble-free service.`,
    compatibilities: `Your best bet for partners live among Leo/Roosters (born July 23 - August 22 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029), Leo/Rats (born July 23 - August 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) and Leo/Monkeys (born July 23 - August 22 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028). Virgo/Pigs (born August 23 - September 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) like your solidity, and you will be attracted to Sagittarians, both Dragon (born November 22 - December 21 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Monkey (born November 22 - December 21 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) variety. Gemini/Snakes (born May 21 - June 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) melt your concrete heart. But Virgo/Tigers (born August 23 - September 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) get on your nerves, as they tend to snobbery. Cancer/Tigers (born June 21 - July 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034), Cancer/Dogs (born June 21 - July 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Cancer/Horses (born June 21 - July 22 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) are too impetuous. Hands off finery-oriented Libra/Rabbits (born September 23 - October 22 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and ethereal Pisces/Goats (born February 19 - March 20 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027).`,
    homeAndFamily: `Home is where the Aries/Ox feels safest. Home is where his or her heart beats fastest and most regularly. When the family is nestled all snug in its roost, you can be sure that Aries/Ox is sleeping peacefully. Anything short of domestic perfection is impossible for the Aries/Ox to tolerate. Nor can the Aries/Ox accept not wearing the pants. At home, this person runs the show. Any attempt at competition will net the remaining family members one real grouchy Aries/Ox. If you don’t want to relinquish the throne, Aries/Ox will sulk and fester until you either say “uncle” or walk out. If you leave them, Aries/Oxen grow even angrier and are capable of saying rotten things about you. But if you don’t care to give up your beautiful home and comforts provided by the Aries/Ox, tickle him by serving feather pie every night for a week. It will help loosen him up. Aries/Ox children will be talented and stubborn. They will not take kindly to discipline unless it seems to be their own idea. School will be a breeze for this child so long as his teachers understand his taciturn nature and don’t mistake it for sulking. Tenderness is the best weapon against a wall of Aries/Ox grump. Lots of jam on that toast too. Aries/Ox loves sweets.`,
    profession: `The Aries/Ox has the wherewithal to earn and keep a lot of money. So long as the energy spent during the youthful years is effort toward gain, no Aries/Ox will ever go hungry. But as laziness doesn’t suit this character, should the early years be wasted, it will be difficult for Aries/Ox to reenter the working world. By age thirty, this subject’s natural caution and deliberation will have taken on enormous proportions. The cheerful Aries credulousness will have rubbed off. And nobody wants to buy anything from a grouch.

Aries/Ox is best off in jobs where there is no superior. Insubordination is Aries/Ox’s middle name. How can a ten-ton truck take orders from a tricycle? To succeed well, Aries/Ox should try starting a business, or opening a school or even a restaurant or laundry. Hard work is no stranger to natives of this sign. But getting along with others in harmony and cooperating in a group effort is dicey. Aries/Oxen are loners. Oddly, despite their retiring personalities, Aries/Oxen usually manage to retain a few very good close friends. It is with their help that this subject can avoid both moral and financial ruin. If you know any Aries/Oxen in need, go and give them a hand. They are too shy and proud to ask. But your gesture will not be forgotten.`,
  },
  "Aries/Tiger": {
    description: `The Tiger’s taste for risk couples nicely here with the Aries’ boyish courage. An Aries/Tiger is always someone nice to know, fun to be with and easy to like. Aries/Tigers are brimming with schemes and ideas. When they apply their multiple talents and energies, Aries/Tigers are unbeatably effective people.

We know that Aries are serious folks. They do not undertake projects lightly. They attack and carry through. Tigers, on the other hand, frequently attack, immediately lose interest, turn their backs and lope away. So the coupling of Aries with Tiger has all the potential for the effectiveness we expect from other Aries. But there is always a pulling away from responsibility and an edge of rebellious excess to watch out for. Don’t get me wrong. Tigers are very serious people too, but to be quite frank, they don’t like to be bored. Aries is capable of tolerating dullness. Tigers can’t. They flip. They flee. And they split.

So the Aries/Tiger wants excitement. But because he’s Aries he thinks excitement may be a bit too much to ask in life. This makes a reluctant Tiger. The ambivalence may just do the poor Aries/Tiger in. Talented in the extreme, there is nothing an Aries/Tiger cannot do. There is no chore, no craft nor enterprise too complex or difficult for this subject to excel at. Not only are Aries/Tigers skillful, but they are conscientious. So everything is open to them. Except perhaps politics.

Politics requires a more supple and strategic approach than the Aries/Tiger wants to take. This is a direct, no-nonsense character who believes in man’s basic goodness. Aries/Tiger will be sorely disappointed by scrapes with crafty brigands who commit petty crimes against law and order. To an Aries/Tiger, what is right is right. There are no shortcuts.

The subject will be happiest owning a shop or running a factory, sailing a ship or even organizing tour groups. Not a natural subordinate, Aries/Tiger is able to take orders from higher-ups, but it isn’t very good for the Ram/Tiger soul. This person is a true independent. Shackles are his nemesis.

And when the Aries/Tiger gets to feeling cramped, watch his dust! The shop gets sold, the boat given away, the dog farmed out with friends in the country and the Aries/Tiger is gone. To the new world? The old? To sea? Forever? I warned you. Aries/Tiger finds boredom intolerable. Here is the real capacity for revolutionary behavior. Aries/Tigers combine the soldierly with the fervent. They are truly warriors in life, believing passionately in freedom and justice for all. Moreover, Aries/Tigers don’t mind sharing their ideals with the world.`,
    love: `Lots of affection and tenderness surround those born under the combined signs of Aries and Tiger. How can anyone resist the slightly callow, yet mellow, boyish or girlish, dominant and strong Aries/Tiger? It’s a swell combination of the holy and the profane. I’d say the proverbial Sunday-school teacher/prostitute “ideal woman” about whom my father used to dream incarnates Aries/Tiger.

There will be much movement in the Aries/Tiger’s love life. Inconstancy is to be expected, not for the sake of infidelity or spite, but simply for change’s sake. The Aries/Tiger will not stick to one mate. This person needs novelty. This character is by turns disobedient, intemperate and excessive. It sounds as though it would be difficult to hope for more than a very torrid affair from Aries/Tiger. But don’t forget that this Tiger is an Aries. And that Aries is a “good guy.” Whatever indiscretions he or she may commit will be handled discreetly and with savoir faire.

If you love an Aries/Tiger and really want to hang on to him or her, then you must learn to let go. It is only when the Aries/Tiger feels completely free that the partner becomes irresistible. Don’t call him. He’ll be bound to call you.`,
    compatibilities: `Your heartthrob may be found among Gemini/Horses (born May 21 - June 20 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) and Gemini/Dogs (born May 21 - June 20 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030). Leo/Dogs (born July 23 - August 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) or Sagittarius/Dragons (born November 22 - December 21 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), Sagittarius/Horses (born November 22 - December 21 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) or Sagittarius/Dogs (born November 22 - December 21 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030). Aquarian/Dogs (born January 20 - February 18 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) or Aquarian/Pigs (born January 20 - February 18 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031)—even Aquarians born in Dragon (1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024)—will enthrall you. Resist the wiles of Librans born Ox (born September 23 - October 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), Capricorn/Monkeys (born December 22 - January 19 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028), and their star-studded Snake (born September 23 - October 22 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) counterparts. Cancer/Snakes (born June 21 - July 22 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) are too moody and complex for your simple tastes, too.`,
    homeAndFamily: `You cannot ask for a more dedicated family member than Aries/Tiger. No matter how far they may roam, no matter what heights they reach or to what depths they dip, Aries/Tigers always remember their mothers’ birthdays. As parents, Aries/Tigers are serious, if a bit long-winded. They feel they must explain everything to their kids and that if they do so, the kids will allow them to dominate and will never talk back. It doesn’t always work out that way. The Aries/Tiger parent gains his or her children’s utter and unmitigated respect. But behind the scenes the kids might wish the Aries/Tiger parent were a little less sure of the rules and regulations. Aries/Tiger kids are delightful. They’re into everything and full of love and warmth. People are drawn to their charms so they hardly ever have trouble with teachers or other kids in school. The Aries/Tiger child is a love bug. And so-o-o-o talented. Music lessons. Tennis camps. Speech classes. Computer classes. Everything interests Aries/Tigers. And they are so capable that providing access to activities will be a pleasure for the parent.`,
    profession: `Tigers exude ambition. They want to get places, accomplish things, build plans out of dreams and always improve their own lives and the lives of those they love. Money? Well, it isn’t all that important to the Aries/Tiger. Both Aries and Tiger are non-money signs. I don’t mean that they won’t have enough money, although frequently Aries really can go without. But the Aries/Tiger will not ruin his health or destroy his home life for the sake of money. Aries/Tiger figures there will always be money to go around as he or she is energetic and active in the extreme and will always be able to earn money. Thing is, Aries/Tiger doesn’t like to stalk money, fight for his share or grab at that of his neighbor. It’s beneath Aries/Tiger’s dignity to scrap for personal gain. An honest day’s work should do the trick. If it doesn’t, then he’ll wait around till it does. Aries/Tiger prefers to save his integrity. His bank account will take care of itself.`,
  },
  "Aries/Rabbit": {
    description: `Caring is the Aries/Cat’s specialty. Not only does this native care about everything solid and traditional and valuable, he also enjoys the capacity to care for those elements. This person is a generator of refinement, an accumulator of wisdom, a dispenser of metaphysical energy and a preserver of life’s finer things. The Aries/Cat is a Cat’s Cat.

Cat virtue lends itself willingly to Aries’ vigorous courage. This person sets about each day on an intense search for peace and beauty. Aries gives him punch. The Cat confers prudence, taste and independence.

You won’t find Aries/Cats managing your local supermarket or hawking rugs in a souk. If you are looking for one of these characters; you’d be better off hunting in an art museum. You see, the cultural bent in Aries/Cat people is never just a hobby. Refinement, beauty and the pursuit of the civilized are the real goals of an Aries/Cat.

Gain, of course, enters the picture too. But this person demands that his wealth come from solid, classical sources. Aries/Cats are not tricksters who long for the coup that will bring them a windfall so they can rush off to South America and cha-cha with a bevy of dark-eyed senoritas. Instead, the Aries/Cat is a model of perseverance. He doesn’t plod the way an Ox or a Taurus can. The Aries/Cat pads gently but diligently along on velvet paws. His back curves upward from time to time when danger approaches. The hairs on his neck stand up. But Aries/Cat doesn’t hiss or spit. This is not a rowdy breed. Vigorous, but never rude or aggressive, the Aries/Cat is a study in moderation.

The addition of the Cat qualities to the dauntless Ram’s heredity lends a quality of refinement not given to every Aries. Aries, as we know, can be a bit on the lumpy side—gauche or even ostentatious. The Cat brings Aries finesse, gentility and prudence. What more could a swaggering warrior want?

Not that Aries needs any, but the Cat certainly comes equipped with a lion’s share of virtue. Cats like to think of themselves as credible and fair in all matters human. For the Aries, who is also a solid citizen type, albeit a most noisy one, a Cat identity comes easy. In the Cat sign there are no major juxtapositions of character trait to which the Aries cannot easily adjust. Comfort is excessively important to this person. Aries/Cats surround themselves with plants and cushions, divans, pillows and elaborate hot water systems with matching bathrooms. At Aries/Cat’s house the stereo system is always top-of-the-line. There may not be other luxuries—I do not claim the Aries/Cat is merely a materialist—but there will always be deep comfy armchairs where one may sit and listen to the finest music chosen by our friend Aries-the-Cat himself.

Food is not crucially important to this Cat. Aries/Cat enjoys fine cuisine, but if there are only bacon and eggs or corn flakes, Aries/Cat will settle for that. Usually, rather than spend hours in the kitchen or marketplace, Aries/Cat prefers visiting other people’s dining rooms. Time spent preparing meals is time in which the Aries/Cat might have gone to an exciting new exhibition, chatted with a fascinating scholar, bought an antique Recamier or grand piano. First, Aries/Cat soaks up the situation through ultrasensitive eyes and ears. Only after “casing the joint” is Aries/Cat ready to embark on any given plan.

Aries/Cats are capable. They can do all manner of work. But Aries/Cat is not what I would call a “creative” sign. Rather, these people lift beauty and ideas from life, polish them in the comfort and beauty of their own homes and refine them for their own use. Aries/Cat is a collector of liveliness, a natural dilettante.`,
    love: `Do I dare say it? Aries/Cat is not very faithful in love. Rather, Aries born a Cat is constantly in love. Aries and Cat together form an emotional independent. Neither of these signs is really the clinging-vine type. Having a partner with whom one makes a home, spends holidays and eventually has children seems on the surface to Aries/Cat like a good idea. But in the doing, Aries/Cat cannot “hack” dense thickets of emotional pushings and shovings. Cats hate conflict, remember? And Aries is ill-equipped to deal with the wars he dreams of fighting. So one-on-one, hard-hitting emotional rows, such as life dumps in the laps of those who cohabit for love’s sake, send the Aries/Cat packing. Or rather, it’s the other way around. Aries/Cat stays. You go. Out!

Now there are ways to deal with Aries/Cat’s reluctance to roll in the mud of emotion. If you love an Aries/Cat and long to take her for your bride, keep your distance. Be the first to back off. “I’m sorry, darling. I just can’t make it Tuesday. I have to go to San Francisco for the whole week.” You may not really have to go to San Francisco. But it doesn’t matter. The Aries/Cat will buy your story. He or she won’t even ring you to see if it’s true. Oh no. Aries/Cat is delighted for a little space in which to plan and do and absorb in his/her own room with books and paintings and music and maybe a few cats lolling decoratively about the comfortable nest he’s made for himself.`,
    compatibilities: `Try going out with Leos born either Dog (born July 23 - August 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) or Pig (born July 23 - August 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031). You’ll be attracted to Sagittarius/Goats (born November 22 - December 21 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) and Gemini/Pigs (born May 21 - June 20 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) and Gemini/Goats (born May 21 - June 20 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027). You’ll fall for handsome Aquarius/Snakes (born January 20 - February 18 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and their cultured Pig (born January 20 - February 18 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) brothers too. If I were you, I’d leave Cancer/Dragons (born June 21 - July 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), Cancer/Rats (born June 21 - July 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) and Cancer/Roosters (born June 21 - July 22 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) alone, give Capricorn/Tigers (born December 22 - January 19 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) a wide berth, and avoid all (beautiful but feisty) Libra/Dragons (born September 23 - October 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and their lusty Tiger (born September 23 - October 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) counterparts.`,
    homeAndFamily: `The individualism present in every Aries/Cat subject’s nature augurs a problematic family life. Aries/Cat is home-loving and careful, sensible and only slightly mad. But this person is so enormously occupied with his world as it has been engineered by him, for his comfort and quietude and wellbeing, that he cannot always exteriorize emotion well enough to maintain a family unit. I don’t mean that Aries/Cats are not conscientious parents or responsible mates. They are. But they are distant.

But there is more than one way to skin an Aries/Cat. They are almost too cool. The other members of the family will need both patience and the ability to distract and amuse Aries/Cat away from his personal pursuits. Amuse an Aries/Cat and you’ll get to keep him for his nine lives. Aries/Cat children have a pleasing quality. These kids are born curious. They are eager to visit and see every monument, museum, theme park, movie, fireworks show, and so on. From the moment they are born, Aries/Cats absorb prettiness. Make them comfortable. Give the Aries/Cat child his or her own beautiful space to evolve in. Take him or her on trips and get him subscriptions to good magazines. You will not regret a minute you spend with this bundle of sensitivity.`,
    profession: `Nothing to worry about with Aries/Cat. There is enough ambition here to share with a few more “laid back” signs. Mind you, don’t go looking for the world-beater, leader-of-the-pack type in Aries/Cat people. Their goals have little or nothing to do with public acclaim. Aries/Cats want to know more, see more and do more than other people. They are forever delving into a new area, picking up a few books on speed skiing or figure skating, or gathering information on famous painters of nudes in order to write the definitive book on the subject. But remember, Aries/Cats make their own success. Where the world is concerned the Cat could not care less. His objectives are security without conflict, comfort without interference, and a reassuring bank balance.`,
  },
  "Aries/Dragon": {
    description: `Here, in the Aries/Dragon, we find a crackling combination of raw Aries energy and Dragon pluck and guile. It’s an unbeatable concoction. Aries/Dragon burns to get ahead in life. Nothing can stop the brand of will and enterprise born into this subject.

Guile, normally so foreign to the Aries’ basic nature, will color every stone the Dragon born an Aries overturns. These people are not only devious; they are not just crafty; they are so self-confident that you hardly notice your silverware is missing. Aries/Dragons don’t ever appear shifty. They behave as ladies and gentlemen. And to hear them talk you might think they are positively callow!

“Did that Aries/Dragon woman really wait till her husband was away on business to rob the whole household of its furniture, kidnap the children and abscond with the bank balance? Did she really move to Hong Kong with her lover?”

“Oh yes. She really did that. She picked up and she left. With a forwarding address.”

“Did she leave her husband a note?”

“No. Just the dog. She knew that he was very fond of the dog. A dachshund named Darling.”

“How strange. Why do you suppose she lifted everything but the dog?”

“She’s very sentimental. ‘Couldn’t bear to think of her husband losing his beloved dog.”

The impeccable Aries/Dragon melts when confronted with sadness. Aries/Dragons fall for all sob stories. Sentimentality is, in fact, very often their undoing. An Aries/Dragon boss may hate his employee with a green disgust. But if said employee comes crying for a raise, Aries/Dragon sends out for Kleenex and a fountain pen to sign the guy’s check. There’s no other way to tell it.

Aries/Dragon are irresistible. They possess unmitigated attractiveness. They give off a kind of brute heat that topples even the iciest opposition. Don’t leave your wife in the same room with an Aries/Dragon if you want to get her home intact. Even a five-minute exposure to the rays emanating from the boyish Aries/Dragon will invest her eyes with blinding stars. And Aries/Dragon women are so gorgeous!

Oh, it’s awful. When a certain Aries/Dragon woman I know comes onto the beach, all the other women bury themselves in the sand.

There is, of course, the danger of arrogance here. So much fire and so little temperance coupled with looks and taste and success—well, it’s an incendiary combination. Aries/Dragons may inspire envy. Their inveterate cunning drives strong, direct people to distraction. Why, wonders the plain-spoken hard-driving straight arrow, does the Aries/Dragon always try to get away with trickery? Can’t he tell that after years we’ve been vaccinated from his wiles? Answer: Yes. Aries/Dragon can see that the straight-shooting Sheriff John Wayne-type character has got his number. But that will never deter Aries/Dragon from trying to have a little fun at the Sheriff’s expense. To the Aries/Dragon it’s all a game anyway. He has the magic touch. So why should he deprive himself of flaunting it?

Actually, underneath the slick exterior, the Aries/Dragon is touchingly sincere. He doesn’t make friends easily. He cares deeply about everyone he undertakes to love. (And Aries/Dragons are capable of true flaming passionate attachments.) They are essentially good and well-meaning. But they cannot resist their own adorableness. They like to bask in their own sunshine, get the most out of life and tear into everything they do with living.`,
    love: `In love with love, the Aries/Dragon never misses a chance to seduce or to be seduced. Fidelity? Never heard of it. But that doesn’t really matter. Intimate moments passed with an Aries/Dragon will be of such intensity that, well . . . who cares what they get up to the rest of the week? As I said above, a Aries/Dragon is sentimental in the extreme. If you love an Aries/Dragon and feel he or she is erring and straying just a bit too frequently, you can always appeal to him or her through the maudlin. Stand at the dining room table, white knuckles gripping the edge, head down, and sob. Yes. Snivel and heave your shoulders a lot. Your Aries/Dragon may have been on the way out of the house when suddenly there comes this choking sound. “My love is crying!” Dragon swashbuckles back up the steps, cuddles you close and asks, “What can I do?”

Stay home once in a while, Aries/Dragon. Stay home and learn to like it. Play with your toys. Dig in the garden. Enjoy the little pleasures of workaday life. If you care about forming a united couple, then you have to do at least half of the uniting.`,
    compatibilities: `You’ll have a lot of fun with Gemini/Rats (born May 21 - June 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), Gemini/Snakes (born May 21 - June 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Gemini/Monkeys (born May 21 - June 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028). Aquarius/Monkeys (born January 20 - February 18 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028), Sagittarius/Rats (born November 22 - December 21 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), and Leo/Rats (born July 23 - August 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) and Leo/Monkeys (born July 23 - August 22 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) will thrill you. But nix on Cancer/Dogs (born June 21 - July 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Cancer/Oxen (born June 21 - July 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). Ditto nix on Capricorn/Ox (born December 22 - January 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) and Libra/Dog (born September 23 - October 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030). You’re too presumptuous for them. They’ll find niggly ways of squelching you – especially in public.`,
    homeAndFamily: `Aries/Dragons are so attracted by the outside world that their need to shine and perform miracles for the gallery may draw them away from their families. I’m not saying Aries/Dragons don’t make good parents or siblings. But they are not the type to be content solely with the admiration of family members. That’s too easy. Aries/Dragon needs universal acclaim. And knows how to go after it. This has to cut down on the number of times he or she will agree to do drudgery. You won’t find many Aries/Dragons pushing a cartful of family necessities at the supermarket. You are not going to find masses of Aries/Dragons at the laundromat either. They love their families. But they are not particularly interested in catering to them.

Aries/Dragons have a tendency to make rigid rules for their children “Don’t talk back. Keep your elbows off the table. Wipe that smile off your face!” are Aries/Dragon phrases. As appearance is of the utmost importance to Aries/Dragons, they want their kids to put on a good show as well. Aries/Dragon kids will be turbulent, noisy and demanding. But they are so loving and tenderly sweet that you cannot stay angry with them Usually Aries/Dragon children are precocious in ways both intellectual and social. They are leader types but not always the most popular kids in the class.`,
    profession: `The Aries/Dragon is synonymous with ambition. Aspiration is the most important part of this character’s life plan. First, Aries/Dragon will undertake to get through the most difficult schools, graduating with top honors and using diplomas wisely to find jobs they deem worthy of their brilliance.

As a young adult, the Aries/Dragon often finds a difficult and taxing pursuit, like buying a defunct mine and trying to start it producing again— or borrowing a huge sum of money to invest in a broken-down building, fix it up and sell it. Or maybe he’ll set about producing books of enormous difficulty and size, which nobody is sure will find an audience. The Aries/ Dragon lives for such challenges. And if challenges don’t present themselves, Aries/Dragons will go out and dig them up.

Success is guaranteed this subject provided pride and debauchery are kept at a safe distance. Aries/Dragons tend to excessive belief in self. If they find themselves in shady deals or are drawn to lubricity they must take care to slither right out again. Go back to the office and apply shoulder to wheel. It’s good for the soul. For this brand of Dragon honesty really is the best— and only—real insurance policy.`,
  },
  "Aries/Snake": {
    description: `The juxtaposition of Aries to Snake is so paradoxical that I scarcely know where to begin. Both signs are ruled by fire. Oh, all right, Snake is little fire and Aries big fire. Obviously, this character is not a cold fish. A Snake born Aries suffers pangs of inner contradiction. Does she tend the little fire or burn brightly with the big blazing one? Fiery Aries always wants to rush out and do and go and experience. The chilly Snake wants, on the other hand, to sit back and ponder, intuit and judge whilst warming her toes before her tiny fire. Whichever of her influences happens to be feeling stronger on any given day gets the upper hand.

Schizoid? Well, not exactly. No Snake is ever very far removed from reality. Snakes are wise. They don’t much rush in where angels fear to tread. They weigh everything forty times and then sleep on it again to be dead sure. So if Aries is born in a Snake year, the benefits in the profundity department are many.

As I see it, the Aries’ headstrong ambition will be nipped in the bud by the addition of the languorous Snake to his character. Being a Snake, this Aries will lean toward creative elements, develop talents and seek wealth and wisdom.

Physically, there is something of the Boy or Girl Scout in all Aries. But here, with the help of the elegantly accessorized Snake, Aries will sport an air of coquetry and be drawn away from hardy sensible shoes and backpacking to more sophisticated city life. Aries’ proud self-righteousness will be tempered by the Snake’s circumspection, too.

The worst that can happen with this combination of Aries and Snake is that the normally energetic and straightforward Aries might develop into a lazy bum who tells a lot of fibs. That’s an exaggeration, but sloth is the built-in enemy of the Snake. Although Aries is not traditionally easy to discourage from leaping into action at the slightest stimulus, the old Snake is intuitive and knows how to persuade. He may be able to con Aries out of his natural drive. Aries, in his rank naiveté, is such an innocent target for the slender Snake! How can any Aries be expected to resist this delightfully attractive cohort?

With determination and lots of encouragement the Aries/Snake can enjoy a secure and very pleasant life. This person will surely be gifted for things artistic and would be well advised to launch an early career, buy a very reliable alarm clock and hire a nanny to keep him or her on the move.`,
    love: `All Snakes desperately need to be loved and Aries/Snakes are no exception to the rule. What sets Aries/Snakes apart from other Aries in matters of the heart is their real touch with the deepest resources of human nature. Snakes don’t miss a trick. They are not only observant, but they are so instinctive. Spookily so. Snakes feel things in a way that Aries rarely can. So again, Aries benefits from his Snakeism. Ardor and caring, not always native to Aries, will be omnipresent in the Aries/Snake. What’s more, the otherwise egocentric Aries personality will be tempered by the Snake’s real ability to create and maintain love relationships.

Contrarily, the Snake’s graspingness will be held in check by Aries’ goodscoutism. The Aries/Snake will no be so all-fired possessive of his loved ones as are so many other Snakes. Finally, the candor of Aries causes the Snake to moderate his tendency toward infidelity. Aries turns Snake’s promiscuity into a quest for brotherhood. All the better for Snake, I would say.`,
    compatibilities: `A wise choice for you lives among Gemini/Roosters (born May 21 - June 20 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) or Gemini/Oxen (born May 21 - June 20 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). Or… the love of your life may be hiding out in the Sagittarius/Dragon (born November 22 - December 21 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or Sagittarius/Rooster (born November 22 - December 21 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) camps. You can search out Leo/Dragons (born July 23 - August 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or Leo/Pigs (born July 23 - August 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031), Aquarius/Oxen (born January 20 - February 18 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) or Aquarius/Roosters (born January 20 - February 18 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029). Cancer/Tigers (born June 21 - July 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) are a “no-no” (except for a fling). You will be able to swallow Libra/Pigs (born September 23 - October 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) whole for breakfast and enchanting Librans born in Snake years (1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) will compete with you.`,
    homeAndFamily: `Here is where the Aries/Snake really shines. For home life and childrearing, decoration and embellishment, caring and feeding, the Aries/Snake is one of the most doting and capable signs.

Imagine the industrious “I am” of Aries married within one person to the Snake “I intuit.” It’s perfect. Aries/Snake could give lessons in the creation and maintenance of family life. Aries likes to build and invent and start projects. Snakes like to make things (and not just hire people to make things) pretty. The Aries enjoys exteriorizing. The Snake is just the opposite. In order to run a good family unlike people are frequently preferable to two similar souls. The Aries/Snake could probably dispense with the other half of a couple and manage beautifully, provided he or she remembers to get out of bed in the morning.

The Aries/Snake child will be bright and energetic. But the tendency to indolence must be curbed young. Don’t allow Aries/Snake children to spend all their time reading with a flashlight under the covers day and night. Push them out into the sunlight. Encourage the Aries side of their natures. The Snake will take care of itself.`,
    profession: `Where there is Snake there is always money, beauty and elegance. This Aries/Snake character is more affable and pleasant than most. It seems unlikely any Snake would go so far as to become a salesperson. But there is a leaning here toward commerce and away from pure intellect. The Aries/Snake will have to look as if he or she is busy. But don’t fall for it for a minute. Those business trips he pretends to be on are mini-vacations. Snakes don’t like to be kept captive. They do the capturing. The earnest desire to sit down and relax may get in the way of this Aries’ normal activities. But it won’t last long. Aries may be childlike and impetuous but they are also brave and strong. The Snake has a hard time pinning the Aries shoulders to the mat for any kind of significant count.

Whatever happens, the Aries/Snake will always have enough money—and that means more riches than you or I ever dreamed of having. So Aries/Snakes will be richer—and more spendthrift—than other Aries. They will also be generous to a fault and eager to please. The Aries/Snake seems to waft to the top of the heap through his own aura of superiority. Not to worry. There’ll always be caviar in the fridge.`,
  },
  "Aries/Horse": {
    description: `There is something of the victorious athlete in all Aries/Horses. They play a mean game, are both fast on their feet and quick of wit. But they don’t always carry through on their serve. Herein lies the first and most bothersome of Aries/Horse faults.

Both Aries and Horse are pushy and active. Both signs are ego-oriented. Both Aries and Horse are guilty of willfulness. Couple them and you come up with a mighty character prone to demanding what he wants when he wants it, putting down his foot—after removing it from his mouth of course.

Some of the positive qualities of Aries/Horse are rank enthusiasm, a certain charming naiveté and pure energy. These people are apparent dauntless, and give the impression of great strength of purpose. They’ll always be the first to tell you how fabulous the day has been, how terrific the world could become and how marvelous life would be if only you know how to look on the bright side. Aries/Horses want to believe. They care about goodness and virtue and really can buckle down and work toward noble and lofty goals. They love truth and are wont to blurt more than their share. And Aries/Horses are incorrigibly practical. They can fix almost anything with their hands, build houses and remodel rooms in a trice; rearrange the furniture and set up new household traffic patterns that nobody else could have dreamed up.

If there is a conclusion hanging about anywhere, you can be sure the Aries/Horse will jump to it. Both Aries and Horse tend to use their energies more readily than their thinking processes, so they are always tempted to try and hit the nail on the head fast and without reflection—and often because of hastiness, they fall short of their ideal.

Aries/Horses are sore losers, too. If they don’t get the applause or approval they are so eagerly seeking in life, they have been known to kick and pout and truly carry on. Failure, for an Aries/Horse, constitutes a personal affront. He doesn’t take kindly to setbacks.

Soldiers to a man, Aries enjoy tilting at large obstacles in hopes, of course, of conquest and eventual annihilation. The Horse character, although far more canny, includes a similar tendency to engage in headlong turns at one’s adversaries. As you can readily see, an Aries/Horse person will be full of dauntlessness.

Trouble is, underneath Aries/Horse is just another “nice guy” who would rather live in peace and quiet than have to survive in a war zone. Aries/Horse always has a secret hiding place carved out for himself in the countryside or even in the city, ready at all times to enwomb his frayed nerves.

Never try to reason with an Aries/Horse. It’s a waste of your precious time. Aries/Horses understand power and strength and (unfortunately) brutality. They are not expertly subtle about their own needs and demands. So they can’t take hints about what it is you might be after. The abstruse won’t reach them. Forget beating around the proverbial bush—chop the damn thing down and walk straight up to the Aries/Horse with your axe visible. If you want to convince the Aries/Horse of anything, you will have to engage in some very direct behavior.

Provided bad luck is not too intrusive, the Aries/Horse will get on smoothly with tasks at hand. He will be amusing and easy to be around. Aries/Horses are quick to make friends and don’t mind small talk. Take an Aries/Horse on a picnic or include him in your next swimming party. He is the helpful sort who enjoys deriving praise and respect from his fellows through his ready application of hands to menial or manual tasks. He will dig you the barbecue pit and drive the whole gang in from the rail station and make everyone laugh because the hostess forgot to buy hamburger buns. Aries/Horse is delightfully accessible and does not suffer from an excess of profundity.

By the end of the party you will find him sprawled on the couch in the living room, snoozing away the exhaustion of a busy, busy day wherein all the activity has in some way concerned him. He’s a pitch-inner, a born hardhat. Even in a topless bikini, the Aries/Horse is both willing and capable of chopping the wood.`,
    love: `Enthusiasm can, as well we know, be the enemy of lasting love as it is often the soul of infatuation. Aries/Horse’s romantic foible is his dauntless enthusiasm. In two seconds the Aries/Horse falls in love. What is it? That skin, those shoulders, the way he slurs his esses, a little je ne sais quoi that is guaranteed to turn our Aries/Horse friend into a veritable abyss of infatuate sentiment. We know that Aries/Horses are not overly sentimental.

And hesitation is not their problem. This quick impulse-buying in the love department rarely works, so over the long run, Aries/Horse can be disappointed. Those shoulders were only part of a chic new couture shirt design, that smooth skin was achieved with makeup, and the cute way he slurred his esses? You guessed it. He was drunk. Aries/Horse should learn early on to watch out for red flags in relationships – otherwise he may find himself strangled with one.

Aries/Horses are sexy people. If you love an Aries/Horse, take him to bed. In intimate circumstances you’ll discover a whole new being. Remember that Aries/Horse is quick on the uptake and a blurter and a sprinter. Any preliminary out-of-sheets foreplay will naturally confound him. But Aries/Horses, remember, are skillful with their hands and tend to be, although not truly athletic, agile and supple-bodied. Are they romantic? Not really.`,
    compatibilities: `You’ll certainly enjoy the company of a Leo/Tiger (born July 23 - August 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or Leo/Dog (born July 23 - August 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030). You may also fall for Sagittarius/Goats (born November 22 - December 21 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027), Gemini/Tigers (born May 21 - June 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or Gemini/Dogs (born May 21 - June 20 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030). Ethereal Aquarian/Goats (born January 20 - February 18 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) may make you feel a bit faint. As for Libra/Pigs (born September 23 - October 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) and Libra/Monkeys (born September 23 - October 22 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028), they are out of the running, as are Cancer/Pigs (born June 21 - July 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) and Capricorn/Pigs (born December 22 - January 19 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031). Generally speaking, avoid alluring Rats. Long term, you will come to blows over power.`,
    homeAndFamily: `The Aries/Horse abode will be practical. The drapes and carpet may be carefully color-coordinated. The furniture will be high quality and sturdy. The general Aries/Horse decor is frill-free, comfortable and serviceable. Aries/Horse people have a lot of imagination but they like to apply it sensibly.

Aries/Horse people make bossy family members. As their specialty is getting things over and done with, they cannot tolerate slow, deliberate methods in others. Around the house, Aries/Horse feels things ought to go his way. He is also convinced that his is the only way. It’s not always restful to live with Aries/Horses. They want everybody to gather at the table at the same time and are always in a rush to get on with the day at hand. God forbid you should be resting in a deep armchair with your feet up, your thumb in your mouth and your eyes glued to a book. Aries/Horse wants you to be more productive. Mind you, if you wish to you may ignore Aries/Horse’s entreaties. He’ll get bored with nagging you after a few minutes.

As a kid, the Aries/Horse will show early talent for instant excellence. He’ll be adaptable and very charming, open and sociable. All artistic bents should be encouraged. The Aries/Horse needs to be occupied and finding a passion early on may save him from much idle boredom in later life.`,
    profession: `The avenues on which Aries/Horses are most successful are not always the ones they choose to plod along. There is an early desire here to get involved in artistic careers. At first, when young and inexperienced, Aries/Horse may think of himself as an actor, singer or even a painter. He may enjoy early competence at these disciplines. But later on, as his understanding of self and of the world accrues, the Aries/Horse is more likely to choose a more secure career where his easy enthusiasms and capacity for rapid decisionmaking are called to the fore. Given the Aries/Horse’s capacity for leaping before looking, she will be more successful, if she has something solid to fall back on.

The Aries/Horse makes a better boss than employee and even more important than that, he makes a terrific independent worker. Working from home might suit him or her down to the ground. Aries/Horse people can gallop along in all fields requiring snap decisions and pleasant working conditions. He can be a computer programmer or a journalist. Aries/Horses make good pilots and translators and policemen. She can do very well in advertising. A job, a campaign and on to the next job, campaign, etc. I don’t advise long-suffering professions such as writing historical treatises for Aries/Horses. The clergy too would be a mistake. They like their share of instant satisfaction and long-winded sermonizing is not their forte.`,
  },
  "Aries/Goat": {
    description: `This character needs “social security” in order to survive. The nature of Aries/Goat is free-thinking, eccentric, and rebellious. But without an atmosphere of total safety and freedom from want in which to evolve without being forced to involve, this person will suffer. The talented Aries/Goat performs best with a safety net.

The Goat is a bit of a bohemian. His nature is easygoing and pleasure-seeking. Aries is a soldier. Aries is enterprising and willful in the extreme. Herein lies the paradoxical character of Aries/Goat. The gentle Goat side of Aries/Goat wants to lie in the sun and dreams of greener pastures and happier days, while the vigorous Aries tugs persistently on the Goat’s tether urging, “Get up! Hurry! Make that phone call. Finish the lunch dishes. It’s time to bake a cake now. You forgot to write that important business letter.” Poor old laid-back Goat doesn’t have a chance in this busy person’s life. The Aries is always mixing cold water in the Goat’s suntan oil.

What happens with Aries/Goat people is interesting. They tend to be creative in the extreme. They dress well and take great care about their appearance. They are poised and affable. They are fun to be with. And they are usually more jaunty and optimistic than other Goat subjects. I say “usually” because the worst thing that can happen to Aries/Goat is to stand by and watch his own well dry up. If poverty strikes the source of the Aries/Goat’s security, he will sink into abject pessimism. Aries/Goat can become physically ill from want of prettiness and comfort. They care more about their own well-being (and of course that of their benefactor) than any other value in life. They depend on sumptuousness.

The Aries side of this subject’s nature lays him open to outside influence. The Aries, remember, is naive and believing. Goats are a bit more skeptical but they are not very industrious. Therefore, if a foul influence wafts over the life of an Aries/Goat, he may very well fall victim to it. What I mean is that Aries/Goat must be protected. He or she does not want to live alone, to go out in the world and fight for crusts of day-old bread or worry about whether those diamond earrings have made a hole in the family budget. However, with all this relying on others for safety, the Aries/Goat behaves in what seems to be an extraordinarily independent fashion. Aries/Goat have snappy tongues. They say what they think and don’t mind shocking others whom they consider less clever than they.

If the Aries/Goat is born into a climate of jollity and casualness, he may never want to leave home. But if he enters a cold unfriendly world where gray winter prevails, he will do everything in his power to seek a new life in a warmer, more sensitive place. Most often, if Aries/Goat leave home, they do so with their partner and their children and pets. They may hate their surroundings. But Aries/Goat rarely leave their kith and kin. The Aries/Goat gives an outward impression of simple gaiety. Smiles and handshakes, jokes and pleasantness abound. Don’t be fooled. The Aries/Goat is not your average hail-fellow-well-met. This is a complex soul who, in order to keep up appearances and not rub people the wrong way, will affect a sunny disposition. Look harder the next time you run into one of these people. Behind that crinkly smile lies a note of disquiet, a hyper-sensitive area that can be hurt so easily—too easily. It’s better to resist harsh criticism with Aries/Goat. They are a lot more vulnerable than they look.

Aries/Goat can be gossipy. They need friends. So they may just be tempted to pretend to be the “best friend” of whomever they are talking to at the moment. They chatter a lot and easily divulge “classified” information such as how much their mate earns every month and who is sleeping with whom.`,
    love: `The Goatly Ram is love-oriented. In fact, emotionally, Aries/Goat depend almost entirely on love and the security it brings them. Possessive in the extreme, the Aries/Goat will not like letting his or her partner out of sight. Unless, of course, the partner has had to go somewhere far away in order to make money so as to bring it home and give it to the Goat. If you are Aries/Goat, you should make sure before you marry or set up housekeeping that your choice of partner is adept at earnest monogamy You should also take care to hitch up with a person whose outside interests lie where yours do, in the creative sector. Aries/Goat don’t make excellent life mates for playboys, scientists or Archie Bunker types. You need to be understood and cheered—not constantly fraught and worried. Aries/Goat emanates a languorous passion. No quickies for this subject. Aries/Goat longs to live in a state of constant foreplay whose sensuality lingers in every syllable and fills the very air with its musky aroma. So make sure Aries/Goat sleeps on the outside of the bed. That way you can just give him a shove and roll him to his feet in the morning.`,
    compatibilities: `It’s love at first sight with Aquarius/Pigs (born January 20 - February 18 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) and Aquarius/Rabbits (born January 20 - February 18 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035). Sagittarius/Rabbits (born November 22 - December 21 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and Sagittarius/Horses (born November 22 - December 21 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) also enchant you. Gemini/Rabbits (born May 21 - June 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) will make you laugh and appreciate your love of beauty and need for stability. Leo/Horses (born July 23 - August 22 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) and Leo/Rabbits (born July 23 - August 22 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) will pep up your social life. But if I were you, I’d give up on Capricorns, especially Capricorn/Dogs (born December 22 - January 19 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Capricorn/Tigers (born December 22 - January 19 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034). Cancer/Oxen (born June 21 - July 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) and Scorpio/Oxen (born October 23 - November 21 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) will be your nemesis. They demand too much in return for any security they may be willing to provide.`,
    homeAndFamily: `Surrounded by family and friends, living in a comfortable house in a friendly neighborhood in a warm climate and adhering to a routine (preferably imposed by a mate or the kids’ schedules), the Aries/Goat will shine. It is at home that the Aries/Goat feels sufficiently secure and warm to really dig in and get at some of the wealth of creative talents he or she owns. Aries/Goat will knit sweaters in crazy difficult patterns for the whole family. They like to dig in flower beds and apply their imaginations to planning new ways to show off their prize magnolias. Aries/Goat simply love to live for others—especially others who appreciate them for who they are and don’t ask them to try to be what they are not.

For the Aries/Goat’s sense of self to thrive, it will be best to reside in a posh neighborhood. Aries/Goat wants to shop at the best gourmet food stores, provide the family with the finest in every available product and will not be above a little showing off for the sake of chic neighbors. In such an atmosphere of luxury and plenty, the Aries/Goat will be able to exercise his or her remarkable talent at parenting. When you think about this person’s extreme duality—the Goat sensitivity vs. the brave drummer boy Aries—you can see why this person deals well with children. Understanding? Yes. But only to a point.

Aries/Goat children must be made to feel safe. They will suffer enormously from divorce or family separations. This is a sensitive and trusting nature. Don’t change his school too often or uproot the Aries/Goat child if you can help it. Instead, try to keep everything running smoothly so Aries/Goat will develop his multiple talents and fine intellect.`,
    profession: `Personal gain is not necessarily this native’s most urgent need. The average Aries/Goat doesn’t dream of making a million dollars, having a yacht and thirty nubile slave girls running around on that yacht waving fans—or fannies. No. The Aries/Goat is not a grasping, vaulting Onassis type. The Aries/Goat will however be willing to die for the success and achievement of someone he loves. There are two reasons for this willingness to take a back seat to another’s spotlight: 1) Aries/Goat depends on others for security. 2) Aries/Goat is most talented at loving. To watch somebody he loves rise to the heights he has always wished for is one of the true dreams of the happy Aries/Goat.

So, ideally, the Aries/Goat should either be cared for by the loved ones he or she has encouraged and nurtured along or be the beneficiary of a large trust fund. But if for some reason either of those solutions is impossible, if Aries/Goat finds himself on his own and penniless, I suggest he go instantly to the nearest bank, borrow a lot of money and open a flower shop. Beautiful things and Aries/Goat make excellent companions. They can be superlative decorators and savvy designers – even trend setters. Obviously, they work best in “glamour” jobs.`,
  },
  "Aries/Monkey": {
    description: `Talkers one and all, Aries/Monkeys are among the finest, most forthright people around. If you ever get to know one and then leave her behind, I believe your most intense souvenir of her personality will be the things she said. Aries/Monkeys are noted for their directness in speech. They can talk your leg off. But they are almost never boring.

Bright and garrulous, Aries/Monkeys are also gifted with the ability to feel for others. They have built-in compassion and truly care for those they love. Coupled with the wit and intelligence of a Monkey nature, this Aries subject’s drive is unbeatably attractive. However, you sometimes feel as though you can’t turn this person off, that inside your Aries/Monkey friend is a really just a non-stop radio talk show. This garrulousness can be charming—or exhausting. Talkative Aries/Monkeys are not exempt from repetition for the sake of emphasis either. There comes a moment when you might want to flick the “on/off’ switch and hear some soothing silence for a change.

There is little an Aries/Monkey can do that won’t lead to success. Accomplishment is this person’s middle name. They are not exactly your average hard-driving-killer-scrambler-elbow-the-others-out-of-the-way-getahead achievers either. No. Aries/Monkeys achieve in areas where they choose to excel. They are not compelled by gain or social approbation. Instead, they measure success by their own built-in standards. What you or I may think really is immaterial.

Aries/Monkeys have second sight. They can see around corners. This sign endows its owners with an uncanny ability to judge the worth and wiles of others. I have seen Aries/Monkeys cut through more bunk than twelve brand new razor blades. Watch them. When they are confronted with a new acquaintance Aries/Monkeys are pleasant and polite and nod their simian little heads, “Yes. Mmmmm. Hmmm. I see,” while the other person is blathering away some nonsense.

Afterward, when the blatherer leaves and you are alone with your Aries/Monkey, he or she will eye you, gauge your approachability and then say, “Did you see that guy who just left?” Yes. You saw him. What about him? (And here comes the good part.) Aries/Monkey pulls up his wiry frame and leans over to your ear in a confidential pose. “That man is a charlatan!” says Aries/Monkey. “He told me had gone to Yale. But he’d never heard of Old Eli and he claimed that the name of his dormitory was Holiday Inn.”

It’s hard to fool the cunning Aries/Monkey. Obviously, the Aries trait of naiveté is overruled by the Monkey’s extreme guile. And it’s a good thing. A skeptical Aries is a happy Aries.

The Aries/Monkey is also a firm individualist. Although gregarious, this person is capable of solitary forays inside himself, whence he is sure to dredge up many cunning ideas. Aries/Monkeys can study hard and achieve excellent results where application of derrière to seat of chair is a prerequisite. They are patient. Not slowly and deliberately patient. But patient nonetheless.

Aries/Monkeys go out of their way to be seductive and charming. If they are not naturally attractive, they get themselves up in ways that ensure appeal. They are what we used to call “striking” people. Unforgettable. One of the pitfalls Aries/Monkeys must watch for is their excessive superstition. People born under this sign tend to be drawn to the mystical rather than the logical solution in an emotional dilemma. They must learn to consult those wiser and more down-to-earth than they. Aries/Monkeys are perfectly capable of heeding good counsel. But they must learn to go out and seek it, not be afraid to appear foolish or untrained in any area at all. This person is able to assimilate anything, but sometimes he goes looking for knowledge in the wrong places.

The Aries/Monkey is basically balanced and stable. But little creeping superstitious doubts can creep in, which will temporarily flummox Aries/Monkeys, cause them to waste time in futile equivocation and tire them uselessly.`,
    love: `In matters of the heart Aries/Monkeys are not, by nature, constant. They can, however, learn to play at being monogamous with great conviction and success. They usually have spouses. But that doesn’t always mean they spend long evenings by the fireside reading the Bible to their faithful mates. Not Aries/Monkeys. They like to be out in the world, chatting at everybody and getting chatted back at by lots of people. Aries/Monkeys love contact.

The tinge of infidelity of which I speak does not prevent our Aries/Monkey subject from indulging in relationships of long-standing worth where passion is the main driving force. Aries/Monkeys are, on the contrary, very fiery and involved lovers. They can get so interested in the dynamics of their relationships that sometimes they can’t even remember to find others more attractive.

If you love an Aries/Monkey, don’t be boring. Keep moving and shaking. Hanging around the kitchen baking cakes will not do the trick. To amuse an Aries/Monkey you have to be on your toes all the time, traveling and entertaining, giving parties, and attending bashes and dos. The Aries/Monkey is a tireless consumer of company. Rent a circus tent and put it in the backyard. Fill it up with new acts and audiences every day. A do-it-yourself three-ring circus might keep the Aries/Monkey content for about a week. But don’t count on it.`,
    compatibilities: `Go for a Leo/Dragon (born July 23 - August 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or Leo/Rat (born July 23 - August 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032). They will find you irresistibly charming. You are drawn to their power. Rats and Dragons in general leave you anything but cold. But you will find particular pounding in your chest cavity over Geminis (born May 21 - June 20), Aquarians (born January 20 - February 18) and Sagittarians (born November 22 - December 21) of those same animal sign groups. Stay away from Capricorn/Tigers (born December 22 - January 19 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Capricorn/Pigs (born December 22 - January 19 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031), and Cancer/Tigers (born June 21 - July 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Cancer/Pigs (born June 21 - July 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031), and don’t become bewitched by the luscious Libra/Snake (born September 23 - October 22 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) or you’ll be sorry you did.`,
    homeAndFamily: `This heady talker will be the happy center of his or her family group. Monkeys tend to have a lot of children and spend untold hours teaching and showing their kids new things. An Aries/Monkey may even pillow fight and roller skate with offspring. The Aries/Monkey enthusiasm for communication is such that he’ll put up with almost any activity as long as he gets to play, too. I’ve said it before. Aries are boyish. Monkeys tend to silliness and juvenility. Imagine the gags at the dinner table, the tricks played on grandma and the giggles while hiding under the bed so Nancy won’t find you. I know an Aries/Monkey who, when he was a kid, filled up his father’s glassed-in shower stall with canned aerosol whipped cream. The father was the type who blindly crashed from his bed at six and never opened his eyes till he was under the stinging shower’s invigorating splash. You can picture this middle-aged executive type, stark naked and spluttering, with whipped cream everywhere, in his ears and under his fingernails . . . everywhere! The Aries/Monkey was doubly proud of this caper because as he told me, “Dad had to go right out and play tennis. He was already late. So he left with half the cream still sticking to him. The cream soured in the sunshine on the court. And he smelled awful. Rancid! It was a riot!”

Typically, Aries/Monkeys love fun. The more the merrier. It’s difficult to upset the natural equilibrium of an Aries/Monkey child. But keep him safe from superstition, watch out for an attraction to sects and excessive attention to mysticism.`,
    profession: `Do-it-yourself projects and manual efforts do not daunt the spirited Aries/Monkey. Yet this person is not likely to choose a thoroughly manual career for life. However, if obliged by circumstances, Aries/Monkeys can do everything well.

The Aries/Monkey’s outgoing personality can take him or her far in almost all jobs. It will be Aries/Monkey who organizes the picnics and invites everybody back to his place for coffee. People are drawn to and enjoy gathering at Aries/Monkey’s house. His wiliness and ability to swerve precisely at the right moment, although useful to any boss, may cause some office jealousies. Aries/Monkeys are well advised not to volunteer for every chore, and to resist the temptation to play the willing employee else he might be accused of boot-licking.

A useful character trait in Aries/Monkey people is that of be willing to take a back seat. It doesn’t bother the clever, capable Aries Monkey to be the brains behind a whole complex operation and not have his name appear in gold letters on the office door. For Aries/Monkey the important thing is achievement—not what the achievement means to outsiders. Many Aries/Monkeys hold important independent positions, opening their own companies or running their own shops. They are attracted to career fields where perspicacity counts—fashion, psychology, teaching, medicine, commerce. Whatever career this subject chooses will eventually work out for him. The Aries/Monkey is a natural.`,
  },
  "Aries/Rooster": {
    description: `Like all Roosters, the Aries/Rooster is a boiling teakettle of enthusiasm. Every single second of life for this character is full to overflowing with activity and eagerness. Aries/Roosters would like to try everything at least once. And if these tests bring them pleasure or intense experience, they would like to try them again, please. This Aries is generous and outgoing, talented, versatile, and curious to a fault.

You’ll never see an idle Aries/Rooster. Lying down or sitting still for long periods of time tends to create a malaise in the ever-whirling Aries/Rooster soul. Exoticism magnetizes this subject. Would you like to go across Siberia to China on foot, but cannot find anyone to accompany you because they’re afraid they won’t find a clean bathroom or a decent cup of coffee along the way? Call an Aries/Rooster. They’ll be packed and ready with a thermos of espresso and a portable shower before you can say “passport.” Their resilience and candor make them fearless in the face of the unknown, and their chic sense of style ensures they’ll look Hawkins look fabulous while doing it.

The Aries/Rooster’s Aries side fuels their drive to take charge and blaze new trails, while the Rooster’s conservatism keeps them grounded in tradition and pride in their achievements. This blend makes them natural leaders who inspire others with their humor and enthusiasm, but their cockiness and tendency to boast can sometimes rub people the wrong way. They’re not afraid to speak their mind—often with a sharp wit that can either charm or sting. Their blind faith in their own abilities can lead to bold moves, but also to occasional overconfidence.

Aries/Roosters are drawn to the spotlight and thrive in environments where they can showcase their talents. They’re not content to blend into the background; they want to be noticed, admired, and remembered. Their bossiness can make them demanding in group settings, but their infectious energy often makes others willing to follow their lead. However, their penchant for dissipation—whether through lavish spending or overindulgence in life’s pleasures—can sometimes derail their ambitions if not kept in check.`,
    love: `In love, the Aries/Rooster is a whirlwind of passion and charm. They pursue romance with the same fervor they apply to everything else, diving headfirst into relationships with grand gestures and bold declarations. Their enthusiasm is contagious, making them magnetic partners who can sweep anyone off their feet. However, their bossy streak and need for attention can make them high-maintenance lovers. They crave admiration and can become petulant if they feel ignored.

To keep an Aries/Rooster happy, you’ll need to match their energy and appreciate their flair for the dramatic. They’re not subtle, so expect big, showy displays of affection—think surprise weekend getaways or extravagant gifts. Their conservative streak means they value loyalty and commitment, but their Aries impulsiveness can lead to fleeting infatuations. If you’re involved with an Aries/Rooster, keep things exciting and don’t skimp on the praise. A little flattery goes a long way with this sign.`,
    compatibilities: `You’ll find sparks with Gemini/Snakes (born May 21 - June 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) or Gemini/Monkeys (born May 21 - June 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028), who can keep up with your fast-paced lifestyle. Leo/Dragons (born July 23 - August 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Sagittarius/Rats (born November 22 - December 21 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) or Sagittarius/Dragons (born November 22 - December 21 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) will match your fire and ambition. Aquarius/Snakes (born January 20 - February 18 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) or Aquarius/Roosters (born January 20 - February 18 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) can handle your intensity and add their own quirky charm. Steer clear of Cancer/Pigs (born June 21 - July 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) or Cancer/Dogs (born June 21 - July 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030), who might find your brashness overwhelming, and avoid Libra/Oxen (born September 23 - October 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), whose deliberateness will frustrate your need for speed. Capricorn/Tigers (born December 22 - January 19 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) are too stubborn to mesh with your domineering side.`,
    homeAndFamily: `The Aries/Rooster’s home is a reflection of their vibrant personality—bold, stylish, and meticulously organized. They take pride in creating a space that’s both functional and eye-catching, often with a touch of flair that screams “look at me!” As parents, they’re deeply involved, encouraging their kids to shine as brightly as they do. They’ll be at every school event, cheering the loudest and probably organizing the after-party. However, their bossy nature can make them overly controlling, expecting their family to fall in line with their vision.

Aries/Rooster children are precocious and full of personality, often stealing the show with their wit and charm. They’ll need guidance to temper their boastfulness and learn patience, but their natural talent and drive make them standouts in any crowd. Encourage their creativity but set firm boundaries to keep their cockiness in check. They thrive on attention, so give them plenty of opportunities to perform—whether it’s in school plays, sports, or family talent shows.`,
    profession: `Aries/Roosters are born for the spotlight. They excel in careers where they can lead, inspire, and be recognized—think event planning, public relations, or entertainment. Their enthusiasm and resilience make them unstoppable when they’re passionate about their work, but their pedantry can make them nitpicky bosses. They’re not afraid to take risks, and their Aries drive ensures they’ll push through obstacles to achieve their goals.

As employees, they’re the ones pitching bold ideas in meetings and rallying the team, but their need to be the center of attention can sometimes overshadow others. As bosses, they’re charismatic leaders who motivate with humor and high energy, but their bossiness can alienate quieter team members. Independent roles suit them best, where they can strut their stuff without answering to anyone. Fields like marketing, fashion, or media are perfect for their flair and ambition, but they’ll need to watch their tendency toward dissipation to stay focused.`,
  },
  "Aries/Dog": {
    description: `The Aries/Dog is a loyal warrior, combining the Aries’ fiery courage with the Dog’s steadfast devotion. This person is a protector at heart, always ready to charge into battle for a cause or defend those they love. Their Aries drive pushes them to take bold action, while the Dog’s loyalty keeps them grounded in duty and responsibility. The result is a person who’s both a fearless leader and a reliable ally, but their tendency to worry and criticize can make them their own worst enemy.

Aries/Dogs are not ones to sit idly by—they’re always on the move, seeking new challenges or righting wrongs. Their nobility and sense of duty make them natural advocates for justice, often throwing themselves into causes with a fervor that can border on obsession. However, their Dog-born introspection leads to bouts of self-doubt, and their pessimism can cast a shadow over their natural enthusiasm. They’re prone to overthinking, which can slow their Aries impulsiveness, sometimes to their detriment.

This combination produces a person who’s both inspiring and intense. Their heartiness and affability draw people in, but their uneasiness can make them seem distant or overly critical at times. They’re not afraid to speak their mind, often with a bluntness that reflects both Aries’ candor and the Dog’s insistence on truth. Their loyalty is unshakable, but their cynicism can make them suspicious of others’ motives, leading to occasional clashes.

Aries/Dogs thrive in structured environments where their reliability and enterprise can shine. They’re the ones you call when you need someone to take charge and get things done, but their worrywart nature means they’ll lose sleep over the details. Their talent lies in their ability to inspire trust and lead with conviction, but they must guard against letting their critical streak alienate those around them.`,
    love: `In love, the Aries/Dog is fiercely devoted but not always easy to live with. Their Aries passion makes them ardent lovers, quick to fall hard and shower their partner with attention. However, the Dog’s loyalty comes with a side of clinginess, and their critical nature can lead to nitpicking or overanalyzing their partner’s actions. They need a partner who can handle their intensity and reassure their worried mind.

Aries/Dogs are protective to a fault, often putting their partner’s needs above their own. They’re not afraid to fight for the relationship, but their pessimism can make them quick to assume the worst during conflicts. To keep them happy, offer stability and honesty—they value trust above all else. Their ideal partner is someone who can match their energy but also provide the calm reassurance they crave.`,
    compatibilities: `You’ll find harmony with Gemini/Tigers (born May 21 - June 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or Gemini/Horses (born May 21 - June 20 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026), who share your zest for life. Leo/Dogs (born July 23 - August 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) or Leo/Tigers (born July 23 - August 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Sagittarius/Horses (born November 22 - December 21 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) or Sagittarius/Dogs (born November 22 - December 21 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) will fuel your passion and loyalty. Aquarius/Tigers (born January 20 - February 18 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or Aquarius/Pigs (born January 20 - February 18 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) can offer the balance you need. Avoid Cancer/Snakes (born June 21 - July 22 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) or Cancer/Roosters (born June 21 - July 22 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029), who may clash with your critical side, and steer clear of Libra/Oxen (born September 23 - October 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) or Capricorns born in Rat (born December 22 - January 19 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) or Snake (born December 22 - January 19 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) years—they’re too rigid for your fiery spirit.`,
    homeAndFamily: `The Aries/Dog’s home is a fortress of loyalty and comfort, reflecting their need for security and their drive to create a safe haven. They’re the parent who’s always there for their kids, cheering at games and double-checking homework, but their critical nature can make them overly strict. They want their family to live up to their high standards, which can sometimes feel stifling.

As children, Aries/Dogs are dependable but sensitive, often taking on responsibilities early and worrying about letting others down. They need encouragement to balance their duty-bound nature with some Aries-driven fun. Give them tasks to build their confidence, but don’t let their introspection turn into brooding. A supportive family environment helps them channel their energy into positive outlets like sports or community service.`,
    profession: `Aries/Dogs are born for roles where they can make a difference—think law enforcement, social work, or advocacy. Their Aries enterprise pushes them to take on big challenges, while their Dog reliability ensures they follow through. They’re not afraid to lead, but their critical streak can make them tough bosses who demand perfection. As employees, they’re the ones staying late to get it right, though their worry can lead to burnout.

Independent roles suit them well, especially in fields like journalism or nonprofit work, where their sense of duty and talent for action shine. They need to avoid getting bogged down in details or letting their cynicism undermine their confidence. Success comes when they focus on their strengths: loyalty, courage, and an unyielding drive to do what’s right.`,
  },
  "Aries/Pig": {
    description: `The Aries/Pig is a fascinating blend of fiery ambition and earthy sincerity. This combination fuses the Aries’ bold, pioneering spirit with the Pig’s honest, pleasure-seeking nature, creating a person who is both driven and deeply human. Aries/Pigs are warm, generous, and fiercely loyal, but their naiveté and tendency toward indulgence can sometimes lead them astray.

Aries brings a headstrong, energetic approach to life, always ready to charge toward new goals with unbridled enthusiasm. The Pig, however, tempers this impulsiveness with a love for comfort, beauty, and the finer things in life. This makes the Aries/Pig a curious mix: a go-getter who dreams of grand achievements but also craves the security of a cozy, well-appointed home. They are not content to simply conquer; they want to enjoy the spoils of their victories in style.

This person is a natural charmer, with a knack for making others feel valued and appreciated. Their gallantry and sincerity draw people in, and they often find themselves surrounded by friends and admirers. However, their Aries-driven willfulness can clash with the Pig’s credulity, making them vulnerable to manipulation or overly trusting in situations where caution is warranted. They may leap into projects or relationships with boundless optimism, only to realize later that they’ve overlooked critical details.

Aries/Pigs are not afraid of hard work, but they work best when inspired by a cause they believe in or a reward that appeals to their sensual side. They have a taste for luxury and are not above indulging in lavish dinners, fine wines, or extravagant purchases. This can sometimes lead to financial strain, as their Aries impulsiveness pushes them to spend before they’ve fully considered the consequences. Yet, their Pig-born honesty ensures they’ll own up to their mistakes and strive to make things right.

The Aries/Pig’s emotional life is rich and intense. They love deeply and are fiercely protective of those they care about, but their temper—fueled by Aries’ fire and Pig’s occasional anger—can flare up when they feel betrayed or slighted. They are not ones to hold grudges for long, though, as their sincere and forgiving nature usually wins out. They thrive in environments where they can express their creativity and passion, whether through art, hospitality, or any endeavor that allows them to connect with others on a meaningful level.`,
    love: `In love, the Aries/Pig is a romantic at heart, combining Aries’ passionate intensity with the Pig’s voluptuous sensuality. They throw themselves into relationships with the same fervor they apply to their ambitions, showering their partner with affection and grand gestures. Their sincerity makes them devoted partners, but their lustful side can lead to impulsive romantic decisions. They need a partner who can handle their emotional intensity and appreciate their need for both excitement and comfort.

To keep an Aries/Pig happy, indulge their love for beauty and pleasure—think candlelit dinners or weekend getaways to luxurious destinations. Their naiveté can make them vulnerable to heartbreak, so honesty and loyalty are non-negotiable. They’re protective and generous lovers, but their temper can spark during misunderstandings, so patience is key. A partner who shares their zest for life and doesn’t mind their occasional extravagance will keep the flame burning bright.`,
    compatibilities: `You’ll find chemistry with Gemini/Rabbits (born May 21 - June 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) or Gemini/Pigs (born May 21 - June 20 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031), who share your love for culture and pleasure. Leo/Pigs (born July 23 - August 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) or Leo/Snakes (born July 23 - August 22 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) will match your passion and flair. Sagittarius/Rabbits (born November 22 - December 21 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) or Sagittarius/Pigs (born November 22 - December 21 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) can keep up with your adventurous spirit. Aquarius/Goats (born January 20 - February 18 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) or Aquarius/Rabbits (born January 20 - February 18 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) will appreciate your sincerity and add their own creative spark. Avoid Cancer/Roosters (born June 21 - July 22 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) or Cancer/Oxen (born June 21 - July 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), who may find your intensity overwhelming, and steer clear of Libra/Dragons (born September 23 - October 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or Capricorn/Snakes (born December 22 - January 19 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025), whose pragmatism clashes with your impulsive side.`,
    homeAndFamily: `The Aries/Pig’s home is a sanctuary of warmth and elegance, filled with plush furnishings, art, and the scent of gourmet meals. They take pride in creating a space that’s both inviting and impressive, reflecting their love for culture and comfort. As parents, they’re nurturing and protective, but their Aries dominance can make them overly controlling at times. They want their kids to shine, often pushing them toward creative or ambitious pursuits.

Aries/Pig children are affectionate and imaginative, with a natural charm that wins hearts. They can be impulsive and indulgent, so parents should encourage discipline while nurturing their creative talents. Give them a cozy, stimulating environment—think art supplies, music lessons, or a well-stocked kitchen—to keep them engaged and happy. Their sincerity makes them loyal siblings, but their temper needs gentle guidance to avoid family spats.`,
    profession: `Aries/Pigs are drawn to careers that blend creativity and ambition—think culinary arts, interior design, or event planning. Their Aries drive pushes them to take on big projects, while their Pig love for culture ensures a refined touch. They’re not afraid to lead, but their credulity can make them susceptible to bad business deals, so they need trusted advisors. As bosses, they’re inspiring but demanding, expecting others to match their passion. As employees, they’re hardworking but may clash with authority if it stifles their creativity.

Independent roles suit them best, where they can set their own pace and indulge their love for beauty. They thrive in fields like hospitality, fashion, or the arts, where their gallantry and taste shine. To succeed, they must balance their impulsiveness with the Pig’s scrupulousness, ensuring their grand visions don’t outpace their resources. With focus, their talent and sincerity can lead to lasting success.`,
  },
};
