// src/lib/new-astrology/cancer.ts

export const cancer = {
  "Cancer/Rat": {
    description: `Because he is born a Rat, the Cancer/Rat naturally lives by his wits. But as he is also a moon child and hence tends to drown in his own emotions this person’s behavior wavers. The Cancer/Rat, we say, is a “private” person. He likes to crawl into his cubbyhole in the tower where he studies life and writes about interior subjects. But just when you think the Cancer/Rat has hidden away for good, will only venture out for the odd crust of bread and seems to be surviving on coffee and water up there in that tomblike turret, an invitation arrives at your door requesting the honor of your company at a huge reception complete with great groaning boards of food and gaiety and sociability to boot. Who is your host or hostess but your favorite recluse, the Cancer/Rat.

Be he a writer or a carpenter, a musician or a head nurse, this character will always be sure to have plenty of evidence of material wealth around him. Objets d’art and antiques abound where the Rat/Cancer lives. Books crowd the shelves, first editions and comic books and the latest jazz reviews, everything counts—especially if it has words on it. Cancer/Rats adore the written word.

This subject is likely to favor a singular elegance in his dress habits. He wishes to stand above the fashionable crowd, to exhibit his individuality through his manner of dress. Even his coiffure will cry: “Me! Look at me! How different I can be!!”

Cancer/Rats like society, but they need to stand apart from banality. They resist mediocrity in every choice they make, whether it be friends or lovers, houses or cars, trips or vacation spots. Not that Cancer/Rats go after the popular “best” or the trammeled idea of what is superior. Rather, they seek their own brand of excellence, and once they have found it, adhere to it like super glue.

Charm is part of the Cancer/Rat’s panoply of qualities, too. He is not your average Don Juan or Lothario though. He won’t sidle around trying to get cozy with you just for the fun of it. Cancer/Rats try to be appealing in spurts. They will invite you to a play or take you to lunch just to be agreeable and pleasant. But the Rat/Cancer charm is subtle. It can even be a little off-putting. You are never quite sure if the Cancer/Rat is going to smile or snap. You cannot tell whether he’s in pain or just looks that way and is instead on the verge of a huge guffaw. The charm of Rat/Cancer is inscrutable.

Like all Rats, this Cancer/Rat is talkative. Unlike, say, an Aries or Leo/Rat, however, this Rat subject will enjoy talking about his feelings. “Do you think he really likes me? Can you tell if I am getting the right vibes? I’m so sad, happy, miserable, pained, ecstatic, joyful bored, annoyed. . . .” If you like this character and want to have him as a friend, you must polish up all of your listening devices. Not only does this person restoke his furnaces in company that he knows how to assemble to this end, but he’ll drub your ears until they fall off in order to figure out vocally what his next step ought to be. There is no question about it, this person thinks on his feet. And remember, don’t try to be the star. When you are at a Cancer/Rat party, you are a mere guest on “The Cancer/Rat Show.”

Creativity abounds in the people born under the signs of Cancer and Rat. The obvious depth of Cancer emotion coupled with the Rat’s tendency to ferret out information infuses this person with a natural talent for writing stories. Too, as the Cancer/Rat possesses this excessive need to expound his feelings and rehash his emotions and ideas, writing books or poems or songs is the perfect therapy for him. Cancer/Rat is a private soul trapped in the body of a public personality.

A curiosity about justice and doing the “right thing” by others causes people born in Cancer/Rat to expend a lot of energy in litigious activity. Not that Cancer/Rats grow suddenly furious and want to get revenge on enemies, but they feel that fair is fair in life and will go to the fore to help a friend in legal trouble or to sort out the truth in a complex dossier. This tendency to want to see that justice is done can sometimes be a form of meddling. I have had a couple of winning, voluble, loyal Cancer/Rat friends who, because they thought my current beau was being unfair me or was behaving in a “macho” fashion, literally edged the unsuspecting gentlemen out of my life. In one case, I think the relationship would have died its own death soon enough. But in the other case, I really wasn’t finished with loving the poor fellow. But my Cancer/Rat friend deemed him unworthy of me. And she chucked him out. Really.`,
    love: `A fascinating subject to love. In romantic situations, Cancer/Rat is always miles ahead of his mate, calculating and feeling, intuiting and sensing, what should happen next. His goal in love is never to be bored, to maintain his passionate sentiment at a pitch difficult to achieve even at age seventeen.

For these ends, the Cancer/Rat is known to be deliberately fugitive, hard-to-get, maverick and elusive. As we already know, he is secretive. When you do notice him from time to time, sleeping next to you as though he hadn’t been gone for ten days (and you don’t dare ask where), it seems such a blessing, a miracle, that you just accept and get on with it.

The Cancer/Rat is not necessarily unfaithful. He may not have gone away for ten days with anyone but himself. But he does usually have many successive lovers and at least a few mates in his busy life.

If you love a Cancer/Rat and want to hang on for a while, I suggest you practice examining his face for signs of retreat, bad temper, dreaminess and /or lust. When you learn to read your Cancer/Rat’s cryptic facial features, you will have won half the battle. Don’t try keep him down on the farm. Don’t fence him in. Don’t smother him with marshmallow kisses. But do provide a secure and safe environment (complete with ivory tower) for his personal development, give him expensive presents, and above all, clean out your ears. You’ll be needing them.`,
    compatibilities: `You are extremely love-oriented. Partners suitable for you will be readily found among Taurus (born April 20 - May 20), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21) and Pisces (born February 19 - March 20) subjects. Prefer Oxen (born 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) and Monkeys (born 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028). They understand your brand of subtle power play. You clash with Horses, especially Aries/Horses (born March 21 - April 19 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026), Libra/Horses (born September 23 - October 22 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) and Capricorn/Horses (born December 22 - January 19 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). Don’t be flattered by the attention of Aquarian/Rabbits (born January 20 - February 18 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), Libra/Rabbits (born September 23 - October 22 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) or Capricorn/Rabbits (born December 22 - January 19 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035). They are not patient with your nervous (and sometimes gloomy) nature.`,
    homeAndFamily: `You won’t find this person happy living in a hovel. The Cancer/Rat’s surroundings will be luxurious and original. The normal plenty of any Rat’s pantry will be redoubled by the inclusion in his sign of the hoarding, acquisitive Cancer. Cancer/Rats are noted for their chic, well-appointed homes, where the dining room is the center of activity. Family dinners and gatherings are essential to this character’s equilibrium. His kin come first. And to defend them, the Cancer/Rat would kill.

As a parent, the Cancer/Rat is strict, possessive and grasping. At first, he loves willingly and without question all of his children equally. Then as time passes and the children begin to take on individualities and express their own desires, the Cancer/Rat will be guilty of some favoritism. He may unconsciously choose to favor the child who needs him most, the kid who can’t make it without Mom or Dad’s help. Cancer/Rats don’t particularly admire independence (from them) in their kids. A strong-minded child who disagrees with his Cancer/Rat parent should leave home early to escape tyranny. The Cancer/Rat feels he must protect his offspring. To do so, he sometimes meddles in their lives.

A Cancer/Rat child will surprise you by turns with his seeming solitary ways and his perfect sociability. The loner side of his nature should be encouraged, as this often difficult and testy-natured child will grow into his own skin best if he has time to do so at his own speed in his own place. Try not to force him to share his toys or his room with a sibling. The Cancer/Rat child is an independent sort.`,
    profession: `It’s difficult for me to imagine any Cancer/Rat who is not a writer. I have four close Cancer/Rat friends and they are all writers. The Cancer/Rat career dice seem to be loaded in favor of the pen. I don’t see this watery creature as an executive or even a whistling happy worker bee. There’s so much emotion to be expressed, so much heart over head in this subject, that I can best imagine him or her in artistic or art-related fields. Of course, as an independent, this person could surely choose dentistry or medicine or law as a career. He certainly has the intellectual wherewithal. Politics and government jobs are out. The Cancer/Rat hates witnessing corruption. If he works in an office he will rail at all in-office inequities. And he won’t stick around very long if he feels these same injustices are about to be wreaked on him. The Cancer/Rat is quick-tempered and a mite snooty when attacked.

The Cancer/Rat is a hard worker. But he will not be pushed or bossed. Jobs requiring solitude or independence will work for him. Even commerce—if he owns his own store—can serve him well. He should, however, steer clear of careers that require plodding and day-to-day hypocrisy. He cannot hack phony smiles and insincere pats on the back.`,
  },
  "Cancer/Ox": {
    description: `It is no coincidence that many, many famous and respected artists of all sorts were born under the twin signs of Cancer and Ox. Here is the personification of determination. The profound sensitivity of Cancer coupled with the Ox’s down-to-earth strength of purpose creates in this creature an emotional forcefulness unparalleled anywhere else in the new zodiac. This person always tries harder.

The Ox side of this subject’s character endows him or her with formidable powers of tenacity and innovation. Cancer gives even more creativity and adds a hefty dose of feeling to the cocktail. These folks go after what they want with acute single-mindedness. For a Cancer/Ox a task is a chore is a rule is a religion! What must be accomplished must be, and there are no two ways about it, no shortcuts, and no tricky escape routes.

Cancerian Oxen hate to fail. Neither do they like to be told what to do or when or how to do it. They are a law unto themselves. They admit it. Yes. They are bossy and smothering and overly possessive. If you don’t like that, then you will have to take your business elsewhere.

The great size of the Cancer/Ox’s achievement is equal to his feeling for those he loves and those who have shown him loyalty. With these people he will share generously. But woe unto Cancer/Ox’s enemies. Woe and begone. The Cancerian born Ox has no room in his spirit for self-doubt. If anyone tries to worm his or her way underneath the Cancer/Ox’s self-confident shield, the Cancer/Ox will quite simply eliminate them. Cancer/Ox is unforgiving and vengeful.

When you encounter such a character, naturally you know you have met someone extraordinary. Cancerian Oxen radiate a dense golden light of superiority. They know how to be alone. They know how to take their time. They know how to study hard. They know enough to get a good night’s rest before a big event. They are exasperatingly perfect, and it is for this reason (and not only because of their talent) that they succeed at what they do. The Cancer/Ox’s brain is nothing to be sneezed at either. These folks are bright. They don’t miss a trick and “never lose sight of the north,” as the French are wont to say. But Cancerian/Oxen are not the intellectuals of the twin zodiacs. Far from it. They are too watery to be strictly gray-matter-oriented. No. The Cancerian Ox is an instinctual being who operates out of grit and endurance. He knows from the beginning that the shortest distance between two goals is straight ahead, and so he applies himself and goes there. Simple, n’est-ce pas?

This person will strike you at first as a beaming, jolly type. He or she seems to proceed through life as though it were all a chuckle. They never let on that anything might be even vaguely wrong. Don’t be fooled. The Cancer/Ox is far less expansive in real life than he or she appears upon first meeting. In fact, they do not enjoy crowds and they only tolerate groups if they have summoned the group for a meeting or a family dinner. Cancerian Oxen are body snobs. They like to be left alone.`,
    love: `For Cancerian Oxen, love is their own private premise. They live for their love and very often stay with the same loved one for life. Cancer/Ox is gifted in love the way he or she is gifted in success. Long-lasting and serious love affairs and marriages take patience and courage and much compromise. The stubborn Cancer/Ox knows surprisingly well how to compromise in matters of feeling. Romance and caring for others is what Cancer/Ox considers his reward for all his grueling hard work. He hangs on in the most perilous of marital storms.

Don’t, however, expect daily bouquets or champagne with every meal. The Cancer/Ox is first of all a sensible being who wants to get somewhere in the realm of the real world. Yes, he or she definitely wants to be number one in your life, too. But don’t underestimate the Cancer/Ox powers of concentration on the concrete. If he needs to finish a job or concoct a new scheme, ardent passions can be abstracted and even forgotten for a time. Emotions and sex interest this subject only insofar as they don’t hinder his progress.`,
    compatibilities: `Strength and mood are your bywords. You seek both in a helpmate. How about a feisty self-sufficient Taurus/Rooster (born April 20 - May 20 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) or even a Virgo (born August 23 - September 22) or Pisces (born February 19 - March 20) of the rugged Rooster family (born 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029)? Or you might take up with a Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21) or Pisces/Rat (born February 19 - March 20) person for easy compatibility. Rats protect you from the outside world and are complicit in spending (or hoarding) your gains. Scorpio and Pisces/Snakes (born 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) make your heart beat faster, too. No Aries/Goats (born March 21 - April 19 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) or Libra/Goats (born September 23 - October 22 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) for you moonchild Ox. Goats in general exasperate you with their airy fairy notions. You will no doubt be fascinated by Tigers. But hands off! Tigers compete with you. Besides, they move too fast and confuse the issue with their undue speed. Capricorn/Dragons (born December 22 - January 19 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) are pretty to look at and lucky in love – but not with Cancer/Oxen.`,
    homeAndFamily: `This character’s snug surroundings promise to welcome the most desolate pilgrim to come in out of the cold. It’s always pretty at Cancer/Ox’s place. There’s a sense is of solidity and coziness together. Overstuffed sofas and traditional tables and comfortable armchairs around a roaring fireplace lend harmony to the Cancer/Ox’s headquarters.

This character will love children—all children. He may even take in strays and adopt orphans. He’s a nurturer, remember. His or her attitude toward kids is that they should be happy but respectful, comfortable but willing to work for their comforts. The Cancerian Ox doesn’t give a his hard-earned money for the sake of a sweet smile or flattering remark. The same holds true for his family. “I love you, but I can only do so on my own terms.” You may find the Cancer/Ox child slow to react and rather more deliberate than other, more active kids. The Cancer/Ox child doesn’t do much clowning or cutting up unless he knows well in advance that his act has been perfected. He likes to be good at things. So he waits till he’s polished them before he shows them off to others.`,
    profession: `One doesn’t have to look far to find your nearest Cancer/Ox’s professional talents. By the time they reach adulthood they will surely have a sound idea of what they want to do. They are definitely more artistically savvy than they are financial or scientific. There are two water signs at work here. Both of them are tough, persevering money-earners.

Where are the weaknesses? Well, this subject’s strength can also be his own worst enemy. Somewhere along the line, because of a categorical refusal to behave frivolously, they are going to miss out on some of the fun that “normal” people get themselves involved in. Also, if by some fluke they should fall into some light-headed scheme or other, they will suffer far more from its unfortunate results than will people who don’t take life so bloody seriously. If you are looking for servitude or subordination, don’t employ a Cancer/Ox. But if you are interested in perfection, professionalism to the nth degree, hire a Cancer born in an Ox year. You won’t be disappointed.`,
  },
  "Cancer/Tiger": {
    description: `Tiger people are essentially combative. Cancers are sensitive, moody and susceptible to melancholy. “Roar!” says the Tiger inside the Cancer’s sulky self. “I want my independence!” Or: “Give me some laughs!” Or “Send me some conflict!”

Cancer and Tiger are a strange, almost comical combo. There is, of course, a lot of true sentiment running around wild here. In fact, their worst enemy is loss of confidence and surrender to a dissolute and rudderless existence. Tigers are restless people who need to learn moderation. It is paramount to their survival. These brilliant subjects, you may recall, are in constant danger of being suddenly snuffed out—often as the result of their own excessiveness. Tigers need good counsel, advice, wisdom and common sense. Cancer is, for the most part, a sensible sign. But Cancers can drown in their own sensitivity. It’s a treacherous combination.

We are, of course, all capable of self-betrayal. We can all be duped sooner or later by our sentiments. But here, with the Cancer and the Tiger together, there is a dicey penchant for self-delusion. Hale and hearty go-get-’em Tigers scarcely ever look before they leap unless they have some brilliant lieutenant standing next to them saying, “Watch out, boss! Take it slow, sir! You may feel differently tomorrow, chief!” The Cancer, with his moodiness and tendency to sulk or brood, is hardly the snappy lieutenant type, is he now?

So the best thing to say to this character is “Watch out!” Take life by steps. Get yourself organized and stick to routines. Structure your life or have someone structure it for you. You will not enjoy this discipline. But it will advance you. And you will enjoy the advancement.

“Eccentricity” is an apt word to describe Cancer/Tigers. These people are capable of living a wholly bohemian life. But that would be a mistake. Cancer is too much of a bourgeois sign to follow in the nutty footsteps of the headstrong Tiger. Better to follow the moon child and go for the traditional home sweet home.

Everyone will enjoy knowing this person. He’s generally cheerful (except when he gives in to his Canceresque melancholy) and amusing. He’s a romantic, a dreamer who would change the world, make everybody nicer and more honest, a sentimental sort who longs for peace of mind and just about never achieves it.

Why? Well, the Cancer/Tiger is a mighty creative figure. New ideas and exotic places, people and pursuits attract him. Just when he or she appears settled and secure, bam! He’s off to new and more hair-raising adventures. You see, the Cancer/Tiger not only enjoys seeking out the unusual, but he likes to be noticed for having done so. The Cancer/Tiger is a preener and a proud fellow when it comes to receiving praise for accomplishment. Praise, in fact, brings out the best in this subject and should not be rationed in his regard. He won’t get a big head over it. Rather, it will urge the Cancer/Tiger on to bigger and better breakthroughs and conquests.

The Cancer/Tiger needs a lot of room to roam. Small spaces rub his back hairs the wrong way. He needs latitude and despite his home-loving nature on the one hand, this Cancer needs change. Even if he only moves the furniture around every other day, he likes to feel himself challenged by new environments.`,
    love: `Unlucky in love in the early part of his life, this person’s true emotional direction takes quite a while to develop. He or she will be very attractive to potential sex partners. Some important creative time can be lost here because of shilly-shallying with impromptu love affairs that rarely work out over the long run.

If you love a Cancer/Tiger, look up to him or her. Admiration and respect are what turn them on. The Cancer/Tiger needs to shine. He’s not a showoff, though. He’s really quite discreet. But he likes to be viewed from his best angle. Flatter him. And most of all, cuddle this lummox. The Cancerian Tiger is very jealous. He hates having his spotlight so much as tiptoed into by someone else. He will fight very hard if he’s attacked but is not the type to be aggressive in domestic situations. Don’t compete with your Cancer/Tiger lover. Instead, do your own thing and let him do his. Be ready for affection at all times. And don’t meddle in this person’s private business.`,
    compatibilities: `Tigerish Cancer that you are, you’ll find Taurus/Dogs (born April 20 - May 20 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030), Virgo/Dogs (born August 23 - September 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Scorpio/Dogs (born October 23 - November 21 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) beguiling. You may flip for Scorpio (born October 23 - November 21) and/or Pisces (born February 19 - March 20) Dragons (born 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Horses (born 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). And of course you find the cultured Pisces/Pig (born February 19 - March 20 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) irresistible. Don’t trifle with Aries (born March 21 - April 19), Libra (born September 23 - October 22) or Capricorn/Monkeys (born December 22 - January 19 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028). Stay away from Aries and Libra/Snakes (born 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and eighty-six all lubricious thoughts about Aries and Libra/Oxen (born 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). Don’t set your heart on a Libra/Goat (born September 23 - October 22 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) either. They are even more temperamental than you.`,
    homeAndFamily: `This area of the Cancer/Tiger’s life is rife with push-me-pull-you-ism. Where the Cancer is home-loving, the Tiger is a wanderer. Where the Cancer is moody and emotional, the Tiger is optimistic. The decor alone will be schizophrenic. Clashing colors and arcane styles abound. Of course the Cancer/Tiger is a natural parent. He or she loves his home and in it he sees family as part and parcel of the picture. The Tigerish side of this person’s character, his spirit of adventure and his tendency to dream, will enchant children. This person is likely to be the “pal” kind of parent whom kids like to hang out with. There will be a certain amount of discipline around the Cancer/Tiger’s house, but remember his bohemian side—a little mess makes a house look more lived in, now doesn’t it? Cancer/Tiger kids are strivers and achievers. But in order to get places they must be taught very early the value of rigor and self control. The marginal side of the character can be the undoing of a child later on in life. So from the start he must be encouraged to give in to routine. Small daily chores and regularity in meal and bedtimes will help this little person to focus his future.`,
    profession: `This character is only partially after gain. Material wealth is of some importance in his scheme of things. But (and this is a big but), because he’s a Tiger, this Cancer’s grabby side will be noticeably diminished. He may be the type who invents a wondrous new process, but when it comes to marketing it, he’ll seem to chicken out. He’ll back down in the face of the kind of long term involvement necessary for real advancement. He wants a BMW. He might even love to drive around in a Rolls-Royce. But if he takes the time to earn the means and then to protect the means thereafter, he fears he will be bored and that some other new wondrous processes will go undiscovered as a result. So Tiger/Cancers tend to live for what they can invent in life.

Of course this approach is good when you are the boss of the enterprise. If you hire the right people, you can stay in your crazy quilt lair and create your head off while your loving staff picks up the paperwork. It’s less desirable for an employee not to carry through on his serves. So, if possible, this subject should work for himself.`,
  },
  "Cancer/Rabbit": {
    description: `A startling combination of the home-loving and the home-loving, if the Cancer/Cat didn’t have to go out and make a living, he indeed might opt to never leave the comfort of his perfectly decorated, carefully appointed and cozily efficient house. To a Cancer born a Cat, the center of his universe is his hearth. If he has any enemies, they will only be able to really wound the Cancer/Cat where it hurts if they attack his epicenter—the home. Don’t get the idea that this person is a recluse. On the contrary, once he gets to know you, Cancer/Cat is a veritable bundle of amiability and chitchat. He lights up when he sees you and launches into a bevy of subjects to please you. Often, this person talks of things to come, dreams and future plans of castles (always castles or manor houses or mansions) in Spain or Normandy or in the lush green dank of Ireland. For Cancer/Cats there is always glory or brilliance and contentment! Ahead.

I know a few Cancer/Cats. They are the epitome of comfort, always inviting you right in to sit and have coffee or uncorking the kind of wine you like. And they invariably recount stories again and again about the day when their great Aunt Tillie, who is ninety-eight and a half, will pass away and their own life will become nirvana. “And don’t think I’ve always lived like this,” says the Cancer/Cat. “Why, in 1965 alone I spent over half what my poor husband earns today on help. Yes, I had maids. I was a lady!” You never really know if the past opulence and future inheritances actually exist. But finally, it’s not important. It is a matter of total indifference because wherever the Cancer/Cat is, in whatever tiny cove he runs aground, this character creates instant chintz curtains, comfy armchairs, a long generous table covered with pretty, tasty foods, and an aura of greeting and welcome that nobody could resist.

Spartans, beware. This Cancer/Cat could draw you into his fur-lined lair and cause you to renounce your faith in frugality. Cancer/Cats are dependable, too. And trustworthy. You can leave them your keys, your kids, your dog and your wife or husband and expect to return months later and find everybody sitting around drinking cocoa and playing Scrabble. No hanky-panky will have gone on behind your back. Cancer/Cats are honorable and virtuous people.

If pushed to the extreme, virtue has the bad habit of becoming self-righteousness or even pedantry. Cancer/Cats have to watch out for this tendency. They can wax a bit sanctimonious from time to time. Cancer/Cats can be guilty of impatience with those less “worthy” than themselves. This minor fault can grow into a real pain in the derrière if the Cancer/Cat feels cornered or threatened. Remember, Cancer/Cats are both crabs and felines. Superficially, they don’t represent any real physical horror or menace. But in both creatures there is the real, ever-present and close-to-the-surface possibility of claws! Be nice with Cancer/Cats. Don’t cross them or try to take their new vacuum cleaner away. These folks can be vicious when irked.

Cancers like to acquire things. Cats like to polish and refine things. Put them together and you have an antique dealer, or worse—a collector. These people collect stuff, hoard material goods and build up stocks of finery the likes of which would turn Sotheby’s or Christies green with jealousy. If you have a Cancer/Cat relative who has no other heir beside yourself, he may not look like a good prospect for a huge legacy with his modest attitudes, but in the attic this guy has more wealth than there are stars in the sky. Careful, cautious, prudent, ambitious, avaricious and secretive. Don’t forget that covert part of this character’s nature. He may strike you as sentimental and even self-pitying and sometimes maudlin, but take my advice: Stroke the pretty Cancer/Cat’s fur the right way—you may live not to regret it.`,
    love: `In love with love. I have that jotted in my Cancer/Cat notes. And it’s true. Cancer/Cats are invariably, unchangingly and impressively in love. Not infatuated or having a crush on someone. The Cancer/Cat is not interested in short-lived intimacies. He wants a home. He wants a family. He wants pretty furniture and authentic oak floors and baptisms and weddings complete with lilies and roses and champagne and chamber music. The Cancer/Cat is an ardent, squishy, soft and delicious love bug—with taste and discernment thrown in for good measure.

The Cancer/Cat needs a solid and faithful partner to accompany him through the vaulted halls of his home life. And one helpmate will suffice. The Cancer/Cat may have some jaunty adventures in promiscuity when young or at loose ends. But this is not a person who can live with a series of one-night stands. Cancer/Cats needs your love, all of it, unconditionally and forever. In return you will receive more than anybody’s share of security and illusion, dreams and cups of warm milky tea, cakes, and even a tiny drop of the finest claret from time to time. If you are lucky enough to fall into the clutches of a moonish Cancerian Cat, lie back and enjoy it. But don’t forget to take out the garbage, wash the windows, get the spare room ready for Grandma and pick up the gold mirror from the refinisher at five o’clock. You’ll be happy. But boy! Will you ever be busy.

Divorce or separation, breakups of all kinds will devastate the Cancer/Cat. No one perceives a broken home as more of a personal failure than the Cancer/Cat. He takes full blame. After a broken heart, the Cancer/Cat broods and sulks and licks his wounds for a long, long time. No rebound flings for this person. But just wait. When finally the Cancer/Cat locates his next true-blue soul mate, he backs off a little, crouches and then-pounce! You’re hooked for life. Do not try to escape. It’s useless.`,
    compatibilities: `Taurus (born April 20 - May 20), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21) and Pisces (born February 19 - March 20) catch your fancy. They are all capable of hunkering down in the coziness of you for life. You’ll particularly enjoy romance with Goats (born 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027), Dogs (born 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Pigs (born 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) of the above sign groups. I don’t see you taking up with either Aries/Tigers (born March 21 - April 19 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034), Libra/Tigers (born September 23 - October 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or Capricorn/Tigers (born December 22 - January 19 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034), Aries/Dragons (born March 21 - April 19 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), Libra/Dragons (born September 23 - October 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or Capricorn/Dragons (born December 22 - January 19 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), Aries/Roosters (born March 21 - April 19 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029), Libra/Roosters (born September 23 - October 22 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) or Capricorn/Roosters (born December 22 - January 19 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029). Too businesslike. You need gentility and a home-loving type to maintain both security and interest.`,
    homeAndFamily: `I’ve already described the Cancer/Cat’s ideal as home. You will be surprised at the number of times you will find him in when you phone this subject. You will marvel at the degree of order that reigns in this persons house. Life is always busily going forward and yet there is room for a smile, a little gab session, a brief gossip over the back fence. And the reason for this cauldron of household efficiency and good cheer? The Cancer/Cat is always chez lui. The Cancer/Cat is a tireless parent, generous and loving, warm-hearted and forgiving. But he’s also quite demanding of his kids. He is himself a tactful and discreet person with a bent for culture and exorbitant dreams of refinement.

It will therefore not do at all for a Cancer/Cat to have undisciplined, ill-kempt or clumsy, vulgar children. All of this person’s kids will respect and admire their Cancer/Cat parent. The Cancer/Cat is capable of great sacrifice for the sake of his kids—but he doesn’t let them forget it either. A Cancer/Cat child must be made to feel warm and secure. He may not seem the most outgoing kid at first. But when he feels really snug, then you will start to notice those crinkly smiles he’s to become so famous for. Surround him with culture. He will be capable of absorbing all variety of artistic endeavor. Don’t make him play football if he doesn’t want to. He’s a refinement freak. Not necessarily athletic-tough, but not necessarily a black belt in karate or an Olympic figure skater.`,
    profession: `Obviously, this home-lover can be a marvelous homemaker. Leave this person home all day and he’ll never be idle or bored. The framework of home life is sufficient to keep Cancer/Cats even-tempered and equilibrated for a long while.

If, however, this person ever gets out of the house, he is talented in medicine, teaching, picture framing or printing, curative and restorative jobs.

The Cancer/Cat makes an excellent, reliable and loyal employee. He can get along well with coworkers because he knows he ought to—not necessarily because he likes them or thinks they are fun to gab with in the cafeteria at lunch time. But the Cancer/Cat is a sensible creature. He knows which side his bread’s buttered on. He’d prefer to have a nice small cozy office with a door that shuts (he cares less for a window than a door) and locks to exclude untoward influences. As a boss, the Cancer/Cat will be efficient and just. He may not be liked by his employees because he seems a mite on the snooty side for their taste. But never mind. He gets the job done.`,
  },
  "Cancer/Dragon": {
    description: `Great emotional vitality is the foundation of this astonishing character’s personality. The Cancer/Dragon is born with all of Cancer’s profound ability to feel life in every aspect. Too, this subject is endowed with the Dragonish pluck and fire we all know and love so well. So we have here a forceful and dauntlessly enthusiastic character. Cancer’s eternal black moods will be lightened by the Dragon’s phoenix-like ability to rise from the ashes of his own immolation by his natural pep and vigor. Dragon’s unwieldy braggadocio will be tempered by Cancer’s good sense and dignity.

Cancer/Dragon is almost boyish in the variety of charm he exudes. He’s got just a soupçon of a twinkle in a very sensual glance. Bedroom eyes with a skylight. Cancer wants to keep this subject home. Dragon longs to race out and beat the world at any game in town. This creates a natural inner conflict. Who decides the issues? What breaks the camel’s back every time? Sentimentality. This Cancer/Dragon subject is terminally sentimental. With this sentimental side, of course, comes a tendency to be hypersensitive. The Cancer is the only Dragon who will cry at weddings and faint at baptisms and bar mitzvahs. They know how to mix feelings with theater. “It’s alarming how charming . . .” and so on.

The impression one gets when encountering this person for the first time is one of great strength of character and giant capability. “Gosh!” you say to yourself. “This woman looks as if she eats elephant meat for breakfast.” Thing is, if you get to know her, you’ll see that this power rarely exploited. Cancer/Dragons have muscle. But they don’t like to have to use it. Though not often classically attractive, this person will enjoy much success with the opposite sex. Much of the Dragonish fire is doused by Cancer’s watery side making this character steamy rather than just sexy. The Dragon/Cancer, then, is less obviously pushy and egotistical. This is a toned-down Dragon. A spiffed-up Cancer.

Cancer/Dragons are curious people and often go traveling and bring back reports or trophies from their wanderings. This person knows how and where to apply the dynamic energy he owns, and makes an interesting—though perhaps a mite too talky for my taste—companion. Dragon/Cancers are idealistic, too. They’d like to change the world—or at least try. The Cancer born Dragon will be drawn to things artistic and will probably be something of a culture vulture. He or she will enjoy appearing in public places well turned out and suffisant. Cancer/Dragon is a sign of strength without the disadvantages that often go along with domination.`,
    love: `In romance as in life in general, the Cancer/Dragon will operate mostly out of energetic sentiment and fiery sensuality. It’s a turbulent mix at best. “I feel for this and love that and adore her and hate him and am passionate about everyone and what’s worse, I am outrageously attractive.” Oh, you poor little waif! You mustn’t feel so guilty. Don’t put your charm back in your pocket. Get out there and wow ‘em with your pizzazz! But be careful. Remember how sentimental you are. This world of admiring strangers is mined with pitfalls for people like you.

You see, for a Dragon to be even the least bit discreet and dignified, reserved and genteel, he has to be a Cancer. This person will be adorably humble on the outside but oozing with Dragonish magnetism, which he’ll never be able to completely hide. For this reason I would not take bets on his fidelity. If you love a Cancer/Dragon, stay home by the phone and keep your little black book well filled with alternatives.`,
    compatibilities: `Taurus/Monkeys (born April 20 - May 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028), Scorpio/Monkeys (born October 23 - November 21 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) and Pisces/Monkeys (born February 19 - March 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) tease you and entrance you, sweet Cancer/Dragon. You may also find happiness with a Scorpio (born October 23 - November 21) or Pisces/Rat (born February 19 - March 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032). You love Snakes for their innate beauty, so why not try a Taurus (born April 20 - May 20) or Pisces/Snake (born February 19 - March 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025)? But beware! Snakes love to tell fibs. And when you’re in love, you can easily be duped. Taurus/Pigs (born April 20 - May 20 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) and their Rooster (born April 20 - May 20 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) brothers and sisters can also turn up your volume. Don’t try coupling with an Aries (born March 21 - April 19), Libra (born September 23 - October 22) or Capricorn/Dog (born December 22 - January 19 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030), a Capricorn (born December 22 - January 19) or Libra/Ox (born September 23 - October 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). And don’t even think about marrying any kind of Rabbit.`,
    homeAndFamily: `This person is a Cancer. So he will have a comfortable and reasonably sane home life. But as he is also a Dragon and wont to show off, I’d say the house will be large and imposing, the gardens well tended and the luxe apparent. Cancerian Dragons do not know how to keep their zip zippered. You will not be unimpressed.

As a parent the Cancer/Dragon’s a doll. He will love his kids to pieces and adore showing them off to relatives and to the world at large. He’ll offer them security and in return he will expect obedience and manners. He or she will also revel in performing for the kids. (If your father or mother is a Cancer/Dragon, I suggest you laugh at their jokes.)

The Cancer/Dragon child will be sweet-natured and quick of wit. You shouldn’t have too many problems with him or her provided there are many outlets for all the energy they are born with. They should be trained at many different disciplines, as they are capable and diligent learners whose aim is to please. He or she will probably have an interest in theater.`,
    profession: `This person is a born leader. He or she needs much education and should seek knowledge from an early age. Their natural curiosity will prepare them for studies of an advanced nature. Cancer is diligent and persevering. The adult Cancer/Dragon has real talent for jobs requiring personal authority. He’s strong-minded. But he is not stubborn. He’s dutiful. But he’s not Pollyanna.

So, as a boss, this person will be both strict and lenient. The trick is always to know just how much of which. If Cancer/Dragon runs into a snag, he can feel his way to the best solution. I have my doubts about Cancer/Dragon’s abilities as an employee. These people really hate playing second fiddle and may sulk if subordinated. Lots of college diplomas should help Cancer/Dragons start out near the top.

Jobs suited to this mix are: preacher, actress, adventurer/writer, journalist, restaurant owner, TV personality, international lawyer.`,
  },
  "Cancer/Snake": {
    description: `As Cancers go, the Snake type is more independent of ponderous emotional fetters than his kin. He’s familial to be sure, and even clinging—after all, he is both Snake and Cancer! But the Cancer born a Snake, unlike certain other Cancers we all know and love, recognizes his own weaknesses, comprehends his black moods and, because of his cool-headed sagacity, usually manages to slither out of the lunatic doldrums for which Cancers can be so famous.

As Snakes go, the Cancer/Snake will be less cold-blooded than other serpents. Cancer’s brooding soulfulness and profound affectivity lend the Snake a blanket, caress his cold exterior and warm the heart into something close to affability. Snakes can be really cool customers. They wiggle and squirm their way in and out of every variety of situation and are clever as snakes at turning most circumstances to their favor. In the Cancerian Snake, this tendency to want the leading role in all of life’s movies is tempered by common sense and natural reserve.

All Snakes are created fabulators. But some are more prevaricating than others. Cancer/Snakes are among the least slippery of serpents. They might not bamboozle their grandmothers just to make themselves look good. Nonetheless, even the sensible Cancer/Snake is capable of rank dissimulation and tells ingenious and Byzantine fibs. He can’t help it. He believes his own fantasies. Fibbing, after all, is part of the challenge of seduction and capture. And all Cancer/Snakes want to be thought of as captivating, charming, beautiful to behold, better than their neighbors and taller and handsomer and better dressed than anybody anywhere ever. Attractiveness is inborn and crucially important to this creature. These folks are not above name-dropping and label-flaunting. Picture the splendid home-loving Cancerian/Snake seated on his designer couch, wearing his designer jeans. His tanned and braceleted arms embrace a brood of beautiful towheads in designer frocks and Bermuda shorts Behind his head, a Picasso. At his feet, a giant Pyrenees hound found only in the furthest darkest caves of Andorra. Everybody knows these huge beasts eat at least one small cow every day, are très, très à la mode and fetch a fortune. Never mind. The image is the message with Cancer/Snakes. No matter the cost or the travail involved, count on your friendly neighborhood Cancer/Snake to own the most chic and fashionable of everything.

Incidentally, if you don’t live in an upper-echelon neighborhood you may never meet one of these gorgeous creatures. If they can help it, Cancerian Snakes don’t hang out in scruffy sections. They may come from poverty, but they are determined not to stay there for long. Up and over they go, attending the “right” schools and rubbing shoulders with the “in” crowd, marrying the one person in the whole gang who is sure to become famous and rich. Cancer/Snakes don’t only like comfort, they think they invented it. These people love to entertain, too. Once they have achieved a modicum of security and know a few of the “top” people, count on the Cancer/Snake to throw some of the most lavish and well-attended parties in town. Of course Cancer/Snakes will have catered food and a pair of bartenders, set a team of servants to work shucking the oysters, and then will circulate. The way he sees it, the Cancer/Snake cannot very well move about among his guests, charm the pants off the chancellor of Germany whose press secretary promised he’d put in an appearance, inveigle the secretary of the art museum to give him a private showing of the new upcoming work of the younger artists and serve drinks at the same time—or can he? Well, it doesn’t really matter, because he won’t. Cancer/Snakes like to be waited on. And as long as they can afford slaves they will be sure to have them. These people are extremely artistic. They have a way of embellishing everything that comes their way. And Cancer/Snakes are also wise and can be of good counsel. They are super intuitive, really can project themselves into other people’s skins and will think long and hard about someone’s dilemma before dispensing a single word of their sage advice. Cancer/Snakes are fun-loving too. They are always up there dancing till dawn with the heartiest of the youngsters, looking fabulous and enjoying being the envy of all present. And don’t put it past a Cancer/Snake to be “that woman who stripped to her undies last week at the posh club over in Soho.” Cancerian Snakes have a naughty streak. They like to be considered a mite outrageous or exotic.`,
    love: `Possessive? Exclusive? Demanding? Intractable? You got it—the Cancer/Snake is all of these and much, much more. The Cancer/Snake is so attractive and sexy and lovely to watch move that people may gather just to watch him or her enter a public place. These people have the market cornered on slink.

Underneath the slink is an amazing amount of good-scouted, good-hearted fellowship and an enormous caring for friends and lovers alike. The Cancer/Snake will not be faithful. But he or she will always be seductive and alluring. Even if he’s carrying on a roaring affair with the German minister’s secretary, the Cancerian Snake will always attend to his or her mate as though he or she were the ruler of Germany itself.

If you love a Cancerian Snake, get ready to make a lot of money, spend it all and then go out and make some more. As the mate of this exciting person, you will luxuriate in perfectly glorious surroundings and have scads of very decorous friends and acquaintances to whom you can complain that your Cancer/Snake companion is too attractive to other men and women and you wish you had married a nice solid Taurus/Dog. In order to get the best out of life with a Cancer/Snake, you have to be able to fall down laughing, ooohhh and aaahhh when he comes down the stairs dressed to kill, and enjoy cooking your own meals and eating them alone by the fireside while Cancer/Snake is out rounding up some new sculptures to beautify your existence.`,
    compatibilities: `You get a charge out of Roosters. Your best shots with them will be found among Taurus (born April 20 - May 20), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21) and Pisces (born February 19 - March 20 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029). The same goes for Oxen in all those categories. You’re not thrilled by Aries/Tigers (born March 21 - April 19 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or Capricorn/Tigers (born December 22 - January 19 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or Aries/Monkeys (born March 21 - April 19 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) or Capricorn/Monkeys (born December 22 - January 19 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028). Leave Pigs alone. I know they are usually naïve and often have lots of money; and you have plenty of guile for both of you and excel at spending money. But, let’s face it. You don’t always have Piggy’s best interests at heart.`,
    homeAndFamily: `Cancer/Snake’s main home will be located, it goes without saying, in the best possible quarter of the closest metropolis to heaven. But then there is, of course, the house in the country. This little manse is likely to want to be situated right in the heart of the most celebrated verdant horse and dog-breeding territory, not too far from the first paradise we mentioned. Then, you have to have a place at the beach. That’ll be located on the prettiest seashore available at the highest price, please. And don’t forget the little mas in the south of France—or was it Tuscany? Well, wherever, it won’t be long before the Cancer/Snake invests in some opulent, trendy foreign real estate.

Inside these homes will live masses of children and dogs and cats and house guests and maids and nannies—well, you name it, it lives at the Cancer/Snake’s house. You see, with all their elegance and savoir vivre, Cancer/Snakes love pets and kids and guinea pigs and horses etc. Cancer/Snakes are really incredibly dear, sweet people. They really don’t mind if your Doberman jumps up on their new St Laurent tweed skirt. If you have a Cancer/Snake child, you must be careful to provide him or her with lots of security and plenty of animals to love. As is true with all Snakes, it’s probably best for the exclusive Cancer/Snake child to be an only child, or at least the baby of the family. Cancer/Snake kids are bright in school and work hard to get ahead. They usually don’t cause their parents many problems and carry on with their lives quite independently of the parents’ intervention. These little people are very affectionate. You must always tuck them in warmly and kiss them goodnight.`,
    profession: `In the early part of his life, the Cancer/Snake, like all his serpent brothers and sisters, will try to wriggle out of chores and tasks. And just because he’s a Cancer doesn’t mean that he won’t have to fight the great battle against sloth that is native to all Snake subjects. But as adulthood approaches and the Cancer/Snake grows more and more independent of parental security, he will note that riches and work are irremediably intertwined. Then his true Cancer nature will take over. He’ll still be on the sit-around-and-look-beautiful side of a lazy Sunday afternoon. But the grown-up Cancer/Snake can be counted on to pitch in when there’s a need for a second shoulder at the wheel.

Talented in everything related to beauty and the home, this person can succeed at decoration, architecture, graphic design of all kinds, fashion or advertising. Gifted in deception, persevering and supremely intuitive, Cancer/Snakes might also choose law—even politics—as a life’s work. This character is more cerebral than manual but might employ his talents well in some light labor such as landscape gardening. Cancer/Snakes can very satisfactorily hold dominion over others. They do not have to abuse power because their authority is so natural that people rarely question it. As an employee, the Cancer/Snake might tend to be a little on the snooty know-it-all side. I’m not sure I’d hire one to do a menial job of any sort.`,
  },
  "Cancer/Horse": {
    description: `This person is a wild card. The Cancerian born in a Horse year is bound to be both gifted and erratic. The Cancer/Horse is a fanciful dreamer who is forever changing his or her mind. One minute he wants to be a lawyer and the next minute he’s decided to race sports cars or fly jet planes. This person is talented at most everything he undertakes. But the undertaking part is shaky. He may be gifted at violin, but will he stick with it? He may be a genius at math, but will he ever get through a whole course?

Cancer/Horses, you see, are impatient. They are always in a hurry to get on to the next project, to discover the next best thing, to try a new method, to move to another city, to change partners, to alter their lifestyle. The Cancer/Horse is not exactly a stable personality. He’s a dreamer and a doer. But he’s not a finisher. He’s too hotheaded and impetuous to see things through to their logical end. This is a person who can be counted on to come up with brilliant schemes and to get them rolling, but when the going gets tough or plodding or boring, the Cancer/Horse gets going—out the door and on to something new.

This subject is magnetic and charming. He or she will always be surrounded by bevies of admirers and friends. The Cancer/Horse has a sunny disposition and a quick wit. He’s a talker and a bit of a clown. People like to have this entertaining character around because he’s fun and makes others laugh. He’s also sexy in a kind of offhand way. He doesn’t mean to be seductive. He just can’t help it.

The Cancer/Horse is usually quite good-looking. He takes care with his appearance and likes to be noticed for his efforts. He may not be a fashion plate but he will surely be clean and neat, combed and pressed, and often expensively clad. He’s not above showing off a bit either. He likes to shine in company and be thought of as special.

This person’s selfishness is not cruel or ruthless. It’s more a question of wanting to have his own way, to be free to come and go as he pleases. The Cancer/Horse is not a homebody like other Cancers. He’s autonomous and needs to feel that he can pick up and leave at a moment’s notice. He’s not a loner, though. He likes company and will always be found in a crowd. But he’s not a joiner either. He doesn’t want to belong to any group or club. He’s too independent for that.`,
    love: `In love, the Cancer/Horse is a romantic. He’s sentimental and emotional, but he’s also fickle. He falls in love easily and often, but he falls out of love just as quickly. He’s not unfaithful in the classic sense. He just gets bored and moves on. If you love a Cancer/Horse, you’d better be prepared for a roller-coaster ride. This person is not easy to pin down. He’s elusive and slippery, and he doesn’t like to be tied down.

If you want to keep a Cancer/Horse, you’ll have to give him plenty of rope. Let him roam and explore, and don’t try to fence him in. He needs to feel free, even if he’s deeply in love. The Cancer/Horse is not a possessive lover, but he can be jealous if he feels his partner is not giving him enough attention. He likes to be the center of attention, even in a relationship.`,
    compatibilities: `You’ll find love with Taurus (born April 20 - May 20), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Pisces/Dogs (born February 19 - March 20 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Pisces/Tigers (born February 19 - March 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034). They can handle your fiery nature and give you the freedom you need. You might also click with a Scorpio (born October 23 - November 21) or Pisces/Goat (born February 19 - March 20 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027). Stay away from Aries (born March 21 - April 19), Libra (born September 23 - October 22), and Capricorn/Rats (born December 22 - January 19 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032). They’re too controlling for you. And don’t get involved with an Aries (born March 21 - April 19) or Capricorn/Ox (born December 22 - January 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). They’ll cramp your style.`,
    homeAndFamily: `The Cancer/Horse’s home will be a reflection of his personality—eclectic, colorful, and a bit chaotic. He’s not a neat freak, but he likes his surroundings to be comfortable and inviting. He’ll have lots of interesting objects and artworks around, but don’t expect everything to be in its place. He’s too busy living to worry about tidying up.

As a parent, the Cancer/Horse is loving but not overly strict. He wants his kids to be free spirits like himself, but he also wants them to respect him. He’ll encourage their creativity and independence, but he may not be the most consistent disciplinarian. A Cancer/Horse child will be a handful—full of energy, ideas, and mischief. You’ll need to keep this kid busy with activities and projects to channel all that enthusiasm.`,
    profession: `The Cancer/Horse is a natural at creative pursuits. He’s got a flair for the dramatic and could excel in acting, writing, or music. He’s also good at anything that requires quick thinking and adaptability—sales, marketing, or entrepreneurship. He’s not suited for routine or repetitive jobs. He needs variety and excitement to stay engaged.

As a boss, the Cancer/Horse is inspiring but not always organized. He’s got big ideas but may leave the details to others. As an employee, he’s a star performer when he’s interested, but he can lose focus if the job doesn’t hold his attention. He’s best in roles where he can shine and be recognized for his talents.`,
  },
  "Cancer/Goat": {
    description: `The Cancer/Goat is a sensitive soul wrapped in a tough exterior. This person is a dreamer who feels everything deeply but doesn’t always show it. The Goat’s capriciousness and Cancer’s moodiness make for a complex personality—one minute he’s up, the next he’s down. But he’s also incredibly creative and has a knack for turning his dreams into reality.

This person is a homebody at heart. He loves his cozy nest and will spend hours making it just right. He’s got an eye for beauty and a taste for the finer things—think soft cushions, warm lighting, and walls covered in art. He’s not flashy, though. His style is understated but elegant.

The Cancer/Goat is a worrier. He frets about everything—money, health, relationships, you name it. This can make him seem a bit whiny at times, but it’s just because he cares so much. He’s not the type to take risks or leap into the unknown. He craves security and will cling to anything that makes him feel safe.

Despite his sensitive nature, the Cancer/Goat is no pushover. He’s got a stubborn streak and can be surprisingly tough when he needs to be. He’s also fiercely loyal to those he loves and will go to great lengths to protect them. His friends and family are his anchor, and he needs their support to thrive.`,
    love: `In love, the Cancer/Goat is a hopeless romantic. He falls hard and fast and dreams of a fairy-tale ending. He’s devoted and nurturing, always ready to pamper his partner with affection and attention. But he’s also needy and can be clingy if he feels insecure. He needs a partner who can reassure him and make him feel safe.

If you love a Cancer/Goat, be prepared to deal with his moods. He’s not always easy to read, and his emotions can change like the tides. Give him lots of love and support, and he’ll reward you with unwavering loyalty. But don’t try to push him out of his comfort zone too quickly—he needs time to adjust.`,
    compatibilities: `You’ll find harmony with Taurus (born April 20 - May 20), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Pisces/Rabbits (born February 19 - March 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and Pisces/Pigs (born February 19 - March 20 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031). They share your love of beauty and comfort and won’t mind your need for security. A Scorpio (born October 23 - November 21) or Pisces/Horse (born February 19 - March 20 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) could also work, as they bring some excitement to your life. Avoid Aries (born March 21 - April 19), Libra (born September 23 - October 22), and Capricorn/Dragons (born December 22 - January 19 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Capricorn/Oxen (born December 22 - January 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021)—they’re too aggressive or domineering for your gentle nature.`,
    homeAndFamily: `The Cancer/Goat’s home is his sanctuary. It’s warm, inviting, and filled with beautiful things. He’s not one for clutter, but he loves to surround himself with objects that have meaning—family heirlooms, handmade crafts, or pieces of art that speak to his soul.

As a parent, the Cancer/Goat is nurturing and protective, sometimes to a fault. He wants his kids to feel loved and secure, but he can be overbearing at times. He’s not great at discipline, as he hates conflict, but he’ll do his best to guide his children with love. A Cancer/Goat child needs lots of encouragement and a stable environment to flourish. Don’t push this kid too hard—he’ll retreat into his shell if he feels pressured.`,
    profession: `The Cancer/Goat shines in creative fields—art, design, writing, or music. He’s got a vivid imagination and a talent for bringing beauty into the world. He’s also good at jobs that require empathy and care, like teaching or counseling. He’s not a natural leader, though—he prefers to work behind the scenes.

As a boss, the Cancer/Goat is kind but indecisive. He wants everyone to be happy, which can make him a pushover. As an employee, he’s diligent and reliable but needs a supportive environment to do his best work. He’s not great with criticism, so handle him with care.`,
  },
  "Cancer/Monkey": {
    description: `The Cancer/Monkey is a bundle of contradictions. He’s a dreamer with a practical streak, a homebody who loves adventure, a sensitive soul with a sharp wit. This person is always thinking, scheming, and planning, but his plans are often more fantasy than reality. He’s got a vivid imagination and a knack for coming up with clever ideas, but he’s not always great at following through.

This person is charming and sociable, with a quick sense of humor that draws people to him. He’s a natural storyteller and loves to entertain. But there’s a sly side to the Cancer/Monkey—he’s not above bending the truth or manipulating a situation to get what he wants. He’s not malicious, though. It’s more about self-preservation than hurting others.

The Cancer/Monkey is deeply emotional, but he hides it behind a mask of wit and charm. He’s sensitive to criticism and can be jealous if he feels left out. He craves stability and security, but his Monkey side makes him restless and eager for new experiences. This push-pull dynamic can make him hard to pin down.`,
    love: `In love, the Cancer/Monkey is a charmer. He’s got a way with words and knows how to make his partner feel special. But he’s also a bit of a flirt and can be hard to trust. He’s not unfaithful in a deliberate way, but his restless nature makes him crave variety. If you love a Cancer/Monkey, you’ll need to keep things interesting to hold his attention.

This person needs a partner who can match his wit and keep up with his ever-changing moods. He’s not great at opening up about his feelings, so you’ll need to be patient and intuitive to get close to him. Give him space to explore, but also provide a safe haven for him to return to.`,
    compatibilities: `You’ll hit it off with Taurus (born April 20 - May 20), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Pisces/Dragons (born February 19 - March 20 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Pisces/Rats (born February 19 - March 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032). They can handle your cleverness and keep you grounded. A Scorpio (born October 23 - November 21) or Pisces/Snake (born February 19 - March 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) might also spark your interest. Stay away from Aries (born March 21 - April 19), Libra (born September 23 - October 22), and Capricorn/Tigers (born December 22 - January 19 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Capricorn/Pigs (born December 22 - January 19 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031)—they’re either too intense or too naïve for you.`,
    homeAndFamily: `The Cancer/Monkey’s home is a mix of cozy and chaotic. He loves a comfortable space but isn’t always great at keeping it tidy. His home will be filled with books, gadgets, and quirky objects that reflect his eclectic tastes. He’s not a minimalist, but he’s not a hoarder either—just expect a bit of organized chaos.

As a parent, the Cancer/Monkey is fun and imaginative. He loves playing with his kids and coming up with creative games. But he’s not the most consistent parent and can struggle with discipline. A Cancer/Monkey child is bright and curious but needs structure to stay focused. Encourage his creativity, but set clear boundaries to keep him on track.`,
    profession: `The Cancer/Monkey is a natural problem-solver. He’s great at jobs that require quick thinking and adaptability—think advertising, journalism, or tech. He’s also got a creative side that could lead him to writing, design, or entertainment. He’s not suited for rigid or repetitive jobs—he needs variety to stay engaged.

As a boss, the Cancer/Monkey is inspiring but unpredictable. He’s got big ideas but may not always follow through. As an employee, he’s a star when he’s motivated, but he can slack off if he’s bored. Give him challenging projects and plenty of praise to keep him engaged.`,
  },
  "Cancer/Rooster": {
    description: `The Cancer/Rooster is a curious mix of sensitivity and strut. This person is deeply emotional but hides it behind a confident, sometimes cocky exterior. He’s a perfectionist who loves order and routine, but his Cancer side makes him prone to mood swings that can disrupt his carefully laid plans.

This person is a hard worker with a sharp eye for detail. He’s diligent and reliable, always striving to do his best. But he’s also a bit of a worrier and can get bogged down in the minutiae. He’s protective of those he loves and will go to great lengths to keep them safe, but he can be overbearing at times.

The Cancer/Rooster is not a wallflower. He likes to be noticed and will strut his stuff with confidence. He’s got a bold streak and isn’t afraid to speak his mind, but his sensitivity means he can take criticism personally. He’s loyal and dependable, but his high standards can make him hard to please.`,
    love: `In love, the Cancer/Rooster is devoted but demanding. He wants a partner who can match his energy and appreciate his efforts. He’s not the most romantic type—his practical side often takes over—but he’s fiercely loyal and will stick by his partner through thick and thin.

If you love a Cancer/Rooster, be prepared for his high expectations. He wants everything to be just right, and he can be critical if things don’t meet his standards. Give him lots of reassurance and show him you value his efforts. He’s not great at expressing his emotions, so you’ll need to read between the lines.`,
    compatibilities: `You’ll find love with Taurus (born April 20 - May 20), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Pisces/Snakes (born February 19 - March 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Pisces/Oxen (born February 19 - March 20 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). They share your love of order and can handle your occasional bossiness. A Scorpio (born October 23 - November 21) or Pisces/Dragon (born February 19 - March 20 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) could also work, as they bring some excitement to your life. Avoid Aries (born March 21 - April 19), Libra (born September 23 - October 22), and Capricorn/Rabbits (born December 22 - January 19 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and Capricorn/Roosters (born December 22 - January 19 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029)—they’re either too flighty or too competitive for you.`,
    homeAndFamily: `The Cancer/Rooster’s home is a model of neatness and efficiency. Everything has its place, and he likes it that way. His space will be comfortable but not overly fussy—think clean lines and practical elegance. He’s not one for clutter or chaos.

As a parent, the Cancer/Rooster is strict but loving. He wants his kids to succeed and will push them to do their best. He’s not the most flexible parent, though, and can struggle with letting his kids make their own mistakes. A Cancer/Rooster child is bright and hardworking but needs encouragement to loosen up and have fun.`,
    profession: `The Cancer/Rooster is a natural at jobs that require precision and organization—think accounting, editing, or project management. He’s also got a creative side that could lead him to design or writing. He’s not a risk-taker, so he prefers stable, predictable roles.

As a boss, the Cancer/Rooster is fair but demanding. He expects everyone to meet his high standards and can be critical if they don’t. As an employee, he’s reliable and thorough but can be sensitive to feedback. Give him clear instructions and plenty of praise to keep him motivated.`,
  },
  "Cancer/Dog": {
    description: `The Cancer/Dog is a bundle of nerves wrapped in a warm, loyal heart. This person is deeply emotional and fiercely protective of those he loves. He’s a worrier by nature, always fretting about what could go wrong, but his loyalty and sense of duty keep him grounded.

This person is a natural caretaker. He’s always looking out for others, whether it’s his family, friends, or even strangers. He’s got a strong sense of right and wrong and will stand up for what he believes in, even if it makes him unpopular. His Cancer side makes him sensitive and intuitive, while his Dog side gives him a sharp, sometimes cynical edge.

The Cancer/Dog is not a showoff. He’s quiet and reserved, preferring to stay in the background rather than take center stage. But don’t mistake his quietness for weakness—he’s got a fierce side and can be aggressive if provoked. He’s also incredibly intelligent and has a knack for seeing through people’s facades.`,
    love: `In love, the Cancer/Dog is loyal to a fault. He’s not the type to play the field—he wants a deep, meaningful connection with one person. He’s nurturing and supportive, always ready to listen or lend a hand. But his worrywart nature can make him clingy or overly protective.

If you love a Cancer/Dog, be prepared to reassure him often. He needs to know you’re in it for the long haul. He’s not great at dealing with rejection or betrayal, so be honest and upfront with him. Give him a sense of security, and he’ll be your most devoted partner.`,
    compatibilities: `You’ll find love with Taurus (born April 20 - May 20), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Pisces/Tigers (born February 19 - March 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Pisces/Horses (born February 19 - March 20 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). They share your loyalty and can handle your emotional depth. A Scorpio (born October 23 - November 21) or Pisces/Rabbit (born February 19 - March 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) could also work, as they bring some calm to your stormy nature. Avoid Aries (born March 21 - April 19), Libra (born September 23 - October 22), and Capricorn/Dragons (born December 22 - January 19 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Capricorn/Monkeys (born December 22 - January 19 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028)—they’re too unpredictable or manipulative for you.`,
    homeAndFamily: `The Cancer/Dog’s home is a safe haven. It’s warm, cozy, and filled with things that make him feel secure—think soft blankets, family photos, and a well-stocked pantry. He’s not a minimalist, but he’s not a hoarder either—just expect a space that feels lived-in and loved.

As a parent, the Cancer/Dog is devoted and protective. He’ll go to the ends of the earth for his kids, but he can be a bit smothering. He needs to learn to let go and let his kids make their own mistakes. A Cancer/Dog child is sensitive and loyal but can be anxious. Provide a stable environment and lots of reassurance to help this kid thrive.`,
    profession: `The Cancer/Dog is a natural at jobs that involve helping others—think social work, teaching, or healthcare. He’s also good at roles that require analysis and problem-solving, like research or law. He’s not a natural leader, but he’s a loyal and hardworking team member.

As a boss, the Cancer/Dog is fair and supportive but can be overly cautious. He’s not great at taking risks or thinking outside the box. As an employee, he’s reliable and dedicated but can be sensitive to criticism. Give him clear instructions and a supportive environment to shine.`,
  },
  "Cancer/Pig": {
    description: `The Cancer/Pig is a gentle soul with a refined taste for life’s pleasures. This person is a dreamer who loves beauty, culture, and comfort. He’s deeply emotional and wears his heart on his sleeve, but he’s also got a hot temper that can flare up unexpectedly.

This person is a natural nurturer. He loves to take care of others, whether it’s cooking a gourmet meal or creating a warm, inviting home. He’s got a refined sense of style and a love for the finer things—think fine wine, classical music, and art galleries. But he’s not a snob—he’s sincere and approachable, always ready to share his good fortune with others.

The Cancer/Pig is a bit naïve at times. He trusts people too easily and can be taken advantage of. He’s also prone to indulgence, whether it’s food, drink, or other pleasures. His Cancer side makes him moody, while his Pig side makes him crave comfort and security.`,
    love: `In love, the Cancer/Pig is a hopeless romantic. He’s all about grand gestures and heartfelt declarations. He’s sensual and affectionate, always ready to shower his partner with love. But he’s also easily hurt and can be clingy if he feels insecure.

If you love a Cancer/Pig, indulge his romantic side. Plan candlelit dinners, take him to art galleries, or just cuddle up with him at home. He needs to feel cherished and secure. Be honest with him—his trusting nature makes him vulnerable to deception.`,
    compatibilities: `You’ll find love with Taurus (born April 20 - May 20), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Pisces/Rabbits (born February 19 - March 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and Pisces/Goats (born February 19 - March 20 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027). They share your love of beauty and comfort and can provide the security you crave. A Scorpio (born October 23 - November 21) or Pisces/Tiger (born February 19 - March 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) could also work, as they bring some excitement to your life. Avoid Aries (born March 21 - April 19), Libra (born September 23 - October 22), and Capricorn/Snakes (born December 22 - January 19 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Capricorn/Monkeys (born December 22 - January 19 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028)—they’re too cunning or restless for your gentle nature.`,
    homeAndFamily: `The Cancer/Pig’s home is a haven of beauty and comfort. It’s filled with soft furnishings, elegant decor, and plenty of good food. He’s not a minimalist—his space is warm and inviting, with a touch of luxury.

As a parent, the Cancer/Pig is loving and indulgent. He wants his kids to have the best of everything, but he can spoil them if he’s not careful. He’s not great at discipline, as he hates conflict, but he’ll do his best to guide his kids with love. A Cancer/Pig child is sweet and sensitive but needs a stable environment to feel secure. Encourage his creativity and love of beauty, but teach him to be cautious with his trust.`,
    profession: `The Cancer/Pig is a natural at jobs that involve creativity and care—think cooking, interior design, or art curation. He’s also good at roles that require empathy, like counseling or teaching. He’s not a natural leader, but he’s a dedicated and reliable team member.

As a boss, the Cancer/Pig is kind and supportive but can be too lenient. He wants everyone to be happy, which can make him a pushover. As an employee, he’s hardworking and conscientious but needs a nurturing environment to thrive. Give him creative projects and plenty of praise to keep him motivated.`,
  },
};
