// src/lib/new-astrology/leo.ts

export const leo = {
  "Leo/Rat": {
    description: `The cinematic image that comes to mind when I ponder the combination of Leo and Rat is of Gene Kelly, umbrella in hand, dancing through teeming rain and singin’ his heart out. Leo/Rats have it all over everybody else in the capacity for conjuring sunshine. They can make a party out of a thunderstorm more lavishly and efficiently than you can imagine possible. Leo/Rats’ attributes are many, their faults serious but few.

When he is loved and properly admired, the Leo/Rat strides through life as though he were going to consume its every facet before noon. He is active and exudes uncommon self-confidence. He has his own rhythm and knows how to pace his every activity so it fits into his jam-packed day. Leo/Rats can take an early breakfast with the queen, spend the morning pep-talking a group of sumo wrestlers and hurry back home to have lunch with their kids. Afternoons can be spent in a flurry of efficiency, getting letters off to the hospital steering committee (of which, of course, Leo/Rat is chairperson) and chatting with the mayor about that new housing project he’s thinking of funding. In between letters and phone calls and visits with dignitaries, Leo/Rat might be doodling a spiffy design for the new wing on his house in the country or listing possible names for his new horse. After work he’ll hurry to a conference with his kids’ teachers and then homeward to dress for the opera, which he attends with rigorous regularity as he does the subscription symphonic series and the appearance of every new film and theatrical effort around. The Leo/Rat ability to accomplish a wide variety of effective deeds in his life is astounding.

Leo/Rats are usually not poor for long. They know how to measure their guile into neat level spoonfuls and dish it out where needed for the making of money. They are extravagant but sensible people. With their hard-earned riches, Leo/Rats are generous and even philanthropic. But they won’t go around giving money to bums and do-nothings just for the sake of charity. Leo/Rats prefer to help out promising young painters or musicians than just proffer money aimlessly. The marriage of Leo’s natural strength and the Rat’s desire for power is unbeatable in business and cultural activities. This person will always be a leader, in the vanguard of human endeavor and serious about the wielding of influence, of which he will probably have masses.

The donation of concrete ideas and the exertion of indomitable will for the sake of furthering great civilizing causes is not to be taken lightly. A Leo/Rat who feels he has been let down by cohorts or associates in his drive for power over evil or famine or poverty will be a portrait of despair. Leo/Rats believe fervently in the potential of friends and colleagues for true trust. Leo/Rat considers his partners long and hard before allowing himself to become their allies. If they disappoint him by virtue of their mediocrity or even lukewarm sentiments, the Leo/Rat takes it as a personal failure. When Leo/Rats fall, they fall hard and hit rock bottom with a deafening clunk. Climbing back up means humbling oneself. And humility is not easy for Leo/Rats. They need to be in control, on top of things. They will be saved by engaging in new and more challenging activities. Not by going into a rest home.

The main talent of Leo/Rats is enterprise. They know how to confront challenge better than many other people. They attack every new obstacle as though it were nothing more than a bigger and better seesaw which will swing them higher into the air and thus improve their lot. Every sport or dance or new wave of trendy jazz that comes their way is examined and understood and conquered and embraced by the Leo/Rats. Show him a camel and he will show you how to ride a camel. Leo/Rat is a natural teacher and shines brightly with achievement when his pupils catch on. Leo/Rats are cranky when confused. He likes to choose which row his entire party will sit in at the movies and prefers to drive than to be driven in automobiles. The Leo/Rat’s bearing is aristocratic and his personal magnetism unparalleled. But he hates to lose. If he does, you’ll hear about it.`,
    love: `As Leo/Rat people have a lot to give, they tend to seek partners whose dimensions permit the gracious reception of hordes of expressions of their devotion. If a Leo/Rat loves somebody deeply and fondly and tenderly, it is very often irrevocably forever. The Leo/Rat is so busy getting places and, once he is there, staying there, that he doesn’t really like to make time for dalliance. He prefers to use his extraordinary imagination to maintain an existing passion than to go out seeking new ones that may only disappoint or deceive him. As I said before, the Leo/Rat invests himself in his relationships, both public and private. He cannot abide disloyalty.

If you love a Leo/Rat and he/she loves you back, you had better hustle to find ways to amuse and entertain this active monster mind. You can expect shortness of temper and loud yawns of utter boredom to emanate from any Leo/Rat person forced to be idle for half a minute. If he sits down, don’t think he’s going to stay down. He’s just waiting for you to fire the starting gun and up and out he will be in a flash. Loving one of these people means expending both energy and emotion. You cannot be only partially in love with a Leo/Rat. He or she will make scenes and cause you untold horrors if you exhibit hesitations about the relationship’s solidity. Be confident. Otherwise . . . well, I’d rather not discuss it. For Leo/Rats there is no such thing as “otherwise.”`,
    compatibilities: `You get on with bunches of types. Your best bet is an Ox (born in 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) subject chosen from among Gemini (born May 21 - June 20), Libra (born September 23 - October 22), Capricorn (born December 22 - January 19) or Sagittarius (born November 22 - December 21) subjects. Other allies can be found for you in the Dragon (born 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) family—especially Gemini, Libra, Sagittarius and Capricorn/Dragons. Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Libra (born September 23 - October 22) and Capricorn/Monkeys (born December 22 - January 19 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) are fun for you too. You are indeed popular. But give wide berth to the haunts of Horses in general and, in particular, flee the likes of Taurus (born April 20 - May 20), Scorpio (born October 23 - November 21) or Aquarius/Horses (born January 20 - February 18 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). Don’t go getting yourself involved with either a Scorpio or an Aquarius/Rabbit (born 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035). Rabbits and Rats????`,
    homeAndFamily: `The Leo/Rat is a provider. Going out into the world and fetching back stores and stores full of wares, which will then be stocked and stashed and displayed on shelves, in cupboards and in closets, is one main pleasure of the Leo/Rat. Moreover, Leo/Rat likes to protect his family from harm and cold and shelter them in sumptuous surroundings. You won’t see a Leo/Rat dragging back to his hovel from a hard day at the mine, and greeting his worn-looking wife and sooty kids with a grunt. Never. This person wants to be greeted at the door of his chateau after a busy, energetic day in the outside world by a bejeweled, intelligent and witty mate who has just spoken to the president and the first lady about an intimate dinner they’ll share next Wednesday in Leo/Rat’s red room. And the children? Preferably Nobel Prize winners who closely resemble Cindy Crawford or Leonardo DiCaprio and speak fourteen languages at age three. In their quest for excellence, Leo/Rats set no limits.

The Leo/Rat child will be demanding and bright. He or she needs lots of very top-drawer education and careful cultural guidance. Don’t be surprised by this kid’s interest in absolutely everything that has to do with power. Leo/Rats are not interested in namby-pamby activities, and will only seek to achieve in areas where stardom is the objective.`,
    profession: `As enterprise and attack are the chief talents of the Leo/Rat, it’s obvious that this person can expect to gain glories in managerial and entrepreneurial fields. If money is available, the Leo/Rat can start his own business and run with it to the end of his life. But if he is not wealthy and has to start at the bottom, the Leo/Rat will always distinguish himself by his tireless energy and innovation in work situations. No boss worth his salt would not promote this masterful character to head of the department, chief of operations or vice president in charge of presidents. To attempt to keep a Leo/Rat down is folly. This person will always seek to rise above and get ahead of his coworkers. He will only prove a good employee if his specialness is recognized and intelligently utilized. I can’t think of anything more annoying than a nervous, energetic Leo/Rat in a lazy snap job— disgruntled? Oh, my.

This sign’s inborn desire to assist his fellows and exert beneficent power qualifies Leo/Rat for all political positions—especially president. He may also make a fine professor whose sideline is writing books and making speeches around the world on his pet subject. Of course the Leo/Rat will make an excellent owner of any type of business and could even be a very successful gentleman farmer on a grand scale. He won’t be too handy at manual tasks. He prefers to be in a position to pay people to fix things for him.`,
  },
  "Leo/Ox": {
    description: `Leadership and dominion combine here to create an unforgettably forceful personality type. The tone of rapport with Leo/Oxen never feels quite intimate or cozy enough. One wonders if there is really a heart beating inside their dense ribcages or whether they are propelled by some remote control device in their garage. This assessment of the indifferent attitude that the Leo/Ox emanates is perhaps harsh, or may seem unfair. But the Leo/Ox is so austere in manner that it’s difficult not to imagine him as obdurately insensitive.

Leo/Oxen get places. They never cease pushing and advancing and arriving at goal upon goal despite hurdle after hurdle. We usually admire the Leo/Oxen that we meet and we cannot help but admit that they are amazing: strong, courageous and, most of all, effective. Leo/Oxen take the reins in every situation and when they are onto a project or idea, they never let up until they have mastered it. These people are opportunists and do not hesitate before the dark wall of the devil. They plunge through fire and never flee conflict.

Normally, Leo/Oxen don’t talk very much. Around the house or office, they come off as strong but silent, even stodgy personages. It’s always obvious that Leo/Ox feels himself individual and separate from the group. And if he involves himself at all in any group endeavor or communion, he must have center stage, do all the talking, crack all the jokes and generally hold forth. Now, all of a sudden, in company with a captive audience, the Leo/Ox becomes gregarious. When he is listened to, the Leo/Ox is an orator, a performer, a fabulous synthesizer of information and a raconteur par excellence.

Leo/Oxen are “know-it-all” types and rarely let anyone get a word in edgewise when they speak. They are not too curious about others’ opinions or reflections on their views. Leo/Oxen is the personification of the Father Knows Best approach. He is the first and final judge of what is suitable and intelligent. If you have a different opinion, keep it. When there is a Leo/Ox in the room, everybody present is on his show. He is intransigently, tenaciously and arrogantly there. You are mere decoration.

The Leo/Ox character seeks permanence and longs for solidity in both personal and public ways. He is as earthy as they come and seems to need to sop up warmth from the outside, to hold on tight to love and marriage and dreams of home and family for dear life. Yes, he is successful and unbeatably strong. But it can get lonely inside that autocratic head. And the Leo/Ox needs somebody else to turn on the heat. He can build and make and do anything at all humanly possible—except simple tenderness. Expressions of affection are not given to the Leo/Ox, and when you get to know them well, you realize that what’s lacking weighs them down. These people have great minds and good memories. In fact, they have trouble forgetting—and forgiving. Humility escapes them. If they goof, they don’t want it to show. Failure is not acceptable. If someone near to their heart disappoints them, they don’t just pass it off as unfortunate or even sad. They take it as a personal affront to their dignity. And they cannot, will not, humble themselves to retrieve lost love.

Although this person is brilliant at order and runs a tight ship, his life will be missing a certain spontaneity. He prefers plans and schedules to the impromptu gathering or hurry-up picnic in the park. He’s rigidly concerned about his image and maintaining same vis-à-vis his subjects. This, of course, cuts down on the Leo/Ox’s jolly times. He’s active and busy and energetic in the extreme. But the Leo/Ox is nonetheless ponderous and somehow, despite the velocity of his life, leadenly slow.`,
    love: `For the Ox, romantic love is frequently reduced to the common denominator of sexuality. The Leo is, however, armed by the sun with inner glowing heat. A Leo/Ox will not be cold in bed nor will he reject the idea of sentiment or sweetness. But he will find it difficult to engage in the frolicsome aspect of love. He cannot forget to take everything seriously. What the Leo/Ox needs as a mate or lover is someone whose sense of permanence helps get the fun together for him. Leo/Oxen are so exaggeratedly sensible that they need to be tickled and teased and learn to accept being jollied up and cheered along by a perfectly adoring and sweetnatured partner.

The real victory in fact, over the Leo/Ox’s dense murk of gravity, is to make him laugh, loosen up and enjoy. If you love an Ox born in Leo, you will surely admire him as well. But that is the easy part. Get him to join a rollerskating club or do yoga. Relax him and limber up the stiff-old-geezer part of his nature. He’ll love you for it and he will never let you down—so long as you obey his every order and don’t get out of hand.`,
    compatibilities: `Green light for Rats (born in 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), Snakes (born in 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Roosters (born in 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) of the Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Libra (born September 23 - October 22), Sagittarius (born November 22 - December 21) and Capricorn (born December 22 - January 19) class. Scorpio (born October 23 - November 21) and Taurus/Dragons (born April 20 - May 20 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) are off limits for you, as well as Scorpio and Aquarius/Tigers (born January 20 - February 18 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034). Taurus/Monkeys (born April 20 - May 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) annoy you with their eternal antics. And Goats? You eat Goats for breakfast.`,
    homeAndFamily: `The Leo/Ox’s home environment will be orderly and impressive. He has always just redecorated and built new closets and bookshelves and had walls removed so that his huge dining table will be better accommodated. Leo/Oxen are big eaters and can learn to be good cooks. They work very hard and need a study or office in their house as well as outside. All will be designed for order and planned to the last butter knife and fish fork for efficient and clean-cut living.

As for his relationships with family and siblings, the Leo/Ox will of course, as always, take all ties and kinships seriously. If he gives a dinner party and doesn’t invite his cousins and nieces and nephews, then he’ll give them a special party of their own the next week. Leo/Oxen are authoritarian but they like to be thought of as fair and just, too.

Woe unto the child of a Leo/Ox who doesn’t toe the mark, work well in school, follow in his mother or father’s well-established social pattern, and do as he is told and not what he wishes with his life. The Leo/Ox gives everything to his kids. He provides them with an array of activities and high-minded outings and holidays and clothes and glut of every possible sort. Leo/Ox is an able and sure-footed family person. But he’s also positively dictatorial. If the spoiled kid with all the toys and clubs and sports doesn’t do what Mama Leo/Ox or Papa Leo/Ox demands, he is exiled.

Leo/Ox kids are impressively self-contained. They want to be allowed to remain separate from the kiddie nucleus and will try to order younger brothers and sisters around. The best environment for a Leo/Ox child is among his peers, where he may find other people of similar strength and sovereignty to learn from. He needs to be taught humility and the value of lightness and frivolity. But he doesn’t learn those qualities easily.`,
    profession: `The Leo/Ox character requires enormous challenge just to get through the day. He is not interested in crazy new notions or zany schemes. He wants to work and achieve and get on with his career. He must be cajoled and coaxed to want to have fun. Mind you, when inspired, Leo/Oxen can be very amusing. They have an uncanny ability to satirize. But their aura is stodgy. And they struggle and plod and drudge toward every performance. Now, you cannot very well put a person like this behind a counter in a five and dime. He’ll take over the whole joint in ten seconds, replace the manager and rearrange the working schedule. Leo/Oxen cannot possibly be asked to perform subordinate roles in their professional lives. Hence, they need to be independent. They must have a sound education and prepare themselves for their work from an early age. They will always rise to the top of any career organization—slowly perhaps, but intensely and certainly.

Bossing is the Leo/Ox’s mission in life. Career possibilities for the Leo/Ox are best selling novelist, Noble Prize winning journalist, president in charge of presidents, king, queen, pope, Dalai Lama, imam or, at the least, chancellor of the exchequer. Another possibility is film director, or any job where a combination of talent for story-telling and dictatorial management is required.`,
  },
  "Leo/Tiger": {
    description: `The old Tiger admonition: “Seek temperance before it’s too late”. fits the Leo brand of Tiger to a T (as in Tiger). If moderation were to be ignored in this borderline arrogant character, the result would be: haughtiness in dissipation, disobedient self-satisfaction, swaggering tyranny. This is a tricky combination. The fate of an intemperate Leo/Tiger could be disastrous.

Throughout his life this subject will feel utterly superior to everything and everybody around him. As a result of his built-in superiority complex, the Leo/Tiger will have difficulty making and keeping friends. Why? Maybe other people just don’t understand how lonely it feels to be the king of the mountain.

Because this person imagines himself a head taller than his fellows, it is impossible for him not to affect a royal bearing. What happens, as he feels a sense of near embarrassment at being so terrific, is that the Leo/Tiger may come off as a snob. His idea of himself is too big to get through the door. So in company he exhibits a kind of phony simplicity, which unfortunately shows. Leo/Tigers try to be appealing, kittenish and even cute. But it doesn’t work. Everybody sees through that air of boyishness. For this reason some people think the Leo/Tiger is insincere. Nothing could be further from the truth. He is merely a tad shy about feeling so magnificent. Leo/Tigers are gutsy. In adversity they have the courage of ten Lions and as many Tigers, all leaders of the pack. They can laugh all the way through illness, exile, sorrow and loss, and still keep their pride posted like a neon sign that flashes HOPE in the densest darknesses that befall them. Theirs is not a bouncy Rooster or Aries resiliency. The Leo/Tiger’s pick-me-up takes the form of a long prowl, watching, psyching out the enemy, slinking through underbrush on padded feet, circling the field hundreds of times waiting for the propitious time for comeback. Then, pounce! They are on their feet and off and running again as though nothing had happened. No migraines. No backaches. Just the panacea of all Tiger ills—movement. As long as the Leo/Tiger doesn’t have to sit in one place waiting for time to heal his wounds, he can get through anything—he can even defy death so long as nobody hobbles his chunky tough legs.

Leo/Tiger people, by the way, are always beautiful to behold. It’s their carriage and poise that gives them the edge in any gathering. They tend toward classical dress and actually don’t fuss much about what they wear as long as it doesn’t get in the way of their actions. Often, they also have that luscious leonine mane of light hair we all long to touch.

This person has a very hard time accepting second place. For example, you may see him dash for the front passenger seat in the car, then catch himself and defer to his grandmother who is, after all, eighty-seven. It’s not the discomfort of the back seat that bothers the Leo/Tiger. It’s the social significance and the sinking feeling of not being up there in front where it’s happening and whence he might even, although he may not be the driver here, exert some control. His lucidity and sense of humor about himself will develop with time, and after thirty-five the Leo/Tiger should mellow into quite a balanced person—providing his head is not irrevocably swollen by years of parental and peer group kow-tows.`,
    love: `Sentiment is not an easy part of the Leo/Tiger’s life. For a start, his natural pride puts people off. The Leo/Tiger’s inner sense of how exceptional he can be and how fabulous he intends to make his life one day may keep him from settling down to one person, making a family and building a home. You see, the Leo/Tiger cannot envisage himself attached to anyone who is not at least equal to him both in power and stature. In so doing, the Leo/Tiger limits his chances for marriage and family life. He does not, however, deprive himself of sexual adventures, wherein he doesn’t much care whether the partner is equal to him so long as he looks up to him and sighs a lot.

Should you find yourself in love with one of these benevolent despots, don’t ever appear weaker than he. Even if you feel like sobbing, keep your dukes up. This person is impassioned by strength, excited by force and turned on by aggressivity. Keep this Cat on his toes!`,
    compatibilities: `Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Sagittarius (born November 22 - December 21) and Capricorn (born December 22 - January 19) enhance your existence. Choose among Dragon (born 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), Horse (born 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) and Dog (born 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) signs. That’s not so many to choose from, but then, you are not the easiest person in the world to please, are you now? Taurus (born April 20 - May 20), Scorpio (born October 23 - November 21) or Aquarius/Monkeys (born January 20 - February 18 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) are out of the question for your lifestyle, as are both Taurus and Aquarius/Oxen. Taurus and Scorpio/Snakes don’t make it for you one bit, and don’t even entertain the thought of a Rabbit partner. Rabbits are not confrontational. But they are subtler than you – and they know how to win by sheer stealth`,
    homeAndFamily: `The Leo/Tiger will probably live in a comfortable but utilitarian home. This person favors authenticity in furnishings and may own only one beautiful antique, which he will proudly display and cleverly place among his other, less expensive, pieces. The Leo/Tiger has an excellent sense of quality and enjoys refinement, but he cannot really be bothered seeking material perfection. He likes to think of himself as a swashbuckler who has no real home, but rather rides the perilous range saving little Native American kids from the rigors of public school education. Heroism and bourgeoiserie don’t go together.

This person is devoted to his family. As long as he is free to race about the earth and busy himself outside the home (if he has one), he will delight in the company of his children, cousins and siblings alike.

Leo/Tiger kids need parental control and lucid reminders that they are not little gods. They will of course have great presence as children, and the temptation is to spoil them rotten and applaud their every blink. Teach them to look in the mirror. Encourage them to try and fit themselves into their own reflection. “There, Johnny. No. Be tinier. Squinch yourself up. That’s it. Now you’re normal. Your superiority complex hardly shows.”`,
    profession: `Talented at managerial jobs, the Leo/Tiger, because of his quest for humility, may not want to boss others. Leo/Tigers like to be left alone to evolve at their own particular pace. They don’t fancy milling about offices with bunches of co-workers and supervisors breathing down their necks. So independent careers are the wisest choices for these people. The Leo/Tiger is a bit of a “cause” person too. He will always find injustices in the world that annoy him and push him toward good deeds. You may find him at the head of charity or socially benevolent organizations. Leo/Tigers are good speakers. They can be teachers or choose sales as a career. They might be excellent actors or singers, too. And the Leo/Tiger may well be gifted in art and follow a calling as a painter or sculptor.`,
  },
  "Leo/Rabbit": {
    description: `This person is so nimble and quick-witted that to know him is to wonder where he went. The Leo/Cat is a double feline with all the evasiveness and slink that such a combination implies. Regal and independent, refined and endowed with Leo’s noble generosity, this sort of person has the wherewithal for greatness. Yet. Leo/Cats rarely seek power or celebrity. Mostly they are content to sit home and listen to their money crinkle. The single character trait that prevents Leo/Cat from forging a public image is squeamishness. This person doesn’t want to see the seamier side or life. He wants no part of bloodshed, conflict, confrontation or enmity. He is after a busy yet peaceful existence.

Being Leo, this subject naturally demands a lot of attention. He likes to be admired. And he prefers to be right. The Leo/Cat retains his leonine right to pomp and vanity, yet he never thrusts his superiority in anyone’s face. The Leo/Cat is a mild-mannered egomaniac. He never forces his high opinion of himself. No matter if you don’t think he’s wonderful, he does. You can trust this creature’s judgment. Leo/Cats have a sixth sense about tricky situations. They sniff out other people’s troubles and lend true assistance to friends in times of need.

Despite this diagnostic gift, Leo/Cats are rarely embroiled in human complexities. Their hunch tells them when something’s about to go awry and they rapidly move in the opposite direction. Leo/Cats eschew muddy waters. They seek clarity in all rapports. Job descriptions are important to them. They must know where they stand in relationships. Whichever way the cookie crumbles, the Leo/Cat doesn’t want any crumbs on his side of the bed.

The Leo/Cat is supremely able. He’s willing and participates—so long as he gets some of the best lines—amiably. He is also capable of fathoming the need for humility and so can learn how to play second fiddle if need be. If they don’t offer him the position of top dog, the Leo/Cat will take a graceful step backward, the better to pounce next time.

I think Leo/Cat skirts the spotlight’s glare out of a sense of selfpreservation. If double cat signs have eighteen lives, it’s probably because they know how to stay out of the line of fire.

This Leo is prudent and munificent, wily and wise. He creeps upon Lady Luck when she isn’t looking. Leo/Cats are loophole leapers. They never use their elbows.`,
    love: `As the Leo/Cat is extremely popular among members of the other sex, he or she will have some difficulty fending off admirers. The character of Leo/Cat is somewhat intense and may give the (false) impression of lust. Actually this person’s main interest in choosing a partner is the other person’s ability to fit into Leo/Cat’s well-ordered universe. He’s more careful than passionate.

If you love a Leo/Cat, never be guilty of vulgarity of any kind. These people deplore shabbiness. Show your taste for refinement. Point up your love of hearth and home. This character’s main pleasures center around what happens in his or her living room. Be a good sport and whatever you do, don’t whine! Leo/Cats have no patience with snivelers. Learn how to blink your eyes admiringly and don’t expect any kudos—just lots of good sound Leo/Cat advice and admonitions about how mindful one should be of everything from drafts to overdrafts.`,
    compatibilities: `You will be attracted to Aries (born March 21 - April 19), Libra (born September 23 - October 22) and Capricorn/Goats (born December 22 - January 19 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) and Capricorn/Pigs (born December 22 - January 19 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031). You find Sagittarius/Pigs (born November 22 - December 21 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) cute, too. Don’t be surprised if you wake up next to a Dog for the rest or your days. You are enchanted by Dog people born in Gemini (born May 21 - June 20), Libra (born September 23 - October 22) or Sagittarius (born November 22 - December 21). They seem so “involved,” which appeals to your sense of altruism. Not so for Taurus (born April 20 - May 20), Scorpio (born October 23 - November 21) or Aquarius/Rats (born January 20 - February 18 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), Aquarius/Tigers (born January 20 - February 18 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Aquarius/Roosters (born January 20 - February 18 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029). You are not exactly crazy about Scorpio/Dragons (born October 23 - November 21 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or Taurus/Rabbits (born April 20 - May 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) either.`,
    homeAndFamily: `The Leo/Cat is certain to want elegance in his or her surroundings. Fine antiques of real value will furnish a solid house, which is most likely paid for. There can be a touch of exhibitionist grandeur in this subject’s taste center. It’s characteristic but not serious.

As a parent this person will be loving and demanding of hard work and respect from offspring. Leo/Cats don’t: usually allow their kids to indulge in folderol. For Leo/Cats, the place for frivolity is on vacation; otherwise, it’s shoulder to the wheel.

Leo/Kittens are smart little buggers who keep their own counsel and usually only clutter up their parents’ lives with their diplomas and honors. They can be cheeky though, as they are always right. And they can even be rebellious if, God forbid, they are horn into a noisy, vituperative family group. Leo/Cats don’t like noise unless they make it—and they don’t do that very often. This child needs his or her own space in which to rest in peace between exams and piano lessons, ballet classes and computer courses. He or she is probably very pretty to look at.`,
    profession: `Not many tasks escape the skill of the Leo/Cat. Be it manual or intellectual, the work is the objective in itself. This person will enjoy what he or she chooses as a career. Whatever he or she does, the result is likely to be brilliant. Leo/Cat likes to shine and be adored by fellow workers, be they subordinates or equals.

It’s very hard for a Leo/Cat not to be boss. But unlike certain Leos this one is able to accept retiring jobs or at least not go mad it he doesn’t get this or that promotion. The Leo/Cat boss will be slightly patronizing but tries to be fair. There is, however, no doubt the show Is Leo/Cat’s personal trip and all employees are paid guests. An obedient servant, the Leo/Cat will only be subservient when he has no other choice.

Jobs best suited to the Leo/Cat personality are: antique dealer, doctor, jeweler, attorney, teacher, philosopher, veterinarian, artist.`,
  },
  "Leo/Dragon": {
    description: `My notes on this combination proclaim: “A total egomaniac with a heart of gold.” Is that what we are to think of Leo/Dragons? Are they truly so selfcentered as to deserve the hyperbolic appellation of “egomaniac”? Yes. They are. But I mean it as a compliment.

It is not given to everyone to be born superior to her or his fellows. And, as I have repeated at least three times in this book alone, no sign is better than another. There is no such thing. But Leo/Dragons are damned lofty creatures whose act is so together and whose health and courage and true sense of “noblesse oblige” are so well developed that one is almost tempted to say all signs are equal but some are more equal than others. Don’t go guessing that the love of my life is a Leo/Dragon and that’s why I’m carrying on like this. It’s not my style at all (much to my own chagrin) to hang out with these monarchical types. I’m a Tiger. These people would have me for breakfast. No. I’m not in love with a Leo/Dragon. But I have always thought that if I’d had a choice of signs to be “when I grow up,” I’d choose Leo/Dragon. It’s so ... so pompous and magnificent, and ever so nice as well.

Leo is the magnanimous Dragon. The fair and just Dragon. The loyal, powerful and protective Dragon. It is this Dragon who best personifies what Dragons are all about. Fire. Sunshine. Noise. Expertise and self-confidence. And in a funny way this is the one sign that allows for Leo’s magnanimity to outweigh his immodest side.

Leos are good-hearted and emanate warmth and like to share their wealth. Dragons can be purely selfish. But they are hopelessly sentimental. The combination is just right for give and take because where the Leo might be too generous the Dragon side steps in and says “Nope. Not thirty tons of jellybeans for the kids at the orphanage. Oh well, go ahead. Yes, give them three tons.” And when the Dragon gets a little stingy, his Leo angel comes along and says, “You should be ashamed of yourself. Give that poor widow a bunch of money and hurry up about it!” Leo/Dragon is a mix that works. The integrity and true nobility of Leo are precisely the qualities lacking in many Dragon subjects. The Dragon’s mistrust calms the Leo’s tendency to believe in himself just a smidgen too much. Also, Dragon brings Leo good health and a kind of sizzling vitality that is sometimes lacking in the slightly languorous Leo.

This subject is so sentimental that it amounts to a weakness. He cannot tolerate the knowledge of personal tragedy. He skips over the articles in the newspaper about battered children and squashed dogs. He’s so soft-hearted that he’s almost squeamish. But he is dutiful, too. He will take the reins and come to the fore if the tragedy happens in his own realm or family. Otherwise he’d rather not discuss the story about the boy locked in a closet for ten years. He’s too sympathetic to the boy’s plight.

Unusual longevity is often awarded the Leo/Dragon. They are extremely vain, so the desire to stay better-looking longer may urge them to watch what they ingest. And this is a sign whose subjects take care of themselves in order to better take care of others. Moreover, they are always so busy with huge, complicated, earth-shaking projects that growing old is nigh unto impossible—they don’t have the time to be decrepit. As well, remember that Dragon people are awarded exceptional good health at birth.`,
    love: `This area of the Leo/Dragon’s life is frequently bumpy, to say the least. Look at it this way: These people are rightly convinced of their superiority from the jump. They rarely hesitate or take stock before deciding what to do. They just seem to know what they want and go after it. The Leo/Dragon rules. It’s his fate by virtue of his title.

As Leo/Dragon is blatantly aware of his innate mission to surpass others, he’s a handful as a lover or mistress, spouse or companion. You will be but an “accessory” and although you may achieve the rank of necessary accessory you will nonetheless remain superfluous to his survival. To love this person properly you must accept living in his shadow, which will loom over your whole existence, protecting and shading you from overexposure to the world. If you like competition, stay away from this person—unless, of course, you are also a Leo/Dragon.`,
    compatibilities: `You are “in like with” Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Libra (born September 23 - October 22), Sagittarius (born November 22 - December 21) and Capricorn (born December 22 - January 19). From among these occidental signs you do well to choose Monkeys (born 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028), Roosters (born 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) and Snakes (born 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025). The Monkey assists but doesn’t compete. The Rooster firms up your plans and carries them through. The Snake is so beautiful that he or she doesn’t need to do much of anything but accompany you to functions and remain attractively quiet.. Aries and Sagittarius/Rats (born 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) will do as well. Taurus (born April 20 - May 20), Scorpio (born October 23 - November 21) and Aquarius/Oxen (born January 20 - February 18 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) and all manner of disquiet Dog (born 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) are too dour and may attempt to impose rigor where you need it least.`,
    homeAndFamily: `Leo/Dragon’s home is his stronghold. He may well build a very tall wall around it too, with or without moat, depending on his means. You are invited at any time to visit or to stay awhile. Leo/Dragons are hospitable in the extreme. Besides, they like having as many subjects around the palace as they can. They tend to like precious antiques and objects made of gold. Why are we not surprised?

Parenting will attract the Leo/Dragon. They often have several children from several difficult unions. But they do not neglect any of their children or spouses. They think it would be nice if everybody sort of lived together. These people are serious about their kids’ welfare and insist that they study and eat properly, be in the house on time and do chores when asked without sulking. Leo/Dragon mothers are not usually smotherers. They rule with an iron hand but they love intensely, too.

A Leo/Dragon child will automatically make the most of his life. There is little you have to do except put up with him. He will certainly be a noisy and demanding child. Pay no attention or, if you’d rather, spoil him rotten. It won’t change anything anyway. This kid is unflinchingly sure of what life has to offer and doesn’t need much advice.`,
    profession: `Sorry, Leo/Dragon, but the job market for benevolent despots is filled to the teeth right now. I’d suggest you try forming your own country. But seriously, the Leo/Dragon has talents for almost anything. He can be a computer expert or a baseball player, a journalist or a novelist, an actor or a designer. Whatever he or she chooses to do, it is likely it will be done well. Failure kills Leo/Dragons off like flies. They normally don’t allow for it. But when it happens, they succumb. The fire goes out and the Grim Reaper knocks insistently.

As an employer Leo/Dragon is all the things I promised earlier and then some. He or she should prove to be fair, just and despotic. Kind underneath all the abrasive personality traits. And , despite the Dragon’s occasional tendency to limit spending, generous. I can’t think of Leo/Dragons as employees, but I suppose they have to start somewhere. Likely they will be a pain in the neck until they get to be boss and take your job away from you.`,
  },
  "Leo/Snake": {
    description: `The Snake born in Leo is always right. Even if he’s wrong. He is nonetheless absolutely certain that he knows best. And frequently, especially for himself and in order to achieve his own ends, the Leo/Snake is not far off. Wisdom and clairvoyance are part of the Snake legacy. But the addition of Leo to the cool-headed Snake character, although it lends some sunshine and warmth, also deals this character a hand loaded with vanity. Now the already extravagant and presumptuous Snake has to carry around excess baggage in the form of a swollen skull that just doesn’t quit. Then too, there is the question of Leo will. The pushiness quotient is rising. And we also have to consider the Snake’s inherent laziness. And his tendency to dissimulate and pinch pennies. Are you beginning to get the picture? Can you see why the Leo/Snake is always—infuriatingly—right? Of course anybody who is so indubitably right has to go very often far wrong. Extremes operate that way. But as they say in French, and I paraphrase, No matter how high up you may be sitting, it is wise to remember you are only sitting on your derrière. Accepting his own pride as occasional foolishness or humbling himself long enough to accept aid or assistance is simply beyond the Leo/Snake. He is one of those people who always gives you an indulgent laugh and snaps, “Don’t be so naive! I know what I’m doing.” Shortly after you have turned tail and left the overconfident Leo/Snake teetering at the edge of his favorite precipice, you hear the thud. He’s not one to complain.

Leo/Snakes invariably arrive at the summits they climb to by means of their attractiveness and charm. These people are not even charming on purpose. They exude, breathe, ooze attraction. When you meet one, be prepared for a metallic “ping” sound to go off in your head. Even if you were not thinking of paying attention to them, Leo/Snakes, by their very presence in the same room with you, will mutely and coldly demand attention.

As you get to know them, Leo/Snakes will loosen up and warm to your personality. They need friendship and are loyal to their pals—especially their old cronies. But they will never, no matter how well you know them, allow you the luxury of giving them advice. They will dish out hours of “you should do this and you must try that” but our Leo/Snake wants none of that nonsense from you. How could you, poor dear, know anything about what they should do? Fact is, this refusal to accept counsel is often their undoing. Leo/Snakes have been known to go under because they wouldn’t listen to reason.

Deep down, Leo/Snakes entertain thoughts of grand charitable gestures and acts of philanthropy. They really think that one day they will make some kind of huge contribution that will cure social ills or help the starving poor. But the day rarely arrives when they actually do much more than adopt a war orphan or cut the ribbon to open the local playground. They don’t mean to be remiss, but Leo/Snakes get too caught up in their own personal tragedies and losses (of which, poor things, they have more than their share) to really see that their grand good deeds get done. Too, they are a little more indolent than they ought to be and fairly self-involved. None of the above makes it easy to do much more than write a check for the United Fund.

The Leo/Snake cannot live happily without bushels of finery. Even the poorest Leo/Snake will always be wearing the latest net stockings, sporting an ivory cigarette holder and blinking out at the world from behind a tiny jet veil. The Leo/Snake has natural class and style. Even ugly Leo/Snakes are beautiful. It’s the way they stand there with that come hither look in their eye that makes Leo/Snake people irresistible. Too, when they can (and they usually get to where they can in a big way), Leo/Snakes shower themselves with little gifties and accessories from Tiffany and Cartier and Van Cleef. These are the mysterious people you are always wondering about who keep posh jewelers like Harry Winston in business. Never underestimate the Leo/Snake’s capacity for drugs either. There is a dangerous tendency here to delight in consciousness-altering substances. It could be that the Leo/Snake is seeking solace from his cold, cold natural habitat. But this tendency must be watched, and watched closely.`,
    love: `Here is the Leo/Snake’s own private quarter. His life will be a veritable merry-go-round of love. He may have lots of affairs and a few marriages and divorces. But that is not what I mean to imply. I mean that the Leo/Snake personality distinguishes itself from others because of its beloved character. Leo/Snake people are always famous loved ones. They incite and inspire great love the way great mythical characters can. Leo/Snakes are the world’s greatest “lovees.” They seem to attract a partner out of nowhere, hold on to him with stranglehold tenacity and will until the person is limp from worshiping his love object, and then—sometimes, not always—they slough the poor creature off into oblivion again.

Now by this I do not mean that Leo/Snakes are any more promiscuous than other Snakes (which isn’t saying much, I know, but fair is fair). It’s just that they are the most loved of all our notoriously lovable Snakes. If you love a Snake, hand in your key to the Chastity Belt Club, rush out and become president of General Motors so you can support the Leo/Snake’s voracious acquisitive instincts and, above all, join a gym. You will never cease to adore your Leo/Snake partner and he or she will probably know that. But my advice to someone who wants to keep any rapacious Leo/Snake under control is to make yourself unavailable. Take an occasional “business” trip. Make the Leo/Snake wonder what you’re up to—for a change.`,
    compatibilities: `I love my wife, but oh you Snake! Gemini (born May 21 - June 20), Libra (born September 23 - October 22), Sagittarius (born November 22 - December 21) and Capricorn/Oxen (born December 22 - January 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) will follow you anywhere you want to go. The same goes for Aries (born March 21 - April 19), Libra (born September 23 - October 22) and Capricorn/Dragons (born December 22 - January 19 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024). Sagittarius (born November 22 - December 21) and Capricorn/Roosters (born December 22 - January 19 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) are wild about you, too. Face it. You’re gorgeous! Even Libra/Roosters (born September 23 - October 22 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) fall flat for your charms. Nix on Taurus (born April 20 - May 20), Scorpio (born October 23 - November 21) and Aquarius/Tigers (born January 20 - February 18 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Aquarius/Pigs (born January 20 - February 18 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031). All Tigers are too speedy and impetuous for your languid pace. And Pigs may be fair game, but you tend to treat their innocence unfairly.`,
    homeAndFamily: `Get out the address and phone number of your favorite domestic service agency and have it tattooed on your wrist. Leo/Snakes need luxury, and they need lots of it! To enter a Leo/Snake home is to finally understand the meaning of the word “palatial.” Leo/Snakes were invented to lounge, to look good in negligees and smoking jackets, to be promised anything and given designer everything. Leo/Snakes are born recipients. They like to entertain and be offered champagne and flowers, introduced to myriad prospective husbands and coddled and cuddled by their guests. Their surroundings are, of course, ultra-important. And always impeccable—providing the maid didn’t take a sick day.

The average Leo/Snake probably gives birth to three-quarters of a child per lifetime. Parenting is not their thing. I mean, picture a glacially gorgeous, pristine princess in a floaty peach peignoir feeding strained spinach to a gurgling infant. It’s absurd. A Yorkshire? Maybe. But not a real live squawking, puking baby! Mind you, when these people do manage to hatch a couple of kids they make serious and intelligent parents. It’s not really in the cards, but when it comes along baby is adored. Leo/Snakes don’t hate children. But they are a mite on the fragile side where emotions are concerned and the traumas of raising children can actually bring on migraines, depressions and anxiety attacks.

Also, Leo/Snakes are bright. They are among the most intellectual of signs. So a lot of the time they are too busy reading to get down to the business of baby-making.

Leo/Snake kids show right from the jump that they are not willing to take any nonsense about doing dirty work around the house or pitching in to run the vacuum cleaner after school. They may offer to find themselves a rich man who will pay for you to have help. But normally, Leo/Snake kids like to do two things: strut their stuff and do their homework. Their health is a bit shaky. Take them often to good doctors. And tickle them once in a while. Leo/Snake children take themselves too seriously.`,
    profession: `Leo/Snakes might be able to work providing the work was cerebral in nature and could be accomplished from the unusual vantage point of a chaise longue. Leo/Snakes are industrious, but only with their brains. They are most decidedly not movers and shakers. I can’t see a Leo/Snake rushing about carrying pots of bubbling fondue to a catering job, or even running an office full of cackling cuties. The Leo/Snake is high-strung and wired for brilliance. He’s a loner, and if he accomplishes anything spectacular, it shows.

This is one employee you would never be able to convince to work in the stock room or accept having an office without a window. If you have a Leo/Snake employee, watch your job. You may be in serious danger of being supplanted by your hired hand. Even so, Leo/Snakes don’t make excellent bosses. They can’t be bothered bossing people around …in a designer negligee?

Standing up to the strong-willed Leo/Snake in any professional capacity will be difficult. He could make a super lawyer or sales person. But your average Leo/Snake would rather know a lot about a lot and then become a famous movie star—it’s prettier than being a lawyer.`,
  },
  "Leo/Horse": {
    description: `The Leo/Horse is a whirlwind of energy and charm, a person who gallops through life with unbridled enthusiasm and a knack for making things happen. This combination blends Leo’s natural charisma with the Horse’s adventurous spirit, creating a personality that’s both dazzling and dynamic. Leo/Horses are the life of the party, always ready to entertain, inspire, or lead the charge into the next big adventure.

Their popularity is undeniable. People are drawn to their infectious optimism and their ability to turn even the most mundane moment into something exciting. They’re accomplished and dexterous, often juggling multiple projects or passions with ease. However, their hastiness and impatience can lead to careless mistakes, and their opportunistic streak sometimes makes them seem self-serving. They’re not malicious, but they’re always on the lookout for the next big opportunity to shine.

Leo/Horses love to be admired, and they thrive in environments where they can showcase their talents. They’re not content to sit on the sidelines—they want to be in the thick of things, leading, creating, or performing. Their eloquence makes them natural communicators, whether they’re rallying a team or charming a crowd. But their fickleness can make it hard for them to stick to one path, and their selfishness can sometimes alienate those who feel overshadowed by their brilliance.`,
    love: `In love, the Leo/Horse is passionate, romantic, and a bit of a show-off. They love grand gestures and sweeping declarations, and they want a partner who can keep up with their fast-paced, adventurous lifestyle. They’re fiercely loyal when truly committed, but their fickle nature can make them flirtatious or restless in relationships that feel too routine. A Leo/Horse needs a partner who’s confident enough to handle their larger-than-life personality and independent enough to give them space.

If you love a Leo/Horse, be prepared for a rollercoaster. They’ll shower you with affection and excitement, but they’ll also demand attention and freedom. Keep them engaged with new experiences, and don’t try to tie them down too tightly—they’ll bolt. Show them you can match their energy, and they’ll be yours for the long haul.`,
    compatibilities: `You’ll find great chemistry with Tiger subjects, especially those born under Aries (born March 21 - April 19), Gemini (born May 21 - June 20), or Libra (born September 23 - October 22). Dogs, particularly Gemini, Libra, or Sagittarius/Dogs (born November 22 - December 21 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030), are also a fantastic match. Goats from Aries (born March 21 - April 19) or Libra (born September 23 - October 22) work well, too. Avoid Rats, especially Gemini, Libra, or Sagittarius/Rats (born November 22 - December 21 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), as their cunning clashes with your straightforwardness. Oxen, particularly Taurus (born April 20 - May 20) or Scorpio/Oxen (born October 23 - November 21 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), may also be too stubborn for your free-spirited nature.`,
    homeAndFamily: `The Leo/Horse’s home is a lively, welcoming space, often filled with friends, music, and laughter. They love to entertain and make their home a hub of activity. As parents, they’re fun and inspiring, encouraging their children to explore, take risks, and chase their dreams. However, their impatience can make them less adept at handling the day-to-day grind of parenting.

The Leo/Horse child is a bundle of energy, always on the move and full of big ideas. They’ll need guidance to focus their enthusiasm and avoid spreading themselves too thin. Encourage their creativity, but teach them the value of patience and follow-through.`,
    profession: `Leo/Horses are born for roles that let them shine. They thrive in creative, high-energy fields like entertainment, marketing, or entrepreneurship. Their dexterity and eloquence make them excellent at pitching ideas or rallying teams, but their impatience can lead to rushed decisions. They’re not suited for repetitive or overly structured jobs—they need variety and the chance to take risks.

As employees, Leo/Horses are dynamic and innovative, but they can be hard to manage if they feel constrained. As bosses, they’re inspiring but sometimes overly demanding, expecting everyone to keep up with their relentless pace. They’re at their best when given the freedom to lead and create.`,
  },
  "Leo/Goat": {
    description: `The Leo/Goat is a delightful blend of creativity and charisma, a person who brings a touch of whimsy to everything they do. This combination marries Leo’s natural flair with the Goat’s sensitivity and aesthetic sense, creating a personality that’s both magnetic and deeply artistic. Leo/Goat people are dreamers who can turn their visions into reality, often with a flourish that leaves others in awe.

They’re inventive and persevere in their pursuits, whether it’s creating a masterpiece or building a cozy, beautiful life. Their gentleness makes them approachable, and their sensitivity allows them to connect deeply with others. However, their tendency toward pessimism and worry can cast a shadow over their sunny Leo disposition, and their dependency can make them lean too heavily on others for support. They’re not lazy, but their tardiness and lack of foresight can frustrate those who rely on them.

Leo/Goat people have a strong aesthetic sense and a love for beauty in all its forms. Their homes, clothes, and even their conversations reflect their refined taste. They’re not as domineering as other Leos, thanks to the Goat’s gentler influence, but they still crave admiration and validation for their creative efforts.`,
    love: `In love, the Leo/Goat is romantic, attentive, and deeply emotional. They pour their heart into their relationships, seeking a partner who appreciates their creativity and sensitivity. They’re not as demanding as other Leos, but they do need reassurance and affection to feel secure. Their dependency can sometimes make them clingy, but their genuine warmth makes it easy to forgive.

If you love a Leo/Goat, be prepared to be their cheerleader. They need encouragement to overcome their self-doubt and pessimism. Offer them stability and appreciation, and they’ll reward you with unwavering loyalty and a love that’s both tender and passionate.`,
    compatibilities: `You’ll find harmony with Rabbit subjects, particularly those born under Aries (born March 21 - April 19), Libra (born September 23 - October 22), or Sagittarius (born November 22 - December 21). Pigs, especially Aries (born March 21 - April 19), Libra (born September 23 - October 22), or Capricorn/Pigs (born December 22 - January 19 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031), are also a great match. Horses from Aries (born March 21 - April 19) or Libra (born September 23 - October 22) work well, too. Avoid Oxen, particularly Taurus (born April 20 - May 20) or Scorpio/Oxen (born October 23 - November 21 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), as their rigidity clashes with your free-spirited nature. Dogs, especially Taurus (born April 20 - May 20) or Scorpio/Dogs (born October 23 - November 21 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030), may also be too practical for your whimsical soul.`,
    homeAndFamily: `The Leo/Goat’s home is a haven of beauty and comfort, filled with art, soft textures, and a warm, inviting atmosphere. They love creating a space that reflects their personality and makes others feel at ease. As parents, they’re nurturing and imaginative, encouraging their children to explore their creativity. However, their tendency to worry can make them overprotective.

The Leo/Goat child is sensitive and artistic, with a vivid imagination. They’ll need reassurance to build their confidence and guidance to stay focused on their goals. Foster their creativity, but help them develop practical skills to balance their dreamy nature.`,
    profession: `Leo/Goats excel in creative fields where their inventiveness and aesthetic sense can shine. Think artists, designers, or writers. They’re not as driven by ambition as other Leos, but their perseverance helps them achieve their goals over time. They thrive in environments that allow them to express themselves freely and avoid rigid, high-pressure settings.

As employees, Leo/Goats are dedicated and creative, but they need a supportive environment to thrive. As bosses, they’re gentle and encouraging, but their lack of foresight can lead to organizational challenges. They’re at their best when given the freedom to create and inspire.`,
  },
  "Leo/Monkey": {
    description: `The Leo/Monkey is a dazzling performer, blending Leo’s charisma with the Monkey’s quick wit and cunning. This person is a master of improvisation, always ready with a clever quip or a bold idea to steal the show. They’re confident, charming, and a little mischievous, with a knack for turning any situation to their advantage.

Leo/Monkeys are stable in their core, but their opportunistic streak makes them adaptable to almost any environment. They thrive on attention and love being the center of the action, whether it’s in a boardroom, on a stage, or at a party. Their loquacity and wit make them excellent conversationalists, but their tendency toward deceit and manipulation can sometimes get them into trouble. They’re not malicious, but they’re not above bending the truth to get what they want.

Their self-involvement can make them seem aloof or selfish at times, but their genuine warmth and humor usually win people over. Leo/Monkeys are ambitious, but they pursue their goals with a playful, almost effortless grace that masks their underlying drive.`,
    love: `In love, the Leo/Monkey is charming, flirtatious, and full of surprises. They love the thrill of romance and enjoy keeping their partner on their toes. They’re generous with their affection but can be self-centered, expecting their partner to revolve around their needs. A Leo/Monkey needs a partner who’s confident, witty, and not easily rattled by their occasional trickery.

If you love a Leo/Monkey, be ready for a relationship that’s never boring. They’ll keep you entertained, but you’ll need to set boundaries to keep their manipulative tendencies in check. Show them you can match their wit, and they’ll respect you all the more.`,
    compatibilities: `You’ll find great partners in Rat subjects, particularly those born under Aries (born March 21 - April 19), Gemini (born May 21 - June 20), Libra (born September 23 - October 22), or Capricorn (born December 22 - January 19). Dragons, especially Gemini, Libra (born September 23 - October 22), or Capricorn/Dragons (born December 22 - January 19 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), are also a fantastic match. Snakes from Libra or Capricorn work well, too. Avoid Tigers, particularly Taurus (born April 20 - May 20), Scorpio (born October 23 - November 21), or Aquarius/Tigers (born January 20 - February 18 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034), as their impulsiveness clashes with your calculated nature. Pigs, especially Taurus (born April 20 - May 20) or Scorpio/Pigs (born October 23 - November 21 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031), may also find your cunning hard to handle.`,
    homeAndFamily: `The Leo/Monkey’s home is a vibrant, eclectic space, filled with quirky touches and bold designs. They love entertaining and making their home a stage for their personality. As parents, they’re fun and engaging, encouraging their children to think outside the box. However, their self-involvement can make them less attentive to their kids’ emotional needs.

The Leo/Monkey child is clever, mischievous, and full of charm. They’ll need guidance to channel their energy into productive pursuits and to learn the value of honesty. Encourage their creativity, but set clear expectations to keep their guile in check.`,
    profession: `Leo/Monkeys shine in roles that require quick thinking and charisma. Think sales, public relations, or stand-up comedy. Their ability to improvise and adapt makes them excellent problem-solvers, but their manipulative tendencies can sometimes undermine their credibility. They’re not suited for rigid or monotonous jobs—they need variety and the chance to shine.

As employees, Leo/Monkeys are innovative and engaging, but they can be difficult to manage if they feel bored. As bosses, they’re charismatic and motivating, but their selfishness can make them less empathetic to their team’s needs. They’re at their best when given the freedom to think on their feet.`,
  },
  "Leo/Rooster": {
    description: `The Leo/Rooster is a bold, confident character who struts through life with a mix of resilience and flamboyance. This combination blends Leo’s regal charisma with the Rooster’s enthusiasm and candor, creating a personality that’s both commanding and refreshingly honest. Leo/Roosters are not afraid to speak their mind, and their humor and chic style make them stand out in any crowd.

They’re resilient and able to bounce back from setbacks with remarkable ease. Their enthusiasm is infectious, and they have a knack for rallying others to their cause. However, their pomposity and cockiness can rub people the wrong way, and their tendency toward pedantry can make them seem overly critical. They’re conservative in their values, preferring tradition and structure, but their Leo flair ensures they’re never boring.

Leo/Roosters are driven by a desire to succeed, but their dissatisfaction can make them hard to please. They have high standards and expect others to meet them, which can lead to tension in relationships or work. Their blind spots—particularly their inability to see their own flaws—can also cause problems, but their humor and warmth usually smooth things over.`,
    love: `In love, the Leo/Rooster is passionate, loyal, and a bit bossy. They love to take charge in relationships, planning romantic outings and setting the tone. They’re candid about their feelings, which can be both refreshing and overwhelming. A Leo/Rooster needs a partner who can handle their strong personality and isn’t afraid to stand up to their occasional arrogance.

If you love a Leo/Rooster, be prepared for a relationship that’s full of energy and honesty. They’ll keep things exciting, but you’ll need to call them out on their bossiness from time to time. Show them you admire their resilience, and they’ll be devoted to you.`,
    compatibilities: `You’ll find harmony with Snake subjects, particularly those born under Libra (born September 23 - October 22), Sagittarius (born November 22 - December 21), or Capricorn (born December 22 - January 19). Oxen, especially Gemini (born May 21 - June 20), Libra (born September 23 - October 22), or Capricorn/Oxen (born December 22 - January 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), are also a great match. Dragons from Libra or Capricorn work well, too. Avoid Rabbits, particularly Taurus (born April 20 - May 20), Scorpio (born October 23 - November 21), or Aquarius/Rabbits (born January 20 - February 18 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), as their sensitivity clashes with your bluntness. Rabbits, especially Taurus or Scorpio/Rabbits, may also find your candor too harsh.`,
    homeAndFamily: `The Leo/Rooster’s home is a stylish, organized space that reflects their love for tradition and flair. They take pride in creating a welcoming environment for family and friends. As parents, they’re encouraging and disciplined, pushing their children to excel while instilling strong values. However, their bossiness can make them overly controlling at times.

The Leo/Rooster child is confident, outspoken, and a bit of a show-off. They’ll need guidance to temper their cockiness and learn to listen to others. Encourage their enthusiasm, but teach them the value of humility.`,
    profession: `Leo/Roosters excel in roles that require confidence, organization, and a touch of flair. Think event planners, public speakers, or corporate managers. Their resilience and enthusiasm make them natural leaders, but their pedantry and dissatisfaction can make them hard to work with. They’re not suited for chaotic or overly flexible environments—they need structure to thrive.

As employees, Leo/Roosters are hardworking and reliable, but they can be overly critical if things don’t go their way. As bosses, they’re commanding and organized, but their bossiness can alienate their team. They’re at their best when given the chance to lead with clear goals in sight.`,
  },
  "Leo/Dog": {
    description: `The Leo/Dog is a fascinating mix of loyalty and charisma, blending Leo’s boldness with the Dog’s deep sense of duty and guardianship. This person is a natural protector, always ready to stand up for those they care about or defend a cause they believe in. Their intelligence and altruism make them a force for good, but their cynicism and anxiety can sometimes cloud their sunny Leo disposition.

Leo/Dogs are fiercely loyal, whether to friends, family, or their principles. They’re not as flashy as other Leos, thanks to the Dog’s introverted influence, but they still command attention with their quiet strength and unwavering commitment. Their stubbornness can make them difficult to sway, and their pessimism can lead to moments of doubt or worry. However, their warmth and genuine desire to help others make them deeply respected.

They’re not ones to seek the spotlight for its own sake, but they often find themselves in leadership roles because of their intelligence and sense of responsibility. Their unease and defensiveness can make them cautious, but once they trust someone, they’re a friend for life.`,
    love: `In love, the Leo/Dog is devoted, protective, and deeply emotional. They’re not into casual flings—they want a partner they can trust and build a life with. Their loyalty is unmatched, but their anxiety and defensiveness can make them seem overly cautious or clingy. A Leo/Dog needs a partner who’s patient, understanding, and willing to reassure them when their worries get the better of them.

If you love a Leo/Dog, be prepared to earn their trust. They’re not quick to open up, but once they do, they’ll be your most steadfast ally. Show them you value their loyalty and share their sense of duty, and they’ll love you fiercely.`,
    compatibilities: `You’ll find great partners in Tiger subjects, particularly those born under Gemini (born May 21 - June 20), Libra (born September 23 - October 22), or Sagittarius (born November 22 - December 21). Horses, especially Aries (born March 21 - April 19), Gemini (born May 21 - June 20), or Libra/Horses (born September 23 - October 22 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026), are also a fantastic match. Rabbits from Libra or Sagittarius work well, too. Avoid Dragons, particularly Taurus (born April 20 - May 20), Scorpio (born October 23 - November 21), or Aquarius/Dragons (born January 20 - February 18 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), as their intensity clashes with your cautious nature. Goats, especially Taurus (born April 20 - May 20) or Scorpio/Goats (born October 23 - November 21 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027), may also find your pessimism hard to handle.`,
    homeAndFamily: `The Leo/Dog’s home is a warm, secure space where family and friends feel protected and valued. They take their role as guardian seriously, ensuring their loved ones are cared for. As parents, they’re nurturing and disciplined, instilling a strong sense of responsibility in their children. However, their anxiety can make them overprotective at times.

The Leo/Dog child is loyal and thoughtful, with a strong sense of right and wrong. They’ll need encouragement to overcome their self-doubt and step out of their comfort zone. Foster their intelligence and sense of duty, but help them manage their worries.`,
    profession: `Leo/Dogs excel in roles that combine leadership with a sense of purpose. Think teachers, social workers, or community organizers. Their intelligence and altruism make them excellent at serving others, but their stubbornness can make them resistant to change. They’re not suited for high-risk or chaotic environments—they need stability to shine.

As employees, Leo/Dogs are reliable and hardworking, but their defensiveness can make them sensitive to criticism. As bosses, they’re fair and protective, but their anxiety can make them overly cautious. They’re at their best when given the chance to lead with a clear sense of mission.`,
  },
  "Leo/Pig": {
    description: `The Leo/Pig is a warm, generous soul, blending Leo’s charisma with the Pig’s sincerity and love for the finer things in life. This person is a natural host, always ready to welcome others with open arms and a lavish spread. Their gallantry and honesty make them beloved, but their naiveté and gullibility can sometimes leave them vulnerable.

Leo/Pigs are cultured and have a deep appreciation for beauty, art, and pleasure. They’re not as domineering as other Leos, thanks to the Pig’s gentle influence, but they still love to be admired and appreciated. Their hot-temperedness can flare up when they feel disrespected, but their sincerity usually smooths things over. They’re materialistic and love indulging in life’s luxuries, but they’re equally happy sharing their bounty with others.

Their scrupulousness makes them meticulous in their pursuits, whether it’s planning a perfect dinner party or pursuing a creative project. However, their self-indulgence and sensuality can sometimes lead them astray, and their gullibility can make them easy targets for those with less-than-honest intentions.`,
    love: `In love, the Leo/Pig is passionate, romantic, and deeply devoted. They love to spoil their partner with gifts, affection, and grand gestures. They’re sincere and open-hearted, but their naiveté can make them overly trusting in relationships. A Leo/Pig needs a partner who’s honest, supportive, and appreciates their generous nature without taking advantage of it.

If you love a Leo/Pig, be prepared to be pampered. They’ll go all out to make you feel special, but you’ll need to be patient with their occasional temper flares. Show them you value their sincerity, and protect them from those who might exploit their trust.`,
    compatibilities: `You’ll find harmony with Rabbit subjects, particularly those born under Aries (born March 21 - April 19), Libra (born September 23 - October 22), or Sagittarius (born November 22 - December 21). Goats, especially Aries (born March 21 - April 19), Libra (born September 23 - October 22), or Capricorn/Goats (born December 22 - January 19 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027), are also a great match. Tigers from Gemini (born May 21 - June 20) or Libra (born September 23 - October 22) work well, too. Avoid Snakes, particularly Taurus (born April 20 - May 20), Scorpio (born October 23 - November 21), or Aquarius/Snakes (born January 20 - February 18 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025), as their cunning clashes with your sincerity. Monkeys, especially Taurus (born April 20 - May 20) or Scorpio/Monkeys (born October 23 - November 21 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028), may also take advantage of your trusting nature.`,
    homeAndFamily: `The Leo/Pig’s home is a warm, luxurious space, filled with beautiful things and a welcoming atmosphere. They love hosting and making their loved ones feel cherished. As parents, they’re nurturing and generous, spoiling their children with love and opportunities. However, their hot-temperedness can make them quick to react when things don’t go their way.

The Leo/Pig child is kind, creative, and a bit indulgent. They’ll need guidance to balance their love for pleasure with responsibility. Encourage their cultural interests, but teach them to be discerning to avoid being taken advantage of.`,
    profession: `Leo/Pigs excel in roles that combine creativity with a touch of luxury. Think chefs, art curators, or luxury brand managers. Their scrupulousness and culture make them excellent at creating beautiful, meaningful experiences, but their self-indulgence can lead to procrastination. They’re not suited for high-pressure or overly practical jobs—they need room to express their creativity.

As employees, Leo/Pigs are dedicated and charming, but their gullibility can make them vulnerable to workplace politics. As bosses, they’re generous and inspiring, but their hot-temperedness can make them unpredictable. They’re at their best when given the chance to create and share beauty.`,
  },
};
