// src/lib/new-astrology/capricorn.ts

export const capricorn = {
  "Capricorn/Rat": {
    description: `Both Capricorn and Rat want to achieve success. Rat wants power. Capricorn wants sway over others. Together the covetous Rat and the solitary mountain Sheep that is Capricorn will go far (many times to the detriment of anything from reputation to family or even health). The Capricorn born in Rat, like the Tiger only more so, is in constant, grievous danger. The old song goes, “Everybody loves a lover.” And it’s partly true. Love is a contagious disease. Nobody, however, loves a power-monger. Power is not a jolly communicable feeling. Power signifies that someone else had to be squashed on the way up. Power implies greed and avidity. Rats born in Capricorn live to achieve power. They want to dominate their peers and want to be the best at whatever they are doing. They are insanely competitive.

There are no bad signs, remember? But Capricorn/Rat does have the potential for badness. He’s slippery and dignified at the same time. He gives the appearance of being solely on the up and up. He even attracts by means of a phony “limpid mountain stream” approach. His speeches are clear-cut and easy to follow. These people send out dependability rays. I’m sure they even believe that their self-seeking projects are for the good of all, for the best, for the sake of humanity.

This is a difficult sign to live in, even harder to live with. The success of this complex and grand human being depends entirely on how impregnable he or she was to childhood lessons in morality. If he has evolved beyond the “gimme” stage it’s usually because of firm and loving tutelage in youth. Most Capricorn/Rats have, of course, developed well beyond the primitive grabby stages and hold positions of remarkable importance in their own realms. They are thorough and efficient. They are congenial and industrious. They are careful and conservative, yet generous and quietly loving. The talents of Rat/Capricorns lie in areas where tremendous application is necessary for mastery of the art. They balk at nothing, are afraid of no one, and often, despite perilous brushes with the pavement, know how to keep coming back smelling like expensive perfume. Wells of new ideas, projects, and wily great plans hatch in the busy head of this character. Capricorn/Rats are never afraid of having an invention filched or a notion pilfered by someone less scrupulous than themselves (yes, such people exist). They have such a well-developed sense of personal eminence that they give away their genius schemes like kisses at a church bazaar. “Step right up and rip off one of my incredible creative notions,” says the Capricorn/Rat, “There’s more where that one came from.” Moreover, as Rat/Capricorns themselves have sticky fingers, they understand.

Having the idea is one thing. Carrying it through is quite another. But not to worry. One of the major strengths of Capricorns born in Rat years is their ability to take their ideas through to a solid conclusion. The Capricorn is a concrete person. Dreams are not enough for the Capricorn/Rat. He or she is gifted for applying abstract concepts to real life situations. The contrary is not true. Capricorn/Rats handle emotional or subjective events poorly. They are uptight about feelings and grapple all the time with rigidity and stiffness. It is precisely this static or unbending approach that will ultimately betray Rat/Capricorn. He needs flexible, conscientious counselors around him to keep him out of the hoosegow.`,
    love: `A sincere need for long-standing love matches characterizes this person’s romantic portrait. As emotion is not of primary importance to this person, the Capricorn/Rat is only tepidly attracted to moonlight and roses (unless he’s buying or selling one or the other of these commodities). What he wants in a mate is help, real bedrock devotion and true grit. The Capricorn/Rat knows full well that she cannot depend uniquely on her own energies to accomplish the millions of necessary details involved with home and family. They are lucid creatures, these Capricorn/Rats. They don’t attempt anything sentimental unless they are very sure they can handle it. Should you care for one of these giant-of-industry types, I suggest you be somebody quite wonderful yourself. No Capricorn/Rat worth his salt will take up with a nudnik. The sign implies strength. You’ll best meet the needs and standards of this demanding person by being strong yourself. Capricorn/Rat loves first and foremost because he admires or looks up to his lover. If you don’t feel particularly equal to the Capricorn/Rat in your life, if he or she makes you feel small and insignificant, move on. Capricorn/Rat is capable of reducing the faint of heart to a smudge.`,
    compatibilities: `The Ox (born in 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) and you together know how to seek and achieve power and security. Find your Ox among the following signs: Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21) or Pisces (born February 19 - March 20). Monkeys (born 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) of the same signs make you happy, except, perhaps, the Virgo/Monkey, whose meticulous ardor irritates you. Taurus, Virgo and Pisces/Dragons (born 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) make you smile a lot. You can take a chance on one of these. Horse or Rat combos are never ideal, as a power struggle inevitably ensues. So hands off Horses, particularly Aries/Horses (born March 21 - April 19 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026), Cancer/Horses (born June 21 - July 22 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) or Libra/Horses (born September 23 - October 22 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). It’s doubtful you will be drawn to Aries/Rabbits (born March 21 - April 19 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) or Libra/Rabbits (born September 23 - October 22 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035). But if you are, don’t say I didn’t warn you.`,
    homeAndFamily: `Capricorn/Rats never deprive themselves of comforts. These folks like to decorate their lives to suit their high opinions of themselves. The home environment will drip with conveniences. Also, Capricorn/Rats are strongly attached to tradition, so the furnishings are likely to be antique but not rustic or countrified. The Capricorn/Rat wants a certain sophistication to inform his decor. You can find hordes of Capricorn/Rats at chic furniture auctions and estate sales.

As the average Capricorn/Rat is not physically demonstrative, you may imagine he or she does not love children. This is, of course, nonsense. Capricorn/Rats adore their kids and want to protect and nurture them carefully. This person will hunger for companionship with his or her offspring. Long talks and activities done as a unit will attract this family-oriented Capricorn. He or she will be strict. No question about that. But there is a deep devotion here that the loving child will instinctively feel. The Capricorn/Rat child requires early moral training in order to temper his overwhelming need to overwhelm. Let’s just say this kid is determined to reach the top and knows few bounds in this resolve. Discipline of the corporal sort will do no good. This child will react strongly to any attempt at physical restraint. Capricorn/Rats have a decided talent for reasoning and logic. So it’s easy to know how to proceed. “I love you but sometimes I don’t love the things you do,” is a good start. Explain the difference between good and evil. Don’t be afraid to give this kid a sound ethical or religious upbringing. Emphasize the Golden Rule.`,
    profession: `The victorious Capricorn/Rat is the happiest one. This person needs to arrive at goals, one after the other, gamboling lickety-split up the cliff toward the isolation of domination. Once in awhile this person should take a quick glance behind him. He or she is at all times and in all circumstances pursued by at least one dedicated enemy. Getting places in life means toppling a few colleagues and stepping on your share of toes. Capricorn/Rats are surrounded by brooding people who have never forgotten that day back in 1948, “when she got the manager’s office and I got the lowly switchboard job.” Ah me. Vengeance. Yes. People are gunning for Capricorn/Rats all over the lot. These subjects must be perspicacious. I’d advise them to be a little less ambitious, but I know it’s out of the question.

Capricorn/Rats are bosses. They will only take employee jobs that guarantee promotion within minutes after hiring. As authority figures they are able to run a tight ship. But their subordinates don’t ever really learn to adore them.

These people are so naturally dominant that I give the following careers as possibles: university administrator, executive officer, writer, performer, politician, musician, entrepreneur, attorney, banker, newscaster.`,
  },
  "Capricorn/Ox": {
    description: `The Capricorn born Ox is a down-home conservative thinker. He’s persistent and poky, stubborn and resolute. The Capricorn/Ox entertains solely his own highly individualistic opinions on everything, takes little time to consider the “other guy,” and can even be accused of a certain spiritual brutality. Capricorn/Oxen are not violent types. But they can be crude—even cruel—in their methods.

Talk about strength of purpose! The Capricorn/Ox is a monster of determination and diligence. He never gives up on a project till he’s pushed it to its absolute limit. He’ll take all the hairs off the dog, if necessary, to find the one flea that’s biting him. He’s a mountain upon which I do not advise you to depend for casual skiing or sledding. This mountain will be choosy about whom it allows to hike up and down its craggy face. And as for seeking its shelter from the elements, you’d better come well recommended or else be family. Otherwise this persnickety, snobbish Capricorn may summon the north wind to whisk you to Siberia. You see, this very vital yet bleak monolith is a veritable alp of a person. You never get to know all of his valleys or study the chasms he’ll have hidden away in his bag of tricks. Some days you’ll think he’s the jolliest, sunniest, most pleasant person you have ever met. The next—gloom and doom. And neurosis. “I can’t and I won’t and I didn’t and I wouldn’t . . ..” Oh Zeus! As solid and concrete and tangible as the Capricorn/Ox seems to be, he is really quite fragile. There is a poet living in every cavern of his mind and a sensitive artist perched in his soul. Yet, on the inscrutable surface you may at times wonder whether this person’s heart is still beating. The average Capricorn/Ox is bright. I’d even venture that most Capricorn/Oxen who have the opportunity to further their education do so. There are scads of intellectuals among these penetratingly ambitious souls. The Capricorn/Ox is nimble with words, will be drawn to the classics and is knowledgeable about things traditional. Here is a person who can turn a run-down railway depot in darkest Slovenia into an internationally photographed showplace for Architectural Digest’s most demanding readers. Everything will be restored with scale-model perfection to its original ethnicity. Capricorn/Oxen are perfectionists for themselves as well as for the rest of us humble creatures.

Food is the realm that impassions the gourmand Capricorn born Ox. We are not, however, dealing with your run-of-the-mill glutton. The Capricorn/Ox couches his ungainly eating habits in the most elegant aura. Every bite of what goes onto the Capricorn/Ox’s table must meet exigent standards of excellence. This person does not want to eat junk food. He or she longs, rather, to be immersed knee-deep in foie gras. The Capricorn/Ox’s taste buds are as stubbornly standoffish as the rest of his substantial makeup. It’s difficult to sway this person from any preconceived notions he might cherish. The Capricorn/Ox is the undisputed ruler of the kingdom of idées fixes. What he or she learned at Granny’s knee is etched in the stone mind of your Capricorn/Ox, never to stray further than the brain cell cluster where it lives happily ever after. “You take the Fifth Avenue bus uptown. Then you hop a crosstown at Fifty-ninth,” he insists. “But there is no Fifth Avenue uptown. Fifth Avenue is one way downtown,” you may protest. My advice? Take the Sixth Avenue bus uptown and don’t mention it again. Capricorn/Oxen are much more pleasant when they think they’re right.`,
    love: `Steadfast and remarkably sex-oriented, the Capricorn/Ox enjoys a lusty and action packed love life. Marriage is a must. The Capricorn/Ox’s sense of family is much too strong to abandon the idea of an enduring kith and kin relationship. Outside of marriage, the Capricorn/Ox may have other fish to fry. Don’t worry, though. The earnest and solid-citizen Capricorn/Ox won’t leave home for one of these little minnows. In fact, if Capricorn/Ox notices a minnow trying to become a shark, he scampers off home where he feels he belongs. Divorce could shatter this delicate hunk of density. Divorce, for the Capricorn/Ox, means failure. Capricorns of all persuasions hate failure and take it personally. So if you’re looking for a steady lover who’ll bring home the bacon for life, get yourself a sober, forthright Capricorn/Ox. Pardon them their occasional peccadilloes and give them lots of reasons to respect you. Capricorn/Ox also responds well to heavy doses of his own medicine. Don’t be afraid to live a little.`,
    compatibilities: `Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21) and Pisces (born February 19 - March 20) are most harmonious for you in their Snake (born 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) incarnations. The Scorpio/Snake may strike you as a bit much. Otherwise you might like to chance it with a Rooster from any of the above-mentioned astrological groups. Taurus, Leo, Virgo or Pisces/Rats would do nicely as well. And then there’s always either Leo/Pig or Scorpio/Dragon to amuse you. Aries/Dragons are too hasty for you, and Cancer/Dragons too moody. Cancer or Libra/Goat is not good for you. Libra/Ox, Tiger and Monkey are out, too, as is the stalwart (and competitive) Cancer/Pig.`,
    homeAndFamily: `The word is swanky. Inside and out, the Capricorn/Ox’s place will reek of swank. He always boasts a good address and he’s invariably proud to announce just how old the building where he lives is. At no extra cost he will furnish the name of the historically famous architect who designed it. If he has a country house (what am I saying? Of course he has a farm!), it will be authenticity itself. A restored stone mill that still works, grinding the wheat he grows, to make it into flour, which he uses to bake that spectacularly tasty bread you’re eating. Or maybe it’s an old church with handcrafted Gothic stained-glass windows brought direct from Chartres by antique sailing vessels. These characters like the real thing, and will accept no substitutes.

The Capricorn born in Ox years is a proud parent. He or she will parade baby Julia and little Alexander in the specially imported pram from London in the finest park right up there with the best of them. As far as Capricorn/Ox is concerned, his or her child can do no wrong. Fact is, in the interest of saving his skin, this person’s child is likely not to commit a heck of a lot of naughty crimes in his life so long as Dad or Mom is there watching. Capricorn/Ox is a driving taskmaster who gives in both time and effort as much as he asks for in return.

Our Capricorn/Ox child will first of all be serious. Then, as he gets a bit older and goes to school, he will become more serious. The little scholar. The valedictorian. The goody-goody. Then, as adolescence approaches and the vision of love halos her horizon, the Capricorn/Ox child will begin to adapt herself to some new demands. Her sexual charm and satirical humor are the fruits of early adulthood when she learns how to be appealing. This kid doesn’t need much more than a roof over his head and plenty of good things to eat. His path is already traced from birth. He’ll grow up to be a Capricorn/Ox. Inflexible but funny.`,
    profession: `Fame is not in the cards for this goal-oriented grind. It happens that a Capricorn/Ox reaches celebrity, but it is not one of his or her real objectives, and since Capricorn/Ox lives for his objectives, well, celebrity doesn’t often occur. This person will, however, reach a respectable position in his or her job life. People will certainly look up to him and wish to be like him. In this way, by sterling example, the Capricorn/Ox obtains sufficient recognition to satisfy whatever small need he or she has for attention from peers. The main worry of every Capricorn/Ox is a fear of not living up to his or her own very high standards of excellence in the career of his/her choice. The Capricorn/Ox wants to feel he has used every ounce of talent and brains he was born with before he dies. He rides himself hard and long in order to achieve this very worthy end.

The Capricorn/Ox works best alone. He’s such an individual that working with groups sometimes rubs him the wrong way. It can be hard on the group, too. Capricorn/Oxen always know best and stick relentlessly to their ideals and choices and habits. They will make intransigent bosses and huffy employees, unless, of course, they are given carte blanche to advance at their speed (slow) and use their methods (deliberate).

As for careers, I think the ones most applicable here are: teacher, farmer, theologian, food critic, fashion journalist, picture framer, architect, art director, consultant.`,
  },
  "Capricorn/Tiger": {
    description: `This whirlwind of staccato remarks and brusque gestures is a living tower of amiable good will. Now you see him, now you don’t. And what you see is exactly what you get—congenial speed. The Capricorn born Tiger is easily bored. The concrete density of Capricorn’s ambitious nature meets here with the hasty and sympathetic Tiger’s bohemian nonsense. How this person even has so much as a second to stop and pet a puppy or kiss a baby is beyond me. The Capricorn/Tiger is jet-propelled. He has the metabolism of four hummingbirds and the true gift of sincere bonhomie. Like all Capricorns, our Tiger subject is a bit awkward. When smoothness or suppleness might be in order to stem the flow of some clumsy social goof, count on the Capricorn/Tiger to end up chewing on his big toe. This character never sees the social amenities as anything more than what he basically thinks of them—hogwash! He’s always in too much of a rush to stoop and kiss Madame Whatsername’s be-ringed hand or hang about outside waiting for the butler to let him in. The Capricorn/Tiger is the person you are most likely to find standing dripping wet in the middle of your living room carpet, having just barged through your front door. “Hi!” he says cheerily. “How’s the weather treatin’ you?”

As Capricorn/Tigers are disdainfully oblivious to the tide of society and carry on at their own hasty pace, they tend to live a parallel existence to the one we know. Their work may take them through insufferably protracted periods of inhuman effort. But they come up smiling. They like a challenge. They prefer results to applause. The Capricorn/Tiger is out for real, tangible proof of his own powers. What other people think is of practically no importance to him at all.

Capricorns born in Tiger years frequently have sinewy, strong bodies that carry them through their race with life in top physical shape. As fast as they run and as manic as they appear, these people are surprisingly comfortable in their own vibrant skins. They are delightful company and attractive to the opposite sex. Is there nothing wrong with this engaging roadrunner? Of course there is. This is astrology. Nobody gets off scot-free. Capricorn/Tigers’ energies are easily dispersed. They go in so many directions at once that they often get confused as to what the pertinent direction was in the first place. They also have expensive tastes and are wasteful with their wealth. They tend to lose track of material things. But in the overall scheme, these people are amazingly all right. They are reasonable, and sufficiently successful to provide a good home for their family. They are naturally empathetic and truly like their fellow man. They have more confidence than the average Capricorn, who doubts himself and his own motives. For a Tiger, this character is rather sedate. He or she will be reliable and dependable (when not distracted) and will always do what he or she is asked in order to assist a fellow human being in need.`,
    love: `Behind the casual air of dishevelment that is native to Capricorn/Tigers lies a profound sensitivity to all living things. There is a noble savage quality to this character. He will probably love animals and tend to take in strays. Yet, as a life partner, she will carefully select a person who can represent her deepest notions of how folks should live. These people want to create a healthy environment for raising a family. The Capricorn/Tiger needs a nucleus from which he can dash off to act on this or that new idea or plan. He needs to be loved oodles, and, in return, he dispenses buckets of generosity and lots of opportunity for fun.

If you have one of these creatures for your very own, hang onto him! Don’t be a fool. Just because she’s gone off to Chile to hunt skunks for an interplanetary deodorizing project, don’t despair. Your Capricorn/Tiger will bounce back into the middle of your trundle bed with all her lights on in a matter of days. Your job as the mate of one of these delectable nutcases is to keep yourself busy while he’s gone, and most of all to learn to enjoy yourself without leaning on old Capricorn/Tiger. This person hates to be tied down, but loves to be married. It’s a shade paradoxical, but it’s very real to him or her. Don’t be a grouch. It will get you nowhere fast.`,
    compatibilities: `You are a natural-born Dog (born in 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) lover. Choose your pet from among Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21) and Pisces (born February 19 - March 20) breeds. If that doesn’t do the trick, then pick up with a Leo, Virgo, Scorpio or Pisces/Horse (born 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). A Scorpio/Dragon (born October 23 - November 21 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) may cause your eventual romantic demise, but the journey is half the fun. Aries (born March 21 - April 19), Cancer (born June 21 - July 22) or Libra/Goats (born September 23 - October 22 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) are not on your sweetheart list. Nor are Aries/Rabbits (born March 21 - April 19 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) or Cancer/Rabbits (born June 21 - July 22 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), Aries/Monkeys (born March 21 - April 19 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) or Libra/Monkeys (born September 23 - October 22 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028), Aries/Pigs (born March 21 - April 19 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) or Cancer/Oxen (born June 21 - July 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) or Cancer/Snakes (born June 21 - July 22 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025).`,
    homeAndFamily: `The Capricorn/Tiger will want to own things and hold property of all kinds, but he won’t be the sort to fiddle with looking after it. This native wants no part of do-it-yourself jobs. Call in an expert. Get a specialist. But don’t ask your carefree Capricorn/Tiger to fix anything more than your broken heart. This person’s house will be unpretentious and comfy. Take off your shoes and put your feet up. This hostess wants her guests to relax. She’ll take care of the racing about, thank you.

In a family situation the Capricorn/Tiger will, of course, provide. His or her children represent stability and even reality to this jumpy sweetheart. Capricorn/Tigers will be snappy to their kids if made impatient, and can do a fine job of yelling at them at the climax of a crisis. But mostly Capricorn/Tigers don’t pay all that much attention, and let their kids run a bit wild. They can’t help it. They equate freedom with love in their own lives. Why should it be any different for their offspring?

The Capricorn/Tiger child will have all the earmarks of hyperactivity. He or she may be giddy and rambunctious and clown a lot. The best thing to do with this type of kid is to let him be giddy. But of course this isn’t always possible. We don’t all live in the vast countryside where we can dump Jason’s kinetic excesses into the garden till he pipes down. My advice is to occupy this child with as many different projects as he or she can accomplish. There will be much innate intelligence available, so if it is properly applied (guide with a tender but firm hand), Jason should become a fine specimen of hyperkinetic adult with a head on his shoulders.`,
    profession: `This person is cut out for working at the kind of job that allows freedom of movement. He can adapt his mind-set to someone else’s rules, provided he sees the wisdom of the rule. Tigers are not very obedient. Capricorn helps here. But still, a Tiger is a Tiger; liberty of action and lots of challenge will keep this person content. His talents are innumerable and, oddly enough, he likes competition. Whatever the obstacle, count on the Capricorn/Tiger to try to locate a fast and efficient solution. Capricorns born Tiger feel that the most important thing is happening right now. They’ll worry about next time, next time.

Of course, if you can pin them down long enough to install them behind a big mahogany desk, these people will make just and compassionate bosses. These bosses are the type who keeps the same secretary for a hundred and fifty years. Capricorn/Tigers also adapt well to employee positions. These folks don’t have any social axes to grind, and as long as they are satisfactorily productive, underling jobs will do fine. Capricorn/Tigers are devoted and constant workers.

Careers that might apply here are: doctor, physical education teacher, veterinarian, cattle rancher, cowboy, forest ranger, book reviewer, translator, script writer, actor, actress.`,
  },
  "Capricorn/Rabbit": {
    description: `In this alloy the cautious Cat blends with the prudent Capricorn and creates a person whose ambition is second only to his gift for success. Endowed from the outset with traits that drive him or her toward slow but sure prosperity, the Capricorn/Cat never makes an important decision rapidly, never leaps wildly into any plan or project, never dashes into relationships without running a marketing study on them first. This person possesses natural wisdom. He’s dynamic, vigorous and up-to-the-minute modern. But he’s also heedful of possible dangers, and can read a threat from miles away.

The personality of Capricorn born in Cat years is pleasant. For a normally retiring Cat subject, this person is outgoing, extroverted. Nothing cheers up the Capricorn/Cat like the prospect of an evening spent at his place with friends, sitting around drinking and eating and having a jolly time. He will put on the record of your choice and show you his latest photos. But he will never monopolize the conversation or attempt to wrench center stage away from anyone else. It’s true about Cats born in Capricorn: They need comfort first. Before this person can feel that he or she belongs to the world, he must have a material bastion of some sort to protect him from the outside. He doesn’t like to face dull reality head on. Moreover, he is too busy working on tactics and strategies, adding and subtracting and figuring out his percentages, to take dull realities in hand. He needs protection from the day-to-day, boring “get the car fixed, buy the groceries and tell me your sob stories” life. For this purpose, Capricorn/Cat usually surrounds himself with people who will perform the dismal chores in order that he can get on with more important factors relative to his ascent to the summit of his profession. Although the Capricorn/Cat may well succeed so resoundingly as to rise to the position of monarch, he or she will never be called the king of tact. Our hero blurts out just exactly what nobody needs to hear at all the wrong moments. “Hey! Where did you get that jagged scar?” or “Did you notice how much weight you have gained?” Such remarks could alienate the best of friends. But that doesn’t happen with our slightly bumptious Capricorn/Cat. People enjoy this creature despite his occasional uncomfortable comments and his general clumsiness. The Capricorn/Cat has the endearing ability to laugh at himself, to poke fun at his own mistakes and to remain stable and sure of himself through it all.

The Capricorn/Cat is altruistic and sentimental. But he will not be the type to give away his shirt to a charity. There is a nice balance in this character’s approach to friendship. Panic is a major emotion native to the Capricorn/Cat. He is not basically changeable or flighty. So when confronted with the probability of a sudden shift or instant novelty, the adrenalin races him around in too many directions at once. Some say the Capricorn/Cat panics over nothing. The Capricorn/Cat likes to sleep late in the morning, tends to be messy about the house, and is hopelessly non-manual. This Capricorn is perhaps the most physically graceful of any.`,
    love: `A Capricorn born in a Cat year will be cuddly and loving. But never in public! This person maintains a dignified surface and will not slobber over love affairs. Essentially, Capricorn/Cats are practical people. They will be attracted to mates who do things. They admire the tangible and seek results in all areas of their lives. A Capricorn/Cat will hardly ever take up with someone for the sake of mere beauty or good looks. They are interested in involvement with the person’s self. They are also fascinated by the exotic, and may well take up with someone utterly different, whose artistic or gypsy like approach amuses and astonishes the Capricorn/Cat. If you love a Capricorn/Cat, prove yourself useful and creative in your own field. Show them what a “mensch” you are. Don’t shrink or be shy. The Capricorn/Cat recognizes skittishness as a fault he himself has had to overcome. He is not interested in what he already knows too well. Be your own person and think up ways to surprise the Capricorn/Cat. He likes surprises. He hates to be bored.`,
    compatibilities: `Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21) and Pisces/Dogs (born February 19 - March 20 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) settle comfortably into your refined lifestyle. Taurus, Leo and Virgo/Pigs (born 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) answer your need for wealth and culture. Leo, Virgo and Pisces/Goats (born February 19 - March 20 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) are capable of providing you with a creative and gentle partner. To avoid conflict (and you do avoid it!) eschew the Gemini (born May 21 - June 20), Cancer (born June 21 - July 22) and Libra/Rooster (born September 23 - October 22 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029). The Cancer and Libra/Rat (born 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) don’t suit you at all. Nor does the Libra in its Tiger (born September 23 - October 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or Dragon (born September 23 - October 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) form.`,
    homeAndFamily: `Home for the Capricorn/Cat should be both comfortable and personal. There is, in this ambitious, upwardly mobile person, a streak of snobbery. How can I say this? Capricorn/Cats want to impress you. They will go out of their way to decorate their homes in a plush, almost lavishly comfortable manner. First of all, they want you to feel at ease. But they also want you to notice that their sofa is made of finest Cordoba leather and that those candlesticks are real brass. Impressive surroundings give the Capricorn/Cat confidence. He likes things to seem proper. I won’t say he’s bourgeois, but almost.

The Capricorn/Cat parent wants a child who can live up to his own selfimage. No whining or sniveling allowed. This person will provide handsomely and give baby Alexander the best education available. But woe unto the lazy child who doesn’t perform in school, bring home good grades, and measure up to Mom or Dad Capricorn/Cat’s standards of virtue. The Capricorn/Cat wastes no time in making his or her position clear. “If you live here, you must do me proud. Otherwise—there’s the door.” The Capricorn/Cat child is wiser than his years. He or she recognizes early on the necessity for paying attention to business. He or she will not take kindly to the interfering brand of parent. Capricorn/Cats are secretive about their feelings and don’t appreciate meddling. This child will give a kind parent very little trouble. He wants to please and to fit in. He needs lots of comforts and will probably favor stuffed animals to live pets. The Capricorn/Cat child is humble, yet sure of himself. You will not have to prod him to do what he likes doing. As for practicing the piano . . .`,
    profession: `Professions requiring a high degree of seriousness and an overdose of raw ambition will suit this character. Social acceptance is of paramount importance to the Capricorn/Cat. He doesn’t want to be connected with shady or even untoward or unsuitable deals. Whatever goes on underneath the table will be considered taboo for discussion. The Capricorn/Cat wants no part of lawsuits or even fiscal audits. Mind you, should he have to entertain a tax inspector or two, all will prove to be in tiptop shape. Capricorn/Cat may be messy about the house but you can be sure that his papers are in order.

The subject born in Capricorn/Cat will make a sincere effort not to ruffle employees’ feathers by shouting or ranting orders at them. This person operates best in a cooperative atmosphere and prefers that his workers smile. As he applies himself to routine well and makes great sacrifices to his goals, he has no time for subordinates who don’t give their all in both labor and devotion.

This person won’t buck the system if he is employed by someone else. Sure, he or she will try by all acceptable means to find a way to regain a certain job independence. But if they have to work for others, they know how to take orders and at least appear to toe the mark. Capricorn/Cats are born starved for success—personal and integral success. Nothing short of unmitigated professional fulfillment will satisfy this craving. Winner jobs will best suit our Capricorns born in Cat years. Entrepreneur, writer, leader, politician, negotiator for international relations, hotshot lawyer, franchise owner, executive officer of a bank, general, sports commissioner, president of a university.`,
  },
  "Capricorn/Dragon": {
    description: `Nobody condemns mediocrity the way the Capricorn/Dragon can. For people born in this combination of signs, prosperity as a result of personal toil amounts to the strongest hedge against the ordinary. The Capricorn/Dragon is special. He or she feels that peculiarity from a young age, realizes its terrible fragility and wants more than anything to be able to hang on to uniqueness forever. Capricorn/Dragon is aware of the pitfalls of upward mobility. He or she knows full well how much of a struggle is required to reach a peaceable victory and call a truce with adversity. But this knowledge does not daunt this angular Dragon subject. Threats and red flags cannot deter the true zealot.

Capricorn austerity is not very obvious here. When first you meet this sunny person with the hearty handshake and open ready smile, you’d almost believe you had been greeted by a glib Gemini or a munificent Leo. But no. Capricornian Dragons are naturally bright and cheerful—unless they are contradicted. Then suddenly you will note a clear aura of cool tension rising from this subject’s epidermis. That’s rigidity and stiffness. The Capricorn/Dragon is talented for projects that ask for vehemence and gusto. He likes to be thoughtful of others and gets a real charge out of the expressions of gratitude they shower on him in return. He’s a crowd-pleaser, but not for gain. His motives are personal. He wants attention and knows how to go after it in a positive fashion. Dragons love festivals and holidays, parties and crowds. The Capricorn/Dragon is no exception. The only difference is that Capricorn likes to give the parties himself, take care of guests with that special appeal native to his sign, and make certain that everyone is comfortable and having a good time. The Capricorn/Dragon is the caterer of the double zodiac. He’s always up for a get-together and he’ll do the shopping and cooking and even the cleaning afterwards, so long as you promise to go home happy.

The main drawback of this character’s personality is his or her inability to say out loud what he or she feels inside. Don’t misunderstand. The Capricorn/Dragon is a competent and eloquent communicator for all that relates to the outside. But when it comes to intimacy, the Capricorn born in Dragon years stalls out. He or she cannot trippingly spill the words “I love you” or “You have beautiful hair” or “Don’t ever leave me” or “My darling Adam, you’re the best ever.” Capricorn/Dragons are privately reserved. They are forever being accused of coldness in matters of the heart.

This very genuine person makes a good lifelong friend. He or she will keep all commitments to loved ones and even stick out a neck once or twice if necessary. If a Capricorn/Dragon likes you, he will go through fire to see you thrive. He’s not only loyal but he carries out his beliefs. If you have a problem collecting a radio you loaned someone a year ago, tell the Capricorn/Dragon of your woe. He’ll tie himself to the person’s house in the name of what’s right. He’ll take the matter to court. Capricorn/Dragons make terrific chums. But God help you if you do them wrong: The Capricorn/Dragon loses interest in traitors as swiftly as he demonstrates his devotion to those he cares for.`,
    love: `The purity streak is very strong in Capricorn/Dragons. They are painfully honest about their preferences, and although diplomatic in every other, area of life, in love they sometimes make terrible romantic faux pas. I think the Capricorn/Dragon would love to settle down and marry and have a family —period! Yet, this person is too appealing for his/her own good. And pleasing is their pleasure. So when someone is too pleased for words and wishes to push the pleasure a bit further, Capricorn/Dragon is sorely tempted. Thing is, Capricorn/Dragons are quite conservative. If they do get involved in extramural sex, they like to think the devil made them do it. Their seething jealousy in love situations is positively frightening. They rant!

If you love a Capricorn/Dragon, don’t hesitate to be firm with them. Make them understand that you love them for something more basic than their good looks or sex appeal. And put your foot down about all those parties, too. With this good-hearted soul you will have to wear the heaviest shoes. Capricorn/Dragons are too busy being nice to realize they haven’t remembered to tell you how much they adore you. They must be reminded. But they don’t hate being prompted. They are the type who might consider backseat driving a favor. “Oh, really? A stop sign? Where?” They really are too cute.`,
    compatibilities: `Dragons are immensely popular. So are Capricorns. There are masses of people for you to try getting along with. Start with Rats. A Leo (born July 23 - August 22), a Virgo (born August 23 - September 22), a Scorpio (born October 23 - November 21) or a Pisces (born February 19 - March 20) will do. Or put a Taurus/Tiger (born April 20 - May 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or Leo/Tiger (born July 23 - August 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) in your tank. Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Scorpio (born October 23 - November 21) and Pisces/Roosters (born February 19 - March 20 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) excite the adventurer in you. Same goes for Snakes born in those four signs. As for Monkeys, you prefer Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21) or Pisces (born February 19 - March 20) to all other types. Who you don’t get on with is limited to Gemini (born May 21 - June 20), Cancer (born June 21 - July 22) and Libra/Dogs (born September 23 - October 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Gemini and Cancer/Oxen (born 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). Otherwise the world is your playground. Enjoy.`,
    homeAndFamily: `Most Capricorn/Dragons wish they lived in well-appointed surroundings. And most Capricorn/Dragons live in bohemian pads. Their chairs don’t match, their cat uses the table top as a bed, their baby has been eating the telephone book again, and darn! Where is the mate to this green sock? Capricorn/Dragons are messy about the house. They like pretty things but can do without. If you want an example, I’d say the average Capricorn/Dragon would rather invest in a magnum of expensive champagne than buy a snazzy couch or an antique chair. They are not really very materialistic people. They like nice things for practical purposes. But they care not about impressing or being like someone else.

These people make happy parents. The Capricorn/Dragon, with his slightly stiff upper-lip air and restrained laugh, is thoroughly amused by kids. They represent innocence and creativity and a carefree life. Capricorn/Dragon’s dream is to have care lifted from his shoulders, to really fly like Peter Pan away from responsibility and worry. Of course, he does precisely the opposite and plunges head first every time into the role of Reliable Roger. So kids, to the Capricorn/Dragon, mean potential freedom. He wishes his little Melody or Mary Lee would grow up to be a great artist so that she would never have to buckle under to dull routines and smile at half-wit superiors. Heaven help the kid whose own lifelong dream is to be an accountant for Xerox.

As a child, no matter his place in the family, this kid will unconsciously take on the role of eldest. He or she slips readily into positions of command, and if siblings and parents see no objection to Capricorn/Dragon taking over the running of the household, he or she will make short work of setting an example for the others. He is not one to lord his power over others. But this child will be a natural leader. And winning? You’ll fall directly in love with this tot. Capricorn/Dragons are irresistibly attractive.`,
    profession: `Capricorn/Dragons recognize their own little foibles and are intensely interested in who they are and how they got to be like that. You will often find them in careers where the mirroring of human nature is the vector. They understand themselves and seek to understand the needs of others. They are generous but nonetheless careful with their money. They have natural talent for directing operations and managing people. When crossed, they can be pitilessly vengeful. The Capricorn/Dragon makes an interesting, lovable boss. He or she encourages subordinates to work rather than ordering them around. And as the Capricorn/Dragon often prides himself on his good manners, he or she will be courteous as well. As an employee this person is always biding time, waiting till he or she gets the big promotion. The Capricorn/Dragon is decidedly not interested in lowly jobs. Suitable careers for this valuable person are: journalist, painter, astrologer, psychiatrist or psychologist, counselor, fundraiser, editor, clergyman, lobbyist, negotiator, public relations person, professor, caterer.`,
  },
  "Capricorn/Snake": {
    description: `An arrogance and aplomb that would frighten Godzilla characterize this match. Capricorn practices what he preaches, puts his ideas to use and is not afraid of his own ambition. Snakes sense things, sniff out solutions and spend a large portion of their lives slinking in and out of crises on the way to the bank, the jeweler’s, the airport, their lawyer’s office or jail. Snakes often have more flair than brains. But with Capricorn as a mate, who needs brains?

The Capricorn born a Snake is in a class by himself. Not only does he feel superior to everyone in sight, but he also looks better than anyone else. These are stately people with built-in stature and class to burn. Their wardrobes alone cost half the national budget of Monaco—not to mention their cars and homes, their boats and their hairstyles.

Capricorn/Snakes are wildly loving of those less fortunate than themselves (everybody) and take in strays, adopt poor kids, hire on slothful employees, and the like. Some say they surround themselves with slobs so they will feel all the more superior. I don’t quite agree with that theory. Capricorn/Snakes are deeply caring. They are often born luckier than other people. Things come to them easily. So my theory is that Capricorn/Snakes like to share their wealth and don’t much care what anyone else’s opinions are. This person’s very presence is powerful. Capricorn/Snakes are showstoppers. They catch the eye of a whole room at once, and by their very carriage manage to keep it riveted on them until they are through basking in the attention. Oh yes. Attention is the Capricorn/Snake’s drug. He wants to be looked at, hugged, talked and listened to, scolded and spanked, and fed and bathed first. Nobody and nothing will be allowed to come between this haughty character and the audience he’s looking to get attention from. Real star quality.

The underside of the Capricorn/Snake’s grand generosity is his appalling wastefulness. These people buy three tuxedos for every one they might need to go to that charity ball next week. They’ll get two different kinds of car for your birthday, just in case you didn’t like the first one. Also, in their eagerness to please and preside, to own the moment in which they live, Capricorn/Snakes are not above any sort of ruse. If smiles don’t work then tears it will be, or fits of rage, hysteria or psychosomatic illness. They want to be noticed. At any cost. If they hate you, you certainly won’t be able to be indifferent to their distaste, either. They will find ways to remind you.

Capricorn is a purposeful little critter. And Snakes are so darn clever. A brush with one of these monsters will never leave you indifferent. There is, in every Capricorn/Snake, the gift of the supernatural. These people could probably live a very full life just following hunches and answering premonition’s call. It’s spooky but true. There is a foresight here unequaled by any other sign. Intuition is even too mild a word. The Capricorn/Snake senses trends, dangers, political movements, events of all natures.

As tough as nails and as sweet as pie, the Capricorn/Snake operates almost exclusively out of a thirst for power, for celebrity, for true greatness in the eyes of his contemporaries. No posthumous kudos for this person! “Give me those dozens of roses right now,” commands the startling Capricorn/Snake. “I shall distribute them to people less fortunate than myself. “ And so she does. Off goes the Capricorn/Snake with her diva personality to draw crowds elsewhere, to throw kisses to her entranced audience, and to sow peace and love among men (as long as they live by her rules). This character is so charmingly bossy you hardly notice you have been given the job as the head of the cleanup committee.`,
    love: `A romantic if there ever was one, the Capricorn/Snake is forever imagining himself “in love” with somebody. Every relationship that comes along feels as if it must be the perfect one. Each stray just needs a little fixing up here and there and before you can say “Mao Tse-tung” he or she will be the perfect lover or mistress, obedient and sane and healthy and brilliant by virtue of his ability to stand on his own feet. (Ordinarily, the people Capricorn/Snakes pick up are quasi-bedridden.) In other words, Capricorn/Snakes are promiscuous by default. They are always losing their lovers to dissipation and sloth. But not to worry. There are more where they came from. People go mad for this creature. He or she is never at a loss for tenderness. They are affection consumers. Capricorn/Snakes eat love. If you love a Capricorn/Snake, you will be in awe of him or her. If you care to keep your Capricorn/Snake, don’t stay that way. This person ends up fixing his affections on the most demanding of his admirers. Capricorn/Snakes need to be confronted daily by a strong and severe judge who helps them get a bead on their mirror image, who knows how to reach their epicenter of softness and true enlightenment. All the scruffy strays in the universe won’t do. Capricorn/Snake needs a tough, no-nonsense partner who knows how to keep him or her in line and who, most importantly, doesn’t let him or her get away with duplicity. Fibbers to a man, Snakes must be constantly monitored for signs of dissimulation.`,
    compatibilities: `Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21) and Pisces/Oxen (born February 19 - March 20 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) and their Rooster (born February 19 - March 20 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) brothers and sisters are all possibles. You may swoon for a Leo/Dragon (born July 23 - August 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or Leo/Monkey (born July 23 - August 22 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028). They have enormous charm and vitality. Besides, they like you too. You’re not likely to get the same flash from Cancer/Pigs (born June 21 - July 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) or Libra/Pigs (born September 23 - October 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031). Aries/Tigers (born March 21 - April 19 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Gemini/Tigers (born May 21 - June 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Aries/Monkeys (born March 21 - April 19 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) and Gemini/Monkeys (born May 21 - June 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) are on another wavelength as well. Don’t bother with Aries/Roosters (born March 21 - April 19 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029). They go too fast and, to you, seem to get nowhere.`,
    homeAndFamily: `The Capricorn/Snake home will not be merely elegant. It will be a bastion, a model, a paragon of studied posh. And why do I even use the word “home” in the singular? Capricorn/Snake people never have just one house. At the very minimum this person will have a town and a country home. From then on, as they acquire the funds, they have one in the Caribbean, a little place in Goa and a condo in Saint Moritz. And the boat? That’s in the Bahamas. To this natural classicist, no number of Corinthian columns on the front veranda will be too many, no carpet too thick, no antique too dear. The best of everything for this character is never good enough. And messy? My God. Miasmatic in the dressing room. Never mind. The maid comes every day. Twice. Sometimes three times.

These people make wonderful parents. Having kids is a bit like taking in stray puppies. Capricorn/Snakes hover and comfort, and stay up all night and wrap their puking infants in the nearest sable stole at hand. Little Lauren or Jimmy should never want for anything. That is the Capricorn/Snake ideal—and if the nanny is nice, the kid is in good shape. Count on the Capricorn/Snake to be gone a lot of the time. When he’s there, he’ll spend intense quality time with the kids. But we are talking about a world-class busy person. The kid should be spared too much of the Capricorn/Snake parent’s vast shadow, anyway. It’s not healthy trying to live up to such a monolith.

The Capricorn/Snake child is first of all loving—graspingly so. Secondly he is loving—sweetly so. And thirdly he is loving—endearingly so. Most of all he likes to be the most adored child in the family. He needs all of his parents’ attention, and if he doesn’t get it, he finds ways. He is a dutiful child and very bright, of course. But if he isn’t first at everything he gets stomachaches, has nightmares, and bites his nails. This never lasts long, as the Capricorn/Snake child always triumphs sooner or later over whatever his or her family was. But while he’s small this kid must be nurtured as though he were a future prize orchid that takes twenty years to come to flower and in the meantime must be worn on your wrist—even as you sleep.`,
    profession: `Most Capricorns born in Snake are destined for some form of prominence. They may be a political leader one day or they may just shine head and shoulders above their peers for some professional or humane reason. Whatever it is that gets them there, they get there. They sincerely believe that they are the best and the greatest at their craft or field, and because of this fervent belief, they often convince both themselves and others of that fact. Capricorn/Snakes aspire to greatness—and they often get it. The Capricorn/Snake knows how to take orders if he or she knows it’s only temporary. These people are good workers (if they can get out of bed) and find brilliant solutions to problems for bosses who know how to use them properly. Capricorn/Snakes do not, however, want to remain employees forever. They like their bread buttered far too thickly to put up with floorscrubbing for long. When they do get to be boss, they will play boss. There is never any question who runs the show and there is never any doubt the show is best run by Capricorn/Snake. The Capricorn/Snake should not attempt to slither out from under his destiny. It will only come back to haunt him.

Suitable careers for Capricorn/Snakes are: entrepreneur, president, millionaire, heiress, movie star, top model, advertising director, religious leader, oil magnate, choreographer, film director.`,
  },
  "Capricorn/Horse": {
    description: `Capricorn’s solidity, when applied to the feisty Horse, creates a curious result. This is a jumpy character whose very skittishness is kept in check by an iron will. The Capricorn/Horse is a study in self-containment. He or she is always trying to temper natural nervous energy with purposeful calm. The result is a kind of jumpy deliberation. These folks give the impression of being both in a hurry and holding back at the same time. It’s unsettling to watch a Capricorn/Horse try to sit still. He’s a bundle of contradictions: He wants to race around the world on his own, yet he’s a stay-at-home. He’s a loner who loves to chat and be sociable. He’s a bundle of nerves who seeks serenity.

The Capricorn/Horse is a worker. He’s never idle and always has some scheme or other up his sleeve. His ambition is relentless. He may not always get to the top. But you can be sure that the Capricorn/Horse will never stop trying. This person is a natural for social life. He or she loves to party, enjoys dressing up, and is not loath to indulge in a bit of epicureanism when it comes to good food and fine wines. The Capricorn/Horse is a bit of a snob, too. He will not be caught dead at a lowlife bar or a tacky disco. This person seeks quality in everything and usually finds it.

Capricorn/Horses are not always easy to get along with. They are critical of others and can be downright ornery when they don’t get their way. They are not above a little healthy selfishness, either. If the going gets too tough, this person is not going to hang around to be beaten up. He’ll take off for greener pastures without so much as a fare-thee-well.

The main difficulty for Capricorn/Horses is their inability to settle down. They are forever seeking new adventures, new places to go, new people to meet. Yet, at the same time, they long for the security of home and hearth. This dichotomy creates a permanent state of dissatisfaction. They are always looking for something they cannot quite define. This is probably why they are such good workers. They keep trying to fill the void with accomplishments.`,
    love: `In love, the Capricorn/Horse is a romantic. He or she will fall head over heels at the drop of a hat. But don’t expect lifelong fidelity. The Horse’s nature is to roam, and the Capricorn/Horse is no exception. They love the idea of love, but they are not always good at the day-to-day maintenance of relationships. They need a partner who is both independent and understanding, someone who can keep up with their pace but also give them the space they need to wander. If you love a Capricorn/Horse, be prepared for a wild ride. They are passionate and exciting, but they can also be unreliable. Don’t try to tie them down too tightly, or they’ll bolt.`,
    compatibilities: `You’ll get on well with Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Pisces/Dogs (born February 19 - March 20 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030). They are steady enough to balance your nervous energy. Taurus, Virgo, or Pisces/Tigers are also good bets for you, as they share your adventurous spirit. A Scorpio/Goat might intrigue you with their creativity. Avoid Aries, Cancer, or Libra/Rats, as they’ll drive you crazy with their need for control. Gemini and Libra/Monkeys are too flighty for your taste, and Aries or Cancer/Oxen are too stubborn.`,
    homeAndFamily: `The Capricorn/Horse’s home will be a reflection of their dual nature. It will be comfortable and stylish, but probably a bit cluttered. They love beautiful things but don’t always have the patience to keep them organized. They’ll have a collection of souvenirs from their travels, and their decor will be eclectic, reflecting their varied interests.

As parents, Capricorn/Horses are loving but not overly demonstrative. They want their kids to be independent and successful, and they’ll push them to achieve. They may not be the most consistent disciplinarians, as their own restless nature makes it hard for them to stick to routines. The Capricorn/Horse child is a handful—bright, energetic, and always on the go. They need a lot of stimulation and opportunities to burn off their energy. Channel their enthusiasm into sports or creative pursuits, and they’ll thrive.`,
    profession: `The Capricorn/Horse is happiest in a career that allows them to move around and explore. They are not suited to desk jobs or repetitive tasks. They need variety and challenge to keep them engaged. They are natural leaders, but their impatience can make them difficult bosses. They’re better off in roles where they can set their own pace and have some autonomy. As employees, they’ll work hard but may clash with authority if they feel micromanaged.

Suitable careers for Capricorn/Horses are: travel writer, entrepreneur, sales executive, event planner, public relations specialist, chef, wine merchant, art dealer, explorer, stuntman.`,
  },
  "Capricorn/Goat": {
    description: `The Capricorn/Goat is a curious blend of steely determination and dreamy creativity. This person is ambitious, but their ambition is tempered by a whimsical, almost childlike quality that makes them endearing. They are practical dreamers, capable of turning their imaginative ideas into reality through sheer persistence. The Capricorn/Goat is not as aggressive as other Capricorns, but they are just as determined to succeed. They simply go about it in a quieter, more circuitous way.

This person is a bit of a paradox. They crave security and stability, yet they are drawn to the unconventional. They want to be admired for their achievements, but they also want to be loved for their quirks. The Capricorn/Goat is highly sensitive and can be deeply hurt by criticism, yet they are also capable of great resilience. They may seem fragile, but they have an inner strength that allows them to bounce back from setbacks.

Capricorn/Goats are generous to a fault. They love to give, whether it’s their time, their money, or their affection. This generosity can sometimes lead them to be taken advantage of, as their gullibility makes them easy prey for manipulators. They need to learn to set boundaries and protect their own interests. Their creativity is their greatest asset, and they are happiest when they can express it in some tangible way, whether through art, writing, or some other form of self-expression.`,
    love: `In love, the Capricorn/Goat is a hopeless romantic. They fall in love easily and deeply, and they are fiercely loyal to their partners. However, their sensitivity can make them overly dependent on their loved ones, and they may struggle with feelings of insecurity. They need a partner who is both supportive and strong, someone who can appreciate their creativity while also providing the stability they crave. If you love a Capricorn/Goat, be gentle with their feelings, but don’t let them lean on you too heavily. Encourage their independence and help them build their confidence.`,
    compatibilities: `You’ll find harmony with Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), or Pisces/Rabbits (born February 19 - March 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), who share your love of comfort and beauty. Taurus, Virgo, or Pisces/Horses are also good matches, as they can keep up with your creative energy. A Scorpio/Pig might appeal to your romantic side. Avoid Aries, Cancer, or Libra/Tigers, as their impulsiveness will clash with your need for stability. Gemini or Libra/Dragons are too domineering, and Aries or Cancer/Roosters are too critical for your sensitive nature.`,
    homeAndFamily: `The Capricorn/Goat’s home is a cozy, artistic haven. They love to surround themselves with beautiful things, and their decor will reflect their creative spirit. Think soft colors, quirky artwork, and lots of pillows. They are not particularly tidy, but their messiness has a certain charm.

As parents, Capricorn/Goats are nurturing and encouraging. They want their children to explore their own creativity and will go to great lengths to provide them with opportunities to do so. They may struggle with discipline, as they hate to be the bad guy. The Capricorn/Goat child is sensitive and imaginative, with a rich inner world. They need a lot of reassurance and encouragement to come out of their shell. Give them a safe space to express themselves, and they’ll flourish.`,
    profession: `The Capricorn/Goat thrives in careers that allow them to use their creativity and imagination. They are not suited to rigid, highly structured environments, as they need room to dream and experiment. They are hardworking but may lack the initiative to push themselves forward, so they benefit from having a mentor or partner who can help them stay on track. As bosses, they are kind and supportive, but they may struggle with making tough decisions. As employees, they are reliable but may need occasional prodding to stay focused.

Suitable careers for Capricorn/Goat are: artist, writer, designer, musician, therapist, teacher, illustrator, florist, interior decorator, poet.`,
  },
  "Capricorn/Monkey": {
    description: `The Capricorn/Monkey is a clever, ambitious soul with a knack for getting what they want. This person combines Capricorn’s drive for success with the Monkey’s quick wit and resourcefulness, creating a formidable character who is always one step ahead of the game. They are charming and sociable, with a talent for making people laugh, but beneath their playful exterior lies a steely determination to achieve their goals.

Capricorn/Monkeys are natural problem-solvers. They can think on their feet and come up with creative solutions to even the most complex challenges. However, their cunning can sometimes cross over into manipulation, and they may not always play fair. They are not above bending the truth or using a bit of trickery to get their way, which can make them difficult to trust at times.

Despite their confidence, Capricorn/Monkeys are prone to self-doubt. They are their own harshest critics and can be plagued by feelings of inadequacy, even when they are succeeding. They need to learn to trust in their own abilities and not let their insecurities hold them back. Their love of luxury and fine things can also get them into trouble, as they are prone to overspending and living beyond their means.`,
    love: `In love, the Capricorn/Monkey is a charmer. They know how to turn on the charm and can be incredibly persuasive when they want to be. However, their restless nature makes it hard for them to settle down, and they may struggle with commitment. They need a partner who is both intellectually stimulating and emotionally grounding, someone who can keep them interested without trying to control them. If you love a Capricorn/Monkey, don’t try to clip their wings. Give them freedom, but hold them accountable for their actions.`,
    compatibilities: `You’ll click with Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), or Pisces/Rats (born February 19 - March 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), who share your ambition and wit. Taurus, Virgo, or Pisces/Dragons are also good matches, as they can match your energy and drive. A Scorpio/Snake might intrigue you with their intensity. Avoid Aries, Cancer, or Libra/Tigers, as their impulsiveness will clash with your need for control. Gemini or Libra/Goats are too wishy-washy for you, and Aries or Cancer/Horses are too unpredictable.`,
    homeAndFamily: `The Capricorn/Monkey’s home is a stylish, modern space that reflects their love of luxury. They are not afraid to splurge on high-end furniture or gadgets, and their home will be filled with the latest trends. They are not particularly tidy, but they know how to make a mess look good.

As parents, Capricorn/Monkeys are fun and engaging, but they may struggle with consistency. They love to spoil their kids and will go out of their way to make them happy, but they may not always be there for the day-to-day grind of parenting. The Capricorn/Monkey child is bright and mischievous, with a quick mind and a love of play. They need firm boundaries to keep their cunning in check, but also plenty of opportunities to express their creativity.`,
    profession: `The Capricorn/Monkey is a natural at careers that require quick thinking and adaptability. They thrive in fast-paced environments where they can use their wit and charm to their advantage. They are ambitious and will work hard to climb the ladder, but they may not always play by the rules. As bosses, they are charismatic and inspiring, but they can be manipulative if they feel threatened. As employees, they are innovative but may need supervision to stay on track.

Suitable careers for Capricorn/Monkeys are: advertising executive, comedian, lawyer, stockbroker, inventor, marketing director, journalist, politician, consultant, tech entrepreneur.`,
  },
  "Capricorn/Rooster": {
    description: `The Capricorn/Rooster is a powerhouse of ambition and resilience. This person combines Capricorn’s relentless drive with the Rooster’s bold, confident energy, creating a character who is not afraid to take on the world. They are hardworking, meticulous, and fiercely determined to succeed, often at any cost. Their confidence can sometimes come off as arrogance, and they are not afraid to speak their mind, even if it ruffles feathers.

Capricorn/Roosters are natural leaders. They have a clear vision of what they want and the tenacity to make it happen. However, their bossy nature can make them difficult to work with, and they may alienate others with their bluntness. They are also prone to overconfidence, which can lead them to take unnecessary risks or overlook important details.

Despite their tough exterior, Capricorn/Roosters have a softer side. They are generous and loyal to those they care about, and they have a surprising sense of humor that can lighten even the most serious situations. They love to be admired and will go to great lengths to maintain their polished, chic image.`,
    love: `In love, the Capricorn/Rooster is passionate and loyal, but also demanding. They have high expectations of their partners and can be critical if those expectations are not met. They need a partner who is confident and independent, someone who can stand up to their strong personality without trying to dominate them. If you love a Capricorn/Rooster, be prepared to match their intensity. Show them you’re just as driven and capable as they are, and they’ll respect you for it.`,
    compatibilities: `You’ll find a good match with Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), or Pisces/Snakes (born February 19 - March 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025), who share your drive and sophistication. Taurus, Virgo, or Pisces/Oxen are also compatible, as they can provide the stability you crave. A Scorpio/Dragon might spark your interest with their charisma. Avoid Aries, Cancer, or Libra/Rabbits, as their reticence will frustrate you. Gemini or Libra/Rabbits are too indecisive, and Aries or Cancer/Monkeys are too manipulative for your straightforward nature.`,
    homeAndFamily: `The Capricorn/Rooster’s home is a showcase of their success. Everything will be meticulously chosen, from the furniture to the artwork, and it will all scream “I’ve made it!” They are not afraid to spend money to create an impressive environment, but they are also practical enough to keep things functional.

As parents, Capricorn/Roosters are strict but fair. They want their children to succeed and will push them to work hard and aim high. They may come off as overly critical at times, but their intentions are good. The Capricorn/Rooster child is confident and ambitious, with a natural flair for leadership. They need encouragement to develop their softer side and learn to listen to others.`,
    profession: `The Capricorn/Rooster is a born leader, thriving in careers that allow them to take charge and make things happen. They are not afraid of hard work and will put in long hours to achieve their goals. However, their bossy nature can make them difficult to work for, and they may struggle to delegate tasks. As employees, they are diligent and reliable, but they won’t stay in a subordinate role for long. They are destined for the top.

Suitable careers for Capricorn/Roosters are: CEO, lawyer, architect, fashion designer, military officer, politician, financial advisor, real estate developer, editor, motivational speaker.`,
  },
  "Capricorn/Dog": {
    description: `The Capricorn/Dog is a loyal, dependable soul with a strong sense of duty. This person combines Capricorn’s ambition with the Dog’s steadfastness, creating a character who is both driven and deeply principled. They are not the flashiest people in the room, but they are often the most reliable. They take their responsibilities seriously and will go to great lengths to fulfill their obligations, whether to family, friends, or work.

Capricorn/Dogs are highly intelligent and have a keen sense of right and wrong. They are not afraid to speak out against injustice, but their self-righteous streak can make them come off as judgmental. They are also prone to anxiety, worrying about whether they are doing enough or living up to their own high standards. Their cynicism can make them seem aloof or unapproachable, but beneath it all, they have a warm, generous heart.

This person is not particularly sociable, preferring the company of a few close friends to large crowds. They value quality over quantity in their relationships and are fiercely loyal to those they care about. Their love of luxury is tempered by their practical nature, and they are unlikely to overspend or indulge in extravagance unless they feel they’ve earned it.`,
    love: `In love, the Capricorn/Dog is loyal and committed, but not overly demonstrative. They show their love through actions rather than words, and they need a partner who understands and appreciates this. They are attracted to people who share their values and work ethic, and they have little patience for flightiness or irresponsibility. If you love a Capricorn/Dog, be patient with their occasional moodiness and give them plenty of reassurance. They need to know they are appreciated.`,
    compatibilities: `You’ll get along well with Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), or Pisces/Tigers (born February 19 - March 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034), who share your sense of loyalty and adventure. Taurus, Virgo, or Pisces/Rabbits are also good matches, as they can provide the comfort and stability you crave. A Scorpio/Horse might appeal to your sense of adventure. Avoid Aries, Cancer, or Libra/Dragons, as their domineering nature will clash with your need for independence. Gemini or Libra/Snakes are too slippery for your straightforward nature, and Aries or Cancer/Roosters are too critical.`,
    homeAndFamily: `The Capricorn/Dog’s home is a sanctuary of comfort and order. They prefer classic, understated decor to flashy trends, and their home will be a reflection of their practical, no-nonsense nature. They are not particularly messy, but they are not obsessive about tidiness either.

As parents, Capricorn/Dogs are devoted and protective. They want their children to grow up with strong values and a sense of responsibility, and they will lead by example. They may be a bit strict, but their love is unwavering. The Capricorn/Dog child is serious and conscientious, with a strong sense of duty even at a young age. They need encouragement to relax and have fun, as they can be prone to taking life too seriously.`,
    profession: `The Capricorn/Dog is a hard worker who thrives in careers that require dedication and integrity. They are not afraid to put in long hours, and they take pride in doing a job well. They make excellent leaders, as their sense of fairness and duty inspires loyalty in their teams. As employees, they are reliable and thorough, but they may struggle with overly authoritarian bosses. They need to feel respected in their work environment.

Suitable careers for Capricorn/Dogs are: judge, social worker, teacher, accountant, police officer, lawyer, librarian, historian, nonprofit director, ethical consultant.`,
  },
  "Capricorn/Pig": {
    description: `The Capricorn/Pig is a refined, cultured soul with a strong sense of purpose. This person combines Capricorn’s ambition with the Pig’s love of beauty and pleasure, creating a character who is both driven and deeply appreciative of life’s finer things. They are hardworking and determined, but they also know how to enjoy themselves, whether it’s through good food, fine art, or luxurious surroundings.

Capricorn/Pigs are sincere and honest, with a strong moral compass. They believe in doing the right thing, even when it’s difficult, and they are not afraid to stand up for their principles. However, their naiveté can make them vulnerable to manipulation, and they need to be careful not to trust too easily. Their love of pleasure can also lead them to overindulge, whether in food, drink, or other sensual delights.

This person is warm and approachable, with a natural charm that draws people to them. They are generous with their time and resources, and they love to make others happy. However, their hot-temperedness can flare up when they feel betrayed or disrespected, and they are not afraid to let their feelings be known.`,
    love: `In love, the Capricorn/Pig is passionate and devoted. They throw themselves into relationships with all their heart, and they are deeply loyal to their partners. However, their need for security can make them clingy, and they may struggle with jealousy or possessiveness. They need a partner who is trustworthy and appreciative, someone who can match their intensity without overwhelming them. If you love a Capricorn/Pig, shower them with affection, but also give them room to breathe.`,
    compatibilities: `You’ll find a good match with Taurus (born April 20 - May 20), Leo (born July 23 - August 22), Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), or Pisces/Rabbits (born February 19 - March 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), who share your love of beauty and comfort. Taurus, Virgo, or Pisces/Goats are also compatible, as they can provide the emotional support you need. A Scorpio/Tiger might appeal to your passionate side. Avoid Aries, Cancer, or Libra/Snakes, as their cunning will clash with your sincerity. Gemini or Libra/Roosters are too critical, and Aries or Cancer/Dogs are too cynical for your warm nature.`,
    homeAndFamily: `The Capricorn/Pig’s home is a luxurious, welcoming space that reflects their love of beauty and comfort. They will spare no expense to create a warm, inviting environment, with plush furnishings and tasteful decor. They are not particularly tidy, but their home will always feel cozy and lived-in.

As parents, Capricorn/Pigs are nurturing and indulgent. They want their children to have the best of everything, and they will go to great lengths to provide for them. They may struggle with setting boundaries, as they hate to say no to their kids. The Capricorn/Pig child is charming and sensitive, with a love of beauty and a strong desire to please. They need encouragement to develop their independence and stand up for themselves.`,
    profession: `The Capricorn/Pig is a hard worker who thrives in careers that allow them to combine their ambition with their love of beauty and culture. They are not suited to mundane or repetitive tasks, as they need to feel inspired by their work. They make excellent leaders, as their warmth and sincerity inspire loyalty in their teams. As employees, they are diligent and cooperative, but they need to feel valued and appreciated.

Suitable careers for Capricorn/Pigs are: art curator, chef, fashion designer, hotel manager, musician, writer, diplomat, interior designer, philanthropist, gallery owner.`
  }
};
