// src/lib/new-astrology/gemini.ts

export const gemini = {
  "Gemini/Rat": {
    description: `A shooting star of infinite genius and practically no end of tales to tell, your average Gemini/Rat flits amiably around the room at any and all gatherings, charming and bright, delighted and delightful. Catch me if you can. And the fact is you can. But you must first discover Gemini/Rat’s secret password. The key to the Gemini/Rat’s most guarded intimacy is “I.” This character observes the world through an almost impenetrable haze of ego. Geminis born in Rat years blend the flittery-fluttery Gemini spirit with the Rat’s excessive nervousness. Both signs thrive on motion. Just think of it! A butterfly with a jet engine inside, moving all the time, busy at applying talents he doesn’t even know he has.

The Gemini/Rat is a generous person. He likes to give away anything and everything. He wants to make people laugh and cry or in any case react to him, respond to his dynamism and admire his marvelous ways. He’s a born doer and always feels that whatever he’s created or earned can be replaced. Gemini/Rat knows instinctively that there will always be another novelty waiting in line inside his head.

Perseverance is another pair of socks altogether. Gemini/Rats can only really learn to stick to a single place or long-term chore if there is the absolute certainty of gain. For money, this Rat will perform nightly at the same spot. But don’t forget to give him top billing. If suitably rewarded, he’ll stay on for as long as the show can run.

There is a whimsicality about the Gemini/Rat that lightens the sometimes heavy atmosphere surrounding other Rat characters. Geminis love to show off. The Rat Gemini is no exception and because he is at the same time active in the extreme and full of Rat drive, he is capable of great theatricality. His sales acumen is such that he might sell stray dogs to the ASPCA.

Where Gemini/Rats are long on dazzle, they are acutely short on decisionmaking. They’re never really sure if they want to do this or that. “Well, maybe, I’ll see what’s going on when Tuesday rolls around I’ll call you. No, look, I’ll think about it. I’m not really all that sure . . .” and on and on. Gemini/Rats are just plain capricious.

The solution to this personality’s major dilemma is for him or her to find the right partner who knows just how much rope to issue every morning so that this nutcase doesn’t go and hang himor herself during the day. A nice, solid sort who knows how to put his or her own ego in a back pocket, allow the Gemini/Rat to zip around basking in his or her own ego and still rein in the little darling when night falls. This person is a handful and a half. But worth it.`,
    love: `Inconstancy is a Gemini fault. The Rat brings skill, a desire to “make it” in the world and to earn power as well as silver and applause. Though steadiness is not innate in this subject, it can be learned. If a Gemini/Rat needs his mate to assist him or her toward the power/money goal, the relationship is likely to go a long way.

Beware of Gemini/Rat seduction routines. These folks will say absolutely anything to beguile. From the jump they want control. It’s never a heavy or ponderous sort of domination. Rather, the Gemini/Rat controls by whim. He wants to be taken to the theater on his birthday. But no. Perhaps he’d rather take flying lessons. It’s uncertainties like this that can baffle an unsuspecting partner and eventually lead to annihilation of confidence. If you love one of these restless people, give the Gemini/Rat plenty of space in which to play at being “me.” Take up one or more outside activities. Go bowling and teach yourself how not to cling. Cloying sentimentality drives the Gemini/Rat to distraction. He may not mind having a loving and admiring full-time partner. But he or she will despise being leaned on.`,
    compatibilities: `There’s an Aries (born March 21 - April 19), Leo (born July 23 - August 22), Libra (born September 23 - October 22) or Aquarius (born January 20 - February 18) in your future. Make sure you choose him or her from among the Dragon (born 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or Monkey (born 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) crew. Don’t hang around with Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), Sagittarius (born November 22 - December 21) or Pisces/Rabbits (born February 19 - March 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035). You don’t seem to think alike. Erase Horses from your mind altogether, and prefer the solid Aries/Ox (born March 21 - April 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) or, for some diversion, why not invite a Libra/Tiger (born September 23 - October 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) to lunch?`,
    homeAndFamily: `This person will live in comfortable surroundings, but he or she will not necessarily be the one who designed them. Most certainly Gemini/Rats will not have stitched up the draperies or painted the baseboards by hand. Gemini/Rat is the idea man in all his pursuits.

Gemini/Rat will depend largely on his mate to raise the children. He is not the type of self-sacrificing angel who struggles to get custody and then deprives himself his whole life long just to raise his kids on his own The main thrust of the Gemini/Rat parent-child rapport will be what the old Gemini/Rat parent can teach to offspring and how much he can amuse them, cajoling them with sales talks on early bedtimes and fun methods of eating their spinach. The Gemini/Rat, like all Rat parents, will be protective of family members and the family name.

As a kid this person will be tremendous fun to have around, always smiling and gurgling, even from the start. As long as you lay on the attention, Gemini/Rat babies will chortle their way to adulthood without a single sulk. But woe unto the busy parent who hasn’t time for Junior. This kid will think up myriad ways to get attention—and keep it. Watch out for hypochondria and trumped-up excuses. This child needs lots of affection and a firm hand.`,
    profession: `The talents of this character lie in his ability to communicate. Gemini/Rats are monsters of perspicacity and quick-wittedness. Their ability to see a situation is their special individual streak of genius. I cannot say your average Gemini/Rat has tenacity because he doesn’t. One big weakness in this person’s makeup is his tendency to blame others for what he does wrong or bungles.

As a boss, this person is too easygoing. He’ll let his employees get away with too much. But because like all Rats he’s a Rat first and a Gemini second, this person will know enough to associate himself with steadier people than he. Gemini/Rats usually succeed through a sound partnership. As an employee, this person will be hard to handle, detached, lighthearted. No amount of yelling and screaming will change that. Gemini/Rats hate taking orders.

Jobs that suit this person are: politician, TV producer, realtor, ad person, entrepreneur, actor or actress, tour guide or chef.`,
  },
  "Gemini/Ox": {
    description: `Ox is a boon to the Gemini’s blithe spirit. This is a settling-down Gemini, a family sort of Gemini with eyes for the good life. A Gemini born Ox will always go forward, albeit more deliberately and ponderously than other Geminis, toward goals big and small. This Gemini is a thinker, yes. But he’s not guilty of leaping from thought number one to idea number thirty-three and back to thought number one in two seconds flat. Concentration is possible and great work may even be accomplished.

This creature can be amazingly unlike what he seems. Gemini/0x, like all Oxen, seems really rather dull. But wait till he starts talking. Wait till she begins telling you the story of her latest car accident and how she ran away from home when she was sixteen because her father beat her and her mother drank. And watch how positively transfixed you will be when your favorite Gemini/Ox recounts the tale of his youngest son who went to university in England and met a girl who practiced witchcraft. You will not blink the whole time. Pick up a Gemini/Ox and you won’t be able to put him or her down. These folks are real page-turners.

Gemini/Oxen are wry, too. They are not the kind of rollicking funny people who tell jokes and try to make you laugh. Instead, they manage to inject humor into their accounts of this or that event so that you hardly know it’s there. You are smiling and keeping your ears cocked for more. No pokes in the ribs. Just a steady stream of wit.

The Ox is often a loner and this one is no exception. The time he spends alone will be the time he enjoys the most. As loquacious and eloquent as he can be, the Gemini/Ox is nonetheless a rock of personal inner strength. He likes his pleasures simple and his ideals healthy. It’s all right to have lofty dreams, but if they are unrealizable, the Gemini/Ox is not interested. “Yes. I would enjoy having a castle in Spain. But as I lave a large house in the United States that takes lots of care and upkeep, and three children to send through college, it doesn’t look as if I’ll ever have one,” says the sensible Gemini/Ox.

The Gemini/Ox prefers the intimate dinner party with close friends to the giant open house where fifty people a minute float by in gossamer and tails. This is essentially a country person whose tastes and needs are easily satisfied by the generosity of Mother Earth. Yes, she will go thirty miles out of the way to buy the right kind of smoked ham. But the Gemini/Ox doesn’t see that kind of detour as luxury. She’s a person who requires quality and finds it difficult to accept second best.

Demanding? Indeed! I would say that this Gemini is just that. He wants things right. He does not mind waiting but he hates clutter and waste and drivel. He’s impatient with flibbertigibbets and has no time for fools. Gemini/Oxen may even be accused of choosiness and a certain degree of name-dropping snobbery. Whom you know seems to the Gemini/Ox almost as important as what you know.`,
    love: `For the Gemini/Ox there are two kinds of love. There is family love. And there is sexual love. Otherwise there isn’t any love. The Gemini/Ox is a worker. He may claim not to be as diligent as he appears. But basically his goal is personal accomplishment. He’s not interested in romance. He’s interested in results.

The above often causes the domestic love life of the Gemini/Ox to be somewhat sterile, if not to say positively chilly. Yet, the Gemini/Ox is a busy and serious seeker of the favors of the opposite sex. It’s an odd mix. On one side, Gemini/Oxen are stay-at-home family types who don’t seem the least sex-oriented. On the other they run after everything that moves. The Gemini/Ox is an armchair Lothario.

If you should have the misfortune to fall in love with such a character, I would suggest you learn early how to turn the other cheek. This person will either choose you for home loving or for sexual loving. Never the twain. And should you have been the one chosen for home loving, don’t you dare get out of line. Oxen never forget.`,
    compatibilities: `You are fond of Aries/Rats (born March 21 - April 19 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), Aries/Snakes (born March 21 - April 19 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Aries/Roosters (born March 21 - April 19 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) too. You and the sexy Leo/Snake (born July 23 - August 22 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) or the efficacious Rat born in Leo (born July 23 - August 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) can also cut the mustard together. A gentle Libra/Rat (born September 23 - October 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) or Libra/Rooster (born September 23 - October 22 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) might do the trick for you as well. And don’t forget that Aquarius/Rat (born January 20 - February 18 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), Aquarius/Snake (born January 20 - February 18 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Aquarius/Rooster (born January 20 - February 18 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) can make you swoon. I don’t advise you to attempt long-standing relationships with Virgo (born August 23 - September 22), Capricorn (born December 22 - January 19), Sagittarius (born November 22 - December 21) or Pisces (born February 19 - March 20) of either the Tiger or Goat families. You won’t exactly adore Monkeys born in Pisces, either.`,
    homeAndFamily: `Here is where the Gemini/Ox’s heart (if he has one at all) really lies. The environment of Gemini/Ox people is, to say the least, cozy. The furniture, the kitchen appliances, the basement setup, the garage and the cars that go in it, the yard and the gardens and the woods and the whole bloody works come from the most authentic, the best and the finest craftsmen. It has all been put together with care and is maintained like a well-run ship. For all his diligence, this person enjoys doing nothing. He doesn’t mind sitting around twiddling his thumbs so long as the cars are freshly waxed and the maid is in the kitchen getting together a feast. This person makes a fabulous parent. There is no area of his child’s life that doesn’t interest him intensely.

The Gemini/Ox child may appear too quiet. The “good baby”, “model child” act is frequent with these kids. Don’t worry, your Gemini Ox child will get up to plenty of mischief by the time he or she is an adult. Be patient and give this little one plenty of time alone. You won’t make him participate no matter how hard you try. It’s just not his thing. He likes himself and his cronies. That’s it.`,
    profession: `Responsibility suits the Gemini/Ox down to the ground. He is capable of great hardheartedness and brilliant strokes of sarcasm designed to break the heart of a glacier. What the Gemini/Ox wants to do, he or she wants to do and will do. He’s a deep thinker and an effective doer. He doesn’t let sentiment get in the way of his actions.

As a boss the Gemini/Ox is unreasonable. She wants things done the day before yesterday and each job must be performed to perfection. Yet, she is indulgent with those who cooperate. She is even open-handed. But she doesn’t want any flak. As an employee this person won’t be very happy. The Gemini/Ox is really better off on her own in some kind of authority position where it’s up to her if the sun shines today or tomorrow. It s better for everybody concerned if this person gets to be the Mommy. Otherwise she goes home. She might even sniffle a bit at how misunderstood she has been. The Gemini/Ox can be quite a baby when it comes to having her own way.`,
  },
  "Gemini/Tiger": {
    description: `This impetuous person needs good brakes. When you combine hotheadedness with mercurial tendencies, you get some very smart dynamite. The pep and seductiveness of this character has a sort of generous pussycat congeniality to top it off. It’s pretty delectable to behold. But it’s very difficult to hang on to.

As Gemini never stops darting from pillar to post, philosophy to news flash, project to love affair, the character is already injected with a large dose of blast-off fuel. To add to the instability, along lopes our old friend the tawny Tiger, whose basic idea of himself is that he is extraordinary, ought to be chosen king of the jungle right now if not sooner and would you please move over so he can sit down on that throne? Charm, magnetism and natural authority added to all that Gemini mutability make a sort of benevolent speed demon.

Gemini/Tigers are forever getting themselves into emotional hot water. Their desire to be considered both winning and wonderful drive them to wish to perform great deeds. But it just isn’t enough to devise dreams. Somebody has to stick around when they come to punch the ticket. Gemini/Tigers have a sort of whirling dervish effect going all the time. Their restlessness sticks out of them like tiny inverted arrows all over their skins which say, “Look at me. I’m the Gemini/Tiger. Am I not marvelous? Do I not impress you with my looks, my brains, my very tawniness?” Yes. Okay. Sit down now. And for heaven’s sake, think! No. Not that kind of flitting-about thinking, real sound planning type of thinking. Where do you really want to go? What is your main goal? How can you avoid all these interim meaningless goals to which you are repeatedly drawn? Gemini/Tiger, you’d get stuck hanging on a bus strap if there was someone watching you who seemed transported by your aura. Three stops later you might remember where you were headed. But then, because you are so ... adventurous, you might not even care where you were going, stay on the bus and follow it to your next chosen destiny. You are not stupid. But you are sometimes too zany for words.

Bad things can happen to people who don’t pay attention to the doughnut and watch only the hole in the middle. And Tigers who are born in Gemini are some of the best targets for ill fates. They are not tied down to the earth by any reality other than the moment, the breakthrough, the jackpot, the fabulous party, the sexy guy in the aisle seat, the dame in red. Of course Geminis born Tiger are smashingly attractive. One is automatically magnetized by their seductive manners and sizzling charm. But eventually, if they don’t settle themselves early into routines that channel their energies and instruct their explosive minds, Gemini/Tigers can become very angry at life. When you are so naturally appealing, it’s easy to float along on your appeal. But then what? What happens when you hit a snag in life? What happens when your mate leaves you or your child falls ill or your job is eliminated? What then, Tiger/Gemini? Where will you go and whom will you charm? The Fates?

No. You can only go on so long casting about from place to place, moving from relationship to relationship. Life will eventually catch up with you. Then you’ll have to face the music and you may even have to face yourself —alone. I know it’s not your favorite idea. But then, you know very well that you have always avoided introspection. But if you did take time to think ahead and apply one or two of your many talents, you would be able to move mountains. You know you are strong. But you are also lazy. You prefer to bask in seduction. That, you are aware, Gemini/Tiger, is silly.`,
    love: `The Gemini/Tiger’s biggest stumbling block in romantic affairs is getting involved with people whose adoration the Gemini/Tiger does not really return. He finds their worship of the very ground he walks on irresistible. Yes, it is egotistical. But not intentionally so. If reminded of this trait, the Gemini/Tiger will humbly agree that she’s not really wild about Jerry, but Jerry loves her so much that it would break his heart if… Well, the “if” inevitably occurs. And then Jerry is left to inhabit the populous past of the Gemini/Tiger siren.

The Gemini/Tiger needs to be given lots of room. He or she will like to be taken to restaurants and shown off at elegant receptions and spas of all sorts. He will often tell silly stories that you have heard a hundred times before. Either get earplugs or bite your tongue. He does not want you to get into the act by venturing, “No, dear, it wasn’t Tuesday when Maria forgot your pants at the cleaners. It was ...” I would give you more advice on how to hang on to one of these flying saucers, but I don’t really think anything will work. They are pretty much alone in life’s crowd and their fate belongs exclusively to them.`,
    compatibilities: `You’ll find happiness with a number of signs. Among them are Aries/Dogs (born March 21 - April 19 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Aries/Horses (born March 21 - April 19 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026), Leo Dogs (born July 23 - August 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) or Leo/Horses (born July 23 - August 22 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026), too, and Librans born either Dog (born September 23 - October 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) or Horse (born September 23 - October 22 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). In Aquarius you’ll be most attracted to the Dragons (born January 20 - February 18 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), but perceptive Aquarius/Dog (born January 20 - February 18 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) won’t disappoint you. You are better off losing Virgo (born August 23 - September 22) and Scorpio/Snakes (born October 23 - November 21 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025), Scorpio/Tigers (born October 23 - November 21 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Scorpio/Monkeys (born October 23 - November 21 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) in the crowd. As for Sagittarians, you should abstain from Horses, Rabbits and Goats of that sort. Don’t take up with a Pisces/Snake (born February 19 - March 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025). They’re too slippery for your clumsy big paws.`,
    homeAndFamily: `Regulation home life coupled with family life and all of its daily habits and chores does not match up very well with the Gemini/Tiger’s desire for movement and experience. They often have very dramatic interiors draped with laces and furbelows, or padded in wall-to-ceiling carpets with remote control lights and mirror effects. Gemini/Tigers can be incredibly theatrical. As parents they are very loving and warmhearted. They encourage their offspring to do whatever appeals to them and will go to great lengths to see that their kid is properly educated. Gemini/Tigers get along well with kids, too. They are extremely spontaneous people. You will often see a Gemini/Tiger parent actually “playing” with children. They are not bored by the company of little people and of course enjoy any extra attention they can get.

The Gemini/Tiger child will need strict control over his penchant for zigzagging. If you as the mother or father of this being can manage to gently urge some degree of self-discipline, this creature may have a better chance of making some kind of normal life. Lessons, regular bed times and hours to brush teeth, telephone curfews and the like are important. If you have the patience, your Gemini/Tiger child has the talent.`,
    profession: `Fast and energetic, the Gemini/Tiger is born with the ability to adapt to new situations in a trice. This person lives his or her life quickly and gets on to his next goal without much ado about the previous one.

Unusual destiny is the best part of being Gemini/Tiger. As a boss he’s hopeless. As an employee too. This person is an original. He cannot be expected to arrive on time and leave at a certain hour. He hates routine and will perform much in the way of mental and physical gymnastics to escape from it. Gemini/Tiger is always succeeding when he least expects to. From out of nowhere flashes luck.

Gemini/Tigers are best employed by themselves in jobs they have thought up for themselves. They take kindly to freedom of movement. Give them a paper bagful of delicious-smelling soaps to go around selling and they will have them all bought up in an hour. The Gemini/Tiger is a remarkable communicator. Trouble is, on the way back to bring you the proceeds, Gemini/Tiger may stop off at the leather goods store and purchase a nicer bag for himself so that next time he goes out selling he’ll be more attractive. It’s a dilemma.`,
  },
  "Gemini/Rabbit": {
    description: `Cat and Gemini make strange bedfellows. The discreet, prudent, careful Cat character infused with Gemini’s mercurial pizzazz gives me pause to ponder how in the world such a person might achieve self-knowledge and control. I mean, look at the problem. Geminis are all sizzle and snap. Cats, on the other hand, tend to gentility, caution, comfort. To me it seems the busy Gemini rushing about tilting at a huge variety of windmills must, when born in Cat years, from time to time feel himself suddenly leapt upon —surprise!—by his feline-nature mate whose padded feet dart out sharp claws to remind the Gemini, “Take it easy. Go slow. Back off. Sit still. Don’t grab. Hang back. Beware.”

Mild schizophrenia.

Superficially this person will give the impression of flitting gaily from flower to flower, of a certain lack of seriousness and of an odd off-center disorganization. But the surface portrait is all wrong. Underneath, the Gemini/Cat is steady, watches every move of those around him, and has a more perfectly ordered inner life than Einstein at the height of his intellectual powers. Agility is the weapon, flexibility is the ammunition, brains the soldier. Gemini/Cat is his own personal army of sinew and muscle camouflaged under cuddly purrs and fur.

The Gemini/Cat’s is an unflinching territorial imperialism: He will invite you to his home, open up his guest room, and even offer you lots to drink. But the Gemini/Cat will never give you the key to his private cupboard where he keeps the microfilm. You will never get beyond the door that leads to the study where a Gemini/Cat operates his personal business. The fortress is beautifully kept, every stone in place and the locks all polished to a blinding sheen. Don’t try to get in. Take what hospitality the cheerful Gemini/Cat is willing to give. But unless you relish wearing long sleeves to cover the gouges on your arms for the rest of your life, I suggest you stay out of his filing cabinets.

In this person, the Gemini indecisiveness is just about canceled out by the Cat’s careful consideration. Once a Gemini/Cat has given due thought to a project, he no longer hesitates or dawdles as to its execution. When they want something, these folks are efficient and know how to zero in on the jugular.

Where performance is concerned, Gemini/Cats are right up there with the stars. Geminis are attracted to all aspects of theater. But for the most part Geminis like to act! They are born performers whose greatest kick in life comes from interpreting roles and inducing thrills or applause from their audiences. The Gemini/Cat is no exception. He takes great pains to please his public, amuse the gallery and remain in character while on stage. Watch a Gemini/Cat give a dinner or cocktail party. From the moment they arrive the guests are all smiles, nodding and listening attentively to the Gemini/Cat’s gripping tales and adventures.

This Gemini is nervous as a cat. Complexity blesses both Cats and Geminis from birth. These are not simple people whose pleasures roll in as uncomplicatedly as the waves on a beach. Oh no. The Gemini/Cat has a Byzantine set of senses. The choices he makes, from foods to clothing to habitat to friends to jobs, are never the obvious ones. Gemini/Cats stalk their options, circle them and test their reactions, walk away and reflect, come back and test again. Then they may deign to make a firm choice. And that vigilant selection may very well forecast the home, or style of mate, of the Gemini/Cat’s choosing.

In Gemini/Cats you may notice a certain false sense of assurance. These people are given to imagining themselves a cut above the rest of us. Gemini/Cats tend to snobbishness and may be accused of name-dropping, too. This person is conservative. Sometimes, his reactions may strike us as puritanical or Spartan. But one must remember that Cats, no matter when they are born, are not naturally quarrelsome. They avoid conflict. The Gemini is a good talker, but when he’s born a Cat that talent can only be used for communication—never for battle. The most important goals in this person’s life are comfort and freedom from confrontation. The Gemini/Cat will do anything to insure those ends.`,
    love: `For Gemini/Cats love is never just a game. These serious-minded yet garrulous people hate anxiety. A broken heart or home can so upset a Gemini/Cat’s fragile nervous structure that he may never rise from his coiled-up shadow in front of the blazing hearth. Single Gemini/Cats are always looking for the partner who will be willing to dare where he cannot, to lash out when he won’t, and to confront where he is incapable. In exchange for the services of a loving, protecting partner, Gemini/Cat offers charm, comforts, coziness, reason and culture. Gemini/Cat is a traditional soul. He will prefer tall windows with curtains to naked picture sized panes. He’s private and warmhearted. But the Gemini side is not exactly compassionate. His understanding of others is limited to polite nods and even an occasional “tsk.” But he’s not the person to run to when you’re in danger or ready to leap out a window. This person does not make a good mate for the troubled and tortured soul. He feels that he is complicated enough himself and will shy away from hitching up with someone who might possibly turn up the heat under an already sizzling network of frayed nerve endings.

If you love a Gemini/Cat, then you must accept solving you problems and even undertaking to sort out some of his. You must be ready to block outside influences and bar the door to trouble. The Gemini/Cat can definitely take care of himself. But his equilibrium can be abetted by coupling with another, less jumpy and more optimistic person than he.`,
    compatibilities: `Aries (born March 21 - April 19) and Libra/Goats (born September 23 - October 22 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027), Aries/Dogs (born March 21 - April 19 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) or Aries/Pigs (born March 21 - April 19 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) subjects will enhance your existence with their ready sensitivities attuned to yours. You’ll also have crushes on Leo/Dogs (born July 23 - August 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Leo/Pigs (born July 23 - August 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) and Aquarius/Goats (born January 20 - February 18 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) and Aquarius/Pigs (born January 20 - February 18 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031). No Virgo/Rats (born August 23 - September 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) or Virgo/Roosters (born August 23 - September 22 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) for you. Nor do I suggest Sagittarius/Tigers (born November 22 - December 21 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or Pisces/Dragons (born February 19 - March 20 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or Pisces/Roosters (born February 19 - March 20 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029). Too cocky and pushy for you.`,
    homeAndFamily: `Don’t expect a Gemini/Cat to pop out seven kids in seven years and enjoy hanging out in the laundry room for the rest of his life. This person is anything but hardy. Of course he can marry and make a good home and even have one or two children. But the need for repose and calm is great here. The turbulent household is not prescribed for the Gemini/Cat’s family life.

Rather, a large dose of refinement, plenty of genteel celebrations for observing birthdays and holidays, and well-behaved children are sure to appeal to the Gemini/Cat person. For him a family is a place to find calm and to escape from the hard-edged world outside. The Gemini/Cat hardly wants a daughter or son who brings in five teenage friends every afternoon to practice rock music in the living room. Not on your nine lives! If you meet a Gemini/Cat parent who informs you, “My daughter Nellie is studying medicine in Boston,” you can be sure you are talking to a happy Gemini/Cat.

Gemini/Cat kids are likable, reasonable and peace-loving. They require understanding from parents, and must be encouraged to develop their minds. They can be talked into sports so long as the game has some tradition behind it. You can send a Gemini/Cat to tennis camp, but don’t expect him to become a bleached-haired Windsurfer who wears an earring in his nose. The Gemini/Cat could well adore being allowed to stay with grandparents, cajoled and spoiled and comforted.`,
    profession: `This is not your average run-of-the-mill hard-nosed businessman. Gemini/Cats know how to engineer schemes and attend to the inner workings of plans. They even manage very well executing the plotting of others and usually get positive results from same. But what Gemini/Cats don’t particularly know how to do is invent devious plots for themselves. In this way they are truly handicapped in commerce. As we all know, negotiation requires a certain degree of ruse and guile. It’s not that the Gemini/Cat doesn’t possess large quantities of both. It’s more that he’d rather not have to use his talent for deviousness. Negotiation can lead to conflict and we know how Gemini/Cats feel about conflict. So not being a businessman or merchant type, the Gemini/Cat will do well to choose careers requiring contemplative behavior, performing, persuasion and execution. The Gemini/Cat should choose to do business without the business. He can sell things, for example, or draw up documents, or stagemanage a theater or become a movie director. Gemini/Cat make excellent lawyers or real estate agents, researchers and scientists. As long as they don’t choose a branch of any of the above professions that requires head-on collision with coworkers, the Gemini/Cat will be safe and secure. In fact, the marriage of Cat and Gemini gives us a sign gifted in security, talented in performance and adept at all variety of refinement.`,
  },
  "Gemini/Dragon": {
    description: `The active, aerated Gemini mind couples brilliantly with our friend the dashing Dragon. Here you meet up with unforgettable characters in the strictest sense of the world “character.” Gemini/Dragons are exciting and bewitching. They have élan to burn and charm galore. Gemini/Dragons personify panache. But don’t count on them to perform any mental gymnastic that requires more than ten minutes’ concentration. Gemini/Dragons are sprinters. The hot fire of novelty burns brightly and excites this subject to create great dreams and formulate giant plans. But the Gemini/Dragon is easily bored. He wants the living room to be painted a beautiful creamy white by the time the guests arrive this weekend. But he cannot stop practicing his golf swing long enough to go to the hardware store to buy the paint.

So, what Gemini/Dragon people are famous for is their aptness at hiring people to do their work for them. Gemini/Dragons are “idea men.” And indeed they can fish new notions out of their bag of tricks as fast as we can say “paintbrush.” They can rally groups and dispense all their ingenious schemes and methods of getting things done—but Gemini/Dragons will not fill out so much as one form or make a single telephone call on their own. They don’t consider dirty work part of their job.

Of course these people have so much personal magnetism and charm—and push!—that they scarcely need much else. Their bravura really does squeak them through. Their self-belief is uncanny. They are rocks of strength and wit. Yet, the loss of a loved one, a business failure or a romantic breakup can cause them to be horribly shaken. And when that happens, watch out! A hurt Gemini/Dragon flails and emotes more savagely and vociferously than a herd of wounded moose. Weep? I never saw anybody weep so much in my life. Rail against fate? It’s the Gemini/Dragon’s specialty: “Nobody loves me. I’ve been wronged. Everybody hates me” ought to be the Gemini/Dragon theme song.

Gemini/Dragons intimidate others. As Geminis, they of course enjoy performing. Early on, they learn that it’s possible to impress others by playing “grump” or “hard-hearted” or even “gangster” roles. The Gemini/Dragons I know behave like scary monsters upon first encounter. They present themselves in a condescending fashion that really makes people stand back and wonder what they might be about to say or do. Fact is, Gemini/Dragons are only paper dragons. You can push one over with one puff of reason or snipe. But you have to dare to puff. And Gemini/Dragon plays his Dragon part so convincingly that you probably won’t even believe me when I tell you that you can make him fall pit apart if you find the path to his gooey roasted marshmallow heart. Try tears or complaining. If that doesn’t work, lie down and pretend that you are so ill you might pass away in the night. Gemini/Dragons melt at sight of weakness in those they love. It makes them fear they might have to do the loved one’s work for him or her, or lose their audience.

In social situations, the Gemini/Dragon is often impossible. I remember seeing a favorite Gemini/Dragon of mine slam away from a party because nobody was paying attention to his jokes. And worse, if a Gemini/Dragon feels threatened in any way, if a person he meets appears more exciting than he, he may say or do the most outrageous crazy things—like turn the coffee table upside down with the coffee still on it—just for attention. Gemini/Dragons are naughty. And that’s the way they like it. Despite the aura of pizzazz and pride that radiates from Gemini/Dragons, their tendency to scold and most of all to unfavorably compare their successes to yours, the Gemini/Dragon is anything but a real meanie. Geminis born Dragon are truly loving, warmhearted souls who hug their children a lot. But they have a way, a manner, a carriage that puts others off. It’s only a front, a façade—but what a cover!

In small doses, Gemini/Dragons make super friends. They are usually amusing (when they are not horrid) and always game for a party or an evening out. In my experience with Gemini/Dragons, they will only cut up or carry on like madmen if you stop paying full attention to them for half a second. Should such a situation arise, I suggest you simply turn on your heel and walk away, pretending you never saw the Gemini/Dragon person before and wouldn’t know him if you tripped over him. Solitude is the Gemini/Dragon’s number one enemy.`,
    love: `Although most Gemini/Dragons may appear trivial and flighty, they are most decidedly not either frivolous or trifling about love. For these people there is no such thing as lukewarm sentiment. Gemini/Dragons adore their partners down to the last toenail paring. They will do anything to prove their loyalty to a loved one. In return, they demand a brand of exclusivity that is not only out of style but is nigh unto impossible. Gemini/Dragon dialogue goes like this: “Don’t read that book! You may fall in love with the main character. I don’t want you going to that movie. It might give you funny ideas about traveling. I don’t want you to travel. Stay here. Stay with me and love me and listen to me and hold my head in your lap and comfort me.”

If you love a Gemini/Dragon (and as a past lover of Gemini/Dragons I attest to the pure thrill of same), be there for him or her. Wait for him to come home, or better still invite lots of people in so your Gemini/Dragon can perform, crowd-please and entertain. As mate or companion of one of these people, it is your job to help him exhibit his talents. You will best serve his purposes by showing him off, giving him the guarantee of your undying passion and keeping your sense of humor for the rough spots. And rough spots there will be.

Gemini/Dragons are not classically faithful. They are passionate, fervent, avid and vocal lovers. They usually have a life partner to whom they cling with unreal ardor. But, Gemini/Dragons are flirts. They cannot help themselves. They go around at parties kissing and hugging and enticing the guests. Young or old, beautiful or plain, exciting or dull, everybody has to be tested, teased, stroked and talked to by Gemini/Dragon. If this sort of public promiscuity doesn’t always terminate in successive affairs, it looks as if it will—which may be worse for the lover who cares about appearances. But then if you cared about appearances, you wouldn’t be with a wicked old Gemini/Dragon the first place, would you now?`,
    compatibilities: `The Aries/Rat (born March 21 - April 19 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), Aries/Monkey (born March 21 - April 19 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) and Aries/Pig (born March 21 - April 19 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) are all capable of improving your dazzling self-image and maintaining your lifelong interest. Leo/Rats (born July 23 - August 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), Leo/Tigers (born July 23 - August 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Leo/Monkeys (born July 23 - August 22 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) will also beckon you, but watch out! They are short on naiveté and you may have trouble fooling them. A nice Libra (born September 23 - October 22) or Aquarius/Rat (born January 20 - February 18 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) would suit you, and a Libra/Monkey (born September 23 - October 22 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) would be perfect. Brush off all advances by Virgo/Oxen (born August 23 - September 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). They are tar too stodgy for your flashy tastes. You won’t want to take up with Scorpio (born October 23 - November 21), Sagittarius (born November 22 - December 21) or Pisces/Dogs (born February 19 - March 20 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) or Pisces/Oxen (born February 19 - March 20 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021).`,
    homeAndFamily: `In the Gemini/Dragon character there is lots of room for children, parents and cousins and aunts and uncles and siblings. This is a big-hearted person whose generosity is as broad-based as his huge sphere of influence at parties. No family member (who doesn’t try to upstage the Gemini/Dragon) will go unnoticed or uncared for so long as the Gemini/Dragon is around. This person is a protector of the weak, a Popeye character who rescues helpless females from the arms of bounders and cads. So long as any person in the ken of a Gemini/Dragon is in need, he can count on the Gemini/Dragon to find ways to sort him out.

Despite his kindness, the Gemini/Dragon will be a demanding parent. The offspring of a Gemini/Dragon will tell you that their mom or dad really made them toe the line. Gemini/Dragons don’t accept any back talk or sulking from their kids. But they don’t necessarily want their kids to achieve a high position in life. The Gemini/Dragon is afraid of having his show stolen, remember? Well, a child who becomes a bigger star than his parent is a threat to the Gemini/Dragon.

Gemini/Dragon children are exhaustingly adorable. They chatter interminably and test your patience with their endless displays of bravado. They love celebrations and are willing to perform anything from magic tricks to skits to baton exhibitions for the guests. They require attention and affection from parents—especially if they have been hurt or rejected outside the home. Failure to please on any level can wound a Gemini/Dragon child deeply. He must be reasoned with and made to understand the necessity of hard work and application to study. He cannot get by on his charms forever.`,
    profession: `The wherewithal for real solid success is present in the Gemini/Dragon character. He is capable and has true vital energy to spend on all manner of projects and jobs. Gemini/Dragons are attractive, too, and people enjoy being around them—for a few minutes at a time. On first glance a Gemini/Dragon seems the incarnation of success.

There is, however, a rub. Gemini/Dragons are sprinters. Their initial performances are always perfect. Their three-month trial period always goes off like a charm. Their first deal is always a huge boon to the company’s accounts. Everybody in the office adores the new Gemini/Dragon on the fifth floor. But wait. Give the Gemini/Dragon on five a chance to settle in. Watch how he or she behaves at the first office Christmas party. Notice how cheeky the Gemini/Dragon has become with his superiors. Watch the boss’s facial expression as the Gemini/Dragon expounds an inside secret to non classified folk. Over the long run Gemini/Dragons just don’t hold to their courses. They fall out of character after about a year or so on any given task. They veer and swerve and sometimes get themselves fired for misbehaving.

For this reason, Gemini/Dragons are best employed by themselves in businesses requiring lots of contact with the public. Sales or public relations, owning restaurants or bars or even performing in general sorts of country-doctor medical careers will appeal to the versatile Gemini/Dragon. This character can be in a thousand places at once and keep track of everything in all of them. Staying put and delving deeply into any one subject or task is beyond the Gemini/Dragon’s pale.`,
  },
  "Gemini/Snake": {
    description: `A paradoxical character is the Gemini/Snake. If he can get a good grip on the specialness that is his natural endowment from birth, this person is qualified for true greatness. The Gemini/Snake is a thinker. Imagine the lucky combination of reflection and intuition! The marriage of the two signs is fortuitous indeed.

But this heady mixture of influences is a veritable minefield of pitfalls as well. People born in Gemini/Snake are sitting ducks for both Byzantine self-delusion and rank laziness. Every single day of their lives these people must bite the bullet and grit their pretty teeth just to get out of bed in the morning. Invertebrate inertia, fueled by an oddly sunny despair, pushes Gemini/Snakes earthward and very often just won’t let up.

Maybe this yellow jaundice of the spirit comes from too much intuitive knowledge of the perils and disappointments each Gemini Snake sees ahead. It is as if this person sensed how deeply he affects the world when he really tries and for that reason simply desists before he begins. It’s inevitable that this combination of signs give us a performing Snake, the actor or actress with the overdeveloped brain, the show business personality with the weighty intellectual baggage, the irresistibly cheery political figure with heartbreak written across his smile. The Gemini/Snake’s hereditary dice are loaded.

So the Gemini/Snake suffers from excessive foresight. Before anything happens to him, he knows it’s about to occur. While it’s happening, he’s relatively excited about it. But when it’s over, he’s convinced that maybe it wasn’t worth the trouble and it might have been more fun to have a vacation instead.

Gemini/Snakes have to discipline themselves to engage in far-reaching and complex pursuits. They must always bite off more than it seems hey can chew? The Gemini/Snake needs not only challenge, but he needs to develop an inner bulldozer to push him into things—encourage him to slither along and accept the cheers and notoriety that are his natural rewards—as well as his neurosis.

Like every self-respecting Snake, this person loves to be rich. Money and the gathering of wealth can become a driving force in the Gemini/Snake’s life. Trouble is, he is too smart to be too rich. Though he may enjoy opulence and be most comfortable in silken sheets, the Gemini/Snake finds the touch of the shekel distasteful and will seek ways to avoid it. When I think of the Gemini/Snake, an image of a lovely furry caterpillar creeps into my mind’s eye. The pace is the same, to be sure—as is the promise. When you see a caterpillar, you know there will one day be a butterfly, ephemeral perhaps but so glorious and so fantastic that its beauty leaves an indelible mark on your life. Temporary permanence is the personification of the paradoxical Gemini/Snake.

This person will surely prove to be fragile of health and testy to live with. There’s so much going on inside this creature that frequently he cannot be bothered seeing to day-to-day material necessities. He wants to use his mind to soar off in twenty mental directions at once, to invent some new philosophy, to change the world, to inspire his fellow man. Why do you persist in asking him to scrub the floor when you know full well that he cannot, does not, will not ever care one way or the other if that stupid floor gets itself scrubbed or not? The Gemini/Snake is above it all. Really. The bright witty company of Gemini/Snakes gives us all great pleasure. These subjects are never boring. Their agile minds follow every train of thought and dart from flower to flower doing justice to each and every one. You can talk with this fellow for hours, jabber, chat and hash and rehash till you come up with a whole new way of looking at something. Gemini/Snakes are inspiring and thoughtful of others. They are persuasive, seductive and remarkable in every way. If this person can begin a task, conquer his latent sloth and dive into a real personal project he will always be a natural winner. Nose to grindstone and one eye in the cleanest, most truthful mirror available—then onward and forever upward he will fly.`,
    love: `First of all, everybody falls in love with Gemini/Snakes. They are usually beautiful to look at. They smell nice and have pretty, fragile, tern natures. They are intelligent and funny and compassionate. Yes. Everybody loves a Gemini/Snake.

For the Gemini/Snake himself, this general acclaim and adulation causes no tiny amount of emotional disturbance. Just as those around him are one by one tumbling at his feet, he is likewise attracted too. Gemini/Snakes tend to promiscuity—and it isn’t even their own fault. Who could resist all those fawning fans? Not I.

As a life partner the Gemini/Snake requires a patient understanding soul mate. This person cannot interact with clumsy or incompetent companions. Solemnity and gloom are also out of the question. Gemini/Snakes have enough trouble getting themselves out of their pajamas and into the car without having to assist someone else in doing likewise. Gemini/Snakes can inspire others. But they will not force-feed them.

The prizes that fall as though by magic into the hands of Gemini/Snakes will be shared and showered on their mates as well. The Gemini/Snake needs love from one reliable and respectable person on whom he can count and whom he trusts forevermore. If you can provide this sort of unflinching adoration and will yourself promise perfect exclusivity, Gemini/Snake can make you very, very happy. But if you feel you can be shaken by infidelity, or that you might envy or compete with this character, stay away. You’ll only be hurt. The Gemini/Snake rules.`,
    compatibilities: `You will automatically be drawn to Aries (born March 21 - April 19) and Aquarius (born January 20 - February 18), both Roosters (born 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) and Oxen (born 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). Leo/Dragons (born July 23 - August 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Leo/Oxen (born July 23 - August 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) please you, too, and so do Libra/Dogs (born September 23 - October 22 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and their Ox (born September 23 - October 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) brothers and sisters. You are not really suited to Virgos, especially Virgo/Tigers (born August 23 - September 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Virgo/Pigs (born August 23 - September 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031). Nor will you find happiness with Sagittarius/Tigers (born November 22 - December 21 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or Sagittarius/Pigs (born November 22 - December 21 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) or Pisces/Tigers (born February 19 - March 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or their Monkey (born February 19 - March 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) counterparts. Take my advice. Steer clear of Scorpios, especially the Tigerish kind.`,
    homeAndFamily: `This temperamental soul is hardly your average family man. As a sibling or cousin or aunt, this person will inspire much respect. But as a parent the Gemini/Snake has some trouble getting down to his kids’ level, crawling around on all fours making googly sounds and playing hide-and-seek. I would say that if this person decides to have children, he should also decide to hire a nanny. He’s not the cuddly, lovable, huggable bear type at all. Children born in Gemini/Snake will seem wise beyond their years. They may cause some parents to be disconcerted by their early grasp of abstract concepts. Don’t worry. It’s normal. This child will always be smart—even brilliant—in school. But he will most likely also favor lying abed till all hours on weekend mornings, then by three in the afternoon hanging about the house like a slug reading mature books and being charming. It’s in his nature. You cannot really do much for this self-possessed child’s future plan except to instill in him a sense of the work ethic and its utter necessity to successful living.

He cannot be treated aggressively but he can be gently rolled uphill by loving and intelligent parents. He probably won’t get on too well with siblings. Don’t worry about it. It’s his nature to be exclusive about affections. He doesn’t need to share his toys in order to learn how to become President of the United States or head of IBM.`,
    profession: `These people always arrive at some form of success in life. They are naturally superior thinkers and although not hard-hitting world beaters of the classical rough-and-ready type, Gemini/Snakes usually manage to find some degree of equilibrium in their work life.

They make excellent teachers and philosophers, doctors and lawyers, writers and even politicians. Gemini/Snakes are magnetic and can learn anything well. They will require an extensive education and their hobbies will probably all have to do with reading and assimilating knowledge. They even do crossword puzzles with a special intellectual knitting of brows. Artist or businessman, rich and famous or not, the Gemini/Snake is always caught between wanting to fit in and longing to opt out. Of course he is ambitious and wants to get somewhere in life. But wouldn’t it be easier to just stay home and dream about how he will get there, read tomes on the subject dearest to his heart and occupy the chaise longue?`,
  },
  "Gemini/Horse": {
    description: `This is an exciting and very movable character. The Gemini/Horse is forever on the go, searching out new places to conquer and new people to enchant. Like all Horses, this one is mad about himself and feels that whatever he undertakes is of paramount importance to the world. Gemini’s mental agility and quickness of wit lend this Horse a special intellectual advantage over other Horses. He’s not only out there looking gorgeous and making everybody laugh, he’s also got something upstairs. The Gemini/Horse is a thinker as well as a doer.

The Gemini/Horse is a double sign. Both Gemini and Horse are on the move all the time. They are both gifted for gab and excel at self-expression. The Gemini/Horse doesn’t mince words. He says what he thinks and doesn’t much care who hears him. He’s impetuous and often decides on the spur of the moment to change his life, move to another country, get married or take a new job. The Gemini/Horse is a spontaneous person whose very changeability makes him exciting to be around.

This person is also a bit selfish. He wants to be on center stage all the time. He doesn’t always take kindly to competition and is not above stepping on a few toes to get where he’s going. The Gemini/Horse is a natural leader. He’s bossy without being overbearing, and funny without being silly. This person will always be more attractive than the average Horse because of his mental dexterity and his ability to turn a phrase.

Gemini/Horses are not famous for their constancy. They are easily bored and will seek new horizons the minute they feel the old ones have lost their charm. This quality makes them difficult to live with. They are not the kind of people who settle down easily. They like to keep moving, keep changing, keep discovering.`,
    love: `In love, the Gemini/Horse is a flirt. He’s charming and seductive and knows how to use his wiles to get what he wants. He’s not above a bit of cunning to win the heart of the one he loves. However, once he’s won that heart, he may not be so keen on keeping it. The Gemini/Horse is a conquest-oriented person who loves the chase but may not be so thrilled with the catch.

If you love a Gemini/Horse, you must be prepared for a wild ride. This person will keep you on your toes, always guessing what he’ll do next. You’ll need to be flexible and open to change, as the Gemini/Horse is not one to stay put for long. A sense of humor is a must, as is the ability to let this person have the spotlight. If you can handle the unpredictability, life with a Gemini/Horse can be a thrilling adventure.`,
    compatibilities: `You’ll get on well with Aries (born March 21 - April 19), Leo (born July 23 - August 22), Libra (born September 23 - October 22), and Aquarius/Dogs (born January 20 - February 18 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Aquarius/Tigers (born January 20 - February 18 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034). A Libra/Tiger (born September 23 - October 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) could be a particularly good match, as could an Aries/Dog (born March 21 - April 19 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030). Avoid Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), Sagittarius (born November 22 - December 21), and Pisces/Rats (born February 19 - March 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) and Pisces/Rabbits (born February 19 - March 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035). They’re too different from you in temperament. A Capricorn/Ox (born December 22 - January 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) or a Pisces/Snake (born February 19 - March 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) might also cause friction.`,
    homeAndFamily: `The Gemini/Horse’s home is likely to be a reflection of his eclectic tastes. It may be a bit chaotic, with a mix of styles and influences from his many travels and interests. This person is not one for routine domesticity. He’d rather be out exploring than scrubbing the floors.

As a parent, the Gemini/Horse is fun-loving and encouraging but may not be the most disciplined. He’ll inspire his kids to dream big and explore the world but may struggle with setting boundaries. The Gemini/Horse child is a handful—bright, curious, and always on the move. Parents will need to provide structure and guidance to channel this child’s energy into productive pursuits.`,
    profession: `The Gemini/Horse is a natural at jobs that require quick thinking, communication, and adaptability. He’s a great salesperson, public speaker, or entertainer. His ambition and courage make him a good candidate for leadership roles, though his impatience and changeability can sometimes get in the way of long-term success.

As a boss, the Gemini/Horse is inspiring but demanding. He expects his employees to keep up with his fast pace and may not have much patience for those who can’t. As an employee, he’s innovative and energetic but may struggle with routine tasks. He’s best suited to careers that allow him freedom and flexibility, such as journalism, travel writing, or event planning.`,
  },
  "Gemini/Goat": {
    description: `The Gemini/Goat is a curious blend of airy intellectualism and emotional sensitivity. This person is a dreamer, full of ideas and creative notions, but often lacks the drive to see them through. The Gemini’s quick wit and versatility combine with the Goat’s artistic flair and whimsy to create a person who is charming, imaginative, and a bit scattered.

This character is highly sociable and loves to be surrounded by people. The Gemini/Goat thrives on conversation and intellectual exchange but can be overly sensitive to criticism. The Goat’s tendency toward dependency and anxiety can clash with Gemini’s need for freedom, creating an internal tug-of-war. This person may want to be independent but often leans on others for support.

Gemini/Goats is a performer at heart, with a flair for the dramatic. They love to entertain and be admired but can be prone to self-doubt and indecision. Their moods can shift quickly, and they may struggle to stick to one path or decision. However, their creativity and taste make them excellent at anything involving art, design, or aesthetics.`,
    love: `In love, the Gemini/Goat is romantic and affectionate but can be needy and insecure. They crave a partner who will provide emotional stability and reassurance while also allowing them the freedom to explore their many interests. They are drawn to people who appreciate their creativity and can keep up with their lively conversation.

If you love a Gemini/Goat, be prepared to offer a lot of emotional support. This person needs a partner who is patient and understanding, someone who can gently guide them without stifling their need for independence. A strong, grounded partner can help the Gemini/Goat channel their creativity into something lasting and meaningful.`,
    compatibilities: `You’ll find harmony with Aries (born March 21 - April 19), Libra (born September 23 - October 22), and Aquarius/Rabbits (born January 20 - February 18 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), Aquarius/Pigs (born January 20 - February 18 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031), and Aquarius/Horses (born January 20 - February 18 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). A Libra/Pig (born September 23 - October 22 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) or an Aquarius/Rabbit (born January 20 - February 18 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) could be particularly compatible. Avoid Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Capricorn/Dogs (born December 22 - January 19 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Capricorn/Oxen (born December 22 - January 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), as their practical, serious natures may clash with your whimsical spirit. A Pisces/Snake (born February 19 - March 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) or Pisces/Rat (born February 19 - March 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) might also be too intense for you.`,
    homeAndFamily: `The Gemini/Goat’s home is likely to be a cozy, artistic haven filled with beautiful objects and creative touches. They love to create a warm, inviting environment but may not be the most practical when it comes to household chores. They prefer to focus on the aesthetic rather than the mundane.

As a parent, the Gemini/Goat is loving and imaginative, encouraging their children to explore their creativity. However, they may struggle with discipline and consistency. The Gemini/Goat child is sensitive and bright, needing plenty of encouragement to build confidence. Parents should foster their creativity while gently teaching them to be more decisive and self-reliant.`,
    profession: `The Gemini/Goat excels in creative fields such as writing, design, or the arts. Their versatility and quick thinking make them adaptable, but their indecision and tendency to procrastinate can hold them back. They need a career that allows them to express their creativity while providing some structure to keep them on track.

As a boss, the Gemini/Goat is inspiring but may lack the firmness needed to manage a team effectively. As an employee, they are innovative and charming but may need guidance to stay focused. Careers in advertising, fashion, or media are well-suited to their talents.`,
  },
  "Gemini/Monkey": {
    description: `The Gemini/Monkey is a whirlwind of wit, charm, and cleverness. This person is a master of improvisation, always ready with a quick quip or a clever solution to a problem. The Gemini’s mental agility pairs perfectly with the Monkey’s cunning and resourcefulness, creating a person who is always one step ahead of the game.

This character is highly sociable and loves to be the center of attention. They are natural performers, whether on stage or in a boardroom, and their quick wit and charm make them irresistible. However, their tendency toward manipulation and deceit can sometimes get them into trouble. The Gemini/Monkey is not above bending the truth to get what they want, and their self-involvement can make them seem selfish at times.

Despite their occasional guile, Gemini/Monkeys are incredibly versatile and adaptable. They thrive in fast-paced environments and can juggle multiple tasks with ease. Their opportunistic nature means they’re always on the lookout for the next big thing, but their inconstancy can make it hard for them to stick to one path.`,
    love: `In love, the Gemini/Monkey is a charmer who knows how to win hearts. They are playful and flirtatious, but their inconstancy can make it hard for them to commit. They need a partner who is just as witty and adaptable as they are, someone who can keep up with their fast-paced lifestyle and doesn’t mind a bit of unpredictability.

If you love a Gemini/Monkey, you’ll need to be confident and independent. This person will not respond well to clinginess or neediness. Keep them engaged with stimulating conversation and new experiences, and be prepared for their occasional manipulative streak. A relationship with a Gemini/Monkey is never dull, but it requires a strong sense of self to keep up.`,
    compatibilities: `You’ll click with Aries (born March 21 - April 19), Leo (born July 23 - August 22), Libra (born September 23 - October 22), and Aquarius/Dragons (born January 20 - February 18 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Aquarius/Rats (born January 20 - February 18 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032). A Libra/Dragon (born September 23 - October 22 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) or an Aries/Rat (born March 21 - April 19 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) could be a great match. Avoid Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Pisces/Snakes (born February 19 - March 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Pisces/Pigs (born February 19 - March 20 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031), as their intensity or seriousness may clash with your playful nature. A Sagittarius/Tiger (born November 22 - December 21 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or a Capricorn/Ox (born December 22 - January 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) might also be too rigid for you.`,
    homeAndFamily: `The Gemini/Monkey’s home is likely to be a lively, eclectic space filled with gadgets, books, and conversation pieces. They love to entertain and will often have friends over for lively discussions or impromptu parties. Domestic chores, however, are not their strong suit—they’d rather be out having fun than cleaning the house.

As a parent, the Gemini/Monkey is fun and engaging but may struggle with consistency. They’ll encourage their kids to be creative and independent but may not always provide the structure they need. The Gemini/Monkey child is bright, curious, and a bit mischievous, needing parents who can channel their energy and keep their cunning in check.`,
    profession: `The Gemini/Monkey is a natural at jobs that require quick thinking, communication, and creativity. They excel in fields like marketing, public relations, or entertainment, where their charm and wit can shine. Their opportunistic nature makes them great at seizing opportunities, but their inconstancy can sometimes hinder long-term success.

As a boss, the Gemini/Monkey is charismatic but may be too lenient or inconsistent. As an employee, they are innovative and adaptable but may need supervision to stay on task. Careers in media, advertising, or entrepreneurship suit their versatile and cunning nature.`,
  },
  "Gemini/Rooster": {
    description: `The Gemini/Rooster is a fascinating mix of mental agility and meticulous organization. This person is sharp, articulate, and always ready with a quick comeback or a clever idea. The Gemini’s versatility and quick-wittedness combine with the Rooster’s precision and self-assurance to create a person who is both dynamic and disciplined.

This character loves to be in control and is not afraid to speak their mind. They are highly organized and thrive on structure, which helps temper the Gemini’s natural inconstancy. However, their tendency to be critical and opinionated can sometimes rub people the wrong way. The Gemini/Rooster is a perfectionist who expects others to meet their high standards, and they’re not shy about pointing out flaws.

Despite their occasional abrasiveness, Gemini/Roosters are incredibly capable and adaptable. They excel at juggling multiple tasks and can turn their hand to almost anything. Their self-assured nature makes them natural leaders, though their overzealousness can sometimes make them seem overbearing.`,
    love: `In love, the Gemini/Rooster is passionate and attentive but can be demanding. They want a partner who is as intelligent and organized as they are, someone who can keep up with their quick mind and high standards. They are not particularly romantic but are loyal and committed once they’ve made up their mind.

If you love a Gemini/Rooster, be prepared for their critical streak. They may point out your flaws, but it’s only because they want the best for you. You’ll need to be confident and capable to hold your own with this person, and a good sense of humor will help smooth over any rough patches. Patience and understanding are key to making this relationship work.`,
    compatibilities: `You’ll find compatibility with Aries (born March 21 - April 19), Leo (born July 23 - August 22), Libra (born September 23 - October 22), and Aquarius/Snakes (born January 20 - February 18 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Aquarius/Oxen (born January 20 - February 18 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). A Libra/Snake (born September 23 - October 22 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) or an Aries/Ox (born March 21 - April 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) could be a great fit. Avoid Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Pisces/Rabbits (born February 19 - March 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and Pisces/Rats (born February 19 - March 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), as their temperaments may clash with your need for order and control. A Sagittarius/Goat (born November 22 - December 21 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) or a Capricorn/Dog (born December 22 - January 19 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) might also be too chaotic for you.`,
    homeAndFamily: `The Gemini/Rooster’s home is likely to be impeccably organized and stylish, reflecting their love of order and aesthetics. They take pride in creating a space that is both functional and attractive, though they may be a bit pedantic about keeping it that way.

As a parent, the Gemini/Rooster is dedicated and involved but can be strict. They expect their children to be disciplined and successful, and they’ll push them to achieve their best. The Gemini/Rooster child is bright and organized but may be overly critical of themselves and others. Parents should encourage their confidence while teaching them to be less judgmental.`,
    profession: `The Gemini/Rooster is a powerhouse in the workplace, excelling in roles that require precision, communication, and leadership. They are natural organizers and can manage complex projects with ease. However, their critical nature can sometimes alienate colleagues, and they may need to work on their diplomacy.

As a boss, the Gemini/Rooster is efficient and demanding, expecting the best from their team. As an employee, they are hardworking and reliable but may clash with authority if they feel micromanaged. Careers in management, editing, or law suit their sharp minds and organized nature.`,
  },
  "Gemini/Dog": {
    description: `The Gemini/Dog is a curious mix of intellectual curiosity and loyal devotion. This person is quick-witted and adaptable, with a sharp mind that loves to explore new ideas. The Dog’s loyalty and sense of duty temper the Gemini’s inconstancy, creating a person who is both dynamic and dependable.

This character is highly observant and has a knack for picking up on details others miss. They are fiercely loyal to those they care about but can be cynical and pessimistic at times, which can clash with the Gemini’s natural optimism. The Gemini/Dog is sociable but also values their independence, needing time alone to recharge their mental batteries.

The Gemini/Dog is a natural communicator and loves to share their ideas with others. They are versatile and can adapt to almost any situation, but their tendency toward anxiety and indecision can sometimes hold them back. They need to learn to trust their instincts and not overthink things.`,
    love: `In love, the Gemini/Dog is loyal and affectionate but can be overly cautious. They want a partner who is both intellectually stimulating and emotionally supportive, someone who can keep up with their quick mind while providing a sense of security. They are not the most romantic but are deeply committed once they’ve chosen a partner.

If you love a Gemini/Dog, be prepared to offer reassurance and stability. This person may worry excessively about the relationship, so you’ll need to be patient and understanding. Encourage their intellectual pursuits and give them space to be themselves, and you’ll have a loyal and loving partner.`,
    compatibilities: `You’ll get along well with Aries (born March 21 - April 19), Leo (born July 23 - August 22), Libra (born September 23 - October 22), and Aquarius/Tigers (born January 20 - February 18 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) and Aquarius/Horses (born January 20 - February 18 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). A Libra/Tiger (born September 23 - October 22 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or an Aries/Horse (born March 21 - April 19 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) could be a great match. Avoid Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Capricorn/Dragons (born December 22 - January 19 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Capricorn/Oxen (born December 22 - January 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), as their intensity or rigidity may clash with your need for flexibility. A Pisces/Snake (born February 19 - March 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) or a Sagittarius/Goat (born November 22 - December 21 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) might also be too unpredictable for you.`,
    homeAndFamily: `The Gemini/Dog’s home is likely to be a comfortable, functional space with a touch of intellectual flair. They value their privacy and need a quiet space to retreat to when the world gets overwhelming. Their home may be filled with books, gadgets, and other items that reflect their curious nature.

As a parent, the Gemini/Dog is nurturing and protective but may worry too much about their children’s well-being. They’ll encourage their kids to explore their interests but may need to work on not being overly critical. The Gemini/Dog child is bright and loyal but may need help overcoming their anxieties. Parents should provide a stable, supportive environment to help them thrive.`,
    profession: `The Gemini/Dog is well-suited to careers that combine intellectual challenge with a sense of purpose. They excel in roles that require observation, communication, and adaptability, such as journalism, research, or counseling. Their loyalty and intelligence make them valuable team members, though their cynicism can sometimes get in the way.

As a boss, the Gemini/Dog is fair and supportive but may be overly cautious or critical. As an employee, they are hardworking and reliable but may need encouragement to take risks. Careers in education, writing, or social work suit their versatile and caring nature.`,
  },
  "Gemini/Pig": {
    description: `The Gemini/Pig is a delightful blend of intellectual sparkle and warm-hearted sincerity. This person is charming, cultured, and endlessly curious, with a quick wit that lights up any room. The Pig’s sincerity and gallantry temper the Gemini’s inconstancy, creating a person who is both lively and reliable.

This character loves the finer things in life—good food, good company, and beautiful surroundings. They are highly sociable and thrive on intellectual and cultural pursuits, but their sensual and materialistic side can sometimes lead them to overindulge. The Gemini/Pig is a natural performer, with a flair for entertaining and a knack for making others feel at ease.

Despite their charm, Gemini/Pigs can be naive and gullible, which can make them vulnerable to manipulation. They need to learn to balance their trusting nature with a bit of caution. Their hot-temperedness can also flare up unexpectedly, but their sincerity and warmth usually win people over in the end.`,
    love: `In love, the Gemini/Pig is romantic, affectionate, and deeply devoted. They crave a partner who shares their love of culture and intellectual pursuits but can also provide emotional stability. They are not afraid to wear their heart on their sleeve, but their naiveté can sometimes lead them into relationships that aren’t good for them.

If you love a Gemini/Pig, be prepared to indulge their sensual side and share in their love of life’s pleasures. You’ll need to be patient with their occasional gullibility and help them see when they’re being taken advantage of. A relationship with a Gemini/Pig is warm, exciting, and full of shared adventures.`,
    compatibilities: `You’ll find happiness with Aries (born March 21 - April 19), Libra (born September 23 - October 22), and Aquarius/Rabbits (born January 20 - February 18 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and Aquarius/Goats (born January 20 - February 18 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027). A Libra/Goat (born September 23 - October 22 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027) or an Aries/Rabbit (born March 21 - April 19 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) could be a perfect match. Avoid Virgo (born August 23 - September 22), Scorpio (born October 23 - November 21), and Pisces/Snakes (born February 19 - March 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Pisces/Monkeys (born February 19 - March 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028), as their cunning or intensity may take advantage of your trusting nature. A Sagittarius/Tiger (born November 22 - December 21 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or a Capricorn/Ox (born December 22 - January 19 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) might also be too domineering for you.`,
    homeAndFamily: `The Gemini/Pig’s home is likely to be a warm, inviting space filled with beautiful objects and a touch of luxury. They love to entertain and will go out of their way to make their guests feel welcome. Domestic chores, however, may not be their strong suit—they’d rather be hosting a dinner party than cleaning up afterward.

As a parent, the Gemini/Pig is loving and generous, encouraging their children to pursue their passions. They may spoil their kids a bit too much and need to work on setting boundaries. The Gemini/Pig child is charming and curious but may need guidance to avoid being overly trusting. Parents should foster their creativity while teaching them to be more discerning.`,
    profession: `The Gemini/Pig is well-suited to careers that combine intellectual challenge with a touch of glamour. They excel in roles that involve communication, culture, and creativity, such as public relations, event planning, or the arts. Their sincerity and charm make them great at working with people, though their naiveté can sometimes hold them back.

As a boss, the Gemini/Pig is generous and inspiring but may be too trusting. As an employee, they are hardworking and creative but may need guidance to stay focused. Careers in hospitality, media, or design suit their cultured and versatile nature.`,
  },
};
