import path from 'path';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

// Static SEO pages generated by scripts/build-seo-pages.mjs. The service
// worker must not swap them for the app shell.
const STATIC_PAGE_PREFIXES = [/^\/stats/, /^\/life-path/, /^\/chinese-zodiac/, /^\/psychic-number/, /^\/sw-cleanup\.js/];

export default defineConfig({
  base: '/',
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      injectRegister: null, // registered manually in src/main.tsx
      manifest: false, // public/manifest.json is used as-is
      workbox: {
        // Precache the app shell and first-screen code only; the large reading
        // chunks are cached on first use (below) so installs stay light on data.
        globPatterns: ['index.html', 'assets/index-*.{js,css}', 'assets/vendor-react-*.js', '*.{svg,png,ico}', 'manifest.json'],
        maximumFileSizeToCacheInBytes: 3 * 1024 * 1024,
        navigateFallback: '/index.html',
        navigateFallbackDenylist: STATIC_PAGE_PREFIXES,
        cleanupOutdatedCaches: true,
        clientsClaim: true,
        skipWaiting: true,
        importScripts: ['/sw-cleanup.js'],
        runtimeCaching: [
          {
            urlPattern: ({ url, sameOrigin }) => sameOrigin && url.pathname.startsWith('/assets/'),
            handler: 'CacheFirst',
            options: { cacheName: 'mc-assets', expiration: { maxEntries: 80, maxAgeSeconds: 60 * 60 * 24 * 60 } },
          },
          {
            urlPattern: ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
            handler: 'StaleWhileRevalidate',
            options: { cacheName: 'mc-fonts', expiration: { maxEntries: 20 } },
          },
        ],
      },
    }),
  ],
  resolve: {
    alias: { '@': path.resolve(import.meta.dirname, 'src') },
    dedupe: ['react', 'react-dom'],
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    chunkSizeWarningLimit: 2500,
    rollupOptions: {
      output: {
        // Split the big interpretation libraries into their own cacheable files
        // so an app update doesn't force everyone to re-download all the text.
        manualChunks(id) {
          if (id.includes('/src/lib/new-astrology/')) return 'data-new-astrology';
          if (id.includes('/src/lib/zodiac/')) return 'data-chinese-zodiac';
          if (id.includes('/src/lib/numerology/monthly-profiles')) return 'data-monthly-profiles';
          if (id.includes('/src/lib/numerology/personal-year-history')) return 'data-personal-year-history';
          if (id.includes('/src/lib/numerology/data/psychomatrix')) return 'data-psychomatrix';
          if (id.includes('/src/lib/astrology/')) return 'data-astrology';
          if (id.includes('/src/lib/famous-birthdays')) return 'data-famous-birthdays';
          if (/node_modules\/(react|react-dom|scheduler)\//.test(id) || id.includes('commonjsHelpers')) return 'vendor-react';
          if (id.includes('node_modules/chart.js') || id.includes('node_modules/react-chartjs-2') || id.includes('chartjs-plugin')) return 'vendor-charts';
          return undefined;
        },
      },
    },
  },
});
