
export const dog = {
    introduction: `Dear Doggie,  
Man's best buddy truly: you are truthful, loyal, and real. You provide true worth back for love. You are a nice pal—when you're feeling happy. To meet you is to like you, unless you toss out a mean remark or shoot quick jabs at us clueless folks nearby. You have a loud yap, Doggie, that makes even your worst chomp feel mild.  

But you kindly fix that. You trust in rightness for everyone and gladly pick up good fights and carry big loads against wrong rules. You honor old ways and prize respect. You find true joy in aiding an older person cross a crowded road. In life's grand cowboy tale, you surely sport a white hat.  

A sharp smart knack lets you spot tricks and chase down cheats. Problem is, this skill for honesty is so strong it sometimes makes you turn gloomy. Deep sadness and even gloom might follow.  

To guard against this drift to despair, try to hang out with fun friends whose cheer and zest keep you steady. Pair up with a bold Tiger, a dreamy Horse, or a warm, calming Cat. At a young age, you’ll start to see the world is a really unfair spot. You’ll jump into missions and aim to fix simple wrongs.  

My tip? Try not to be so stiffly proper. Welcome some give-and-take. Snuggle up here by the flames and picture brighter times.`,
    elements: {
        Wood: `With a huge heart, this Dog is very caring, gentle, and sweet. Once people figure out how to break through the Wood Dog’s tough shell, they adore him, and this time, he feels the same. Wood Dogs love meeting others. They wish to chat with all kinds of folks, grow varied friend circles, and mix with every sort of person out there. For this Dog, team fun, work buddies, and group tasks are not just okay but best.  

The Wood Dog often builds himself up. A natural edge comes from being super careful and stubbornly set. This mix pushes Wood Dogs to the top of nearly any job they pick. Plus, they’re great at managing everything, even themselves. They watch every little bit, track each task with close care, and can’t step away from hard work for long without feeling bad. This focus gives the Wood Dog a big lead in jobs needing deep study, exact plans, and pure grit.  

The Wood Dog can sniff out a phony, catch fibs, and dig up hidden stuff. He’s smart in a figuring-out way and has a firm style fit for leading. The Wood Dog has a talent for stirring crowds to big aims. This tough person holds very solid beliefs, too. Somehow, he thinks he can shift the world in just days. He won’t bend easy when pushed on a dream or value. He shows no mercy to fakes or flops and naturally knows how to pick helpers when given a big role.  

The top thing about the Wood Dog is his sense of trust. This guy can be counted on. If he says he’ll do something, you can bet it’ll happen, right when he promised, with no slack or wait. On the flip side, it’s wiser not to push the Wood Dog into stuff he hasn’t set up for. Like most Dogs, he dislikes shocks. Worse yet, he hates being caught off balance. He chases perfection and truly believes he must run every part of his (and maybe your) life to get there.  

Since this guy struggles to handle flaws, sometimes the Wood Dog loses faith in making a perfect world and quits work life way before age says to. Instead of dealing with a half-good fix, the Dog will just step away from the mess, head to the hills, tend goats, and drop thoughts of ruling all. He’s not often bitter, just settled.  

This Dog is clever, too. He has a sharp nose for the funny, a biting wit, and a gift for crafting short sayings. Bold jokers, like Alan Arkin, are often Wood Dogs. Their laughs poke at the dullness of everyday folks. They tease normal life and know how to get us chuckling at ourselves. If they pick poems or songs to share, their lines are often sharp, packed with big thoughts on people.  

Fixers love catching tricks, too. Ralph Nader built a life pointing out flaws in things we buy. His job fits a Wood Dog perfectly. He’s free yet works with a crew. He’s asked daily to judge and spot mistakes. He’s paid to be exact and honest.  

This Dog is so tender and frail, so big-hearted and loving that the only way he might dodge a breakdown is to pour his sad energy into a mission. See Shirley Maclaine’s quests and tales of mystery. Folks called her wild, but that didn’t halt her from wagging, yapping, and leaping at people till she got a crowd. Same with Kate Millett, women’s rights fighter, or Brigitte Bardot, who, though long done with movies, spends all her days and cash bettering animal lives in France. She backs pet homes, runs TV fundraisers for the SPCA, and pops up on shows to push kind care for creatures and fight hunting. Cash? She’s got plenty. Coins don’t really grab her. She’s not in it for profit. Bardot fights for the beasts.  

Wood Dogs are tender, sturdy, and charming, but with a hint of old-school ways, they often bloom late, stay choosy, and don’t dive into big romance till their mid-twenties or even early thirties. With so much warm love to give, they feel they must be super picky about where and how they share their deep, true care.  

The Wood Dog isn’t into stuff. In work and play, he’s a real plodder and worker. Yet cash flows easy to this busy soul. He toils hard, but usually not for gain, just to ease his busy mind. He thinks he should cheer up his neighbors and lift his kin to better goals by showing how. The Wood Dog, aside from his taste for judging folks too hard and his nosy streak, is a straight and able person.`,
        Fire: `Don’t bet on the Fire Dog to sit quietly still and pretty by your home’s fire. All Fire Dogs are lively. Their natural bounce and simple charm add a cute, kid-like spark to a bold spirit and make us warm up and trust them fast. Energy is the big word here.  

Since this guy is so real, serious even, we can’t help but want to hear, get pulled into his kindness, and enjoy his plain talk. “Why don’t we shield the Sahara folks? They live like long ago. Their ways should be safe.” is the kind of warm, good thought we might catch from him. Fire Dog thinking is so pure and basic you almost hope it’s true. Take my Fire Dog brother Peter’s latest smart note on the battle of men and women: “Ladies hate guys flipping TV shows all the time cause gals like to stay put, and guys love to roam.” It’s a sweetly easy take. The Fire Dog is open, and he’s spirited, but his views are often simple and off track. His good points are sweetly full of gaps.  

Fire Dogs are eager fans of their own dream lands. They can turn into lone pushers for fair but kinda basic goals. Since their listeners are usually more jaded and used to the world’s risks and twists, Fire Dogs often struggle to gather followers. Despite lots of flops in sparking big cheers for their dreams, they keep going. They trust their hopes. Really, their sky-high wishes are what pull them up each day. Every morning, they wish and plot for a nicer world. The Fire Dog is a brave dreamer who will rush into the fight and push hard for what he trusts in. We’re glad to have them around—most days.  

Sometimes, before he gets far enough against the tide, the Lone Ranger Fire Dog gets down from the tough facts he faces to hit his mark. Folks he counted on let him slip. Jaded lovers keep damping his sweet dreams. Messy games have fired him up too often. The fiery spark Fire Dog hates to lose. Yet lose he often does—even before he’s beat. In this spot, he might lift his paws and (worst case) turn to booze, pills, overeating, or some bad habit to dull the sting of loss and push-away.  

Though he lets himself slide into his own slips, the Fire Dog doesn’t have much room for his pals’ faults. The Fire Dog struggles to tame his wild spirit or get his act in line to shape his own ways. So, he’s an easy mark for clingy bad habits and must keep a sharp watch on his shaky state. When he’s mad at the world, the Fire Dog stops wanting to rein himself in and might pout or pick flaws in all and everyone near. Of course, as a Dog, he still wants to stay true to his buddies and keep faith in their basic goodness. So he often sits in a mix of mixed-up feelings. This up-and-down tug in his heart stirs inner trouble and brings aches to the Fire Dog. That hurt might quickly set him up for more risky self-soothing tricks.  

Fire Dogs make awesome reviewers, fixers, problem-solvers, and guides. They can spot a slip and find the weak spot in nearly any shield. But no matter how much they try, these hot-tempered folks can’t see their own flaws straight. They might call out “chubby” or “slow” or “tipsy” folks all around, but in the mirror, their own belly or laziness or heavy sipping magically vanish. They love the style of a sharp-dressed person and want to look good too, but they’re often stumped on trends. They feel odd in fancy gear and might even scoff at cool looks, arguing loud against fads or styles.  

Sour grapes? Not quite. It’s more a “who cares” vibe, coming from the Fire Dog once again feeling left out, misread, and mad at people.  

Though they often deal with hot tempers and short blue spells, Fire Dogs never look down. They are always friendly folks whose nice ways come straight from a true wish to help and love for others.  

Fire Dogs are driven go-getters and will push harder than most to rise and stay ahead of the group. Their real foes are: their fiery zeal, their struggle to handle how they react to wrongs, and their unlucky habit to huff, puff, and grumble.  

Since the Fire Dog is basically humble, his open anger fades fast. He thinks of others and would blush to be caught making big scenes. Still, bitterness digs deep into the Fire Dog’s warm little heart and muddles his knack for letting go.  

His recall for details is amazing. He can tell you what shirt his mom wore the night she skipped tucking him in and which shelf hid the candies at the summer cabin his kin borrowed in Maine. Yet this guy’s memory, like much of his makeup, rests big on heartstrings. He remembers the day he missed a tuck-in and recalls losing sweets. But the happy times might slip away.  

Since his deep feelings make the Fire Dog sense things so strong, he often soaks up the darkest bits of any moment. By grown-up years, the hurt might grow too big, and the Fire Dog might turn into a top-notch downer and Sad Sam. He must, for sure, fight this pull to see all in shadows and should stick with calm, bright, cheery folks whose feelings match his. He should also settle in quiet green places so kind Mother Nature can always ease his tender nerves.  

Fire Dogs aren’t quick to bend. They should dodge contests, power games, or trade deals. They aren’t super skilled for smooth talk or tough deals since they wrestle with greed and half-steps.  

Good jobs for the Fire Dog lie in healing or teaching, writing, or tunes. Though the shady ups and downs of showbiz might test the Fire Dog’s core kindness, he’s got a knack for speaking deep and can shine big on stage. Behind-the-curtain roles fit this touchy soul: he’ll make a top sleuth writer or quiet detective. Law or leading, as long as the fierce Fire Dog isn’t asked to haggle deals, give him a great shot to speak out on missions and use his fixer spirit.  

In love, the Fire Dog sees himself as the top one. He’s usually not bold or bossy in romance, though. He’s a careful type and always checks for hints of drift in his sweetie. In bed and out, he loves to be teased and wooed. Once in love, he’s soft and warm. His fretful yet kid-like outside doesn’t even hint at the wild passion he can let loose when sparked right. He’s not meaning to cheat. But he’s often mighty tempted to wander. The Fire Dog is a born love bug who needs steady comfort. Tell him often he’s cared for, and he’ll stick to you like glue on a post.  

Lively, free, and true to the end, the puzzling mix of the odd bold yet shy Fire Dog promises never to dull you.`,
        Earth: `The Earth Dog is quiet. Like other Dogs, he might trust in missions and push for fairness, might hope for a nicer world, but the Earth Dog isn’t a hothead. He’s calmer and more easygoing than his fellow Dogs, more careful and peace-seeking. Thanks to his sharp senses, the Earth Dog is quick to feel shifts in the breeze and can’t miss even the tiniest change around him. He’s super picky. His keen instincts catch the smallest jab or snip, giving him real heart pain. When he’s stung, he walks around in a steady wince. He’s so sensitive and breakable he’d rather stay out of the glow.  

Earth Dogs are artsy and soft, made to live in the wildest green lands, circled by plants and pets. They need a shield from harsh truth and do best with gentle pats and a safe feel.  

The Earth Dog is a maker who shines alone. Again, due to his finely tuned nerves, he has to store up strength, which he does by soaking in nature, keeping clear of crowds, and dodging the rush. Look at Michael Jackson, a star and live-wire on stage for sure, but fragile, lone, and open. He cuts a song or clip and slips back to his California hideout where he stays solo, with critters, helpers, and playthings as his only pals.  

Notice, too, that the list of big-name Earth Dogs is pretty slim. Dogs touched by the Earth often stick to quiet jobs forever. They surely aim for cash wins, and they might keep low, but they aren’t timid. Instead, the Earth Dog is naturally chill and super private. He wants his close moments to stay close and his messes to stay tucked away. If a loud career risks his quiet life, an Earth Dog might pull back for good.  

Since Earth Dogs usually skip the big buzz, they can float, watching how others roll. This gives them a great launch pad to kick off a path as a writer or news hound, peacemaker, or rule-setter. I’d bet not many Earth Dogs mess with power games, as they don’t like or stand for fake talk and fluff. The Earth Dog might turn into a fine builder or style maker, room fixer, or picture-taker. He gets the fine points of people’s ways and, as he’s naturally fresh, he’ll craft works of warmth and grace. Earth Dogs make top thinkers, too. If they turn to doctoring, they’ll likely thrive in study labs.  

This hushed, deep soul is also famed for his charm. Though he might not always flash it, the Earth Dog can sweet-talk leaves off branches. He’s shy, steady, and knows how to hear. He’s kind and gets other, busier, twisty, talky folks. The Earth Dog is real bendy of mind and, for a firm Dog, pretty ready to tweak his ways to match any spot.  

Like all Dogs, the Earth Dog can snap out sharp words when you least guess. Yet thanks to his soft heart and basic goodness, his words are less mean and rough than those of his kin Dogs. If he bites at all, the Earth Dog will likely make his point softly, hiding his sharp edge by nudging your neck or patting your bare legs.  

The Earth Dog is a homebody. He puts heavy thought and care into the happiness of his own clan. Always the helper of the kid who lost his ride or skipped his tasks, this guy makes a great teacher. He naturally knows how to blend big-heartedness with a steady push. He adores kids and tends to hold tight views on birth control and choice.  

Last, the Earth Dog is a jumpy, edgy person. He’s not often cranky, but when he is, he craves quiet, alone time, and rest. His body woes often tie to his slow belly, as he’s not exactly a zippy Dog. He should be nudged to munch lots of greens and fiber, sip tons of water, and get heaps of fresh-air play. If he tends his tender nerves and minds his meals, this guy can live to a grand old age.`,
        Metal: `This is the Dog who aims to fix the world—at least his own patch. He’s firm-minded plus big-hearted and giving. He’s a bold, noble soul whose only point for being here is to hunt the perfect prize. Metal Dogs live for their own quests. They’re clear, eager, orderly, and strict. They don’t buy into fights or chaos, feeling calmer, kinder ways can and do win. They reach for a dream with a drive that stuns the heads of less keen, less set folks.  

Oddly, though they sometimes seem hard to reach, Metal Dogs want more than anything to be known, loved, and looked up to by their crew.  

Metal Dogs are the sort most likely to nab a top award, scale a huge peak, find a fix for a skin itch, or reshape a land’s rules. They’re not just tireless chasing a high aim; they never quit, even holding a long grudge. They’re folks of big swings whose targets are rarely small or mild. When he hunts change, the Metal Dog won’t take less than a total flip.  

Metal gives a kinda me-first streak to this Dog. He can and will do grand things. He’s open and even sweet, but he wants the gains he earns through his own sweat to carry his mark and show his trusts. He’s deeply sure his dreams are finer, his goals more right, and his ways more solid than those of less able sorts.  

Metal Dogs get the need for teamwork. Most Dogs like going solo, but the Metal Dog won’t shy from close ties, especially ones that might speed him to his aims. He’s not scared to set his will on others and can build a work squad and keep it rolling as a unit to push his cause. He’s born with top smarts and can dig up fast, bright fixes to nearly any snag he hits. He’s me-focused and not past getting a smug buzz from the praise, nods, and claps of his work mates.  

He’s often wanted as a pal, teammate, or party guest. When it’s about big stuff, the Metal Dog is almost too deep a talker. Yet he doesn’t skip light chat with Madame La Comtesse, whose main worry might be her pup’s bare patch. He’s a high-driven, truly giving soul who can be leaned on to pitch in as he only wants to do right by all.  

As a parent, the Metal Dog can shine bright. He sticks to plans and naturally knows how to steer a home well. He’s me-first without being grabby. Kids won’t just gain from his big spirit and feel a grounding pull from him, but will never doubt their own worth. The me-focused Metal Dog doesn’t question his own or aim to dim his kids’ sense of self.  

Despite a deep care for others, this guy can be sharp and even harsh on weak spots he spots in outsiders. But his high-and-mighty air fades as, with years, the Metal Dog grows softer and milder. It’s young Metal Dogs who are so loud and stern with their peers, kin, and “the rules.” School heads often clash with Metal Dog kids, as they’re bold to call out plans or dislike strict moves. Since they’re usually top learners, the head might be stumped by this outspoken kid’s stand-off ways.  

Once he’s grown, though, self-control is a trait the Metal Dog handles easy. He can dive into law or healing or take up any thinker’s path as he can focus for hours on thick, dull pages the rest of us might hate even lifting off a shelf.  

To chase his aims, wrap up his learning, and climb to ever-higher spots, this guy needs to feel safe. He might stay home till thirty or set up a place young with a pal or sweetie. His crave for home order is key. The Metal Dog is a picky but true lover and mate. He won’t let home fights or fuss pull him from his trust or goal. He wants a calm, steady life and will stop at nothing to lock it down for him and his clan.  

Sometimes the aims of this driven heart rule out a family. Take Mother Theresa, whose call to aid the poor fills her days full. She smartly picked the safety and rhythm of a faith life: home life for such a driven giver would be too tough.  

There are few “famous” showbiz Metal Dogs, who never settle for the empty cheers of cash or fame alone. Metal Dogs want to hit big marks. Some, like Jacques Cousteau, Akira Kurosawa, Andre Agassi, and Sean “Puff Daddy” Combs, might’ve used the spotlight to share their plans and dreams, but they don’t just wish for a shiny, hollow star life. They aim to touch the whole earth.  

Thanks to his pull to go all-out, the Metal Dog often wrestles with up-and-down feelings. He might be chipper and playful one tick but the next drop into a pit of gloom. He needs folks to prop him up, cheer, and praise him in tough times as he might lose trust in his aim and need a morale lift before jumping back in.  

The Metal Dog has huge wonder and must dig to the root of whatever he takes on, checking every bit till he knows the real deal. Nothing slips this guy’s wide pull of sight, making him a detail nut, always sniffing around, hunting hints, and wildly shaping order from mess. When you pair the fixing giver with the snoop, you’ll see the Metal Dog makes a standout law keeper, sleuth, crime pro, or digger.  

Though he’s usually lean and long of build, the Metal Dog loves to eat hearty. He savors top-notch eats and is often a careful cook himself. He’s set on top quality yet cares little for cash piles or wins. If coins are there, he’ll know how to spend smart, grabbing only the best goods, dining at prime spots, and wearing fine, lasting threads. If he’s got no cash, the Metal Dog can still find a way to live comfy and proper. He might mingle, but he doesn’t give a lick what folks think of him or his yard’s shape.  

The Metal Dog is often a big talker. He’ll launch into a tale, tossing in bits and side stories, yapping with pup-like glee through twists of stray points. He very often (yawn) loses his listeners in a flood of loose details. The only fix for this quirk is to clock his chats, then tell him they run too long. He loves exactness and dreads looking silly. If you note his talk on old fish lasted sixteen minutes and thirty-five ticks, he’ll catch on quick. If that still flops and your top Metal Dog won’t stop droning, grab a debate rule book and a loud stopwatch that rings when time’s up. The Metal Dog loves order. He’ll fall right into the debate bell’s trick, and you might get table chat that doesn’t stretch from starters to sweets. If that still fails, drop me a note, and I’ll try to dream up a stricter fix.`,
        Water: `There’s a quirky crew for you. A big batch of writers, a sprinkle of tune-makers, lots of actors and actresses, a pair of movie bosses, and even a couple of power players—bright stars, all of them!  

The watery kind of Dog is tricky to know. Not only are they cool and distant when they first meet you, but they might even growl and flash their teeth. Bold? Yep. But the Water-born Dog is also gentle. He takes charge for those he feels life has hit hard, soothing their hurt feelings and boosting their own basic worth. He’s a “softer” type, milder and gentler than his fellow Dogs, able to show and grasp even the trickiest feelings.  

The Water Dog’s power sits in his knack to break down and blend info into art. He’s got a born gift for neatly sorting the leftovers of people’s ties into a bowl and baking them into a tasty, sharp, and fun treat. He’s a Dog, so he’s naturally super tuned-in. Yet he stays grounded and tough enough to hold up under push or knocks. His task here is to teach us to giggle, weep, feel, hurt, or wake up under the pull of his deep art work.  

The Water Dog never skips a beat. He’s born with skills that let him peek around bends, grab thoughts before they’re said, or catch a noise long before it hits our dull ears. Thanks to this extra sense, in a chat, he might seem to float off short into some hidden spot.  

Funnily, if the Water Dog weren’t so skilled as an artist, we might not spot him. He shows such a far-off air he might seem uncaring. The edge we sense in him usually comes from too much caution. Since he never feels sure of others and doubts new faces, the Water Dog might act distant out of care. He’d rather skip empty chatter, so he opts to stay apart. He’s watchful, but he’s not short on self-trust. He’s just born with a quiet, held-back way.  

Weirdly, once you know the Water Dog and turn into his tight pal, he almost never stops yakking. All Dogs have great recall for tiny bits, but this one’s a geyser of small stuff. He doesn’t just tell how he met his first flame; he spills it like a deep-dive reporter might track a growing cell over a day. He kicks off, “There we were at the thirty-seventh line at fourteen minutes and thirty ticks past seven. He wore a tan vest over a bluish soft shirt. His pants were rough weave, the kind with bumpy twists, not the angled sort. The air was muggy and warm, and he was sweating at the sides. A plane flew over. One motor sounded off. Maybe it was skipping or choking…” Water Dog lead-ins are wildly detailed. It feels like he’ll never hit the end.  

As a buddy, he’s warm and friendly, helpful, and giving. He dives into all you do and never drops a speck of your smallest worry.  

The Water Dog is a fair soul whose hot wish to see right done sometimes makes him poke in. You know how it goes when a kind-hearted type steps up for you when he thinks it fits and ends up catching a heap of flak. The Water Dog often gets this unfair payback. No matter how touchy the spot, the Water Dog can’t fight the urge to jump in with friendly meddling. Water Dogs make awesome, true pals, but they’re not slick peace-weavers, deal-makers, or smooth-talkers. They flash their growl before hearing the other side’s tale.  

These pretty beings are super alluring. Early on, tons of their time goes to wooing and bedding lovers. Since they’re Dogs, they do aim to stay true. But sometimes they can’t resist flaunting their tasty charm on someone fresh. Cheating brings the Water Dog awful guilt, which feeds his born gloom. His best move is to dodge the pull of side flings since his feeling frame is pretty frail, and too much guilt can drag him to dark lows.  

The Water Dog is never mean or nasty. Though he sometimes acts out his upset with a snap, he hardly ever breaks rules or swings fists. He doesn’t hunt excuses for his rare slip-ups. He’s a straight dealer, owning his faults and making up for them by crafting fine art, doing good deeds, and always hauling his load of the group deal.  

Another standout trait here is looks. We can’t help but see it. Male Water Dogs are sharp and classy. Their lady kin are stunningly pretty, mixing a crisp face shape with a moving hint of ache. Water Dogs try to live with grace, circling themselves with fine things and savoring nature’s gifts. Water Dogs are busy, but they’re also deep thinkers. They rarely jump before they peek. They push hard and hit big wins without fake swagger or self-pats. Water Dogs will spend a long, wild youth hunting a life mate and are likely to wed folks way older than them.`,
    },
    compatibilities: {
        "Rat": "This is a potentially happy marriage. Providing the cards are played fairly, Rat and Dog can be more than satisfied in each other’s company. But be prepared for long, heated discussions sorting out political, social and financial differences of opinion. The materialistic Rat can find it difficult to reason with a generous Dog. The Dog gives money away, sometimes forgetting to save enough for the rent. Dogs can’t resist the opportunity to salvage the needy. The Dog’s stability depends on being seen as the philanthropic good guy. Rat does not agree. He’s the hoarder, ravaged by anxiety about savings, unable to understand his puppy-faced mate’s desperate need to give it all away. Disagreements abound. But as each half of this couple feels deeply passionate about the other, true harmony is possible. The Dog’s love is unconditional, offering a gentle cradle for the Rat’s frenetic soul. The happiness you find together in and out of bed will be enhanced by the arrival of scads of kids and pets whom you will nurture and raise together as a team.",
        "Ox": "Don't expect the loyal Dog to bay at the moon out of blind love for an Ox mate. They have polarized goals. Dog’s job—pleading a case for the homeless in Alaska—is bound to take priority. And, the Ox? He will be going to bat for a major corporation and grossing 50 per cent of the winnings. These two are so different in their philosophies that mini-battles form craters in their living room carpet. Despite a gentle, loving nature, a puppy Dog, graced with lucidity, knows that this is a Dog-eat-Dog world, yet believes only in justice and equality. The Dog wants no part of the Ox’s haughty domineering and answers only to the call of the wounded. The Ox believes that charity begins at home and will beg Doggy to leave the world’s problems behind. Both are devout moralizers. But they don’t see eye to eye: the Dog argues about starving children in India, trying to sway the Ox to contribute to the noble cause; the Ox fights for justice at home, complaining that the money used on creating a shelter for the homeless last month was really meant to pay for the children’s private school. Sex between them can be fun! This is the only place where an Ox's roll over command has clout. The Dog is tickled by and admiring of the Ox’s relentlessness and brutally frank style in bed. This is just an okay marriage. No sexual fireworks or undying passion will hold these two very different people together.",
        "Tiger": "Harmony incarnate. Dogs and Tigers just plain get along. They have common causes and common philosophies. But they are very different. The Tiger is overly optimistic, the Dog pessimistic. Each helps the other to understand these basic character differences. The Chinese call this pairing a happy alliance of muscle and heart. The Tiger has the strength to put the Dog’s ideals across to the public. The disquiet Dog keeps watch and prevents the Tiger from leaping into the wrong frays. They are, simply, a great couple. Harmony reigns right from the start. And because Dog and Tiger respect each other’s deepest convictions, mutual admiration sticks them together like super glue. In bed, the Tiger usually takes the lead, which is felicitous for the tense, nervous Dog, who often needs to be thawed out before engaging in any heavy intimacy. With time, this couple learns to blend eroticism with affection to achieve physical fulfillment. It is rare that such a marriage ends in divorce.",
        "Rabbit": "In Chinese astrology, Cats and Dogs traditionally get on with each other. Although sexual intimacy is not the most salient point of contact here, companionship is. Everybody knows how important companionship is to animal Dogs. Cats like to be safe and well housed too. This couple’s marriage is based on profound mutual affection and respect for each other’s opinions and aesthetic choices. Both Cats and Dogs have a marked tendency to mood swings. Both are critical and easily discouraged by the realities of everyday life and its various injustices. Although Dogs are more pessimistic, Cats can be testy and crotchety when the chips are down. Their complicity will be based largely on their mutual mistrust of human nature. Their shared cynicism is their consolation for putting up with an imperfect world. Both parties are dutiful and unafraid of working hard. Money should not be an issue. Mutual participation in professional and paraprofessional projects will lend strength to their union. The Dog’s spontaneous expressions of lapping affection might get on the Cat’s taut nerves. But one thing is for sure: the Cat can depend on the Dog’s loyalty which, in the cautious Cat’s heart, counts for a lot.",
        "Dragon": "Polarized outlooks might find happiness, providing the sex is sensational. But with the Dragon/Dog duo, this is plainly not the case. According to Chinese astrologers, few relationships are less likely to withstand the test of time. Dragon/Dog bickering and barking prevail. Dragons and Dogs are full of enthusiasm, energy and vigor. But their styles are so different as to make them near enemies. Dogs hate making a fuss over nothing. Dragons intentionally create daily scenes complete with flames, smoke and noise. Dragons deem the moralizing, pessimistic, stern Dog a downright bore. Dragons live primarily for themselves. Dogs live for others. The Dragon will wish the Dog a more obedient mate. But the freethinking Dog will never buckle under to oppression. While the Dragon boasts of successes, the Dog gloats over his or her mate’s resounding failures. I have to agree with the Chinese soothsayers. Dissonance reigns. No marriage here please.",
        "Snake": "This partnership is lopsided. We are dealing with two disparate types of people. Dogs are pessimistic, given to depression and worry. Snakes are naturally relaxed, less anxious, and certainly less sarcastic. Sometimes the doubting Dog even mistrusts a pet Snake’s charm and will whine and snap about it, criticizing the Snake for both frivolity and an easygoing nature. Basic personality differences do not have to destroy relationships. But the Dog hates society, has few friends and stays at home a lot. Snakes are just the opposite, yet need a home to go back to after their numerous forays into the big world. Returning to the cozy Dog home after imbibing a faceful of society’s cupidity can be refreshing for the sociable Snake. Even though they snarl and threaten, Dogs always forgive, are loyal to a fault and never waver in their devotion to their loved ones. Both parties are sensitive to causes, feel strongly about combating injustice, and believe in right over might. This similarity of purpose can serve to harmonize their relationship and round out some potential hard edges. The problem is, their sexual selves are very different. Dogs are physically conventional and direct. Snakes are highly adventurous in bed and enjoy intricate sexual play. The two may not clash over this issue, but the Snake may eventually get bored, resume a natural bent for flirting and irrevocably damage the Dog’s tender-hearted soul.",
        "Horse": "If this pair hires a nanny and a housekeeper, a laundress and a cook, they can establish a very sound love relationship. Neither these two effective, active, project-oriented people is enchanted by a career as a house drudge or nose-wiper, staying at home waiting for the other to appear. Horses are characteristically profligate with money. They gamble away and take chances others would not. This risky trait fills the disquiet Dog with fear. The Horse hates to be reminded of profligacy but the sarcastic Dog cannot keep quiet for long. Fights—yes, I said fights—ensue. As harmony reigns in their bedroom, these two usually end up being friends after vibrant lovemaking sessions wherein each lavish pleasure on the other. The Dog is giving and the Horse is loving. It’s a good sexual match. The lovemaking may be salutary, but what will ultimately hold this pair together is their deep respect for each other’s integrity. They are mutually honorable people with a refined sense of social and loyalty. Time will round off whatever sharp angles this pair encounters. A durable, solid relationship is assured.",
        "Goat": "Not much love is lost between these two. The Dog is all moral standard and high-mindedness. Very often, the Goat’s ideals begin and end with where the next meal is coming from. Goats are on the side of the person carrying the wallet. Dogs deplore pandering. Goats know no other way of life. As a couple, unless the Dog decides, uncharacteristically, to shoulder the burden of changing a poor misunderstood Goat whom he or she believes to be a hidden genius, they will be two very different people going in opposite directions. The Dog likes things to be clear, just and fair. The Goat doesn’t even know what those terms mean. Goats are dreamers whose ephemeral plans often go up in smoke. Dogs dream too, but their dreams are founded in concrete and seek real solutions to real problems. Goats, of course, love sex and favor open relationships wherein they have full freedom. Dogs wouldn’t think of being disloyal. They may stray—but only for a minute or two. To a Dog, devotion and loyalty come first. To a Goat, blind devotion and loyalty are for fools who don’t know which side their bread is buttered. It would be too optimistic to expect harmony from this essentially unbalanced romantic equation.",
        "Monkey": "The Dog is a blazing idealist. The Monkey lives for the opportune moment. They may well meet up and fall in love when engaged in a social struggle together. Each possesses qualities lacking in the other. Although this might make them seem perfectly matched, it takes more than dovetailing qualities to make two such impervious individualists communicate. Each is so accustomed to living on his own wavelength that they have real trouble shifting gears to make themselves understood to someone on another plane. The remedy is talk. These two nervous souls must sit and yammer for hours, days and months before they reach comprehension. The Dog will have to give up blurting nasty remarks and the Monkey must accept being tethered for at least part of the time. Although they can be guilty of it, Dogs don’t take kindly to philandering. But Monkeys like sexual freedom. Monkey seems carefree and Dog laughably frustrated. Being of basic good intention, if they wish to stay together, this pair can work out a harmonious sex life together. This relationship’s harmony is possible but will not be won without effort. Unless the union is inevitable, I advise imagining it can work forever.",
        "Rooster": "Incompatibility reigns supreme in this couple. Dogs and Roosters are equally flinty and raw-nerved. Dogs are forever blurting criticism and bruising the egos of those around them. Roosters are cocky but deeply unsure of themselves. One yelp from the Dog’s storehouse of biting blatancies can put the Rooster under for days, depress him and undo his hard-earned image. Do these people fight? They never stop. Backbiting, carping, bickering over details. They don’t agree on anything. Dogs are classically left wing, kindly and trustworthy. Roosters are born conservatives who believe in the system, adhere to society’s basic tenets and cleave to traditional ways. This couple’s home life is a constant push-me pull-you of political unrest. Dog wants revolution. Rooster devoutly wishes for status quo. Dog thinks mismatched china and a pallet on the floor will do nicely. Rooster wants Spode or Limoges set with crystal grasses on an heirloom table. Dog wants to spend money on causes. Rooster wants to keep his money in the bank. Rooster demands more and varied sex than Dog has to give. Rooster needs to puff up his ego and preen his feathers. Dog couldn’t care less what he looks like in bed. He feels sex rather than performing it. Besides, Dogs are slightly puritanical. They don’t believe one should overindulge in pleasure. Leave the Rooster/Dog love relationship alone.",
        "Dog": "Seriousness and anxiety could cloud the union darkly between two Dogs who want to live together as a team. There exist, of course, areas of mutual understanding regarding causes and social ills, justice and humanitarian issues. But their abrasive Dog personalities and incessant caustic remarks could make pain the order of the day. There is however much reciprocity here. There are, after all, many breeds of Dog. One type of Dog will always help the other with everything from grocery shopping to projects. There are few, if any, artificial barriers about who is male or female and which tasks befit either. Both have respect for the other’s time and an understanding of his partner’s desire to be effective in the world. Trouble crops up in this relationship because of an age-old enemy—boredom. Both Dogs will be hyper-puritanical, chronically anxious, guarded, skeptical, cynical, critical and lacking in joy and lightheartedness. Life around the Dog house could be Gloomy Gus City. Stodgy moralities will be the rule rather than the exception. Self-righteousness will be knee-deep. But… if one Dog happens to be a Labrador and the other a Doberman—maybe a certain barking order will be established and the two Dogs can make a go of it. There is not much natural chemistry between Dog born people, so the act of love will be healthful but unimaginative. Intimacy frightens Dogs; they mistrust closeness. A second Dog sniffing behind them for a quick pop in the grass is about as much this couple can expect to have in bed.",
        "Pig": "Intimacy between Dog and Pig people promises great enduring love, respect and passion. The Dog and Pig are complementary in thought and feeling. They both believe in the basic good of humankind. They both love the countryside and adhere to sanity as a fine way to live. Mind you, there are some basic differences to contend with: Pigs love opulence while Dogs couldn’t care less about luxury. Pigs tend to be conservative; Dogs are liberal. Pigs are sensualists—there’s nothing they love better than a good dirty story—while Dogs are puritanically-inclined. But all these differences are worked out between the Dog and Pig because they are each willing to respect and even admire the other for their individual tastes and preferences. Dog loves the cozy security Pig provides and Pig sees Dog’s politically active friends as perfect guests. He feeds them to death. Pig may at first be flummoxed by the Dog’s seeming sexual indifference. But Pigs have clever (sometimes devious) ways of getting people’s attention, and will always find a way to their Doggie’s heart. Pigs are infinitely patient. They know how to bide their time and cajole until they get what they want and need out of their cranky, but basically sweet-tempered Dog partner. Providing they husband and promote their mutual talent for goodwill, this pair will be blissfully content for a very long time.",
    },
    futures: {
        "2025": { "year": "Snake", "element": "Wood", "prediction": "This year, the philosophical Snake will make you anxious. The Snake’s tendency to speak in riddles will try your patience, and his love of luxury will strike you as downright wasteful. Dog years are frugal; Snake years are not. You may feel a bit out of place amid all the elegance and high-mindedness. You are likely to become embroiled in disputes with family or colleagues this year. Try to be less critical. Your frankness is not always appreciated, especially by the sensitive Snake. My advice? Spend more time alone this year. Take up a new hobby or learn a new language. This is a good time for personal growth. Travel is not particularly favored, so stick close to home and focus on self-improvement. Your love life may be a bit tumultuous. Be wary of making any long-term commitments. Wait until next year, when the atmosphere is more favorable for Dogs." },
        "2026": { "year": "Horse", "element": "Fire", "prediction": "The Horse is your ally. This year will be a dynamic one, full of activity and progress. You will feel energized and motivated. It’s an excellent time for new ventures, career changes, or moving to a new home. The Horse’s practicality and your sense of justice make a powerful combination. Together, you can accomplish great things. However, the Horse’s independent nature means you won’t have to worry about being smothered. You will both respect each other’s need for space. Financially, this is a promising year, but be cautious of the Horse’s tendency to take risks. Your conservative nature can provide a good balance. Romantically, it’s a passionate time. If you’re single, you may meet someone who shares your ideals. If you’re in a relationship, it will be a period of renewed excitement and deep connection." },
        "2027": { "year": "Goat", "element": "Fire", "prediction": "This will be a challenging year for you. The Goat’s whimsical, artistic nature clashes with your down-to-earth practicality. You may find the general atmosphere of the Goat year to be frivolous and unproductive. You believe in hard work and tangible results; the Goat believes in inspiration and dreams. This fundamental difference will cause friction. You may feel that no one is taking things seriously, and your attempts to instill order will be met with resistance. It’s best to avoid major conflicts. Focus on your own projects and don’t try to change the world—or the Goat. Your love life may also feel a bit unstable. The Goat is fickle and requires constant admiration, which you may find exhausting. Patience is key. If you can tolerate the Goat’s capriciousness, you’ll get through the year unscathed. It’s a good time for introspection and planning for the future." },
        "2028": { "year": "Monkey", "element": "Earth", "prediction": "The Monkey’s cleverness will both fascinate and irritate you. While you admire the Monkey’s ability to solve complex problems, you’ll be wary of its cunning and sometimes deceptive tactics. This is a year of intellectual stimulation. You may find yourself engaged in lively debates and strategic planning. However, the Monkey’s love of games and tricks can make you feel insecure. You prefer honesty and straightforwardness. To navigate this year successfully, you must rely on your strong moral compass. Don’t get drawn into the Monkey’s schemes. Professionally, it’s a good time for collaboration, as long as you can keep the Monkey focused on the task at hand. Romantically, it’s a playful period. The Monkey’s humor can be a refreshing change, but its lack of seriousness may frustrate you in the long run. Keep your wits about you, and you’ll find this year to be both challenging and rewarding." },
        "2029": { "year": "Rooster", "element": "Earth", "prediction": "This year is fraught with conflict. The Rooster’s vanity and your idealism are a recipe for disaster. You will find the Rooster’s need for constant praise and attention grating, and the Rooster will be deeply wounded by your sharp criticisms. Expect arguments over everything from politics to decorating. You believe in substance; the Rooster believes in style. This is a fundamental clash that will be difficult to resolve. Financially, it’s a tense time. The Rooster is extravagant, while you are frugal. Money will be a constant source of disagreement. In your professional life, you may find yourself at odds with superiors who value appearance over performance. It’s a frustrating period, and you’ll need to draw on all your reserves of patience. Your love life will be equally stormy. The Rooster’s possessiveness will make you feel trapped, and your need for independence will be perceived as rejection. It’s best to keep your distance and avoid making any major decisions this year." },
        "2030": { "year": "Dog", "element": "Metal", "prediction": "This is your year to shine, but it’s also a time of great responsibility. You will feel a strong urge to fight for justice and right the wrongs of the world. Your leadership skills will be in high demand. However, be wary of becoming too self-righteous. Two Dogs together can create an echo chamber of pessimism and anxiety. Surround yourself with optimistic people who can provide balance. Professionally, you will excel in roles that allow you to advocate for others—law, social work, or politics. Financially, it’s a stable year, but your generosity may be tested. Don’t let your ideals lead you to financial ruin. Romantically, if you’re with another Dog, you’ll find deep companionship and understanding. However, the lack of lightheartedness can become oppressive. Make a conscious effort to have fun and enjoy life’s simple pleasures. This is a year for making a difference, but don’t forget to take care of yourself." },
        "2031": { "year": "Pig", "element": "Metal", "prediction": "This is a harmonious and prosperous year for you. The Pig’s good nature and your loyalty create a wonderful synergy. You will feel supported and appreciated, which will allow you to thrive. The Pig’s love of comfort and your practical nature will lead to a beautiful and secure home life. It’s an excellent year for family and friendships. Professionally, you will find success through collaboration. The Pig’s luck with money and your hard work will lead to financial gains. It’s a good time to invest, especially in property. Romantically, this is a blissful period. The Pig’s sensuality will help you to relax and open up emotionally. Your devotion will be deeply appreciated. This is a time of peace, love, and contentment. Enjoy it." },
        "2032": { "year": "Rat", "element": "Water", "prediction": "Though you and the Rat can find common ground, this year will be a test of your patience. The Rat’s ambition and desire for power will clash with your idealism. You may find yourself in situations where you have to compromise your principles for the sake of progress. This will be difficult for you. Financially, the Rat’s acquisitiveness can lead to risky ventures. Your cautious nature will be a valuable asset in preventing disaster. It’s a year for careful planning and avoiding impulse buys. Professionally, you may feel that your hard work is not being recognized, as the Rat takes credit for group efforts. Stay true to your values and don’t get discouraged. In your love life, the Rat’s need for excitement can be draining. You crave stability, while the Rat seeks novelty. Communication is key to navigating these differences. It’s a year of challenges, but also of growth." },
        "2033": { "year": "Ox", "element": "Water", "prediction": "You will feel frustrated and constrained by the Ox’s rigid and authoritarian nature. Your desire for justice and fairness will be met with the Ox’s unyielding adherence to tradition and rules. This is a year of ideological conflict. You will want to fight for the underdog, while the Ox will defend the status quo. Professionally, you may find yourself in a stifling environment where creativity and independent thought are discouraged. It’s a time to lie low and avoid confrontation. Financially, the Ox’s conservatism means it’s not a year for growth, but it is a time of stability. Don’t expect any windfalls, but you won’t face any major losses either. Your love life will feel dull. The Ox’s lack of romanticism and your need for emotional connection will create a distance between you. This is a year for patience and perseverance. Endure it, and better times will come." },
        "2034": { "year": "Tiger", "element": "Wood", "prediction": "This is a year of great synergy and mutual respect. The Tiger’s courage and your loyalty make for a powerful alliance. You will be inspired by the Tiger’s optimism and energy, and the Tiger will be grounded by your practicality and wisdom. Together, you can achieve great things. Professionally, it’s a time for bold moves and new ventures. Your combined strengths will lead to success. Financially, it’s a prosperous year, as long as you can temper the Tiger’s impulsive spending habits. Romantically, it’s a passionate and fulfilling time. You will find a deep connection with your partner, based on shared ideals and mutual admiration. This is a year of action, adventure, and achievement. Embrace it with open arms." },
        "2035": { "year": "Rabbit", "element": "Wood", "prediction": "This is a year for quiet companionship and mutual support. The Rabbit’s gentle nature will soothe your often-anxious soul. You will find comfort in a peaceful and harmonious environment. Professionally, it’s a good time for working behind the scenes. Your loyalty and diligence will be appreciated, even if you’re not in the spotlight. Financially, it’s a stable year. The Rabbit’s prudence and your own caution will ensure you have a secure nest egg. Romantically, you will enjoy a deep and affectionate bond with your partner. It’s a time for quiet evenings at home and for enjoying each other’s company. This is a year for finding peace and contentment in a stable and loving environment." },
        "2036": { "year": "Dragon", "element": "Fire", "prediction": "You will find the Dragon’s flamboyance and ego a bit much to take this year. Your down-to-earth nature will clash with the Dragon’s need for constant adoration and spectacle. It’s a year of potential conflict. Professionally, you may find yourself at odds with a powerful and charismatic leader. Don’t be afraid to speak your mind, but do so with tact and diplomacy. Financially, the Dragon’s extravagance will make you nervous. Stick to your own budget and don’t be tempted by risky schemes. In your love life, the Dragon’s passion can be exciting, but its self-centeredness can be hurtful. This is a year for standing your ground and for staying true to your own values, even in the face of overwhelming pressure." }
    }
}
