
export const tiger = {
    introduction: `Honorable Tiger, noble and fearless, you are respected for your courage and simultaneously feared for your ferocity and persistent lack of moderation. Like a raging river, you constantly overflow your boundaries. Where are you rushing to with such haste? Can you not take just one tiny glance before you pounce? Try to slow down; practice a little restraint. Stop being so devastatingly attractive; it is exhausting.

Of course, some individuals find you so daring and spirited that they wish to join you and experience the adventure. But you, dear Tiger, are a daring solitary individual. The top is the only place you desire to be. You actively seek danger. The more formidable the adversary, the more dramatic and catastrophic the situation, the broader your Tigerish grin becomes. Your unpredictability, disregard for rules, self-sufficiency, and carefree swagger could ultimately be your downfall.

In matters of the heart, you are excessively demanding. However, you are certainly not dull. You get along best with devoted Dogs, independent Horses, and complicit Dragons also find loving you quite delightful. Monkeys admire you, but remember—Monkeys can be cunning. Whatever you do, do not become involved with a tempestuous Tiger like yourself; you are lucky, but not that fortunate.

You will navigate your youth with ease. But by the age of thirty-five, the excesses of half a lifetime may begin to catch up with you. Bring yourself to order by forty, and by the time you reach fifty, you will feel revitalized, prepared for a productive old age. A piece of advice? Go ahead and accept the position as a five-star general, but select your lieutenants wisely—you will require much loyal counsel.`,
    elements: {
        Wood: `Energetic and resilient, the Wood Tiger is a hyper-creative innovator who bounds around like a frenzied dervish, leaping unharmed in and out of monumental vats of scalding hot water. This Tiger lacks the cunning and stealth of more subtle Tigers. It is sociable, direct, and constantly yearns to undertake the most ambitious projects and publicly express its extraordinary views, both of the world and of itself!

There is a positive aspect to the Wood Tiger's impulsive behavior. With so many endeavors in progress simultaneously, it is perpetually busy juggling, planning, and strategizing. It is never bored. The Wood Tiger is delighted when its alarm rings in the morning, as it can almost anticipate the diverse possibilities for expansion and immediate involvement in new deals that each new day offers.

All Tigers enjoy change, but this one is addicted to it. The mere thought of purchasing a loaf of bread from a new shop or taking a different route to the hardware store sends shivers of anticipation down its striped spine. You will never find it philosophizing or languidly daydreaming. The Wood Tiger has an extremely difficult time sitting still. It is also amiable and quite easy to get along with, but it is proud and resents it when others attempt to direct or advise it.

This individual is not an intellectual, but it thinks brilliantly on its feet. It is impatient with lofty idealism and theoretical discussions. It prefers to get straight to the task at hand and complete it—the faster, the better.

It believes it can accomplish everything—and enjoys seeing it done well. Furthermore, it thinks you should not only follow it and believe in it, but to demonstrate your loyalty, you should not hesitate to invest your money in its ventures. The Wood Tiger is a world-beater but often feels frustrated because it cannot find allies as fearless as itself. Its perception of the world is highly personal, sometimes incisive, and often witty. Part of the charm of this magnetic Tiger lies in its never taking itself or anyone else very seriously.

The Wood Tiger's devil-may-care approach does not align with its earnest desire to find a life's work or a true vocation that genuinely suits it. It is constantly torn between settling down and rampaging about, activating its charm and dispensing unsolicited advice to its devoted admirers. The Wood Tiger cannot resist even the slightest hint of an opportunity to shine, to captivate, and to convince others that it is correct.

It is quick to anger and just as swift to calm down. It is a charming, fortunate person who can be taken anywhere at all levels of society without causing embarrassment. It loves all types of people and is tolerant and democratic in its choice of friends and partners, making it a wonderful addition to any social gathering. It always has many clever things to say and a multitude of obscure ideas to contribute to any conversation. The Wood Tiger is generous and will shower its loved ones with comforts. But it is also selfish and, in all human interactions, demands the role of Top Tiger.

What this Tiger requires is a strong, interesting, and stable mate who can hold its attention and compel it to focus diligently. If the home life of the Wood Tiger is sufficiently loving, cozy—and disciplined—it can achieve great things.

The best way to deal with this willful yet lovable, elusive individual is, regrettably, to manipulate it. Telling a Wood Tiger directly what you think of its grandiose delusions or criticizing its ill-conceived plans head-on may result in little more than a black eye or, at best, a wounded ego.

Flatter this daring character, and it will follow you anywhere—at least until something more enticing comes along.`,
        Fire: `The Fire Tiger is a charismatic, highly dramatic, and sensual leader. Fire imbues the vibrantly impressive Tiger with even more dynamism and vigor. It is as energetic, if not more so, than its Tiger siblings. However, its power often outpaces its good judgment. It is recklessly extravagant with its strengths and overdoes and over-achieves everything it undertakes. The Fire Tiger simply refuses to conserve its own vitality. It pushes, strains, and forces itself through the most challenging obstacles for the sake of its brave ideals, exhausting itself to give form to projects in which it believes almost too fervently.

Sleepless nights are the norm rather than the exception. Erratic dietary habits and excessive sexual escapades are the fuel that powers this powerhouse's constantly revving engine.

From the age of fifty onwards (if it lives that long), the Fire Tiger would be well advised to slow down, take things easy, stabilize its private life, and engage in a consistent program of healthy diet and exercise or yoga. After fifty, it should content itself with delegating authority and managing its vast empires from behind the scenes. It should cultivate hobbies and/or take up meditation. To lead a full and healthy life in its later years, it must narrow its scope of action and find ways to calm its overactive mind. Otherwise, it will be taking a great risk: its nerves may suddenly give out, its heart may suffer an attack, or a stroke may cripple it. I do not even want to contemplate the extreme irritability of a bedridden Fire Tiger.

The Fire Tiger is also a revolutionary. It desires change and is not afraid to initiate it, manage it, and promote it to the public. Consider what Hugh Hefner accomplished in America with the Playboy philosophy. Not only did he establish a magazine, he transformed people's views on many aspects of their sex lives. The same applies to someone like Edouard Leclerc in France. He built a supermarket empire, defied government rules and regulations, undercut and outsold everyone else, and never ceased to be outspoken about it. Then there is Martin Gray, the man who survived the Warsaw Ghetto and wrote a book about it. Afterward, he lost his wife and three children in a forest fire in the South of France and established a foundation to preserve forests. At well over sixty, Martin Gray headed a foundation for global preservation and unity. The Fire Tiger expresses itself freely and openly and is unmoved by disapproving critics who would see it sanctioned for its outrageous ideas. The Fire Tiger is a resilient individual. It devises grand plans effortlessly and can execute them better than almost any other Tiger. Most Fire Tigers either make a world-class impact or perish in the attempt.

Imprudent as this Fire Tiger may be, and as often as it finds itself embroiled in difficulties, it is remarkably resilient. It is almost as if adversity recharges the Fire Tiger's energy. Not only does it desire to be the first and the best, it is always ready to re-enter the arena after being repeatedly defeated. The Fire Tiger possesses immense courage.

The home life of the Fire Tiger will be disrupted by its constant movement. These individuals do not typically marry young. For the sensual, passionate Fire Tiger lover, marriage is an inevitable part of plan B—the period of slowing down. Its sexually liberal youth represents an immature approach to sex, and the element of conquest remains with the Fire Tiger longer than with most. Perhaps in youth, it is too preoccupied with world-altering projects to dedicate sufficient time to long-lasting and profound emotional exchange, or perhaps it is a classic late bloomer. Whatever the reason, do not be surprised if you encounter a sixty-year-old Fire Tiger with a couple of children still in strollers.

The Fire Tiger values honesty and wishes to be regarded as fair and just. However, if provoked, it is capable of deception and even ruthlessness. It does not tolerate foolishness and will swiftly leave any detractors behind without a backward glance. It believes that the ends invariably justify the means. The Fire Tiger knows that its schemes and ideas will improve humanity's condition and never questions its motives or allows self-doubt to hinder its progress.`,
        Earth: `We twentieth-century Earth Tigers have a grim history of premature death resulting from sudden and tragic events—suicides, accidents, and even murder. In China, the Earth Tiger is known as the thinking person's Tiger. It is believed to be less restless, more determined, and wiser than its counterparts. Earth Tigers make excellent political leaders or top business executives. The desire to lead is strong, as is the desire to occupy a respected position in society. The spirit here is independent, self-reliant, and fiercely individualistic. Despite the calming influence of the Earth element, this Tiger is impulsive and headstrong. It devises scheme after scheme and rushes around, flashing its engaging smile and captivating everyone. However, it generally avoids complete ruin because it seeks advice before acting on its rash impulses. It consults its friends, its lawyer, doctor, and even the neighbors before making significant decisions.

Another distinctive quality about this Tiger is its un-Tiger-like ability to relax and do nothing. Most Tigers find it difficult to sit still, but Earth Tigers can gaze into the distance for hours, contemplating and dreaming of greater moments. They are the most relaxed and temperate of all Tigers.

The Earth Tiger enjoys learning new disciplines and formulating logical plans for the betterment of its own life and the lives of others. Because of this, it is sometimes perceived as meddlesome and overly interfering in the lives of those it cherishes.

Earth Tigers are pillars of strength and champions of justice. They cannot tolerate unfair practices and will fight against social injustice and combat ethical wrongdoing. Like a combination of a terrier and an elephant, the Earth Tiger seizes an idea and holds onto it indefinitely if necessary, because it never forgets. Vengeance will not leave its mind until justice has been served. Nothing brings the Earth Tiger greater satisfaction than demanding and receiving payment for a long-overdue moral debt.

The Earth Tiger is wildly passionate in love. It adores both seducing and being seduced. It is a playful individual who knows how to indulge its mate in imaginative love games. It is relatively faithful and true and prefers not to be informed of its mate's infidelities, as it dislikes being made a fool of. If mistreated, an Earth Tiger can bound away from a negative relationship without even a flicker of regret. It requires total reciprocity in love and rarely allows its heart to rule its head. Unrequited love? It seems like a shameful waste of its precious time.

The health pattern of most Earth Tigers is inconsistent and uneven, but they are fundamentally strong. Although danger befalls them in surprising and terrifying ways, they can survive astonishing ordeals and tend to land safely on all four paws. They assume leadership with ease, enjoy having a good time, and do not give much quarter to self-pity or whining. The Earth Tiger is dutiful and will pay dearly to uphold its beliefs and ideals. But, when wronged, it can also be ruthless and callously cruel. It is purposeful and unyieldingly independent. This last quality can indeed be a flaw, as in its resolute way, the Earth Tiger often ends up stubbornly adhering to its views and feelings without giving space to others, whose fervent desire to love it can never be as grand as its desire to remain aloof.`,
        Metal: `The Metal Tiger is principled, straightforward, conservative, and energetic, yet it retains its Tiger charm and powerful drive. It is a powerhouse of energy and a performer of grand deeds. But it is somehow more serious than most Tigers. It is not one to leave projects unfinished. It is a bulldozer with the engine of a tank and the scope of at least sixteen aircraft carriers.

The Metal Tiger has a reputation for making the right decisions at the opportune moment and will patiently wait for the precise instant to strike. This behavior can sometimes appear to be procrastination, but its hesitation is a form of strategy. It lies in wait, occasionally raising an eyelid to survey the scene. Then it rises, yawns, stretches its limbs, tenses its muscles, and acts decisively!

On the other hand, if the Metal Tiger has to wait for someone to appear or for something to happen, it becomes frantic. It desires what it wants when it wants it and struggles to understand why others might not wish to adhere to its schedule. It dislikes obeying, yet insists on obedience from others.

This Tiger also possesses a somber inclination. From a young age, it may be fascinated by weapons and intrigued by death and symbols of mortality. It faces a lifelong struggle to suppress this tendency. The Metal Tiger needs to surround itself with optimistic people who keep its mind focused on the positive aspects of life. Otherwise, a predisposition for self-destruction, blind heroism, and a taste for danger can lead it into serious—even fatal—accidents.

The Metal-born Tiger child should be raised in harmonious surroundings, taught to love peace and cherish its fellow human beings. Wise adult choices should lead to harmony and a close-knit family life. Tensions within the family or a tumultuous marriage could disrupt its mental stability. Divorce would be preferable to a stressful marriage.

On the surface, the Metal Tiger appears optimistic, cheerful, and full of humanity. And, on a grand scale, it is. Yet it is not always compassionate in one-to-one situations. You cannot persuade it to sit down and express its thoughts or discuss its feelings. Other people's needs and the complexities of emotional situations seem to escape this Tiger's notice. It can be callous and heartless in love and in family relationships. Yet if its cold-heartedness is remarked upon or criticized, it simply dismisses it with a laugh, pretending it does not exist. There is no remedy for the Metal Tiger's emotional shortcomings. My advice is to adapt to it. Do not take its sharp comments and lack of empathy too seriously, and the Metal Tiger will never seek your sympathy—it sees no use for it.

This Tiger is a creature of legendary magnetism—not classically handsome or even overtly sexy, but more like a charismatic Pied Piper who instinctively knows how to convince its audience and enlist the minds of others in its pursuit of superiority. It is no surprise that de Gaulle was a Metal Tiger. This is a formidable leader who stops at nothing to achieve its objectives. It knows precisely where to strike at the most vulnerable point.

The Metal Tiger desires to improve the world. It will not accept advice or listen to any condemnation of its often unreasonable methods to achieve its goals. For the Metal Tiger, any deception or manipulation is acceptable in the pursuit of victory. And for it, the conflict is always ongoing: right versus wrong, good versus evil, them versus him. It is right, and they are wrong.`,
        Water: `Water Tigers exhibit smooth, refined manners and appear to lead a charmed life. Great personal success, often achieved early in life, characterizes their existence. This Tiger is a lovable and loving creature, whose strength of will and determination to gain both respect and power are admirable. People honor and esteem the Water Tiger. It is more stable and leads a more balanced life than many of its fellow Tigers. It is often artistically inclined and capable of performing in public. Water Tigers tend to be musical and know how to imitate accents and speech patterns with remarkable accuracy. Possessing a good ear makes them natural linguists. Travel appeals to their preference for effortless adventure; they prefer to journey first class.

Long-term discipline is not always a Tiger's strong suit, but the Water Tiger is capable of sustained diligence in the accomplishment of work projects. It also boasts a socially pleasing personality and enjoys being with groups, telling jokes, and displaying its seductive talents. As this Tiger loves company, it desires to be a family-oriented person. It is reliable and takes responsibility for its relatives and looks after its home.

The Water Tiger is known for its sense of fairness. Unlike some Tigers who cannot tolerate advice or criticism, it is able to view its own shortcomings objectively. Its open-minded approach to difficult issues might lead it to pursue the study of law. It would make an excellent magistrate; its judgments would be unbiased and humane.

Water Tigers are not as intensely vain or ambitious as other Tigers. Scholarly pursuits such as philosophy, languages, and comparative literature are possible, but it is the entertainment professions—especially those concerned with music and communication—which will ensure both the Water Tiger's career stability and bring it joy. Failing success on the stage or screen, it might choose to be a professor, a literary agent, or even a promoter of concerts or other spectacles.

Although they make excellent performers, these Tigers do not crave to be constantly in the spotlight during every waking moment of their lives. They can work contentedly behind the scenes, creating, inventing, and planning. An eager, clear-thinking Water Tiger is a welcome addition to any group effort.

This Tiger is mostly a virtuous creature whose greatest flaw is its rare but terrifying rage. The Tiger cannot tolerate betrayal and will react impulsively when it falls victim to it. The Water Tiger appears calm and unruffled, affecting a smooth, cheerful exterior. It is everyone's friend—until it is wronged. The bitter anger that follows is ruthless and leads to a long-term quest for revenge—a dangerous trait!

Cultivate the friendship of this Tiger. Enjoy its love and bask in its charming company. Accept its proposal to collaborate. But do not try to harm it—or it will turn you into a puree and spread you on its toast for breakfast.`
    },
    compatibilities: {
        "Rat": "At first meeting these two charm the pants off each other. The Rat finds the Tiger charming and would love to show him off, while the confident Tiger is amused by the Rat’s vigorous chatter and lively sense of humor. But there is bound to be friction in the long run. After the first spark of love, these two will find fault with each other. The rambunctious, adventurous Tiger will forever be seeking excitement—off on safari to Kenya, then on to San Francisco to catch the next earthquake. The Rat, being more domestic, will come to hate the sight of suitcases. The Tiger stalks instability, tempted by danger and the prospect of having a new job every year. Everything is challenging to this aggressive beast. The Rat will not always find the Tiger’s inconsistencies appealing and will be plagued by worry. Rat’s mental stability depends greatly on material security and, with the Tiger always job-hopping, the Rat will fret over money. To endure, both must remember the initial reasons which drew them together. They have lots to talk about and agree on many things. If the Rat can recall how the Tiger roared attractively into his or her life, and the Tiger can continue to appreciate the Rat’s powers of seduction, there is hope for an exciting, long-lived marriage.",
        "Ox": "Disastrous. No matter how you slice it, this combo is in for a rocky ride. Both possess an iron will, backed by the power to exert it. Equally self-possessed and determined, the obstinate Ox and temperamental Tiger are better known as rivals than accomplices. Frankly, this quarrelsome duo is best off entangled at the center of a boxing ring. Often, the Tiger jump-starts the Ox’s tranquil day by stirring up trouble. The stoical Ox wants only to stay close to home and plod on. He must exercise much patience with the rambunctious Tiger. And the Ox finds that exhausting. The rebellious Tiger roars off to a trade union demonstration, complaining bitterly about the humdrum, dreary Ox, while the Ox bullies the Tiger, accusing him or her of everything from incurable restlessness to insanity. If round three takes place under the covers, there is hope for reconciliation. The Tiger’s raw sensuality thaws the Ox’s glacial resistance. With the Tiger, the inhibited Ox feels free. Twenty-four-hour truces may result. Even so, the union is best-suited for friendship or business partnership, where dual iron wills can effect real progress. The Tiger/Ox emotional match is a tug of war. It is not romantically promising.",
        "Tiger": "Two Tigers? Bum-out alert! Tigers believe fervently in love at first sight and may pounce on each other with gusto. Yes. A Tiger tandem is full of instant enthusiasms, quick fix plans, and clever strategies. But there is a basic problem. While both Tigers are out changing the world, who’s watching the store? Candlelight dinners. Vibrant, witty foreplay. Banter and excitement. “My place or yours?” decisions rapidly executed. Groans, sighs, crackings of zippers, and tearing of clothes, twin tigers are so turned on, they never make it to the bed. They consume each other. Afterwards, they’ll sip champagne and pore over the world's fate. Their torrid embraces become passionate arguments. Forever in combat, the Tiger twins are messily content. Come morning, two Tigers regain their respective lairs, freshen up and dash off to work. No time lost, and no extra romantic palaver to cloud the clear purpose of a busy day. Tigers are inveterate meddlers, always shoving their paws in where they ought to abstain. Two Tigers will contradict and wrongly advice each other all over the place, leaving no other alternative than to swim around in boiling water for the rest of their lives. Help! Perhaps they should forego marriage. A love affair will be played out in fast-forward mode and promises to be ultra dynamic. But this marriage is unlikely to be either peaceful, long-lasting or productive. And…God help the Tiger cubs. The insecurity! The ever-changing domiciles and decors. Arrgh!",
        "Rabbit": "A style clash. This couple might very possibly enter into a so-called “marriage of convenience”, but underneath roils a mute tension that screams, “Get me outta here!” With a Tiger/Cat union, it’s the Tiger who’s doing the silent shrieking. What then? The Cat usually has the money, and the Tiger, who married the Cat for the loot, is busy having a nervous breakdown. Tigers live for change and victory. Cats dream only of peace and quiet. Get the picture? No common ground. Trying to outwit each other, these two felines stealthily compete for the household throne. The Tiger goes at it with typical self-serving vengeance and the Cat skulks around the house seeking opportunities to entrap the Tiger. Imagine, two wily cats under the same roof. They merely tolerate each other. An occasional playful interlude can degenerate into a clawing, hissing brawl. Cats require security and build their nests with refinement and taste. The Tiger might enjoy these surroundings but, unlike the Cat, the Tiger craves change and favors a more Bohemian lifestyle. The seductive Tiger might be tempted to grab some of the Cat’s dough and dash off to the Amazon, leaving only a deep skid mark outside the Swiss bank. Even in bed, this pair is not apt to be compatible. The Tiger is aggressive, possessing such a raw, frank, pushy sexuality that the Cat’s delicate sensuality is overwhelmed. Cats require coaxing, seductive, slow-moving lovers and Tigers are ill-suited to satisfy this need. I see the Cat/Tiger match as either an intense summer romance, or perhaps a long-lived “loving friendship” wherein they get together in bed once in a blue moon for old times’ sake. Marriage? Only if the Cat has a private income and protects it from the Tiger’s spendthrift clutches.",
        "Dragon": "Sexed! The Tiger/Dragon love relationship bears serious consideration. Combined, their strength is almost excessive. And energy! Enough to fuel several large power plants. There is EGO flashing in red neon all over this couple. Overbearing and self-propelled, they are both a bit too much. But as a pair, they can succeed. Despite an excess of commando muscle, this combo lives peaceably together. Mutual respect and admiration offsets the expected clashes. The dashing Dragon begs for constant flattery and applause. However, the strong-minded Tiger finding the pontificating Dragon tiresome and teases the spotlight away. The Tiger is undaunted by fire-breathing antics. In fact, the intrepid Tiger loves a good shouting match and respects a worthy opponent. The generous Dragon is amused by and tolerates the Tiger’s love of danger and precipitous behavior. In short, these two get along. Tiger with Dragon is not only a sensual match. They carry themselves with bravado and flair. An air of madness colors everything they do. People flock to their home to bask in their aura and share in the high of their hazardous love. Not afraid to share power, they take turns sitting on the throne, complicity taking precedence over their individual roles. This relationship is good for marriage. Battles will be waged, but at the end of the day the force of their attraction ensures they will be lovers for life. Entwined in their own whirlwind of passion and steamy sex, this couple knows the road to heaven. The Dragon sets the tawny Tiger alight and the rapacious Tiger devours the dashing Dragon’s scalding hot fire. Enjoy!",
        "Snake": "The elusive Snake and the tempestuous Tiger are irresistibly drawn to each other, but this union is not advisable. A Tiger/Snake pairing can be a disastrous alliance. As different as black and white, yin and yang, the Tiger/Snake combination simply does not blend. Should either of you be unfortunate enough to fall for the other, a preliminary restraining order could save you from catastrophes. If not, here is what to expect: The slow-moving Snake will inflict tremendous frustration upon the energetic Tiger's psyche. Initially, the jungle predator mistakenly perceives the enchanting serpent as quiet and submissive, and attempts to dominate. But reptiles do not respond well to bullying; they retaliate. Snakes are aloof, independent-minded, and strategic masterminds. Haughty indifference and disdain are among their sharpest weapons. They are also prone to repeated instances of infidelity, which will certainly shatter a Tiger mate's considerable ego. The impressive tantrums of the Tiger can make the Snake's calm, reflective, philosophical life miserable. Equally magnetic, Snakes and Tigers compete for attention. The Tiger does so aggressively, and the Snake slyly bewitches. At their own cocktail party, Tiger/Snake hosts may appear quarrelsome. The Tiger recounts stories about its days in the Sinai desert. The Snake subtly encroaches on the Tiger's territory, captivating the company with the Dance of the Seven Veils, learned (coincidentally) in the Sinai desert. Outmaneuvered, the Tiger loudly outdoes the Snake, recounting further desert expeditions. Subdued, the Snake joins the applause, but adds, in a cultivated, soft-spoken voice, that everything the Tiger knows about deserts was learned from the Snake. Tigers are fast and alert, while Snakes are quiet and deliberate thinkers. Tigers are impulsive and may act heedlessly. Snakes rely almost solely on intuition and take things slowly. These creatures may cohabit for sensual pleasure, but they do not see eye to eye. Sexual intimacy? The Snake's need for beautiful, romantic foreplay is denied by an aggressive Tiger, who simply gets down to business. It is best to abstain!",
        "Horse": "Auspicious, to say the least. Both parties have unruly natures. Individually, they are independent. They might clash, but the attraction between them is strong and so is the mutual respect. In love, they become wilting passion flowers of vulnerability. As a loving pair, their passion knows few bounds. The Tiger and the Horse are equally inventive and creative. In family matters, the Horse’s conservatism curbs the Tiger’s hotheadedness. They work hard together to raise a fine family in a proper way, yet, thanks to the Tiger’s rebelliousness, the kids will get some relief from the seriousness of Horsey’s approach. Both are optimistic and strong. Usually, if a depression comes along, the Horse is up and the Tiger is down, or vice versa. And no boredom here either. These two are active, lusty life-grabbers. Unless one learns to be practical with money, they may have financial crises. Both know how to earn and both love to spend. The initial sexual attraction is volcanic and they are both imaginative and faithful enough to keep sex exciting over the long haul. This relationship can endure.",
        "Goat": "This union is among the worst possible known to Chinese astrologers. Although the couple may make a fabulous start (in bed), from there on it's all downhill. The practicalities just don't work out. Goat is charming, beautifully seductive and loving. Tiger is passion and mettle. But who will bring home the bacon? In this family, nobody wants the job. No concessions are made. The Goat remains laid back while the ambitious Tiger bombasts a hole in the kitchen ceiling. What was a great passion ends in lifelong misunderstanding and acrimony. Affairs? Yes. Marriage? Abstinence is advised.",
        "Monkey": "These two make eager lovers. Initially, they will leap frequently on each other’s bones, accomplishing astonishing feats of extreme passion, but in the long run, the ardor may die a natural death, because Tigers hate to be clung to—and innately neurotic Monkeys don’t know how not to cling. The strong intellectual tug between Tigers and Monkeys frequently keeps them together, anyway. The Tiger admires the Monkey’s keen eye for strategy and the Monkey enjoys and applauds the Tiger’s feisty wit and temerity. Monkey gives Tiger plenty of presents and kudos. Tiger gives Monkey spunk and encouragement. These two have an easy common viewpoint, and, even if they cannot keep the love flame burning, will go far together as lifelong pals. Except… the Chinese say that the Tiger should beware. Traditionally, the Monkey is Tiger’s natural enemy. I don’t advise marriage.",
        "Rooster": "I don’t recommend this pair for marriage. Both parties are aggressive and opinionated; neither will back down easily. The atmosphere will be taut and most arguments one-sided. Conflicts and collisions are guaranteed to hinder the harmonious progress of this couple. Tigers bounce back and forget every nasty word that was said. But Roosters carry grudges and cannot forget how badly they were treated by a Tiger last time they had a row. Impasses are common. In bed, there may be some fairly exciting fireworks, as the Rooster is imaginative and energetic enough to keep the demanding Tiger interested. They are both impetuous and uninhibited lovers capable of grand gestures and profound intensity. Unless the disagreements of the day carry over into the bedroom, this couple is well aspected for a long, healthy sex life—without marriage.",
        "Dog": "Harmony incarnate. Dogs and Tigers just plain get along. They have common causes and common philosophies. But they are very different. The Tiger is overly optimistic, the Dog pessimistic. Each helps the other to understand these basic character differences. The Chinese call this pairing a happy alliance of muscle and heart. The Tiger has the strength to put the Dog’s ideals across to the public. The disquiet Dog keeps watch and prevents the Tiger from leaping into the wrong frays. They are, simply, a great couple. Harmony reigns right from the start. And because Dog and Tiger respect each other’s deepest convictions, mutual admiration sticks them together like super glue. In bed, the Tiger usually takes the lead, which is felicitous for the tense, nervous Dog, who often needs to be thawed out before engaging in any heavy intimacy. With time, this couple learns to blend eroticism with affection to achieve physical fulfillment. It is rare that such a marriage ends in divorce.",
        "Pig": "The basic characters here are vastly different. Pigs are scrupulous and peace-loving. Tigers strategize every move and carry banners for their own noisy causes. Yet with the proper amount of gentle understanding from Piggy and the sort of generous reasonableness for which Tigers are famous, the pair can make a real go of marriage. The Pig admires the Tiger’s punchy gall and the Tiger respects the Pig’s guilelessness and purity of spirit. Pigs are mostly even-tempered and good-natured, while Tigers are pathologically changeable. Pigs find Tigers too mobile but they don’t mind staying at home and holding the fort white Tiger rushes about being self-important. Instead of clashing, these two complement one another. Their physical relationship is full of tenderness and mutual understanding. The Pig is sensual, adores pleasure and is lavishly generous. Tigers need a lot of affection and cherish the sort of warmth and homeliness the Pig offers their restless nature. Steamy cuddling sessions abound in the Pig/Tiger household."
    },
    futures: {
        "2025": { "year": "Snake", "element": "Yin Wood", "prediction": "As you undoubtedly already know, the Snake consistently desires influence. In relationships, in business, or in government, the Snake aims to dominate. Now, for you Tigers, this particular Snake characteristic is both unsettling and extremely irritating. You do not necessarily wish to be in control of many things; answering phone calls and emails in an office all day, waiting for people to attend tedious meetings, would bore you immensely. However, the Snake does not necessarily understand this about you. You appear so strong and self-assured that the cautious Snake feels threatened. Consequently, your life in the Snake year may prove to be less than delightful. The Snake might attempt to obstruct even your most innocent desires for leadership, belittle your most ingenious ideas, and may even sabotage your plans. You see, the Snake not only desires power; it also seeks security and is a meticulous accumulator and saver. You are the more extravagant, carefree individual who believes that money is abundant and that if you keep seeking new opportunities, there will always be more available to you. Conflict will arise between your spending habits and the Snake's desire to accumulate. My advice? Plan to travel this year and remain out of public sight. If you do not threaten the Snake in any way, it will do you the favor of completely ignoring you." },
        "2026": { "year": "Horse", "element": "Yang Fire", "prediction": "Many people believe Horses and Snakes do not harmonize. Many people are correct. This year will be challenging at best for Snakes, as the Horse is not even-tempered and does not particularly care about its subjects’ well-being. Horses are intensely pragmatic; they simply want to do things their way. They are talented and shrewd, and they are artistic, but not necessarily altruistic. You Snakes are motivated by compassion and philanthropy; you sincerely believe in your ability to contribute to the betterment of humankind. So, Snake dissatisfaction is common in the ego-centered Horse year environment. You will feel as though you just cannot make progress on any project and maintain it without obstacle after obstacle being thrown up and roadblocks appearing at every turn. You might, moreover, become entangled in a legal battle over a contract or real property. As the climate in Horse years is unfavorable to a positive outcome for Snakes, you will not have much chance of winning. It would be better to try some cunning tactic to delay the lawsuit until next year when the gentle Goat will rule—a more lenient climate for Snakes involved in legal disputes. Obviously, this year will not be your favorite. Take your frustration on a long holiday somewhere warm and tropical with your significant other in tow. Should your significant other be (for some strange reason) a Horse, I advise that you leave him or her at home. Perhaps you should consider seducing someone more philosophically inclined." },
        "2027": { "year": "Goat", "element": "Yin Fire", "prediction": "Tigers generally fare better under the Goat’s influence this year; however, they also have to strive harder to achieve their desires. The Goat and you do not perceive life in the same manner. Fundamentally, Goats enjoy being confined to fertile areas where they can exercise their creative abilities without the concern of having to exert themselves independently. You are quite the opposite; you are inherently independent. You do not enjoy being restricted anywhere, ever. As a consequence of this significant difference in approach, in Goat years, you often feel disapproved of. Not that you care in the slightest whether or not you are liked or accepted by the Goat. But you do wish it would not try to curtail your style. Ideally, in these years, you will engage in more travel for both business and pleasure. You will enjoy the wandering. Meeting some new like-minded individuals will help keep your energy levels high for the twelve rather unhurried months ahead. The financial deities are on your side in Goat years. This may not signify that millions will be bestowed upon you, but it does indicate that you are doing something correctly, that is, traveling!" },
        "2028": { "year": "Monkey", "element": "Yang Earth", "prediction": "No frivolous behavior! These next twelve months will offer you a burst of activity, precisely to your liking. Multitasking, numerous meetings, and multiple proposals for work, cultural, and sports experiences. Accept the Monkey's invitations for all these propositions. You, more than any other sign, are certainly capable of managing such a diverse array of ongoing activities. Where other people might feel overwhelmed by such an abundance of new things to learn and do, you revel in the novelty of it all. A change in your work environment is also forthcoming this year. You are an individual whose enthusiasms require alteration as frequently as you change your shirt. So, start diligently searching for that unusual job immediately this year. You will not regret doing so. Love life? Medium rare. I say that because the romantic situation you have been in for so long is, by this time, well done. Overdone, in fact. Hence, it is time to make significant changes. Now, briefly pursue new romantic interests. See how it feels to enjoy the thrill of seduction again. Change is the central theme of the Monkey year for Tigers. P.S. Your current partner will most likely be overjoyed to see you depart." },
        "2029": { "year": "Rooster", "element": "Yin Earth", "prediction": "Allow the Rooster to manage the proceedings. Or at least give him or her the impression that they are in a position of leadership. Roosters prefer to act swiftly, enjoy themselves, and (unlike yourself) prefer not to leave a trail of casualties behind. As you probably have a new romantic interest by this time, you will be busy devising new strategies to retain this prize. However, you need to apply yourself diligently to work this year. Roosters expect people to be actively engaged in their various projects and are not amused by idlers. So, maintain a prominent presence. When you are laboring under the hot sun or mining coal deep underground, groan frequently and sweat profusely to convey to your superiors just how demanding a Tiger's life can be. Otherwise, if you are not attempting to overshadow him, the Rooster will leave you to your countless independent pursuits. Travel and visits to relatives in distant cities are favored now. There is a family member you have been avoiding. Make it your priority to pay them respect. It is in your financial interest to be kind to them now and make amends for any past neglect." },
        "2030": { "year": "Dog", "element": "Yang Metal", "prediction": "Phew! There is relatively little that can go utterly wrong for a Tiger in Dog years. You and Dogs get along well together because you share similar beliefs and adopt a global perspective on even the most minor events. Differences of opinion arise when you sense the Dog's inherent paranoia surfacing unexpectedly. Dogs possess a unique understanding of Murphy's Law; they instinctively know that if something can go wrong, it will, and they are more than willing to announce it beforehand. Hence, in Dog years, an atmosphere of pervasive anxiety lingers, which drives Tigers to distraction. My advice to Tigers in this otherwise somewhat challenging year is to enjoy the goodwill that the Dog offers you as its protective companion. Relax a bit. Ease off the accelerator at work. Spend some enriching downtime simply socializing with friends or family—or both. In Dog years, you can also enjoy engaging in cultural excursions. Take tours of exotic lands you have always promised yourself you would visit. Go see the Pyramids or visit Niagara Falls. Do something wonderful for yourself, but leave the Dog and its paranoia at home." },
        "2031": { "year": "Pig", "element": "Yin Metal", "prediction": "Pigs admit to a certain wide-eyed admiration when confronted by you restless Tiger individuals. Pigs are strong, knowledgeable, and culturally adept people. But they do not comprehend your exaggerated need for change. You are constantly bustling about, never settling long enough to accumulate capital, amass riches, collect art, or acquire luxurious homes—whatever it is the Pig considers wealth. Nevertheless, the Pig and you can be close companions. You admire the Pig's purity and authenticity of spirit. What it does not understand about you is what will hinder you this year. The atmosphere of abundance will lead you to assume you can spend, give, and squander your money, and so—in a word or two—you overspend. If you are not more careful about where your money is going in the first part of this Pig year, by September, you will find yourself in a difficult financial situation. So, tighten your resolve, Tiger. Control your desire to be overly generous to those you love or those you feel are in need. Hold onto your financial reserves and do not sell the family jewels to acquire a fancy new car to impress your beloved. Put yourself on a budget. Give your love freely, but take fewer financial risks. Slow down. Sit still. Read. Knit. Go to the countryside. Sit under a tree and reflect." },
        "2032": { "year": "Rat", "element": "Yang Water", "prediction": "This year, the Rat’s influence may be detrimental to Tigers. Rats love to dominate, and you do not particularly enjoy being told what to do. The atmosphere in Rat years can be tense for Tigers as well. You will need to travel this year, and you may also need to do so in the company of a Rat whose political views are not at all in harmony with your own. As Rat years are all about power, this will be a good time for you to avoid seeking promotions or asking for a raise. Maintain a low profile. Do not attempt to be the leader of anything you cannot fully control, as the Rat will be waiting to seize any opportunity to undermine your authority. I would not advise that you and your romantic partner or spouse take any lengthy journeys together, as the stress of the year will cause both of you to be irritable. If you can take separate vacations, do so. In general, your romantic life this year should be put on hold until a more favorable period. Your health is generally good. There is no need for you to undergo any plastic surgery or cosmetic procedures." },
        "2033": { "year": "Ox", "element": "Yin Water", "prediction": "I must caution you against attempting to earn a significant amount of money or securing the prestigious job you desire in an Ox year. Why? It is not merely because the Ox does not wish for your success, but also because your rapid, opportunistic methods exasperate the Ox. As a long-term planner, the Ox becomes disoriented simply observing your quick acceleration and swift movements. Ox individuals possess great talent for leadership; they often become autocratic figures. However, they are not particularly quick on their feet, and they are even slower in their intellectual processing. Their minds operate in an unhurried fashion. Do they linger and adopt a leisurely approach to managing their year or their domain? Absolutely not. But they persevere steadily, and you act impulsively. Therefore, in an Ox year, it is advisable to preemptively temper your intensity so as not to appear threatening or to bewilder the deliberate, task-oriented Ox. You will not need to humble yourself to advance. However, you will need to agree with those in positions of authority. Since you detest being anyone's subordinate, you may experience digestive issues, migraines, and other stress-related ailments as a consequence. Maintain the well-being of your romantic life by making a special effort to perform loving acts of kindness and deference towards your beloved or spouse (or both) in this rather challenging, unaccommodating Ox year. You need all the approval and affection you can gather from those who cherish and admire your spirited demeanor." },
        "2034": { "year": "Tiger", "element": "Yang Wood", "prediction": "This year is your year. You are in charge. You must, therefore, be vigilant and ensure your subjects do not overthrow you. Do you recall that last year, you were able to spend your time peacefully managing your projects and were not subject to any sudden changes or unexpected events? Well, this year promises to be quite the opposite. The Tiger is an extremely volatile individual who enjoys a thrill a minute. You can handle the chaos, but you will not appreciate having to frequently revise your meticulously planned timetables. Tigers thrive on constant change, and you... well, you do not. I would like to be able to advise you to travel and avoid this hectic atmosphere. Unfortunately, the Tiger and the Ox are traditionally at odds. So, you must remain on guard. If you are not present and vigilant, your enemies will seize the opportunity to usurp your authority. Do not take risks. Do not change jobs or move to a new house. Do not buy a new car. Do not have a baby. Do not invest your money. The only advice I can offer you is: stay where you are, and do not make any significant moves." },
        "2035": { "year": "Rabbit", "element": "Yin Wood", "prediction": "You will need to maintain a low profile in this Cat/Rabbit year. They do not enjoy the chaos and general disorder that you Tigers create in your professional lives. However, if you are discreet and cautious, you can accomplish a great deal. The Cat/Rabbit will ignore you if you do not make a lot of noise. Your health will be good, and your romantic life will be passionate. As the Cat/Rabbit is a homebody, you will feel the need to remain close to your family and friends. This is an excellent year for home renovation projects, building a new house, or constructing an addition. You will be able to manage these projects without much interference from outside sources, but do be careful not to make any foolish investments. The Cat/Rabbit is very shrewd about money and will be watching you closely. If you appear to be squandering your finances, the Cat/Rabbit will not hesitate to report you to the authorities. So, if you are not up to date on your tax returns, I suggest you get them in order." },
        "2036": { "year": "Dragon", "element": "Yang Fire", "prediction": "Dragons love you Tigers. They adore your spirit and admire your courage. They will do everything in their power to assist you in your endeavors. So, this year, you can anticipate success in all your projects. You will be able to travel, and you will be able to earn a significant amount of money. You will also be able to find a new romantic interest, and you will be able to maintain your current relationship without much difficulty. The Dragon is a generous individual who will not interfere with your personal life. However, you will need to be careful not to take on too many responsibilities. The Dragon is a very demanding individual, and you will need to be able to keep up with his or her pace. If you can manage to do so, you will have a very successful year. If not, you will find yourself in a great deal of trouble. The Dragon does not tolerate failure, and you will be held accountable for any mistakes you make. So, be careful, and do not make any foolish decisions. If you can manage to do so, you will have a very successful year." }
    }
};

    