// src/lib/new-astrology/scorpio.ts

export const scorpio = {
  "Scorpio/Rat": {
    description: `A sharp-tongued magpie if ever there was one, the Scorpio born in a Rat year will be chatty and cutting. This person is generally lithe and agile as well as quick-spirited. He or she will probably enjoy all manner of graceful sport and prove able at competitive games.

The Scorpio/Rat is an amiable fellow. People like him or her straightaway and never guess that behind the ready smile is a rare drive for power. He does not necessarily want to rule others, but he does want to hold a potent place in whatever area he has chosen as his own.

The Scorpio/Rat has a strong character. He is not namby-pamby and knows precisely what he wants out of life. With the sneaky old Scorpio to temper his aggressiveness, this person will be more reserved than the average Rat. He will surely enjoy receiving visitors and entertaining them generously. The Scorpio/Rat is often gregarious for his own interests, but his charm is that he does not hide this fact. He’s not afraid to admit that he’s out for himself and those he loves and that he intends to protect them by any means available.

One of the most striking traits of this person’s character is his vision and sense of the future. He is an excellent critic of things both artistic and political, and seems to have a sixth sense about what will be popular and well liked in years to come. The Scorpio/Rat is more than intelligent. He is wily and clever and full of guile. If he puts this cunning to good use as a creator or protector, the Scorpio/Rat’s fate will be felicitous. He’s a caring and understanding creature and can do much good for humankind. If, however, he is tempted by underhandedness, disaster may strike. The Scorpio/Rat is more vulnerable to disapproval than he seems. This is basically a noble nature that on the whole wants no ill to befall others. He is both nervous and suspicious, so he worries a lot and may suffer from anxiety attacks. He is magnetic and projects a pleasant presence. He will not take kindly to the meddling of others but can be accused of meddlesomeness himself.

Scorpio/Rat enjoys judging others and is adept at pinning them down to fine points or nailing them on delicate subjects. This person can make himself very unpopular with adversaries if he is not ever so careful on whom he passes his hasty judgments. The creative side of Scorpio/Rat is frequently scotched by his need to compete and win. He does not handle failure well. He or she can be leveled by setbacks and will give up anything and move to the country if the establishment gets in the way.

Finally, the Scorpio/Rat is quite sufficient unto himself. Although he persists in wanting to shine against the foil of competition and to triumph over those he considers his opponents, if he will learn to sit back and take stock, to quiet down and examine his problems calmly, he may be surprised to note that he does not need to pit himself against the opposition in order to prove his worth. It’s obvious anyway.`,
    love: `The Scorpio/Rat is a hatcher of complex romantic plots. He or she will not be attracted for long to any fly-by-night lover. Scorpios born Rat must find the person they finally settle down with exceptional. They are extremely sensual and preoccupied by passion early in their lives. Yet as they know themselves to be tempted by conquest, they often decide to marry homebody types whose very seriousness keeps the Scorpio/Rat on the straight and narrow. You may not often hear about the spouses of these busy, sometimes treacherous, souls. That’s because the ideal Scorpio/Rat mate keeps the home fires burning.

If you love a Scorpio/Rat, you must arm yourself with a bludgeoning ability to defend yourself. Scorpio/Rat is a harsh and demanding critic. He is nothing short of a perfectionist when it comes to relationships, mulling over every detail to verify the sentiment’s purity. This person is competitive, too, and may be rapaciously jealous. If he or she is capable of running around, then you, too, must be guilty. It’s an odd turn of mind, but it’s the Scorpio/Rat’s specialty.`,
    compatibilities: `You can probably walk hand in hand forever with Cancer (born June 21 - July 22), Virgo (born August 23 - September 22) and Pisces/Ox (born February 19 - March 20 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) subjects. Another one of your prospects might be the Cancer, Capricorn (born December 22 - January 19) or Pisces/Dragon (born February 19 - March 20 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), along with Cancer, Virgo and Capricorn/Monkeys (born 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028). All of the above love to listen to your late night worries. A less willing ear will be lent by Taurus (born April 20 - May 20), Leo (born July 23 - August 22) or Aquarius/Horse (born January 20 - February 18 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). Be sure to keep your distance from Taurus and Aquarius/Rabbits (born 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035).`,
    homeAndFamily: `Rats born in Scorpio are strong-willed. They like their surroundings to say something about them, show off their achievements, be identifiably theirs and no one else’s. Many Scorpio/Rat interiors are sleekly ultramodern. This subject is forward-thinking and always imagines herself in the avantgarde. Too, Rats born in Scorpio are creative and will tend to display their works to best advantage at home.

The Scorpio/Rat parent is reliable and protective of the brood. This person never forgets to be prepared for any eventuality or emergency. As kids are the soul of the impromptu, the spontaneous Scorpio/Rat is often Johnny-on-the-spot when Junior needs a map of Venus for school the next day and it’s already past midnight. Scorpio/Rats are affectionate and communicative with their offspring.

A Scorpio/Rat child will be alert and ready with friendly smiles from the cradle. This kid is a charmer. He wants attention from parents and teachers, neighbors and his peers. He knows how to go after approval through achievement. He or she is bound to be very powerful among peers or else busy seeking power. These natives compete mercilessly all their lives for first place. They need parental encouragement to go after the things they are interested in.`,
    profession: `The Scorpio/Rat’s ideal profession is vociferous critic. He is expert at picking apart situations that need decorticating. He or she can be canny at law or excellent at diagnosing diseases, trouble-shooting in industry or entertainment, or inventing things that demand minute attention to detail. He is of sunny disposition but will be acquisitive and hungry for power. You can hire the Scorpio/Rat, but his or her eye will be on the throne from the jump. Scorpio/Rats prefer first place to subordination and they usually don’t have undue qualms about reaching goals. They train or learn how till they’ve got the whole system down pat and then Bingo! They’re running the company. Machination is the stuff of the Scorpio/Rat’s life. As a boss, the Scorpio/Rat will be demanding and protective, patronizing even. As he or she is very effective at any level and can handle any and all the jobs at hand, the same kind of behavior will be expected from underlings.

Some careers that fit this competitive person’s nature are: fashion journalist, insurance salesman, inventor, athlete, performer, critic or politician.`,
  },
  "Scorpio/Ox": {
    description: `A whiz kid with a crazy streak is the Scorpio born in Ox years. Oxen are deliberate, plain people who, as a rule, stodge their way to success come hell or high water. They are slow and they are thorough. Scorpios are very tricky and fanatical, mistrustful and magnetic. They veer all over the place in order to attain goals that the Ox heads for, horns lowered, steady as you plod. Put these two signs together and you get a kind of zippy Kremlin or a slightly kooky Sherman tank.

Scorpio/Oxen are uncanny. They seem to know instinctively how to elbow their way through a crowd without so much as grazing the sleeve of opposition. These people are always on their way somewhere. Their dust makes Challenger look like a third-class railway carriage in Darjeeling. Not that the Scorpio/Ox is in a hurry—oh no. He is simply ruthlessly and sadistically determined to get where he’s going, which in this case is always to the top of the profession where there are the highest salaries and the most glory and seniority and hoopla.

A curious facet of this person’s character is the unspoken superiority he or she carries around. There is never any question about who’s boss in groups when Scorpio/Ox is present. You see, this person is equipped with both the natural sovereignty of Scorpio and the strength of purpose of Oxen. Decisions, he feels, should be made without any consideration for sentiment. Scorpio/Oxen can understand the need for emotion, and indeed store up their share of lunatic experience in a lifetime. But they don’t usually allow their passions to interfere with progress. If they do, they know full well that their goose will be cooked.

Of course, Scorpio/Oxen are domineering. They have to rule others. But they are pleasant about their ability to take over in any situation and have the gift of gab necessary to put their message across with charm. These people are often quite humorous and know how to make others laugh. They are not terrific at laughing at themselves, however, as their egos are quite a lot stronger than their self-awareness.

Because of their apparent ease of success, Scorpio/Oxen are enviable. People become easily jealous of them and often try to hinder their progress by violent or underhanded means. But not to worry. Scorpio/Ox is a tough customer. He does not give up territory willingly. He drives a very hard bargain. He is a wicked adversary and a devoted friend. Scorpio/Oxen are self-centered people whose heavy step can be felt across continents, and who don’t hesitate to make big (surfer-variety) waves in order to ensure themselves smooth sailing.

No Scorpio is more vengeful than the Scorpio/Ox. He never forgets a wrong done to him by another, and will recall a debt, whether moral or financial, after decades of silent fury. He doesn’t like mollycoddling and is never guilty of indulging others. Fools? Either he makes use of them, or “Off with their heads!” Because of his or her insistence on taking perilously stubborn stands and living fast, madcap lives, Scorpio/Oxen are often in mortal danger.`,
    love: `As the Scorpio/Ox is attractive as well as powerful, he or she will have many admirers. Among these, they will be likely to choose a mate for malleability and beauty rather than for smarts. Scorpio/Oxen are not really too interested in intellectual exchange with a lover but are rather fascinated by the thunder and lightning storms of angry outbursts, rows, separations, and breakdowns. They get their kicks from emotional crises which are hardly ever of their own making.

It’s a pretty risky business being the mate or even the casual lover of one of these impressive maniacs. They are passionate and sexy. But they are also always right, always on top and always slightly cuckoo. It’s nice cuckoo. But cuckoo, nonetheless. If I were to be attracted to a Scorpio/Ox, I’d think twice before tying any permanent knot. The Scorpio born Ox can be a right rascal and a bit of a tramp to boot.`,
    compatibilities: `Rats (born in 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) agree with you—especially from the Cancer (born June 21 - July 22), Virgo (born August 23 - September 22), Capricorn (born December 22 - January 19) and Pisces (born February 19 - March 20) families. Roosters (born 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) are winner mates for you, too. Choose from Cancer, Capricorn or Pisces. Snakes will wrap you in happiness if they belong to Cancer, Virgo or Capricorn. Not so happy will be relationships with Gemini (born May 21 - June 20), Taurus (born April 20 - May 20), Leo (born July 23 - August 22) and Aquarius/Goats (born January 20 - February 18 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027). Disappointments aplenty await you with Taurus and Gemini/Dragons (born 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024). Your sullen moods will not mix with Taurus/Monkeys (born April 20 - May 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028), Gemini/Horses (born May 21 - June 20 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) or Aquarius/Tigers (born January 20 - February 18 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034).`,
    homeAndFamily: `The Scorpio side of this person may make him or her a little outrageous, but his or her choice of lifestyle, due to the stolid Ox’s penchant for domesticity, will be far more earthy than his personality indicates. The Scorpio/Ox will enjoy a gracious country life and be attracted by quiet, plush surroundings. He will be sure to have limelight installed in all the rooms of his ponderous great mansion.

The family life of this hefty creature will depend on whomever he has the intelligence to hitch up with. As Scorpio/Ox is often out in the world being a whiz kid, he must either keep a dedicated staff at home to look after details such as children and pets, or else travel with family in tow. The busy life inherent in this sign often demands mobility. Scorpio/Ox will be a devoted parent and maintain communication with his or her kids long after they have left the nest.`,
    profession: `Power professions are those that attract the Scorpio/Ox. But his eloquence will also attract him or her to all aspects of performance. This person is an acting genius born. He can also lead crowds to giant deeds and even to revolution. He’s a shade too crazy to be entrusted with military force. Besides, he prefers laughter to aggression.

Careers that might suit this person are: performer, entertainer, actor or actress, political leader, teacher, writer, film director, theatrical director, communications expert, comic.`,
  },
  "Scorpio/Tiger": {
    description: `At the risk of being accused of vest pocket autobiography, I confess that this sign is my very own. Moreover, I like my sign and have many friends of the same persuasion. Forgive me if I wax sentimental in this portrait. First off, I’ll tell you that all Scorpio/Tigers are excessive. They do everything to extreme. They never take life as it comes, but rather race out and try to head it off at the pass. They are constantly in dangerous situations, where they have plunked themselves deliberately. They never take their time and plan every detail, or write lists to be sure that every last mothball gets accounted for in the winter clothes. These people are hasty and hotheaded and really honestly quite mad. I call Scorpio/Tigers “blitz” people. They come screeching up to every new experience, gobble, slurp, inhale, consume, build, make, bake, scrape, paint, fix—and they’re off to the next challenge. Scorpios born in Tiger years are always trying to get three lives out of one.

The combination of Scorpio’s dark magnetism and Tiger’s swaggering charm makes this subject fairly fascinating to other people. This translates into Scorpio/Tigers being quite popular among their peers. People look up to this character and Scorpio/Tiger loves to be looked up to, told how wonderful he is and, in return for admiration and approval, goes to great lengths to continue to be wonderful so that the applause never dies down. Scorpio/Tigers are egomaniacal. But they’re nice about it. These headstrong characters are automatic leaders. But they are not exactly crazy about being leaders. Scorpio/Tigers know how to do a lot of different things and tend to be jacks-of-all-trades. The dream of this contrary soul, then, is to do one thing well. Scorpio/Tiger is a proud person. But he rankles at his own tendency toward pride and is constantly kicking himself in the derrière, saying, “Be more humble. Don’t get carried away. Shrink your head to normal size.” And worst of all, Scorpio/Tigers are fighters. They are ferocious and even dangerous as adversaries. They can be both rancorous and bloodthirsty. But they hate being so mean. They long to be nicer. Now that you understand the basic Tiger/Scorpio schizophrenia, I will tell you what they need to do so as not to die young: Scorpio/Tigers must gain wisdom at an early age. This wisdom will not come from within. It will always be delivered by an outside source. Scorpio/Tigers must keep their floppy little ears clean and listen carefully to the wise people in their hectic lives. Spunk they have. Sagacity they don’t. When this person finally learns reason and temperance, he can move any mountain he comes upon with a single switch of his tail. Without common sense and measure this person is a goner.

Once the Scorpio/Tiger has assimilated level-headedness as a way of life he or she can go very far indeed. These people boast a certain brilliance, possess panache to burn and are competent in the extreme. There is nothing you cannot entrust to them. They are self-starters, pushy but congenial, and they’ll battle to the death with injustice. Scorpio/Tigers hate rules unless they make them themselves. They always think they know best. They are hotheaded, jealous and ruthless when crossed. They don’t mind brute force but they hate trickery. Scorpio/Tigers stalk dishonesty in the dark of night. They thrive on victory and just about never admit defeat.`,
    love: `This person doesn’t find true love in two weeks. First of all, he or she lives a tumultuous life, full of adventure and change. Without change, the Scorpio/Tiger would turn to drink or drugs. He does not necessarily want to switch partners, and I would even say the Scorpio/Tiger is a faithful type, but he likes to change scenery, alter his habits, move the furniture around in his life. When and if he finds someone to follow this restless prowling, Scorpio/Tiger can settle on a mate. He’s very sexual and can even be kittenish in the bedroom.

If you love a Scorpio/Tiger and wish to remain near him forever, you must first be respectable. Scorpio/Tigers want to be the crazies in the family. They don’t want any competition in the cuckoo department. Moreover, this subject has to feel admiration for the one he loves. Otherwise he loses interest. So be your own person, be thoughtful and wise. Do not, I repeat, do not cling, lean or fawn. All of the above cause Scorpio/Tigers to lose their lunch.`,
    compatibilities: `Bliss might arise from complicity with you and Cancer (born June 21 - July 22), Virgo (born August 23 - September 22), Capricorn (born December 22 - January 19) or Pisces/Horses (born February 19 - March 20 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). You’ll be barking up the right tree if you choose a Dog (born 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) partner from the same western astrological signs. Pisces/Dragon’s (born February 19 - March 20 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) fire will light up your life. Discord, on the other hand, will ensue if you take up with Aries (born March 21 - April 19), Taurus (born April 20 - May 20) or Aquarius/Goats (born January 20 - February 18 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027). Taurus/Snake (born April 20 - May 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025), Taurus/Monkey (born April 20 - May 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) and Taurus/Pig (born April 20 - May 20 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031) could cause you inner turmoil. You will surely quibble with Gemini/Tigers (born May 21 - June 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034). Money will be an issue with Aquarius/Oxen (born January 20 - February 18 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021).`,
    homeAndFamily: `This person’s home will be a palace of funk and whimsy. Scorpio/Tiger is interested in decoration only insofar as it expresses his personality. He moves into a house and guts it, turns it inside out, raises or lowers beams to suit his habits, adds a room for his hobbies, puts in a wall-to-wall dishwasher so he can store up his dirty dishes for weeks. Scorpio/Tigers don’t care to impress anybody, and will arrange their environment to suit themselves and those they love—period!

The Scorpio/Tiger parent is loving but strict. He doesn’t want little Mary or Betty to grow up to be unruly like him. Actually, what Scorpio/Tigers want from their kids is that the kids not need them. Scorpio/Tigers are very private at home and are not eager about helping with homework or putting up Christmas trees. They are sincere parents who care a great deal about their kids but who would prefer not to have to care for them. Nose wiping grates on their nerves.

Little Scorpio/Tigers are defiant and a bit odd. They don’t join in much with the other kids and they always have a thousand projects going at once. They are naturally rebellious, and may think up some doozies to bedevil their parents. They need to be left alone except when they are on the brink of committing some major booboo—which is often.`,
    profession: `If this person has found temperance and buckled under to reason, there is no career closed to him. He is clever and wily, strong and reliable, capable and trustworthy. Trouble is, it usually takes about ten extra years in the young life of this reckless character for him or her to settle down. He likes to test careers, try new projects, join different groups and travel before he is ready to zero in on one in particular. You’ll never meet a Scorpio/Tiger who tells you he always wanted to be a baker and went to baking school at age twelve and here he is at forty still baking bread. No way. Scorpio/Tigers have usually tried at least a hundred different jobs by the time they are forty.

If I were to employ a Scorpio/Tiger, I would keep a close eye on his method of doing things. These people don’t like rules, remember? They tend to make up their own. Let a Scorpio/Tiger loose in your office and you may find your filing system totally reorganized before morning. They are efficient and obedient—but only to a point.

As a boss, the Scorpio/Tiger is loving and tough. These people command respect easily, and as they don’t like bossiness, they try to turn their orders into suggestions. They are not above cleaning latrines, either, as they like to teach by example. They also work well alone.

Some fitting careers for Scorpio/Tigers are: preacher, prospector, psychiatrist, politician, traveling salesman, personnel manager, publicist, journalist, editor, mercenary, leader.`,
  },
  "Scorpio/Rabbit": {
    description: `An imposing figure is the Scorpio/Cat. He is respectable, able to earn and keep his money, and he commands respect from peers. On the outside he is calm and refined. On the inside there’s a blazing fire of intent. Scorpio/Cat means what he says and says only what he means. He’s thought it all through beforehand and believes fervently in whatever theories or precepts he is advancing.

People are inspired by this person’s presence. He has poise and handles tricky situations with aplomb, knowing just how to defuse potentially angry crowds and reckless madmen. The Scorpio side of this person’s nature understands darkness and has a thorough knowledge of what causes fear. The Cat brings him steady-as-you-go tact and finesse.

The combination is unbeatably self-assured. Scorpio tempers the Cat’s squeamishness and gives him the courage to face adversity. The cautious Cat shuts down the Scorpio’s sadism, increasing his capacity for compassion. The outward appearance of this humanitarian soul, then, is dignity personified. Inwardly he may be shuddering with fright at the prospect of what he has undertaken. But never mind. Stage fright is only a passing state of mind. And when Scorpio/Cat finds him or herself in front of the audience, not a hair out of place, not a whisker atwitch, the effect is powerful.

The Scorpio/Cat knows how to make a silk purse from a sow’s ear. He can drag himself up from nothing, bounce back from illness or poverty and sally forth to real success without blinking an eye. This person is a dreamer of impossible dreams and can, quietly and without undue commotion, make his visions into realities.

The Scorpio born Cat is a natural performer too. He is comfortable before a group of people to whom he is delivering a message or teaching a concept. He is not very flexible, however, and can sometimes be accused of bigotry or narrow-mindedness. He believes so fervently in his ideas that he never wants to give them up. He cherishes what he has espoused in the way of creed, and sticks closely to its tenets.

The Scorpio/Cat usually has a good sense of humor. Cats are circumspect and tend to watch the world from a privileged position, hovering about three feet above everybody’s head. Scorpios keep a well-honed tongue in their heads and are ever ready with a sharp crack. The combination can be unbearably acid and satirical.

The secretive or private side of this character is slightly overdeveloped. Scorpio lends suspicion to the Cat’s already stealthy and reticent nature. It won’t do to try and jolly this person out of his private moods. He does not take kindly to criticism, feeling that he is alone the judge of what’s best for him. Scorpio/Cat can be admirable, but also haughty and sometimes pompous.`,
    love: `Love, to the Scorpio born Cat, is a matter of great import. As this person generally has a mission or cause to accomplish in life, he cannot permit himself the luxury of lots of petty superficial affairs. He may err from his solid marriage or stray occasionally from the mate he has chosen, but such peccadilloes will be handled with tact and delicacy. Scorpio/Cats are looking for a mate who will ensure the management of day-to-day events in order that he or she might get on with the serious business of living. If you love a Scorpio/Cat, it is probably because you first admired him. The natural progression with these impressive creatures is from one kind of worship to another, more intimate type. As they are rather strict about their ideas of how you should appear as their mate and cohort, you will need to be adaptable and ready to fit into a mold to please society.`,
    compatibilities: `Your honeymoons will most likely be shared with Cancer (born June 21 - July 22), Virgo (born August 23 - September 22), Capricorn (born December 22 - January 19) or Pisces/Goats (born February 19 - March 20 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027), Pisces/Dogs (born February 19 - March 20 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Pisces/Pigs (born February 19 - March 20 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031). Their love of nature and the good life will help to calm your occasional emotional qualms. Irreconcilable differences exist between you and Taurus (born April 20 - May 20), Leo (born July 23 - August 22) and Aquarius/Roosters (born January 20 - February 18 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029). The Leo/Rat (born July 23 - August 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) will give you trouble too.`,
    homeAndFamily: `Here the Scorpio/Cat is the ruler. All things homelike must revolve about the leader and his or her needs. The main room in the house might well be Scorpio/Cat’s office. The rest will be comfortable and refined in the extreme. But the center of the home for this very “central” person will be decorated to suit his taste. Each individual child may have his or her own color scheme, and yet there will always be the sense that the careful Scorpio/Cat has supervised it all. Clashes are not allowed. Harmony is the objective.

The Scorpio/Cat is a reliable and responsible, if a bit too authoritarian, parent. Rules are unspoken but they are nonetheless laws to be adhered to closely and with respect. The Scorpio/Cat has very likely brought herself to a certain social position through hard work and diligence. She will not tolerate disobedience or bad examples from her kids. Scorpio/Cats like to save face.

As children, these people will be secretive and enjoy playing alone. They will seek audiences for their plans and theories as soon as they are old enough to read and formulate schemes themselves. They like security but are able to overcome upsets gracefully and philosophically. They can be cheeky. It’s best to reason rather than spank. They cannot abide violence.`,
    profession: `It’s fairly obvious to me that these people are made for responsible jobs. They truly enjoy taking care of others and seeing to the well-being of a group. They are serious people whose no-nonsense approach is much appreciated by employers. As they can be haughty and even persnickety and viper-tongued, it’s not easy to be employed by them. They have an attitude of “I’m only doing this for your own good,” which can be trying. Good careers for these people are: astrologer, musician, psychiatrist, research scientist, preacher, tour guide, teacher.`,
  },
  "Scorpio/Dragon": {
    description: `When you add Dragon to Scorpio and mix well to blend, the batter thickens. Scorpio lends mystery and ruthlessness to an already plucky and boastful Dragon nature. Add a dash of swagger and some good old Scorpio vengeance and jealousy and you will concoct yourself a mighty baroque human being. This dish is spicy and copious.

Seriously, the Scorpio/Dragon is a Dragon’s Dragon and a Scorpio’s Scorpio. All of the characteristics of each sign are magnified by their amalgamation. This person is ambitious. She will have masses of personal charm and will know how to go after what she wants. They see no reason why they cannot be head of the world if they so choose.

Scorpio/Dragon holds his scaly green head up so high that he can peer directly over the mountain at the lush green valley of his success. Often, however, his eyes are bigger than his stomach. The mountain he must cross presents him with innumerable insuperables. Trudging from obstacle to obstacle with your pride in your front paws can be discouraging. Scorpio/Dragons have been known to give up. But mostly they bounce back and, like the phoenix, rise from the ashes of their own funeral pyre to strike again.

Scorpio/Dragons come on strong, and have gigantic reserves of courage and cunning. They want to get places in life. They are combative and charming. But their giant pitfall is that they want to be paid homage as well. Modern life is difficult for these haughty creatures. The Scorpio born Dragon has a hard time with moderation. He is drawn to excess and self-indulgence and has a tough time resisting the dissipation of his or her talents. Magnetism is indeed a fabulous trump card in the game of life. But it is not quite sufficient to ensure either success or happiness. Some warmth, pith and density must be incorporated very early on in the preparative stages of this person’s life. He must not get carried away from basics and then one day find himself standing naked and frightened atop his mountain—alone! The Scorpio/Dragon may seem invincible, but he’s still a Dragon and he’s sentimental. Deep down he weeps over stories about lost dogs. He’s a pushover and a soft touch. Perhaps that’s why he seems stonefacedly to have no sense of humor. He doesn’t want to show his hand. Scorpios born in Dragon years are strongly individualistic. They have plenty of imagination and can think up a hundred new schemes a minute.

People automatically like them and even agree to take them in and feed them and care for them because of their unusualness. Thing is, the Scorpio/Dragon is not always cooperative and sometimes gets asked to leave after only a few days. Why? Because in their struggle for singularity, these people often alienate the very plain folks they need most by snubbing them or simply ignoring their needs. It doesn’t hurt a Scorpio/Dragon to help with the dishes. But it somehow doesn’t occur to him or her that such lowly tasks exist. I’m not suggesting that the Scorpio/Dragon is a snob. He’s just oblivious to simplicity.`,
    love: `You cannot expect this passionate fanatic to cool his ardor anywhere—especially in the bedroom. The Scorpio/Dragon is adorable and knows how tempting he seems to potential lovers and mistresses. But sometimes, just to be perverse, he will be faithful in the extreme to a single and wonderful person who knows just how to applaud the Scorpio/Dragon while twisting his earlobe to make him behave.

Scorpio/Dragons like to think they are sexually free. If you love one of these interesting and irresistible characters, I advise you to give her lots of space to roam about, lots of liberty and the distinct impression you couldn’t care less whom she gets involved with. Such a casual attitude will keep her close to home. Your apparent indifference will serve as a challenge to her. Scorpio/Dragons are predictably jealous.`,
    compatibilities: `Snuggle up to a Virgo (born August 23 - September 22), Capricorn (born December 22 - January 19) or Pisces/Ox (born February 19 - March 20 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) or Pisces/Monkey (born February 19 - March 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028). Cancer (born June 21 - July 22), Capricorn and Pisces from the Tiger (born 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) group are your second marriage signs. Cancer/Rat (born June 21 - July 22 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) and Pisces/Rat (born February 19 - March 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) are both terrific in bed. Cancer and Virgo/Roosters (born 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) turn you on as well. And the luxury-loving Cancer/Snake (born June 21 - July 22 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) is one of your surest matches made in heaven. Dragons get along with practically everybody except the Leo/Ox (born July 23 - August 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) and Aquarius/Ox (born January 20 - February 18 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), the Taurus/Rabbit (born April 20 - May 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and the Leo/Rabbit (born July 23 - August 22 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), and Taurus (born April 20 - May 20), Leo (born July 23 - August 22) and Aquarius/Dog (born January 20 - February 18 in the years 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030).`,
    homeAndFamily: `The Scorpio/Dragon likes a comfortable home, but he’s not one to putter about clipping the hedges and evening out the flowerbeds. Scorpio/Dragons don’t see the need for excessive nit-picking in decoration. They like clean lines and surfaces on which to work and/or receive their multitudes of guests. They impress as much with their presence as with their interior, so they often don’t make much of the latter.

The Scorpio/Dragon parent is patently crazy about his or her kids. These are proud people, remember. They set great store by their kids and are proud of what their kids achieve. They love unconditionally, yet expect great deeds. The Scorpio/Dragon parent knows how to play with kids and will invent games and spend time with the little ones. He can also be a grabby parent. I would not, for example, want to have a Scorpio/Dragon mother-in-law. The Scorpio/Dragon child is indestructibly perky. You will want to take him or her home with you. They smile and giggle and coo and sing little songs to charm and win attention. They can be sulky, too. But nonetheless you will be hard put not to spoil this little tyke. If you resist the temptation to shower him or her with admiration and worship, this kid will have a chance to learn humility. A measure of modesty learned early on will be money in the bank for this prideful darling.`,
    profession: `The Scorpio/Dragon career is often pockmarked with mini failures. I don’t want to sound discouraging, but the Scorpio/Dragon person has more fervor than he does perseverance, and sometimes expects too much in return for the effort exerted. In order to prosper, this person must first learn to hold his emotional tongue and not consider anything gained until all the bets are in. He will benefit from a solid classical education, against which he will probably rebel. Find that person who knows how to twist earlobes so lovingly and put him or her on the case.

This subject wants power over others. It does not, however come easily. Conferring authority on one so self-enraptured is tricky and dangerous. As a boss, this person could be perfectly heinous. As an employee with an impressive title, the Scorpio/Dragon and his coworkers are better off. Watch him or her for streaks of lording it over others. Keep the Scorpio/Dragon busy and insist he apply his fine imagination to getting concrete results. A happy Scorpio/Dragon is an occupied one. Careers that might suit this heady personality are: TV performer, politician, fashion designer, public relations officer, mercenary, undercover agent, entrepreneur, gossip columnist, religious leader.`,
  },
  "Scorpio/Snake": {
    description: `To a Scorpio/Snake, life without beauty and luxury, tenderness, compassion, admiration and extravagance is not worth living. This person is sensitive in the extreme and, for a cool-handed Snake, remarkably warmhearted and loving. People appreciate this character for a certain innate nobility, which is both unquestionable and very comforting. Scorpios are already very sensual people with a tendency to introspect and suspect. To add the Snake characteristics of sagacity, clairvoyance and intuition certainly doesn’t diminish the philosophical side of Scorpio’s nature. This person is deep-thinking, sometimes even tormented.

There will necessarily exist in Scorpio/Snake’s makeup a flamboyance and attention to wardrobe that sets him or her apart from the rest of us. You will never see a shabbily dressed Scorpio/Snake. They may be said to push personal appearance to the limit. Their manner of getting themselves up might even be called “costuming.” They are invariably arrayed in finery so unusual as to be stunning, and fit only for their type of personality. This person has a native ability to intuit the needs and desires of others. He or she is able to understand nuances that escape even the most discerning audience. Scorpios born in Snake years have a kind of special genius for picking up hints and following hunches that takes them very far in a worldly way. It may be something as simple as guessing the direction a stock will take or foreseeing the need for a certain market in commodities or goods. Scorpio/Snakes are not often poor.

The variety of superiority that the Scorpio born Snake possesses is of near cosmic proportions. You cannot encounter a Scorpio/Snake and come away from said meeting without a vivid picture in your mind’s eye. Snakes born Scorpio may not impress you favorably, but they always impress you. You see, they embody a sort of arrogance that, I suppose, arises from the fact that they have easy success in life, are lucky with money and generally suffer only from emotional pain that they inflict on themselves. Scorpio/Snakes preen a lot and keep their noses in the air. The effect is not “Look at me!” the way it might be with a Dragon or even a Rat personality. Rather, Scorpio/Snakes command attention. The unspoken charisma is just there.

As you might have already guessed, the Scorpio/Snake’s ego fares well. There is a very healthy sense of self here. But Scorpio/Snakes don’t let their ego get too far ahead of their inner logic. They strike a careful balance between reality and dreams. Oh, they are capable of lying. The famous Snake powers of dissimulation are very active in this subject. But Scorpio/Snakes don’t often lie to themselves. They like to maintain a cool head no matter what cloud tempts them to climb on for a joyride. Scorpio/Snakes are jealous people. They want to keep everything—especially power—for themselves and their loved ones. They don’t like to share the spotlight and they make no bones about it. As Snakes go, the Scorpio is not too lazy, either. He’s so avid for gain and attention that his ambition keeps him moving. Fact is, he doesn’t have to make much effort to succeed. It comes naturally.`,
    love: `Everybody wants to love a Scorpio/Snake. These characters are so untouchably gorgeous and unutterably cool that they can literally be said to attract everyone. But don’t worry. The Scorpio/Snake is choosy about whom he takes up with. Often, this person takes a mate he or she can manipulate and even enslave.

If you love a Scorpio/Snake, join the club. Get in line. Queue up. Really, if you are attracted to such a person, it’s no surprise. It’s not even your fault. If you like being outshone in public, take up with one of these stars. You had best enjoy staying home and burning those fires because Scorpio/Snake will be out slaloming through the admiring hordes whether you like it or not.`,
    compatibilities: `You and the Dragon (born in 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) are fast friends. Choose yours from out of the Virgo (born August 23 - September 22), Capricorn (born December 22 - January 19) and Pisces (born February 19 - March 20) lot. There are four Roosters (born 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) who love your company. They are Cancer (born June 21 - July 22), Virgo, Capricorn and Pisces/Roosters. Accept no substitutes. And then there’s a Cancer/Ox (born June 21 - July 22 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). And that’s about it for affinities. Less advantageous are alliances with Taurus (born April 20 - May 20), Leo (born July 23 - August 22) and Aquarius/Monkeys (born January 20 - February 18 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028). Taurus and Leo/Tigers (born 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) are not quite perfect for you, either. If you care about your self-respect, avoid Taurus and Gemini/Pigs (born 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031).`,
    homeAndFamily: `The Scorpio/Snake home will be large and impressively decorated. Silks and brocades abound. The last little pickle fork will have been hand-fashioned of vermeil. Luxe ain’t the word. Posh is more like it. The Scorpio/Snake resides in a decor comparable to his stature and opinion of herself.

The Scorpio/Snake parent is serious but likes to be quite indulgent with little ones. He or she will spoil children materially but demand that they appear like ladies and gentlemen for company. There can be a problem of jealousy here. Scorpio/Snakes don’t take kindly to competition for attention. If the kids are too charming, Mom or Pop might freak. The house should perhaps be outfitted with wall-to-wall spotlights.

These kids will be, first of all, extraordinarily attractive. They will probably have to be protected from admirers and taught that there is more to life than being an eye-catcher. They will also tend to fib. Don’t wash their mouths out with soap. Show them instead that you have seen through them. Scorpio/Snake kids operate best when parents are firm but loving. Don’t be seduced by this wily beauty. He or she needs you, the parent, to represent truth.`,
    profession: `This person is mostly creative. He or she will take to all activity wherein the spirit of invention is useful and applicable. Scorpio/Snakes might work well alone but can fit into the system, provided the system recognizes their superiority and remunerates it accordingly.

Bossing suits the Scorpio/Snake best. He will be a reluctant subordinate. If he is the boss, you can expect him to be democratic and understanding of his workers. He likes to have power, but is not one to wield it unless crossed or pushed. Then, watch out. Scorpio/Snakes are ruthless and attack their enemies pitilessly. Competition? Never heard of it.

Natural careers for this super Snake are: king, queen, movie star, pope, and so on. But in reality, if they have to actually work at jobs, they might like to try: modeling, acting, advertising, or stocks and bonds. They make terrific artists, too.`,
  },
  "Scorpio/Horse": {
    description: `This jaunty creature embodies most of the positive traits of the signs it combines. Scorpio/Horses are magnetic. And they are popular. They are disciplined and accomplished. They are persuasive and inspired, dedicated and fashionable. Scorpios born in Horse years are both independent and autonomous. There is little to prevent these folks from succeeding in a world class way.

This character has the vision and perspicacity of Scorpio and knows how to couple it with the Horse’s natural vitality. He will take on projects that would cow anyone less competent, and carry them to their logical ends with remarkable facility. The Scorpio/Horse is a doer of impossible deeds. Success is written all over whatever he touches. He’s not afraid of work and he’s got some of the most unbelievably fanciful notions you ever heard of. This bent for fantasy can sometimes be his undoing. The Scorpio born Horse does not fit in well with his peers. He is popular and admired, but people don’t understand him very well. He’s too different. He’s too odd to make others feel completely comfortable about him. Scorpio/Horse is, moreover, unafraid of popular opinion and carries on with his fancy ideas no matter what or who tries to get in his way. He’s not cruel. Just ruthlessly determined to get where he is going.

Scorpio/Horse takes no detours, either. Nor does he beat around the bush. He says what he thinks needs saying and then he sits calmly watching the fireworks. He is the voice of truth. He proclaims outrageous verity with apparent impunity. Once you know this person and understand how extraordinarily individualistic he really is, you expect the satirical banter, which can also make you crack up laughing.

The Scorpio/Horse has a rather difficult time getting started in life. He is easily affected by his surroundings, and if his family life is not perfectly peaceful, he can suffer undue guilt feelings. He’s an anxious sort, and so sensitive to what is going on around him that he feels responsible and may retreat into his shell as a child. As a young adult he will search hard to find his true path. Once he gets past thirty, nothing can stop him. He’s a winner, an eccentric, and quite a deep thinker as well.

Scorpio/Horses likes to dress up in fanciful garb. They are drawn to the conservative but find adding a rhinestone clip or splashy tie irresistible. He likes to present well and is overly concerned about physical attributes, both in himself and others. He cares if he’s going bald. She worries if she notices a wrinkle.

This person will have excellent skill with things manual. He or she may build rooms or restore old houses or design wallpapers or knit shawls with weird patterns in them. Scorpio/Horse is, in fact, a bit of a bohemian by nature, and does not hesitate to flout convention or commit acts that “shock” society. Scorpio/Horses are compassionate and will help out those less fortunate than themselves. They are not comfortable with money. They are, by turns, stupidly spendthrift and stingy.`,
    love: `The love life of Scorpio/Horse people is rarely based on undying passion. Scorpio/Horses, like all other horses, are practical above and beyond everything. They choose mates for their convenience and comfort. They take lovers if they need to enjoy the odd fling. But inside their marriages they appear staid and perfectionist.

Have you a Scorpio/Horse mistress or lover? If so, you already know that she or he is totally weird and wonderful. There is depth and charm in this character. You will be entertained and amused. The Scorpio/Horse likes sports and enjoys games. You will love him or her best by standing by in times of crisis and otherwise staying out of his or her way. The Scorpio/Horse needs a helpmate in the truest sense. He would like to do it all himself and certainly could—but he’d rather have a nice sidekick.`,
    compatibilities: `If you meet up with a tawny Tiger (born in 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034) or graceful Goat (born in 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027), you’ll probably fall for the Cancer (born June 21 - July 22), Virgo (born August 23 - September 22), Capricorn (born December 22 - January 19) or Pisces (born February 19 - March 20) variety. The Virgo and Pisces/Dogs (born 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030), despite their apparent disquietude, appeal to your sense of caring. Rats never get on with Horses. Be particularly wary of Taurus (born April 20 - May 20), Gemini (born May 21 - June 20), Leo (born July 23 - August 22) and Aquarius/Rats (born January 20 - February 18 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032), especially when it comes to matters of the home. Aquarius/Rabbit (born January 20 - February 18 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) is the last person on Earth you should hang around with.`,
    homeAndFamily: `Scorpio/Horse is meticulous about his interior. He wants it just right and comfortable as well as beautiful. He likes things orderly but is not maniacal about cleanliness. Mostly, Scorpio/Horse is conscientious about his surroundings, and if they are pleasant it is because he made them that way. As a parent, this person can be accused of fanaticism. Scorpio/Horses adore their kids. They live for their offspring and they do far too much for them. They give their kids everything any kid could want, and more. They spend time with them and they play with them. Scorpio/Horses should have scads of children. They are really good at it.

These children are cuddly and wise, sensitive and sensible. If a parent says “You can’t have that today, dear,” the Scorpio/Horse child, reasonable beyond his years, will invariably say, “All right. I can always have it another time.” These kids are loving and easy to raise. They go it alone for most of their lives, and ask little more than love and feeding. They spend much time on their own, and like to be allowed to do crafts and pursue hobbies.`,
    profession: `Gifted for achievement, the Scorpio born Horse mutely proclaims from the moment he is born, “I demand to create.” It is a motto that suits him down to the ground. He will carry off all professions with aplomb but will be best suited to artistic ones.

As an employee, the Scorpio/Horse may prove unruly. He hates routine. He can adjust to workday habits, but he prefers to do things on his own time and in his own personal way.

I see the Scorpio/Horse best suited for leadership or even for independent solitary work. He is always champing at the bit to get his project done. He needs little prodding.

There is no reason Scorpios born in Horse years cannot be bosses. But I expect they would have difficulty delegating authority and might tend to do rather too much of the work themselves.

Suitable careers for this character are: undercover agent, lawyer, medical researcher, entrepreneur, chef, choreographer, singer, city planner, graphic artist, film producer, actor.`,
  },
  "Scorpio/Goat": {
    description: `This person is a fanciful dreamer. He or she has the Scorpio’s depth and magnetism and is gifted with the Goat’s marvelous ability to live with his head in the clouds whilst keeping both feet firmly planted on terra firma. Scorpios born in Goat years are people with vast imaginary resources who, if they can tear themselves away from their rich inner lives, are able to move mountains in the real world.

The Scorpio/Goat is a visionary. He sees life through a special lens that lends beauty to the ugliest situations and glamour to the most banal. This person has a fine imagination and a deep-rooted desire to create. He is talented for all sorts of artistic endeavor and can probably paint or write or compose music better than the next guy. The Scorpio born Goat is often a shade too sensitive for his own good. He is easily hurt and frequently disappointed by the harsh realities of life.

As a Scorpio, this person is quite secretive and likes to maintain a certain mystery about his comings and goings. The Goat side of his nature, however, makes him slightly dependent on others and causes him to seek out friends and colleagues to lean on. This character will always be a bit of a paradox to his peers. On the one hand, he wants to be private and keep his own counsel. On the other, he is needy and seeks approval from those around him.

Scorpio/Goat has a highly developed sense of the aesthetic. He is drawn to beauty in all its forms and will go to great lengths to acquire lovely objects and live in harmonious surroundings. This person is also quite spiritual and may be attracted to religion or the occult. He’s a deep thinker who spends a lot of time mulling over the meaning of life.

The Scorpio/Goat’s major flaw is his tendency to pessimism. Because he is so sensitive, he takes life’s knocks very hard. He may wallow in self-pity if things don’t go his way. This person must learn to bounce back from adversity and not allow himself to be crushed by setbacks. He is also prone to laziness and can be a bit of a parasite, relying on others to do the hard work while he dreams up new schemes.`,
    love: `In love, the Scorpio/Goat is tender and passionate. He seeks a partner who can understand his complex nature and provide the emotional support he craves. This person is not one for casual flings; he wants deep, meaningful connections that feed his soul. He can be jealous and possessive, but his devotion is unwavering once he commits.

If you love a Scorpio/Goat, be prepared to offer a lot of reassurance and stability. This person needs to feel secure in a relationship and will not tolerate betrayal or disloyalty. Be patient with his mood swings and try to appreciate his artistic and spiritual side. A partner who can share in his dreams and visions will win his heart forever.`,
    compatibilities: `You’ll find harmony with Cancer (born June 21 - July 22), Virgo (born August 23 - September 22), Capricorn (born December 22 - January 19), or Pisces/Rabbits (born February 19 - March 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), Pisces/Pigs (born February 19 - March 20 in the years 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031), and Pisces/Horses (born February 19 - March 20 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). These signs appreciate your sensitivity and will provide the emotional grounding you need. Less compatible are Taurus (born April 20 - May 20), Leo (born July 23 - August 22), and Aquarius/Oxen (born January 20 - February 18 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021), who may find your dependency and moodiness hard to handle. Taurus and Aquarius/Dogs (born 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030) and Taurus/Rats (born April 20 - May 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032) are also likely to clash with your sensitive nature.`,
    homeAndFamily: `The Scorpio/Goat’s home will be a reflection of his artistic soul. Expect eclectic decor, with an emphasis on beauty and comfort. This person loves to surround himself with objects that inspire him, and his home will likely be filled with art, books, and unusual treasures.

As a parent, the Scorpio/Goat is loving but can be overly protective. He wants his children to have the freedom to dream and create, but he may struggle with letting them face the world’s harsh realities. He’s a nurturing parent who will encourage his kids’ artistic talents and spiritual growth.

The Scorpio/Goat child is imaginative and sensitive. He may be shy or withdrawn at times, needing extra encouragement to come out of his shell. This child thrives in a supportive environment where his creativity is nurtured and his emotions are validated.`,
    profession: `The Scorpio/Goat excels in careers that allow him to express his creativity and vision. He’s not cut out for mundane or overly structured jobs. Artistic fields like painting, writing, music, or design are ideal, as are roles that involve helping others, such as counseling or spiritual guidance.

As an employee, the Scorpio/Goat can be a bit unreliable if the job doesn’t inspire him. He needs work that feeds his soul, or he’ll quickly lose interest. As a boss, he’s compassionate but can be moody, which may confuse his team. He’s best suited to roles where he can work independently or in a creative team environment.

Some suitable careers: artist, writer, musician, interior designer, counselor, spiritual leader.`,
  },
  "Scorpio/Monkey": {
    description: `The Scorpio/Monkey is a powerhouse of energy and cunning. This person combines Scorpio’s intensity and magnetism with the Monkey’s quick wit and resourcefulness. The result is a dynamic individual who can charm, manipulate, and outsmart just about anyone. Scorpio/Monkeys are driven by a desire for success and will use their considerable intelligence and charisma to get what they want.

This person is a master of improvisation. No matter what life throws at them, they can think on their feet and come up with a plan. They’re not afraid to bend the rules or use a bit of cunning to achieve their goals. Scorpio’s depth gives them a keen understanding of human nature, which they use to their advantage in social and professional situations.

The Scorpio/Monkey is fiercely independent and doesn’t like being told what to do. They have a strong sense of self and are confident in their abilities. However, their manipulative streak and tendency toward deceit can get them into trouble. They need to be careful not to alienate others with their scheming ways.

This person is also highly creative and loves to tackle challenges. They thrive in environments where they can use their problem-solving skills and think outside the box. However, their intense focus on their own goals can make them seem self-involved or even ruthless at times.

The Scorpio/Monkey’s biggest challenge is learning to balance their ambition with integrity. They have the potential for great success, but only if they can resist the temptation to take shortcuts or manipulate others for their own gain. When channeled positively, their energy and intelligence can lead to remarkable achievements.`,
    love: `In love, the Scorpio/Monkey is passionate, intense, and a little bit dangerous. They’re drawn to partners who can match their wit and keep up with their fast-paced lifestyle. They love the thrill of the chase and can be quite seductive, but they’re not always looking for long-term commitment.

If you love a Scorpio/Monkey, be prepared for an exciting but unpredictable ride. This person needs a partner who is strong-willed and independent, as they have little patience for clinginess or neediness. Honesty is crucial in a relationship with a Scorpio/Monkey, as they can be suspicious and jealous if they feel betrayed.`,
    compatibilities: `You’ll find great chemistry with Cancer (born June 21 - July 22), Virgo (born August 23 - September 22), or Pisces/Dragons (born February 19 - March 20 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024) and Pisces/Rats (born February 19 - March 20 in the years 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032). These signs can handle your intensity and appreciate your cleverness. Less compatible are Taurus (born April 20 - May 20), Leo (born July 23 - August 22), and Aquarius/Tigers (born January 20 - February 18 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034), who may find your manipulative tendencies off-putting. Taurus/Snakes (born April 20 - May 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Aquarius/Horses (born January 20 - February 18 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026) are also likely to clash with your strong personality.`,
    homeAndFamily: `The Scorpio/Monkey’s home is likely to be a lively, eclectic space that reflects their dynamic personality. They enjoy modern, functional decor but may add quirky or unexpected touches to keep things interesting. They’re not overly attached to their home, as they’re often out chasing their next adventure.

As a parent, the Scorpio/Monkey is fun-loving and encouraging but can be a bit inconsistent. They want their children to be independent and creative, but their own busy lifestyle may mean they’re not always available. They’re great at inspiring their kids but need to work on being more present.

The Scorpio/Monkey child is a handful—clever, mischievous, and always up to something. They need firm boundaries and plenty of mental stimulation to keep them out of trouble. Encourage their creativity but watch out for their tendency to manipulate or bend the truth.`,
    profession: `The Scorpio/Monkey is a natural leader who excels in fast-paced, challenging environments. They’re drawn to careers that allow them to use their intelligence, creativity, and charisma. They’re particularly good at roles that involve strategy, negotiation, or problem-solving.

As an employee, the Scorpio/Monkey is innovative but may struggle with authority. They prefer to work independently or in roles where they have a lot of freedom. As a boss, they’re inspiring but can be demanding and impatient. They need to learn to temper their intensity to get the best out of their team.

Some suitable careers: entrepreneur, marketing executive, strategist, lawyer, actor, inventor.`,
  },
  "Scorpio/Rooster": {
    description: `The Scorpio/Rooster is a formidable combination of intensity and precision. This person is driven, focused, and fiercely determined to succeed. Scorpio’s passion and magnetism blend with the Rooster’s shrewdness and organization to create a personality that is both charismatic and meticulous.

Scorpio/Roosters are natural leaders who command attention wherever they go. They have a sharp mind and a keen eye for detail, which makes them excellent at spotting flaws or opportunities others might miss. They’re not afraid to speak their mind and will do so with a candor that can sometimes be shocking.

This person is highly disciplined and expects the same from those around them. They have little patience for laziness or incompetence and can be harsh critics when things don’t meet their high standards. Their perfectionism can make them difficult to work with, but it also ensures that they produce outstanding results.

The Scorpio/Rooster’s biggest challenge is their tendency toward obsession and vindictiveness. They can become fixated on their goals or grudges, which can lead to tunnel vision or destructive behavior. They need to learn to let go and not take every slight personally.

Despite their intensity, Scorpio/Roosters have a softer side. They’re capable of great tenderness and loyalty toward those they care about. They’re also surprisingly witty and can use their sharp tongue to entertain as well as to criticize.`,
    love: `In love, the Scorpio/Rooster is passionate and demanding. They want a partner who can match their intensity and share their drive for success. They’re fiercely loyal but can be jealous and possessive, expecting complete devotion in return.

If you love a Scorpio/Rooster, be prepared to meet their high expectations. They need a partner who is confident, capable, and not easily intimidated. Honesty and loyalty are non-negotiable, as this person has no tolerance for betrayal. Show them respect and admiration, and they’ll reward you with unwavering devotion.`,
    compatibilities: `You’ll find strong connections with Cancer (born June 21 - July 22), Virgo (born August 23 - September 22), Capricorn (born December 22 - January 19), or Pisces/Snakes (born February 19 - March 20 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025) and Pisces/Oxen (born February 19 - March 20 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021). These signs appreciate your discipline and can handle your intensity. Less compatible are Taurus (born April 20 - May 20), Leo (born July 23 - August 22), and Aquarius/Rabbits (born January 20 - February 18 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), who may find your critical nature too harsh. Taurus/Rabbits (born April 20 - May 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and Aquarius/Monkeys (born January 20 - February 18 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) are also likely to clash with your strong personality.`,
    homeAndFamily: `The Scorpio/Rooster’s home is impeccably organized and stylish, reflecting their need for order and beauty. They take pride in creating a space that is both functional and aesthetically pleasing, with every detail carefully considered.

As a parent, the Scorpio/Rooster is strict but loving. They want their children to succeed and will push them to achieve their best. They can be overly critical at times, so they need to balance their high expectations with encouragement and praise.

The Scorpio/Rooster child is bright, confident, and a bit bossy. They like to be in charge and may struggle with sharing or compromising. They need parents who can provide structure while allowing them to express their individuality.`,
    profession: `The Scorpio/Rooster is a powerhouse in the workplace. They excel in roles that require precision, leadership, and strategic thinking. They’re not afraid to take charge and will work tirelessly to achieve their goals.

As an employee, the Scorpio/Rooster is reliable but can be difficult to manage due to their strong opinions and perfectionist tendencies. As a boss, they’re demanding but fair, expecting everyone to meet their high standards. They thrive in environments where their leadership and organizational skills can shine.

Some suitable careers: CEO, editor, surgeon, architect, financial analyst, critic.`,
  },
  "Scorpio/Dog": {
    description: `The Scorpio/Dog is a complex and intense individual, blending Scorpio’s depth and magnetism with the Dog’s loyalty and vigilance. This person is fiercely protective of those they love and will go to great lengths to defend their principles and loved ones. They have a strong sense of justice and are not afraid to stand up for what they believe in, even if it makes them unpopular.

Scorpio/Dogs are deeply intuitive and can often sense trouble before it arrives. Their watchful nature makes them excellent judges of character, and they’re not easily fooled. However, their suspicious and cynical side can make them overly cautious or even paranoid at times. They need to learn to trust others and not let their fears get the better of them.

This person is highly disciplined and has a strong work ethic. They’re not afraid of hard work and will push themselves to achieve their goals. However, their tendency toward worry and inner anxiety can hold them back, causing them to second-guess themselves or become overly critical of their own efforts.

The Scorpio/Dog is a loyal friend and a formidable enemy. They don’t forgive easily and can hold grudges for a long time. Their aggressive streak can come out when they feel threatened or betrayed, but they’re also capable of great tenderness and compassion toward those they trust.`,
    love: `In love, the Scorpio/Dog is intensely loyal and deeply emotional. They seek a partner who can provide stability and security, as they need to feel safe in a relationship. They’re not interested in superficial connections and will only commit to someone they truly trust.

If you love a Scorpio/Dog, be prepared for their intense emotions and occasional moodiness. They need a partner who is patient, understanding, and willing to stand by them through thick and thin. Betrayal is the ultimate sin in their eyes, so honesty and loyalty are essential.`,
    compatibilities: `You’ll find harmony with Cancer (born June 21 - July 22), Virgo (born August 23 - September 22), Capricorn (born December 22 - January 19), or Pisces/Tigers (born February 19 - March 20 in the years 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034), Pisces/Rabbits (born February 19 - March 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035), and Pisces/Horses (born February 19 - March 20 in the years 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026). These signs share your need for loyalty and emotional connection. Less compatible are Taurus (born April 20 - May 20), Leo (born July 23 - August 22), and Aquarius/Dragons (born January 20 - February 18 in the years 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024), who may find your intensity overwhelming. Taurus/Oxen (born April 20 - May 20 in the years 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021) and Aquarius/Monkeys (born January 20 - February 18 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) are also likely to clash with your strong personality.`,
    homeAndFamily: `The Scorpio/Dog’s home is a sanctuary, designed to provide comfort and security. They prefer a cozy, welcoming environment where they can relax and feel safe. Their home may be filled with sentimental items that hold deep meaning for them.

As a parent, the Scorpio/Dog is fiercely protective and deeply devoted. They’ll do anything to keep their children safe and happy, but their worry and anxiety can make them overbearing at times. They need to give their kids room to grow while providing a stable, loving environment.

The Scorpio/Dog child is sensitive and perceptive, often picking up on emotions that others miss. They need a supportive environment where they feel secure and valued. Encourage their independence while reassuring them of your love and support.`,
    profession: `The Scorpio/Dog excels in careers that require dedication, intuition, and a strong sense of justice. They’re drawn to roles where they can make a difference, whether through protecting others or fighting for a cause. They’re not afraid of responsibility and will take on challenging tasks with determination.

As an employee, the Scorpio/Dog is reliable and hardworking but can be stubborn and resistant to change. As a boss, they’re fair but demanding, expecting loyalty and commitment from their team. They thrive in environments where their skills and dedication are appreciated.

Some suitable careers: lawyer, detective, social worker, therapist, activist, security consultant.`,
  },
  "Scorpio/Pig": {
    description: `The Scorpio/Pig is a fascinating blend of intensity and indulgence. This person combines Scorpio’s passion and magnetism with the Pig’s love of pleasure and sincerity. The result is a charismatic, larger-than-life individual who lives life to the fullest and isn’t afraid to go after what they want.

Scorpio/Pigs are deeply emotional and have a strong desire to connect with others. They’re generous and warmhearted, always ready to lend a hand or share their good fortune. However, their intense Scorpio nature makes them prone to jealousy and possessiveness, and they can be hot-tempered when crossed.

This person loves the finer things in life—good food, beautiful surroundings, and luxurious experiences. They have a strong sense of aesthetics and may be drawn to art, fashion, or design. Their love of pleasure can sometimes lead to excess, and they need to be careful not to overindulge in food, drink, or other temptations.

The Scorpio/Pig is highly driven and has the stamina to achieve their goals. They’re not afraid to work hard, but they also expect to enjoy the fruits of their labor. Their sincerity and gallantry make them well-liked, but their naiveté and gullibility can sometimes get them into trouble. They need to be cautious about who they trust.

Despite their occasional excesses, Scorpio/Pigs are deeply loyal and caring. They’ll go to great lengths to protect their loved ones and will fight fiercely for what they believe in. Their combination of passion, dedication, and warmth makes them unforgettable.`,
    love: `In love, the Scorpio/Pig is passionate, romantic, and deeply devoted. They seek a partner who can share their love of life and provide the emotional intensity they crave. They’re not afraid to dive headfirst into a relationship, but their possessiveness and hot temper can create challenges.

If you love a Scorpio/Pig, be prepared for a whirlwind romance filled with passion and excitement. They need a partner who is strong enough to stand up to them but also appreciates their warmth and generosity. Honesty and loyalty are crucial, as this person has no tolerance for betrayal.`,
    compatibilities: `You’ll find great chemistry with Cancer (born June 21 - July 22), Virgo (born August 23 - September 22), Capricorn (born December 22 - January 19), or Pisces/Rabbits (born February 19 - March 20 in the years 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035) and Pisces/Goats (born February 19 - March 20 in the years 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027). These signs share your love of beauty and emotional connection. Less compatible are Taurus (born April 20 - May 20), Leo (born July 23 - August 22), and Aquarius/Snakes (born January 20 - February 18 in the years 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025), who may find your intensity and possessiveness overwhelming. Taurus/Monkeys (born April 20 - May 20 in the years 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028) and Aquarius/Roosters (born January 20 - February 18 in the years 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029) are also likely to clash with your strong personality.`,
    homeAndFamily: `The Scorpio/Pig’s home is a luxurious, welcoming space filled with beautiful objects and comfortable furnishings. They love to entertain and will go all out to make their guests feel special. Their home is a reflection of their personality—bold, vibrant, and full of life.

As a parent, the Scorpio/Pig is warm, generous, and deeply devoted. They want their children to have the best of everything and will work hard to provide for them. However, their tendency to spoil their kids can lead to problems, and they need to balance indulgence with discipline.

The Scorpio/Pig child is charming, affectionate, and a bit spoiled. They love attention and may act out if they don’t get it. They need parents who can provide a loving but structured environment to help them develop their potential.`,
    profession: `The Scorpio/Pig excels in careers that allow them to combine their passion, creativity, and love of beauty. They’re drawn to roles that involve art, design, or hospitality, as well as those that require dedication and stamina. They’re not afraid to take on big projects and will work tirelessly to achieve success.

As an employee, the Scorpio/Pig is hardworking but can be stubborn and resistant to criticism. As a boss, they’re generous and inspiring but may expect too much from their team. They thrive in environments where they can express their creativity and connect with others.

Some suitable careers: chef, fashion designer, event planner, artist, hotel manager, public relations specialist.`,
  },
};
