
export const dragon = {
    introduction: `Magnificent Dragon, self-assured, dynamic, and rarely inconspicuous, you are a born master of ceremonies. Be it fireworks, parties, festivals, holidays, or rallies: you know how to initiate events and keep them lively. You are spirited and endowed with power and good fortune.

People admire you. You can be flamboyant—and a bit of a braggart. When you believe you are correct, you are unyielding. In business, you appear formidable. You are shrewd and not easily deceived. But even you, dauntless Dragon, are not invincible. All those flames are merely camouflage. Beneath, you are easily influenced, a pushover. You are deeply moved by the sight of a weeping willow. Sentimentality lies just beneath the surface of that scaly green exterior. You cannot resist its emotional pull.

Faithful to friends and loyal to family, you are sometimes less so in romantic matters. You are devastatingly attractive, and romantic too. You long to retreat into one cave after another with a series of passionate lovers who simultaneously excite, challenge, and thrill. You dream of a lifelong moment of ecstasy.

Engage in flirtation with a hard-driving Rat or a clever Monkey. But when you choose a mate, select a reliable Rooster or a Tiger (your accomplice). Do not bother with taciturn Oxen. Outspoken Dogs will both attract and challenge you. A regulated, disciplined family and school life in childhood may frustrate your need for applause and unearned attention, but it may also set you on a more realistic path than one you would have chosen yourself. Your mid-life crisis will be spectacular! But if you are still alive at age fifty, your hard work will begin to yield rewards. You know how to learn from your mistakes. Dare I offer you advice? Do not let your ego overpower your intellect. Practice laughing at yourself in the mirror. Lower your profile. Consume plenty of humble pie.`,
    elements: {
        Wood: `The Wood Dragon is the most amiable and sociable of all Dragons. He is a ray of sunshine, full of goodwill and helpfulness, freely offering advice and assisting his friends whenever called upon. He is a devoted partner, never shirking duty or responsibility once accepted.

This Dragon also possesses a special capacity for profound philosophical thought. His ability to handle abstract concepts and synthesize ideas from them is well-known and highly regarded among his peers.

The Wood Dragon is also a peacemaker. He can swiftly defuse a potentially explosive situation with his clever tongue, injecting humor and light-hearted logic into stressful circumstances. His counsel is often sought by influential individuals, as he has an uncanny talent for seeing through ambiguous situations and uncovering the truth. Although he does not consciously intend to cause pain, his incisive comments often strike a sensitive chord.

Wood Dragons are so perceptive and open-minded that they could become seers or spiritual leaders. Concepts from realms beyond our world seem to reach this individual, and the Wood Dragon often knows what will happen before it occurs. This gift enables him to pursue astrology, study metaphysics, or become a prophet or healer. A Wood Dragon could also enter the medical and religious professions or even politics and government. Because he is multi-talented, he might choose painting, sculpting, writing, or acting, but whatever his choice, the Wood Dragon will never be bored or boring. His life is filled with activities and hobbies. As long as he can sew or build, plant and pot, paint and decorate after work, the Wood Dragon is content.

This artistic inclination diminishes some of the stigma of fussiness that characterizes so many other Dragons. Wood Dragons have a Bohemian streak that allows them the freedom to live in a relaxed manner, to forget to replace the barbecue cover, or to resist the urge to straighten every painting in someone else's house.

All Dragons are fun-loving and festive, but the Wood Dragon is the master of dramatic parties. Wherever he finds himself, the Wood Dragon ensures he is the center of attention. Salvador Dali was a Wood Dragon—recall his penchant for spectacle. He was no recluse; a true Wood Dragon, Dali yearned for company, lived for theatricality, and exhibited himself shamelessly. From his outlandish costumes to his shockingly wild sweeping statements, Dali was the quintessential Wood Dragon.

This Dragon is not particularly courageous or enduring. Adversity throws him off course, disturbs his sensitive core, and causes him to retreat. As the Wood Dragon is not aggressive—one might even call him a reluctant Dragon—he shies away from conflict, preferring diplomacy to aggression and love to hate. Because he is a philosopher and wishes to be regarded as an instrument of harmony, the Wood Dragon becomes involved in the most convoluted discussions over simple issues. The important thing for him is to appear knowledgeable: do not hesitate to suggest he cease speaking if he distracts you from the matter at hand. He may be furious—but his rage will not last long.`,
        Fire: `Fire is the Dragon's inherent trait, making this the most quintessential Dragon. It is certain of its superiority, blatant about its lofty ambitions, and entirely self-driven. Fire Dragons rarely require assistance or seek a loan, because when they desire something, they take it.

This energetic, spirited, dynamic individual is always someone to be reckoned with. Whether a Fire Dragon is born into humble beginnings or enters the world with immense privilege, it stands out from the crowd. It makes a name for itself and causes significant trouble for anyone in the immediate vicinity who does not wish to comply with its plans.

It is also exceptionally generous. Devoted family members and favored friends praise its loyalty and open-handedness. It is intelligent, quick-witted, and gregarious. A wry smile often accompanies its brisk remarks, as it perceives the irony in everything. An innate natural authority lends it an air of grandeur and compels it to behave in an irritatingly condescending manner. It inflates itself like the worst kind of dictatorial monarch, appearing simultaneously to look down its nose and inspect you for flaws.

Even so, the Fire Dragon is one of the most attractive, charismatic creatures in the Chinese zodiac. Its personal magnetism is legendary. People cannot leave it alone. It is bafflingly contradictory. It is intensely sensual and full of wisdom. It constantly offers advice and is not afraid of taking major risks or embarking on eccentric campaigns to achieve the impossible. It can be warm-hearted and giving, but when crossed, it is ruthlessly vindictive.

The Fire Dragon is impressive. Upon meeting it, we are initially taken aback. It presents an image of courtesy coupled with masterful hospitality, a kind of inherent nobility. But make no mistake: it may be fabulous to behold and imposing to encounter, but it is also vulnerable. The Fire Dragon's ardor to achieve and succeed is born of true passion.

Likewise its sentimentality: despite its apparent armor, the Fire Dragon's feelings are easily hurt. Its skin is thinner than those green scales would have you believe. And, like many great people, it is a victim of emotional highs and lows which keep it in a dangerous state of nervous tension. It must be wary of overextending itself, of diluting its cohesive forces by having its finger in too many pies, and of being toppled by a craftier, less generous soul than itself.

One of the greatest strengths of the Fire Dragon is its ability to acknowledge its mistakes. Although it is always making sweeping gestures, involving itself in grandiose schemes, and craving attention, it is not afraid of the criticism its behavior often attracts—it seems to fuel its fervor. Its determination to dominate frequently places it in the public eye, and its earth-shaking decisions often put it on the public firing line. But the Fire Dragon can handle criticism. Its ego (unlike many Dragon egos) never obstructs its desire to be king. A composed individual, it understands the necessity of diplomacy and knows how to withdraw gracefully from untenable positions to clear the way for a comeback at a more opportune time. Obviously, politics suit this Dragon perfectly.

The Fire Dragon adores engaging in vast projects. It is enterprising and will not involve itself in anything trivial or that is not guaranteed to reward its efforts with world renown. Although it truly wishes to be effective and use its intelligence wisely, it is not interested in thankless behind-the-scenes work that might not lead it to leadership and celebrity.

Does the Fire Dragon desire a better world? Yes, it does. But it also wishes to create it itself, name it after itself, and rule over its obedient subjects.`,
        Earth: `The Earth Dragon is the most ego-driven of all Dragons. It requires flattery, applause, and the brightest spotlight under which to manifest its magic. When its ego is nurtured, its mind becomes vibrant. Tell it how magnificent it is, and it will preen and swell to larger-than-life proportions, capable of achieving astonishing feats. Compliments and approval are the fuel of its daily existence, and without them, it is lost, desperate, and susceptible to depression and even addiction.

Earth Dragons possess abundant charm. They effortlessly attract more members of the opposite sex than they can manage. Their captivating physical presence commands every eye. People never disregard an Earth Dragon, who shines like a beacon in any crowd, drawing hordes of admirers.

The Earth Dragon desires to help. It is always willing to involve itself in the problems of others, offering aid and assistance to friends, family, and even those it does not know well. The Earth element bestows an uncommon gentleness upon the spirited Dragon nature, and this Dragon is easily affected by the pain and struggles of others. It offers sympathy and even financial assistance to those it feels need its helping hand. As it is completely ego-driven, it will also give its shirt to anyone who pays it tribute.

I would not advise anyone to confront this Dragon over personal policies or ideals. The Earth Dragon is not only serious about its convictions, but it can become passionate and even dangerous if crossed—especially by people it considers its friends. Friends are its lifeline: family is necessary, and business acquaintances are pleasant, but what truly matters are friends. The Earth Dragon pampers and caters to them. It invites them to dinner, takes them to lunch, and brings them along on its extensive fishing trips. Wherever there is an Earth Dragon, you will find a host of fine, seasoned, genuinely loyal companions on whom it can rely and for whom the feeling is mutual.

Career choices for this Dragon should always consider the necessity of the spotlight. Money alone would never be enough to motivate this Dragon to work: no Earth Dragon will be content performing accounting tasks in an unseen office somewhere. Even if it decides to be a philosopher or a poet, it must be given top billing and abundant visibility.

This Dragon will never be solitary. It will always choose to be married or at least committed to someone it loves. It will probably not be capable of sexual fidelity, as it is so captivating and outrageously charming that people fall at its feet for the potential delight of a one-night stand or an afternoon of stolen bliss. But its unfaithfulness is not treason. It will never abandon its family, as no matter how mischievous it knows itself to be, it understands that its family reveres it most and will provide it with more adulation than a thousand fleeting encounters. The Earth Dragon is level-headed and will never sacrifice security for superficiality.

Strangely enough, this Dragon is also somewhat of a Bohemian. Although it requires constant attention and depends on its public's applause for its sanity, it would prefer to live as an outsider, a rebel, a non-conformist. It delights in eccentricity: no Earth Dragon is happy as a middle-class bourgeois living in the suburbs. It desires flair, seeking out the unconventional and hunting down the rare. Sometimes it leans towards laxity, forsaking discipline in favor of indulging in peculiar pastimes such as associating with idlers, drinking, gambling, or taking drugs. This can be its downfall, and it should monitor its bad habits from an early age to enjoy a long, healthy life.`,
        Metal: `This Dragon allows nothing to impede its work. It is a Doer. Projects abound—the more challenging and demanding, the better. Metal Dragons dislike being idle; they always choose activity over inertia. No sitting on the sidelines for this Dragon, who never accepts a secondary role. Like time, Metal Dragons wait for no one.

Astrologers say that, of all Dragons, those influenced by Metal are the least favored by the gods. They often encounter situations where the atmosphere (and the company) is unsavory, and are then drawn into intrigue and, ultimately, misfortune. Perversion and even sadistic tendencies are common among Metal Dragons. Their type puzzles even the most astute psychoanalysts, as they appear so strong, stable, amiable, and gentle.

Even the politest, nicest Metal Dragon often finds joy in deviant behavior. Its salvation lies in being clever enough to know how to use this inclination constructively—otherwise, it may fall victim to its own (real or imagined) demons.

The Metal Dragon is tough and believes in mind over matter. Thanks to its power, it need not be afraid or shrink from asserting its way out of unpleasant circumstances. It is both knowledgeable and determined where its work and ideals are concerned, and will always know how to extricate itself and rise to the top—even if it chooses not to.

This Dragon is ambitious beyond all our dreams. It desires to be someone significant, and it earnestly wishes everyone else to notice. It is happiest when involved in some lofty cause. Anything from orphans to orchestras will suffice, but the Metal Dragon should always have a favorite charitable cause that keeps it absorbed and interested enough to stay out of trouble.

It needs to travel to distant lands. Jobs in public relations or international banking or politics will suit its restless nature. It is very observant and gifted with a prodigious memory. Journalism or scholarship will suit its passion for collecting facts and extrapolating knowledge from them. Traveling outside its normal environment provides just the challenge the Metal Dragon needs to feel that its mind is being kept sharp. Also, it is attracted by cult religions, which allow it to deviate from its childhood ethics and explore new ways of solving philosophical problems. The Metal Dragon might undertake a pilgrimage to the highest regions of Tibet where it dines with monks in rarefied atmospheres and returns renewed, quiet, and calm. The Metal Dragon is perpetually seeking new approaches to old problems.

The Metal Dragon is responsible and makes an excellent parent. It will usually prefer to be married or at least committed—even though it strays occasionally, if only for novelty and perhaps an unusual learning experience.

Metal Dragons typically earn substantial money in stable, sensible jobs. They can assume management positions and bring order out of the worst corporate chaos. They can handle the most challenging issues and invigorate any group with their wise and humanitarian leadership policies. Elect it president, yes, but do not hand over the purse strings. The Metal Dragon spends money like a drunken lottery winner. And it dislikes being told to be more economical. It desires no back talk or criticism from its subordinates and will display its superiority—even at the expense of its composure.

Its temper control is very sensitive. The Metal Dragon erupts into wild fits of anger and will direct them at whoever happens to be brave or foolish enough to confront it. These tantrums do not last long, yet they are so impressive that more rational people may question the perpetrator's sanity or at least find it difficult to forgive it. It should be warned against having these outbursts when not among friends.

Above all, the Metal Dragon loves money. Its work is important to it, and so are its family and friends, but most of all, it desires to live lavishly, be waited on and deferred to, have meals prepared and be cared for, to laugh and joke with its adored friends, to gaze at beauty, and to curl up in the comforting lap of luxury. It will be happy to work towards this goal, but it will also be greatly annoyed if it does not reach it. A Metal Dragon who fails in this regard would be capable of marrying for money, living as a courtesan, or settling down in a posh nunnery for the rest of its days.`,
        Water: `Are Water Dragons contradictory? And contrary? You can be sure of it! But even though influenced by water and seemingly relaxed, this Dragon is exceptionally sensual and sexual. It is an inveterate show-off throughout its life. Its Dragon-like dynamism is only slightly tempered by the influence of Water. It does not present itself like other spirited, noisy, sometimes arrogant or bombastic Dragons. Instead, it gives the impression of high-born gentility. It appears well-mannered, well-bred, scholarly, and informed.

You can rely on this individual: friendship is its exceptionally strong point. When it takes a liking to someone, and the feeling is mutual, the Water Dragon vows to involve itself forever in that person's welfare and well-being. It is thoughtful, calls its friends weekly, cheers them when they are down, and gives them a boost or even a loan in a difficult situation. The Water Dragon is home-loving, adores having a large house, a supportive mate, and many offspring, pets, and other comforts. It revels in inviting companions over for drinks and dinners, card games, a round of badminton, or simply a long, pleasant conversation. It is also possessive, showing off its property, boasting about the new trees it has planted, and the special blossoms of its flaming yellow lilies.

It is also a curious person—like all Dragons, but more so. The Water Dragon is nosy: it cannot glimpse a slip of paper lying on a table or desk without intensely desiring to know what is on it. "Where did you get this letter? Who wrote it? Are you going to answer? What will you say?" are just a few of the questions that Water Dragons can devise to insinuate themselves into every corner of your private life.

The Water Dragon's contradictory nature often makes it unsure of its ambition. On the surface, it seems driven with clear goals for success, but underneath, it is not as energetically involved in "getting there" as it appears. If having money and achieving success means conformity, you can count this Dragon out. If being a star depends on kowtowing to a bunch of witless, cigar-smoking producers, the Water Dragon will back out before it begins. Either success comes because of its talent, its unusual gifts, and its remarkable brilliance, or it simply cannot be bothered. It would rather go live in the country and raise goats.

This Dragon is intuitive and can advise you on almost anything. If it does not know an answer to a direct question, it will say so. But it will always have an opinion and will probably know where to look for any facts it is missing. It has the capacity to be a true seer. It can sense coming events that will occur in the future for others.

Love is its main objective. Even though it has affairs and flings galore, and seduces and captivates lovers far into its old age, what truly matters for the Water Dragon is genuine love. Family, children, and long friendships are the mainstay of its emotional stability. It lives for improving the structure of its family and thrives on the approval and gratitude it receives from them.

Most of all, the Water Dragon is creative. Its ideas are innovative. It knows how to combine the new with the established and devise plans that surprise us with their improvisational yet solid practicality. It is also economical—even penny-pinching. It likes to be careful with money so it does not have to work at that dreadful office where conformity threatens to spoil its enjoyment.

The greatest dilemma facing any Water Dragon is caused by its multitude of talents: it finds it difficult to eliminate any in favor of a single pursuit. Most Water Dragons can paint, write, invent, dance, and even sing. They are amusing, attractive, and easy to like. Early on, when it becomes obvious to the young Water Dragon that it will be forced to choose one discipline over another, it may hesitate. It wants to imagine, because of its vast stores of energy, that it can one day do it all, have it all, and be everything to everyone. If it does not make some definite choice before the age of twenty, undertake a course of study that offers it a solid future or profession, it had better inherit a lot of money from its rich Uncle Harry. A clever Water Dragon can happily spend its formative years as a professional creative genius or even as an idler. But when age thirty arrives, bringing with it responsibility, children, and the desire for security, an under-educated or unemployed Water Dragon whose finances do not match its self-image may indeed end up dissatisfied.

My advice? Structure. Discipline. Focus.`,
    },
    compatibilities: {
        "Rat": "This is an absolutely delicious marriage: the Chinese claim it as one of their best-arranged unions. The restless Rat will be warmed by the heat of the dashing Dragon and the Dragon will bask in the Rat’s generous applause. These two will complement each other beautifully. Guaranteed bliss. With the strong-willed Dragon around, the Rat will be happy to give up total control: anxieties slowly subside, bringing peace and comfort. The Dragon is so emotionally effusive that the burden of worry will be taken off the poor little Rat’s shoulders. Bigger and bolder, the Dragon will carry the weight of the loving Rat’s turmoil. The Rat will not feel competitive about the Dragon’s position of strength in this couple, happy to stand in the shadows of a fervent friend/mate. The Dragon and Rat team will feel like king and queen. In the Rat’s eyes, the Dragon does no wrong. All the better for the lucky Dragon who loves to shine. The dazzling Dragon is so bright and exciting that even the Rat’s usual hearty appetite for sex may be overwhelmed and suddenly wane. Despite his innate wisdom, the proud Dragon may fail to see the problem (The Dragon’s ego can be bigger than his brain at times.) and place blame on the Rat. A relaxed, rational discussion will clear the air, and in no time, the Dragon’s conversational fireworks will re-ignite the Rat’s temporarily diminished sensuality.",
        "Ox": "Be prepared for plenty of late-night squabbles in an Ox/Dragon combo. Both believe they are righter than right. The Dragon dictates his will over the opinionated Ox and the Bull bullies back. The Ox has little patience with vanity. The Ox’s indifference to the Dragon’s fiery appearance is a perpetual disappointment to the Dragon’s ego. The glamorous, extravagant Dragon loves to spend money but, with the Ox counting pennies, feels hampered and ill at ease. The Dragon’s wandering eye unsettles the faithful Ox who rarely strays from a good sexual union – he just doesn’t have time! Too busy working. With so much conflict, how can this duo reconcile? Their mutual love of home and family could save them from total despair. Both enjoy sex, although the Ox’s routine techniques may bore the Dragon, whose sentimental nature yearns for puffy clouds of pink cotton candy to enhance lovemaking. He won’t often see fireworks with the Ox. Also, the methodical Ox expects a regular living schedule. The Dragon, however, favors a more erratic time code, exorbitant stormy sex for a week followed by peace and quiet for three. An excellent business partnership, this union is not recommended for either marriage or romance—unless the Dragon can be free to roam and hunt excitement elsewhere.",
        "Tiger": "Sexed! The Tiger/Dragon love relationship bears serious consideration. Combined, their strength is almost excessive. And energy! Enough to fuel several large power plants. There is EGO flashing in red neon all over this couple. Overbearing and self-propelled, they are both a bit too much. But as a pair, they can succeed. Despite an excess of commando muscle, this combo lives peaceably together. Mutual respect and admiration offsets the expected clashes. The dashing Dragon begs for constant flattery and applause. However, the strong-minded Tiger finding the pontificating Dragon tiresome and teases the spotlight away. The Tiger is undaunted by fire-breathing antics. In fact, the intrepid Tiger loves a good shouting match and respects a worthy opponent. The generous Dragon is amused by and tolerates the Tiger’s love of danger and precipitous behavior. In short, these two get along. Tiger with Dragon is not only a sensual match. They carry themselves with bravado and flair. An air of madness colors everything they do. People flock to their home to bask in their aura and share in the high of their hazardous love. Not afraid to share power, they take turns sitting on the throne, complicity taking precedence over their individual roles. This relationship is good for marriage. Battles will be waged, but at the end of the day the force of their attraction ensures they will be lovers for life. Entwined in their own whirlwind of passion and steamy sex, this couple knows the road to heaven. The Dragon sets the tawny Tiger alight and the rapacious Tiger devours the dashing Dragon’s scalding hot fire. Enjoy!",
        "Rabbit": "The flamboyant Dragon’s exaggerated pizzazz does not suit the Cat ‘s need for discretion. The fire-breathing monster goes about wowing crowds with his pyrotechnic displays while the Cat sits by disdainfully, deeming the Dragon’s antics vulgar. The classy Cat finds all grandiose public exhibits absurd. He would much rather stay at home and polish the silver coffee urn. Although a Cat/Dragon marriage usually proves unfulfilling, there can be a positive aspect to this duo: a wise Dragon sometimes chooses a gentle, sensible Cat as savior. With much patience and forbearing on Kitty’s part, their marriage might work. Unfortunately, the gentle consideration the Cat lends to a tempestuous Dragon partner can never really be reciprocated. The Dragon needs to be in the limelight, to lead a gregarious life, careering around, currying ovation, and the domesticated Cat is often left at home, tending the household, where overly sensitive to the Dragon’s indifference, poor Kitty sits alone by the fire, doing a slow bum.",
        "Dragon": "This relationship is almost too volatile for any long-term good to come of it. What we have here is a lifetime battle royal for supremacy. In competitive situations, neither Dragon can allow the other’s gigantic ego to prevail, so whether it’s a pitched combat over who gets to manage the TV remote or a tussle about who drives the car on the next trip to the supermarket, the air will always be full of strife. At first, all this emotional power play may seem to the Dragon couple like a love storm of glorious emotion. They are not ill suited sexually and, even when they are furious with each other, may have some of the most exciting sex of their lives together. Yet, day-to-day living threatens to be so highly charged, so noisy and fraught with shouting and name-calling, that one wonders if a few moments of occasional earth-shaking sex is worth it. Unless it’s irreversible, I advise against this marriage. Two giant uncompromising, fire-breathing beasts may well be doomed to set each other’s hearts ablaze, but they are patently unsuited to keeping the home fires burning.",
        "Snake": "In Chinese astrological parlance, these two are considered kissin’ cousins. The Dragon adores sporting a gorgeous, attractive, sexy Snake partner and the quiet, subtle Snake admires the Dragon’s world-beating flamboyance and style. In turn, Dragon protects Snake. Snake coddles Dragon’s ego and lets Dragon blab away without so much as a hint of criticism. Of course, no relationship with any Dragon can ever be calm, but the Snake/Dragon duo comes close to being a levelheaded, harmonious union. Wisely, the Snake never confronts the Dragon’s ego head-on. Snakes deal subtly with clashes, slithering and examining all sides before striking at just the right spot to get results. Sexually—with the Snake’s huge capacity for erotic activity and the Dragon’s giant appetite and innate talent for same—you can just imagine ... the chemistry is sublime. They agree on living luxuriously, too. The Dragon buys endless scrumptious accessories for the Snake’s pleasure and the Snake allows the Dragon—within reason—to indulge in filling the house with gadgetry. Their home life is peachy. They make a handsome couple. It’s truly a match made in heaven.",
        "Horse": "This couple will, no doubt, boast vociferously of having fallen in love at first sight. Both of these effusive people are firm believers in falling in love as a way of life. The sex meter will be permanently set to hot and heavy mode. They won’t be able to keep their hands off each other. Fact is, sex is about the only thing that distracts these two from a full-time war of wills which inevitably besets their relationship. Horses are authoritarian and don’t like to be told what to do. Dragons like to dominate and hate to be bossed around. Each one is proud, touchy, irritable, self-centered and headstrong. Neither is acquiescent. The Dragon, at least, is sentimental, but the Horse is hard-nosed and tough-minded and knows how to make the Dragon cry. The Dragon is the less conventional of the two and will not hesitate to embarrass the socially correct Horse in public for revenge. I also see money conflicts here. The Dragon and the Horse like to spend. If allowed to have their way, they’ll be broke and in debt ail the time. This ill-suited couple is only happy during the initial, sexy infatuation stage. From there on it’s all downhill. No marriage plans? Keep it that way.",
        "Goat": "In Chinese astrological circles, this is said to be a sound marriage. Goats are essentially dependent. They are easily swayed and don’t mind being bamboozled and manipulated by their loved ones. Dragons need to command direct operations and dominate. Goat’s good-natured passivity. The acquiescent Goat inspires the Dragon to protect and be chivalrous and thrives in the security provided by Dragon’s authority. Their sexual life together will be as near to an erotic dream as you can get. Dragons like to take charge and Goats like to lie there and be loved. Being two very sentimental as well as sensual beings, these two will know instinctively how to blend sex with affection. Their intimacies will be satisfying and frequent.",
        "Monkey": "Despite the obvious differences in their characters, these two have a lot going for them. The Dragon is bombastic and needs to be adored, yet reveres the Monkey’s keen intelligence and ability to see around corners. Monkeys love spectacle and invariably enjoy the show Dragons put on. Dragons get themselves embroiled in world problems. Monkeys are born solvers of problems—big and little. There is plenty of room for personal evolution in this couple. Impressed by the efficiency of the Monkey’s exceptional mind, the Dragon (atypically) will become almost dependent, let up on the accelerator from time to time and even take an occasional back seat to Monkey’s brilliance. Monkeys enjoy being appreciated for their skillful talents, are not particularly interested in the number one position, and let a Dragon bask in the footlights. As a result of this clever balance, the Dragon/Monkey match becomes a strong bond, built on compromise and mutual respect. Sex, however, may not be the strongest element that binds these two. The Monkey’s normally healthy appetite seems moderate by comparison to the Dragon’s voracious and conspicuous need for consumption of his or her mate’s intimate favors.",
        "Rooster": "Both passion and glamour are missing from this otherwise well-balanced relationship. It is workable. Dragon protects with gusto and Rooster obeys with serious intent to do the right thing. Neither is ecstatic in this arrangement but, then, neither is blatantly unhappy. Roosters recognize and respect the Dragon’s need to shine, to assert superiority over others and go out and beat the world at its game. Despite sometimes flamboyant outward appearances, the Rooster is a rank conservative. Roosters do want to voice their truths and implement their ideals. But they don’t show off. With a brave and daring Dragon partner, the Rooster can carry on being quietly cocky while the Dragon plays the conspicuous role. I’m afraid the Dragon’s exorbitant sexual needs may prove overwhelming to the less sensual Rooster. Rooster’s rebuffs may destroy Dragon’s ego. The solution will only be found in frank discussion with an objective third party. A therapist? A clergyman? A family friend?",
        "Dog": "Polarized outlooks might find happiness, providing the sex is sensational. But with the Dragon/Dog duo, this is plainly not the case. According to Chinese astrologers, few relationships are less likely to withstand the test of time. Dragon/Dog bickering and barking prevail. Dragons and Dogs are full of enthusiasm, energy and vigor. But their styles are so different as to make them near enemies. Dogs hate making a fuss over nothing. Dragons intentionally create daily scenes complete with flames, smoke and noise. Dragons deem the moralizing, pessimistic, stern Dog a downright bore. Dragons live primarily for themselves. Dogs live for others. The Dragon will wish the Dog a more obedient mate. But the freethinking Dog will never buckle under to oppression. While the Dragon boasts of successes, the Dog gloats over his or her mate’s resounding failures. I have to agree with the Chinese soothsayers. Dissonance reigns. No marriage here please.",
        "Pig": "Most Dragon/Pig marriages last forever. The two have just enough in common and just enough differences to keep them both interested. The Pig is compliant and easygoing, always gives the benefit of the doubt to the other fellow and admires gutsiness and audacity in a mate. The Dragon needs an ally, a helpmate, a shoulder to cry on and someone nice to boss around—preferably someone who forgives easily. The Pig amply fills the bill. Both characters adore opulence—the more gilt sconces they can stick on the walls of their châteaux, the happier they will be. The Pig applauds Dragon’s successes and turns a blind eye to all chicanery. In turn, Dragon protects and admires the Pig’s scrupulousness. In short, Pig helps Dragon maintain the shine on an overactive ego. Dragon adores being put on a permanent pedestal and makes it clear that Pig’s homemaking talents are all he or she has ever dreamed The sex is good. The Pig cleaves to sensuality and the Dragon just plain loves sex—lots of it. Piggy wants romance so Dragon must temper crudity and learn a thing or two about the value of hearts and flowers.",
    },
    futures: {
        "2025": {"year": "Snake", "element": "Yin Wood", "prediction": `You will be compelled to cease your playful escapades and quell those party instincts this year. The Snake is not a slave driver, but he/she requires all the attention. You also fall squarely into the attention-seeking category, but you are not fond of competition. You prefer floodlights and marching bands. The Snake prefers soft Debussy and fragrant bathtubs surrounded by flickering colored candles. One may be equally attractive as the other. However, this is not your year; it belongs to the quiet, unobtrusive, philosophical, but powerful Snake. So, what will occur between you and the Snake year is a clash of styles. It is your turn to don a bushel basket to cover your head and scuttle along walls so as not to be noticed. This may cause you some degree of indigestion because when the limelight fades, you grow despondent and sometimes even pity yourself. Self-pity is unbecoming to dauntless creatures like you. So, check yourself before you sink into your self-made oblivion. Keep in mind this is the second year of your twelve-year cycle, and you need to have a plan. Where did you put that list I suggested you write last year? Find it. Add to it. And implement each step one by one so as to stay on track.`},
        "2026": {"year": "Horse", "element": "Yang Fire", "prediction": `Dragons can easily find themselves bewildered by Horse years. First of all, these years are notoriously fraught with tension. The Horse is often a strong yet troubled soul whose sense of self can be easily disrupted by the slightest setback. You, Dragon, might just be part of one of those setbacks, as you are not daunted by the prospect of conflict with anyone—least of all a Horse. You sense the Horse’s strength, but sometimes you do not intuit the Horse’s skittish fragility. Horses are powerhouses of talent, but they do not always seek to shine. They are not as interested in monopolizing the stage as you are, but they do want, need, and actively seek recognition. This year, I suggest you relax. Hold back a bit. Look around in your own life and reflect on how much progress you have been making over the past couple of years. Then, cautiously, return to the fray without causing disturbances or provoking the Horse’s aggression. You will be able to make enormous progress in Horse years and enjoy significantly more time with your family... if only you can suppress your flamboyance. Horses need understanding. Sentimental people like you are capable of generosity and compassion. Utilize those talents this year, and you will navigate smoothly and unhindered.`},
        "2027": {"year": "Goat", "element": "Yin Fire", "prediction": `You are a star with Goats. Why? Because they need your power and are willing to go to almost any lengths to be able to depend on it. Goats are all about creativity and eccentric, whimsical notions. They love ease and yearn for comfort. They dream of languishing in abundance. But they are not always able to secure those dreamed-of luxuries by themselves. So when a big, strong, capable Dragon comes confidently along, Goats perk up their ears and remain vigilant for opportunities so they might benefit from the Dragon’s willingness to lead them forward. Goats have many more good ideas per second than a Dragon can contain within its proud, scaly head. Goats do not mind being humble and even modest. But they do not ever want to have to compete or impose their wills in the challenging world. They prefer to support strong leaders. So your role in a Goat year, as one of those same strong leaders, is to take the reins without appearing to. Manage the show from behind the scenes and let the Goat have its moment. He or she will thank you forever after and shower you with love and devotion for a lifetime.`},
        "2028": {"year": "Monkey", "element": "Yang Earth", "prediction": `No frivolous behavior! These next twelve months will offer you a burst of activity, precisely to your liking. Multitasking, numerous meetings, and multiple proposals for work, cultural, and sports experiences. Accept the Monkey's invitations for all these propositions. You, more than any other sign, are certainly capable of managing such a diverse array of ongoing activities. Where other people might feel they have been overwhelmed by such a plethora of fresh things to learn and do, you revel in the novelty of it all. A change in your work environment is also forthcoming this year. You are an individual whose enthusiasms require alteration as frequently as you change your shirt. So, start diligently searching for that unusual job immediately this year. You will not regret doing so. Love life? Medium rare. I say that because the romantic situation you have been in for so long is, by this time, well done. Overdone, in fact. Hence, it is time to make significant changes. Now, briefly pursue new romantic interests. See how it feels to enjoy the thrill of seduction again. Change is the central theme of the Monkey year for Dragons. P.S. Your current partner will more than likely be overjoyed to see your scaly rump slink out the door.`},
        "2029": {"year": "Rooster", "element": "Yin Earth", "prediction": `Let the Rooster manage the proceedings. Or at least give him or her the impression that they are in a position of leadership. Roosters prefer to act swiftly, enjoy themselves, and (unlike yourself) prefer not to leave a trail of casualties behind. As you probably have a new romantic interest by this time, you will be busy devising new strategies to retain this prize. However, you need to apply yourself diligently to work this year. Roosters expect people to be actively engaged in their various projects and are not amused by idlers. So, maintain a prominent presence. When you are laboring under the hot sun or mining coal deep underground, groan frequently and sweat profusely to convey to your superiors just how demanding a Dragon's life can be. Otherwise, if you are not attempting to overshadow him, the Rooster will leave you to your countless independent pursuits. Travel and visits to relatives in distant cities are favored now. There is a family member you have been avoiding. Make it your priority to pay them respect. It is in your financial interest to be kind to them now and make amends for any past neglect.`},
        "2030": {"year": "Dog", "element": "Yang Metal", "prediction": `Phew! There is relatively little that can go utterly wrong for a Dragon in Dog years. You and Dogs get along well together because you share similar beliefs and adopt a global perspective on even the most minor events. Differences of opinion arise when you sense the Dog's inherent paranoia surfacing unexpectedly. Dogs possess a unique understanding of Murphy's Law; they instinctively know that if something can go wrong, it will, and they are more than willing to announce it beforehand. Hence, in Dog years, an atmosphere of pervasive anxiety lingers, which drives Dragons to distraction. My advice to Dragons in this otherwise somewhat challenging year is to enjoy the goodwill that the Dog offers you as its protective companion. Relax a bit. Ease off the accelerator at work. Spend some enriching downtime simply socializing with friends or family—or both. In Dog years, you can also enjoy engaging in cultural excursions. Take tours of exotic lands you have always promised yourself you would visit. Go see the Pyramids or visit Niagara Falls. Do something wonderful for yourself, but leave the Dog and its paranoia at home.`},
        "2031": {"year": "Pig", "element": "Yin Metal", "prediction": `Pigs admit to a certain wide-eyed admiration when confronted by you restless Dragon individuals. Pigs are strong, knowledgeable, and culturally adept people. But they do not comprehend your exaggerated need for change. You are constantly bustling about, never settling long enough to accumulate capital, amass riches, collect art, or acquire luxurious homes—whatever it is the Pig considers wealth. Nevertheless, the Pig and you can be close companions. You admire the Pig's purity and authenticity of spirit. What it does not understand about you is what will hinder you this year. The atmosphere of abundance will lead you to assume you can spend and give and squander your money and so—in a word or two—you overspend. If you are not more careful about where your money is going in the first part of this Pig year, by September, you will find yourself in a difficult financial situation. So, tighten your resolve, Dragon. Control your desire to be overly generous to those you love or those you feel are in need. Hold onto your financial reserves and do not sell the family jewels to acquire a fancy new car to impress your sweetie. Put yourself on a budget. Give wantonly of your love but take fewer fiscal risks. Slow down. Sit still. Read. Knit. Go to the countryside. Sit under a tree and think.`},
        "2032": {"year": "Rat", "element": "Yang Water", "prediction": `Here comes a bonanza year for you Dragon people. Nobody admires your dashing self more than the astute Rat, and the feeling is often mutual. You will be inundated with proposals for new projects and asked to direct (an activity you simply adore!) everything from the village orchestra to the Neighborhood Watch. You are a Star in this Rat year—and what's more, you can feel it. A rush of approval and freedom comes over you around mid-March and will not dissipate until the end of January. Take wise advantage of the opportunities presented to you because they are almost all excellent chances for the betterment of both your financial and personal life. A romantic interest appears about halfway through the year. If you are in a committed relationship, beware of temptation; this person is highly attractive and drawn to your charismatic personality. If you are unattached, pursue it. Family members' needs may impinge on your time in the Rat year. Offer some of your moral support to those in need, but do not be tempted to shower them with your newfound wealth. You have better things to do with your money than bail people out of gambling debt or lend your new BMW to your irresponsible brother-in-law who lost his license for drunk driving.`},
        "2033": {"year": "Ox", "element": "Yin Water", "prediction": `Provided you keep a lid on your notoriously flamboyant nature, the Ox will not interfere with your progress this year. What most irritates the Ox is your tendency to concoct disorder and create chaotic celebrations out of everything from the dog’s wedding anniversary to your wife’s sister-in-law’s menopause. Ox years are about hard work and order. Oxen are not always fond of anything or anyone who deviates from the established norms in life. They love tradition and social structure. You do too, but you need to make a fuss about it, and the Ox does not. Oxen, too, are assertive; they enjoy giving orders and do not accept them very graciously. As you are a more natural leader—a beloved despot—you may find conflicts arising where you least expect them. I am not suggesting this will be a difficult year for you—unless, of course, you forget to lower your voice and keep your vociferous opinions to yourself. Because of the conservative atmosphere in this Ox year, let me suggest that you take a closer look at your accounting strategies. Pay down your credit cards. Wild spending sprees occasioned by last year’s elation are not favored in Ox years. Adopt a more conventional approach to budgeting, or you are in for some unsettling surprises.`},
        "2034": {"year": "Tiger", "element": "Yang Wood", "prediction": `There are several aspects of your character that irritate the spirited Tiger. First of all, he detests snobbery and name-dropping. The Tiger finds your casual boasting about the famous person you saw at the fancy restaurant, or which celebrated author gave you her estimable autograph, or who you sat next to at the Academy Awards, irritating. Big talkers’ words fall on his deafest ear. Tigers do not care much about who's who, and they deplore pretensions of all kinds. So, no matter if the Pope attends your funeral, do not engage in any bragging or attempts to impress during this Tiger year. The same applies to your famous sentimental displays and your tendency to want to steal every show. Basically, this can be an excellent year for you financially. All new and unusual projects are favored. The Tiger is your ally; he admires your spirited nature, and your words of sensible advice are always welcome. As long as you do not spout any flames through his bedroom window or steal his beloved with those seductive swishings of your scaly tail this year, the Tiger will encourage all your pursuits and applaud most vigorously when you succeed. Be as subtle as you know how, and do not show off. Tigers dislike braggarts.`},
        "2035": {"year": "Rabbit", "element": "Yin Wood", "prediction": `These tranquility-seeking Cat/Rabbit years are never your favorite and frankly get on your nerves. You are constantly searching for excitement, seeking sources of joy, and igniting your own fireworks displays. The Cat/Rabbit perceives this boisterous Dragon-like behavior as rowdy and disruptive. Face it, you Dragons are a noisy bunch! Cat/Rabbits are quiet and even secretive. So the overall atmosphere in this current year will aim to temper your life. Frustration is in store because you genuinely feel sad when the fireworks cease and the last of the Roman candles lies sizzling at your feet. How to manage it all? Reflection is not your strong suit, but you can do it when pushed. This year you will not be pushed; rather, you will be summarily removed from the main stage and find yourself in the quiet backstage of most of the action (which in Cat/Rabbit years usually occurs in banks and other such esteemed institutions). So why not learn to meditate or join a Dragon support group where you might learn to keep quiet and engage in deep, deep thinking? Why? Because you need a plan. Make lists. Set goals. Build new dreams. Next year is the Dragon year. You had better be ready to go!`},
        "2036": {"year": "Dragon", "element": "Yang Fire", "prediction": `The year is all yours! For Dragons, the words "all mine" are particularly meaningful. You like to have control of your own existence and are not disinclined to taking control of a few other lives along the way. You have just had eleven long years to complete your previous twelve-year cycle, and now you are embarking on a new one! But of course, you are in the rebirthing stage of the cycle, the very first year indeed. So you may find yourself uncharacteristically childlike again. Louder than ever. More flamboyant and outspoken. Increasingly self-important and just a touch on the boisterous side. Never mind. Go ahead and frolic and enjoy the party. But, when you wake up each morning, do remember to add something substantial to your list of accomplishments you want to be proud of over the next dozen years. Ask yourself: "Where do I want to be in 2 years? 5 years? 9 or 10 years?" How do you intend to live out your dreams and with whom by your side? All of these considerations are key to a person’s success as a significant human being. Do not plan to fritter away a couple of years in sabbatical mode. You cannot afford to miss a single opportunity to shine. A Dragon’s life is always a barrel of monkeys. Make the best of it.`}
    }
};

  

    