
export const snake = {
    introduction: `Oh, Tempting Snake, how does it feel to be irresistible? It must be wonderful to know that the whole world is captivated by you, with your enchanting allure, your silken scarves, and your glamorous accessories. Everyone is in awe of your appearance. And you, in turn, are in awe of how adoring your admirers are. You truly love to please. Some consider you to be the quiet type, but you can be very talkative when there is something important to convey.

People value your sagacious advice. Those seeking peace of mind are drawn to you for counseling and wisdom. You can always sense what is about to happen before it does. One wonders if you receive messages from other realms. If you do, do not resist it; listen to the spirits and learn. With money, you are both frugal and extravagant. Rather than raising the thermostat a few degrees, you will wrap yourself in sable and curl up with a good lover. You are famous for demanding exclusive rights to your partner while casually maintaining your own busy private life on the side. Security is your all-time favorite source of happiness. Marry a resourceful Rooster or a stabilizing Ox. The first two phases of your life will be hectic and nerve-wracking, but old age suits you. Enjoy it.

Some advice? Be generous with your glory. Try to decline the spotlight when someone who needs it more than you is present.`,
    elements: {
        Wood: `This Snake is the public speaker, the actor, the skillful communicator, and presenter of grand-scale ideas. Its exquisite articulation of information guarantees it success. It instinctively knows what place in society it wants to carve out for itself.

Although the Wood Snake experiences more than its share of setbacks, it will make a million comebacks, valiantly returning to the front lines to begin again, perhaps in a different manner, to climb the golden ladder of success. The Wood Snake, like all Snakes, has to combat a tendency towards laziness and an exaggerated love of luxury for its own sake, but because of its intense desire to reap applause, renown, and great wealth, it will always overcome its negative inclination for idleness.

It is a dreamer and often has to force itself to be practical. But unlike some Snakes who are incapable of disciplining themselves, when it comes to earning money, the Wood Snake can be downright pragmatic. If it cannot succeed as a painter, it will try illustrating children's books—and if that does not work, it will go into advertising or commercial design. The objective is to achieve success; any means to that end is valid. The Wood Snake may be vain, but it is not proud. It is always able to discern winning from merely getting by—and it knows that what it desires most is to win.

As a genuine Snake, it is conscious of a deep-seated, subtle desire to enjoy all the pleasures of life. It is not one to refuse the joys of taste, sight, sound, and whatever else it can experience physically. No matter how immense its projects or how public its image, the Wood Snake is always furiously involved in seeking new ways to enjoy itself.

The Wood Snake's drive to achieve fame and fortune is powered by its ambition to please, to win approval, and to convey its ideas and persona to its audience or public. It loves praise; being admired is its preferred stimulant. It is a perfectionist in its work and stops at nothing to learn more, constantly challenging its intellect to break through new territory and find novel means of transmitting both its charismatic image and powerful ideas to the world.

All Wood Snakes fear rejection and abandonment. It is difficult for them to accept flaws in others. They want their partners to be wholly attentive to and responsible for their well-being. They require constant attention and large doses of compassion and understanding to survive. They also need security and a calm environment to thrive. If the object of their affection cannot provide these or does not measure up to the stringent criteria set forth by this demanding lover, the Wood Snake's heart may be broken—and it frequently is.

Although it demands intellectual freedom for itself and is scandalously flirtatious—even sometimes unfaithful—it is jealous, exclusive, and monopolistic when it comes to love. It will never take a secondary role or allow total freedom to the other person. For the sake of its love for another, the Wood Snake is not above dissembling and employing emotional blackmail. It will make its loved one feel guilty until they either conform to its ideal or give up and leave. Emotional involvement with the Wood Snake is anything but simple: the rules are hard to follow for anyone who has outside interests. Extricating oneself is even harder. The process of detaching the Wood Snake's stubborn tentacles of unconditional love and devotion from someone it loves is a horrible, painful spectacle to observe.

As being left alone is precisely what this Snake fears most, the loss of a loved one can mean physical as well as nervous collapse. Serious illness and depression may overcome the poor, bereft creature. The road back will be long and arduous, but it does recover, and once restored in body and mind, it enjoys renewed stability, rekindled ardor, and belief in the all-powerful emotion for which it truly lives—love.

People adore this charming individual. Its presence is always desirable, as it converses easily and possesses a quick sense of humor. The Wood Snake genuinely enjoys social interaction; it is happiest when surrounded and adored. It is friendliest when it knows it is liked and is a wonderful companion whose wise advice is invaluable to its many acquaintances. It is a fervent advocate of the arts, spending much time and money promoting cultural activities. Its homes are showcases of precious works of art and antiques. It entertains with generosity and style. Its manner is obliging, and as long as its own advancement and personal interests are in no way compromised, it will go to great lengths to accommodate those it cares for.`,
        Fire: `The deep-thinking Fire Snake is not only brilliant; it is power hungry. When it wants to succeed, it is capable of gigantic, masterful strokes that will propel it into the public eye, eliminate the competition, and, with a flick of its tail, bestow upon it a title it can be proud of. This Snake means business.

The Fire Snake's will is stronger than that of its fellow Snakes. It can glide in and out of social gatherings with panache. It sidles up to important people and turns them into putty with its inimitably subtle charm. It makes contacts and uses them to its own benefit, leaving, if necessary, the contact behind. Fire Snakes are ruthless, glamorous, and profoundly learned. They are unafraid of scholarship, know how to concentrate, and assimilate knowledge the way other people soak up sunshine.

Friends and acquaintances play a significant role in the Fire Snake's life. It makes friends easily and keeps them interested because of its charm and willingness to participate in their lives. It will always help out a friend or even give a leg up to a person it has just met, because the Fire Snake believes avidly in the goodness of humankind and in its ability to rectify its own wrongs. To this essentially altruistic person, nobody is entirely foolish or criminal.

Unlike their somewhat reticent counterparts, Fire Snakes have strong opinions that they are not afraid to express with vehemence and clarity. This gift makes them keen politicians, actors, singers, writers, poets, and filmmakers—professions that give them the chance to put their strong ideals into action.

One drawback to the Fire Snake's charm is its unquenchable thirst for sexual intimacy. Its overactive sensuality is so forceful and directive that it is almost hindered by it. Sex is omnipresent in its thoughts. Its propensity for promiscuity is so great as to constitute a danger to its personal safety. It so needs to be found attractive, to make love, to be courted, admired, hugged, kissed, wooed, and smothered in love that it can forget its usually excellent manners and commit acts of foolishness that threaten its reputation and even its personal safety. It usually curtails its murky private involvements sufficiently so as not to tarnish its public persona. But if it is not careful, it may be blackmailed or attract negative newspaper coverage. Scandal sheets seem to sense the vulnerability of the Fire Snake.

Although it usually marries for love, the Fire Snake will not often remain physically faithful for long. Inconstancy comes with its nature. It is incapable of resisting the pull of sexuality that keeps it constantly on the prowl, hunting for new encounters. Its mate, however, should not interpret this as disloyalty. The Fire Snake is fiercely devoted to its family. It spends a lot of time with them, nurtures its children, and dotes on its partner. It depends on its family to anchor its fickle heart and keep it from drifting off into uncharted territory forever.

The Fire Snake enjoys traveling and is at ease in all social gatherings. Its manner is sardonically subtle and secretive. Although it is a deep thinker, when it comes to relationships, it is not profound. It can be counted on to keep a confidence or to uphold its end of a bargain. It is sometimes too judgmental and not indulgent enough with those it feels are insufficiently socially responsible. But the Fire Snake is a gentle sort. Its sterling integrity informs its every act—except, of course, in the bedroom, where no holds are barred and the sky is the limit.`,
        Earth: `Here, in the Earth Snake, is the very lightest of Snakes. The Earth element lends frivolity to the already delicately constructed Snake and gives it an extra dose of feminine charm.

More than any other, this Snake feeds on dreams. It is often lost in reverie and seems to be floating above the clouds. The baser aspects of life, such as violence, raw sexuality, squalor, and poverty, upset the Earth Snake so much that, to survive, it must always remain at a safe distance. Its cozy swarm of illusion serves as a cocoon for this fragile creature's sensitivities and protects it from harsh reality.

The Earth Snake is, nevertheless, an intelligent person, full of wild ideas and exciting plans. But, no matter how it works, it is not always able to carry through with its plans because of its curious, self-defeating habit of self-deception. It is a potentially marvelous magician who knows how to twist and turn facts and create its own version of the truth, but it fails to apply this talent to the outside world where it might need it to make a deal or navigate some difficult stage.

Instead, it tells itself that everything will be all right as long as it believes its own fabricated version of what is truly happening. This Snake ends up with a reputation for lacking perseverance and stability. It is perpetually joining forces with people who are even better at deception than it is, and finding itself lost and without an anchor for the duration.

To counteract this tendency, the Earth Snake is a marvelous seeker (and finder) of rock-like mates to shelter it from the harsh world and who know how to appreciate (and perhaps even exploit) the Earth Snake's brilliant deceptions.

I renovated a ruined house in a Provencal village some years back. My mason was a fantastically inventive Spanish craftsman named Juan who built me a fabulous four-bedroom house out of a ten-room dump. Juan always told me the truth—his truth. But sometimes his truths were just fantasies about how it could be so much more beautiful if I had a mezzanine here or a terrace there.

"I prefer to work on a house," he explained, "that I create myself, rather than just execute some foolish plan made by a mere architect!" Juan was a typical dreamy, inventive Earth Snake. Sometimes his wild dreams were feasible; sometimes not. When I didn’t have the necessary funds to meet his need to build me a roof garden or install a wrought iron staircase instead of a simple wooden one, Juan pouted or simply didn’t come to work for a few days. The fact is, he took my practicality as a slight—a desire to hinder his creativity.

As long as this Snake is well married or still in the safe embrace of its parents' home, it will not encounter too many disasters. At home, it is a kind of genius: it is tenderhearted and makes an excellent family person who always listens and understands the miseries of other members. It is an excellent parent and a superior host. Its warm welcomes and pleasantries infuse its guests with joy and a feeling of warmth from the moment they cross the threshold. It is generous and spontaneous, giving of its possessions and itself for the sake of friendship or loyalty to its clan.

The Earth Snake is more dependent than the other Snakes. It is very hard-working and clever at resolving difficult issues. Ideally, it should be employed by a large corporation or at least a solid small company or even the government. An insecure job where money and stability are not part of the package would cause it too much inner turmoil and lead to its departure or failure to uphold its responsibilities. It is not hard-hearted enough to boss others around, but because it is so exceptionally creative, it has plenty of trouble following orders.

The nature of this gentle soul is so pleasing, and its temperament so even and cheerful, that people with selfish motives, who criticize it for its timidity, its love of luxury, its easy-going attitudes, and its pure joy in living, often take advantage of it. It must be careful not to attach itself to those who do not have its best interests at heart. Those who associate with it must know how to appreciate its easy charm and be able to leave it at that. It cannot be hurried, pressured, or changed.

If alerted to the dangers surrounding it, the Earth Snake can usually identify the predators who seek to control and torment it. It is more than wise; it is cunning and exceptionally clever at understanding reality. It may become cynical and crudely aware of what is, but it tries to remain oblivious. It prefers to dream, plot, and scheme than to get up every morning and contend with the truths of the hard life ahead.

Aware of its frivolous nature, this Snake is often attracted to conservative types. Somehow, it is able to discern, through its haze of fantasy, that the best way to survive is by locating people more down-to-earth than itself and cultivating their friendship and love. It will often seem very creative and even silly by comparison to its steady mate. You might wonder why it chooses to live in a secluded area when it seems more like a typical Bohemian. The truth is, it is happier among the middle class, who demand only that it gossip or shop, cook or dispense love. And... it is happiest in a natural setting where trees, woods, and flowers provide a constant refuge from aggression. By staying out of the way, it is not obliged to leave its cozy nest of fantasy and can indulge in its dreams all day in complete safety.

The wise Earth Snake knows what it needs to survive and uses its innate charm and cheerful demeanor to obtain it. Perhaps in the context of suburban bourgeois security, or as a country gentleman, it will energetically fundraise for museums or restore a lovely old mansion, feed the starving millions from its brocade armchair, or even adopt unfortunate third-world babies. But do not count on the sensitive Earth Snake's willing participation in any projects requiring scrambling in challenging conditions. Even though its governing element is Earth, this Snake will fade and be miserable if it has to dip so much as its delicate big toe in the mud.`,
        Metal: `This type of Snake yearns for a grand life and even greater wealth. It is an individual with grandiose ideas—one might even say, delusions of grandeur. It is ambitious and desires notoriety. It seeks to display its talents to capture the attention of the entire world. Because of its intense need for public acclaim, it often succeeds in becoming something of a star, wherever it may live or practice its profession. The life of the exceptionally talented Metal Snake is marked by difficulty. It often experiences significant setbacks, losing fortunes or loved ones, succumbing to drug excesses, or cultivating misguided religious beliefs, both of which lead to disaster and cause it to lose precious time in its quest for fame and fortune. But it always regains its composure and resumes its pursuit.

Like all Snakes, because of its deep desire to please and be accepted, the Metal Snake is vulnerable, but it is even more so because it does not hesitate to openly express its emotions, to voice its opinions, and to open its heart to the general public. It melts with joy at thunderous applause. But it is unwary of the fickleness behind the applause of a public quick to lose interest, to grow critical and unkind towards the unprotected Snake whom they have admired. Negative publicity or an unappreciative audience can defeat this unguarded genius and drive it to suicidal thoughts.

Although it is insufficiently cautious of its public, this Snake is usually suspicious in its private life. It does not trust easily and will search for a long while before committing to marriage or family life. It wants to be sure it is not taken for a fool. It needs to know that its partner will be faithful and uphold its ideals. It must be assured of security before agreeing to bear the responsibilities of family. Of all Snakes, it is the most naive and believing in the fundamental goodness of humanity. It tries to be a good person, to emulate those it admires, and to advocate for humanitarian causes. Because the Metal Snake is sincere, it is easily deceived by unscrupulous characters who do not have its best interests at heart, accept its favors, use it, and then discard it. I would not go so far as to say it is attracted to undesirable individuals—but perhaps it is.

The Metal Snake takes delight in the chase and may not be able to remain faithful forever to a sexual partner. It knows that one day it will break the covenant of good faith that marriage demands. It does not necessarily enjoy this aspect of its character and even perceives it as somewhat of a handicap. Nonetheless… it was born with a restless urge and sometimes acts on it.

When it becomes aware of its imperfections, conflicts arise within the Metal Snake's responsible, stable mind, and it is not always comfortable in its own skin. It may experience periods of self-doubt. Or, more likely, it may do what it is so gifted for: rationalize. It will tell itself that it needs freedom to be creative, or that it must be at liberty to roam so that it can help humankind, or that a few infidelities will ultimately benefit the marriage. This Snake is highly deceptive but means no harm.

Ironically, Metal Snakes are chronic truth-seekers. They may be superficially sociable and desire to succeed in the world, but they secretly dream of solitude, of living in a state of blissful detachment with an unlisted phone number. In their daily life, they sometimes simulate a desert island anonymity by choosing not to answer personal questions, evading reality to maintain an aura of mystery about and for themselves.

There is none so opportunistic as this incisive and intuitive person, whose creative genius usually finds a lucky star on which to ride to the top. The Metal Snake can perceive an opportunity for success in everyone it meets. It cultivates contacts the way farmers grow cabbages. Its method of operation begins with charm and ends with seduction. One day, it will secure a partnership with the perfect sponsor, and before you know it, you'll be reading about its superstar status in everything from the tabloids upwards.

Despite its vulnerability and desire for fame and positive cash flow, this Snake is somewhat of an intellectual. It is curious and interested in the inner workings of the mind and will spend much of its spare time reading and studying, listening, or discovering new things. It may choose to specialize in history or even delve into obscure fields of philosophy and exotic Eastern religions. It keeps its own counsel, is superbly self-confident, and manages to remain remarkably independent—for a Snake.`,
        Water: `Great minds characterize these eminent Water Snakes. Their advantage over other, less logical and more thoroughly sensory Snakes, is that they are meticulous planners. Before embarking on any far-reaching project or moneymaking scheme, the intuitive Water Snake designs a sound, well-thought-out schedule with specific parameters and follows it precisely. It is a world-beater, a force to be reckoned with.

The Water Snake is wildly imaginative. It spends much of its time meditating on new ways to solve old problems or speculating on inventing new ones. It is devoted to childhood's fairy-tale world and cannot ever climb completely out of the comfortable cradle of infantile fantasy. An active imagination can be a marvelous asset, but the fertile mind of the Water Snake may exaggerate events, interpret them too vividly, and muddle reality. If this trait overwhelms it and it succumbs to exaggerated mental wanderings, the Water Snake may become paranoid and suspicious, fearing aggression or threats that are not truly present.

This person can be gainfully employed as an astrologer, soothsayer, or psychologist. Its psychic abilities are appreciated by friends and clients alike, who do not hesitate to call on it for advice. Its cool, reserved personality inspires confidence, and its soothing voice calms the shattered nerves of many who consult it. It knows so well how to soften harsh realities that it can make even the most afflicted person feel better.

The Water Snake preserves its good looks long into middle age. It takes care of its body and its diet. Vanity plays a part in this, but so does common sense, of which, despite its penchant for the fantastic, it possesses a good measure.

The Water Snake is socially responsible and cares deeply for the outcome of human events. It worries a great deal and is anxious by nature. Unfortunately, it also suffers from a mini-martyr complex and would rather play the victim than be the aggressor in its partnerships. This attitude may lead to self-pity, which, again, borders on paranoia. With luck, its tendency to whine and feel sorry for itself will always be discouraged and managed by the good sense with which it was born.

The Water Snake can never be accused of maliciousness. It is kindly and tries to comprehend the legitimate motives of people who hurt it. It is never unnecessarily judgmental or cruel. It boasts numerous friends who enjoy its sweet nature and approve of its methodical approach. It is generous—except when it has to pay for necessities—and can be a lavish spender. It is often an excellent cook, too, and prepares feasts at a moment's notice.

It is drawn to professions where music and art play an important role. Beyond that, anything from architecture to advertising or telecommunications would suit it. Like other Snakes, it seeks power and money, but unlike them, it is not conniving. It knows how to go about achieving its goals in a reasonable and honest fashion. It usually studies diligently at school and graduates with decent grades. It is able to conform to the norm sufficiently to make itself liked by its classmates as well as respected by its teachers.

The Water Snake is an active, serious person who lives life to the fullest, yet remains more than most other Snakes on the marital straight and narrow. It might enjoy the occasional dalliance with a stranger, but knows that such a transgression might jeopardize its overall plan and confuse its already complex psyche. It convinces itself that such dangerous temptations are not for it and finds comfort in its fantasy world, drawing, painting, or listening to music while reinventing the wheel.

Because it is dreamy, the Water Snake exposes itself to huge disappointments. It often overvalues a person or gives too much credit to an event and then discovers it was wrong. Its views are clouded by its desire to improve on reality. This sets it up for emotional or sentimental decision-making, which can be disastrous. It should always perform a severe reality check before embarking on any important, new plan.`,
    },
    compatibilities: {
    "Rat": "Although this alliance can often lead to an interesting friendship, I would not recommend it as a romantic relationship. Rat and Snake may be sexually attracted to each other, but ideally, their connection should remain purely social. On a daily basis, life for a Rat/Snake couple will be filled with upheaval, disagreement, and disappointment. After the initial physical attraction, the Snake will withdraw and keep aspects of its life securely private. The Serpent's inclination for flirtation will be even stronger if the Snake is attached to a clingy Rat. The Rat will grow uneasy and fearful about security. The Snake's investments may not prove profitable, and the restless Rat will have to take charge of the family's finances. Tempers will flare, especially the Rat's, who struggles under the burden of trying to maintain the crumbling foundation. The Snake? It will storm out of the house to the nearest Dior boutique to add to an already extensive wardrobe of fine lingerie. The only moments of tranquility in this union will be spent intimately, passionately entwined for hours. The Rat will appreciate the sexual attention the elusive Snake provides and, ever generous, will be forgiving. Be cautious, gentle Rat, of your enchanting Snake. If you are not careful, even you can become a victim. Snakes will draw you in with promises, love you intensely, then metaphorically consume you whole for breakfast.",
    "Ox": "A nimble Snake entwines itself around an Ox's yoke and accompanies it on its journey. The Ox welcomes its agile passenger and steadily progresses through life with contentment. A Snake feels comfortable in the Ox's presence. Yet, the fickle Snake possesses an appetite for new experiences—especially those yet unexplored. Oxen are devoutly monogamous. Deep down, of course, the Snake is devoted to the Ox, whose stability is crucially important for the Snake's survival. If the Ox can learn to curb its suspicious nature and control a jealous temper, this creature can retain an appealing Snake partner better than anyone else. After all, the Ox possesses all the money, power, and patience, and Snakes adore all those qualities. Should the Ox begin to worry over failed ventures or depleted reserves, the Snake must subtly lead it to bed. The Ox is happy to comply with lusty quantity, but to prevent the reptile's attention from wandering, it must develop more imaginative foreplay. This union can be a good one if the Ox can remain courageous and undaunted by a challenging (yet fascinating) Snake mate.",
    "Tiger": "The elusive Snake and the tempestuous Tiger are irresistibly drawn to each other, but this union is not advisable. A Tiger/Snake pairing can be a disastrous alliance. As different as black and white, yin and yang, the Tiger/Snake combination simply does not blend. Should either of you be unfortunate enough to fall for the other, a preliminary restraining order could save you from catastrophes. If not, here is what to expect: The slow-moving Snake will inflict tremendous frustration upon the energetic Tiger's psyche. Initially, the jungle predator mistakenly perceives the enchanting serpent as quiet and submissive, and attempts to dominate. But reptiles do not respond well to bullying; they retaliate. Snakes are aloof, independent-minded, and strategic masterminds. Haughty indifference and disdain are among their sharpest weapons. They are also prone to repeated instances of infidelity, which will certainly shatter a Tiger mate's considerable ego. The impressive tantrums of the Tiger can make the Snake's calm, reflective, philosophical life miserable. Equally magnetic, Snakes and Tigers compete for attention. The Tiger does so aggressively, and the Snake slyly bewitches. At their own cocktail party, Tiger/Snake hosts may appear quarrelsome. The Tiger recounts stories about its days in the Sinai desert. The Snake subtly encroaches on the Tiger's territory, captivating the company with the Dance of the Seven Veils, learned (coincidentally) in the Sinai desert. Outmaneuvered, the Tiger loudly outdoes the Snake, recounting further desert expeditions. Subdued, the Snake joins the applause, but adds, in a cultivated, soft-spoken voice, that everything the Tiger knows about deserts was learned from the Snake. Tigers are fast and alert, while Snakes are quiet and deliberate thinkers. Tigers are impulsive and may act heedlessly. Snakes rely almost solely on intuition and take things slowly. These creatures may cohabit for sensual pleasure, but they do not see eye to eye. Sexual intimacy? The Snake's need for beautiful, romantic foreplay is denied by an aggressive Tiger, who simply gets down to business. It is best to abstain!",
    "Rabbit": "The intuitive Snake and the philosophical Cat find each other mutually interesting. Both possess keen minds and are deep thinkers. Should they encounter difficulties, this couple can rely on their shared innate wisdom to guide them out of trouble. The extravagant Snake makes weekly shopping appointments with salespeople at Cartier and Dior. This upsets the cautious, tradition-bound Cat, who disapproves of the Snake’s inclination for the lavish. Conflicts are easily resolved if the Cat is permitted to manage the finances. However, unless the Cat learns to understand the Snake’s desperate need for the most opulent accessories and surroundings, a powerful python partner may become a listless garden Snake. A deprived Snake can also be a hostile reptile. These two pleasure-seekers can usually resolve their differences, spending an evening over a bottle of Pommard. As a couple, this pair exudes charm. They make excellent guests and can expect invitations to all the most desirable parties. In public, the Cat fears the Snake’s incessant flirtations, finding the Snake’s open, raw sexuality difficult to handle. But Snakes have their irresistible ways with reserved Cat lovers. Both are potential psychics; if all else fails, they can always become traveling fortune-tellers.",
    "Dragon": "In Chinese astrological terms, these two are considered very close relatives. The Dragon adores having a gorgeous, attractive, and sensual Snake partner, and the quiet, subtle Snake admires the Dragon’s world-beating flamboyance and style. In turn, the Dragon protects the Snake. The Snake pampers the Dragon’s ego and allows the Dragon to speak freely without even a hint of criticism. Of course, no relationship with any Dragon can ever be entirely calm, but the Snake/Dragon duo comes close to being a levelheaded, harmonious union. Wisely, the Snake never directly confronts the Dragon’s ego. Snakes handle conflicts subtly, observing and examining all sides before striking at precisely the right moment to achieve results. Sexually—with the Snake’s immense capacity for erotic activity and the Dragon’s vast appetite and innate talent for the same—you can just imagine... the chemistry is sublime. They also agree on living luxuriously. The Dragon buys endless delightful accessories for the Snake’s pleasure, and the Snake allows the Dragon—within reason—to indulge in filling the house with gadgets. Their home life is excellent; they make a handsome couple. It is truly a match made in heaven.",
    "Snake": "This relationship is characterized by drama, sexual intensity, luxury, promiscuity, passion, and potential ruin. Two Snakes could be doubly indolent. Both tend to dissimulate and desire to be surrounded by beautiful things and unusual friends. The couple’s life will be fraught with intricate complexities and unexpected occurrences. A Snake couple is artistic. Together, they will enhance their cultural existence, regularly attending exhibitions, concerts, and theater. As they also tend to be philosophical and are drawn to the metaphysical, they will often engage in exciting New Age activities and hold conversations that last far into the night. This sexually compatible pair will entwine upon first meeting and subsequently have great difficulty disengaging for even the most important practical matters. Tenderness, romance, and passion are the very cornerstones of their intimacy. Although the financial aspect of their joint life might be a real mess, an overwhelming physical attraction binds them together. Despite a tendency towards infidelity on both sides, no jealousy will cloud their lovemaking. In fact, these two may hardly emerge from between their smooth satin sheets long enough to allow the live-in, full-time maid to wash them.",
    "Horse": "These two are strongly attracted to each other. The Horse admires the Snake’s natural ease with people and appreciates its considerate, charitable nature. The Snake, on the other hand, likes and respects the Horse’s spiritedness and innate enthusiasm. Their social life will be rich and full. Trouble begins when the Horse realizes that its adored Snake mate is 'running around.' Promiscuity does not sit well with the straightforward, faithful, devoted Horse. So, the Horse shifts into a mode of recrimination, which forces the Snake to conceal any extracurricular activities more cleverly—but not necessarily to abandon them. The Horse does not handle duplicity well, and storms ensue. The Snake has a generous heart. The Horse is more conservative with money. This disparity will cause some significant arguments. It is best to let the Horse manage the finances and dispense money to the Snake for trivialities. But do not expect the money-loving Snake to accept that arrangement; it wants to spend! The Horse may bolt. Almost everyone is happy with a sensual Snake person in their bed. Horses have little confidence in their sexuality, but Snakes have more than enough to share. They make good, considerate teachers. The match can work if the Horse can learn not to fall apart when the Snake embarks on sensual, romantic interludes, and the Snake can learn to curb its inclination for minor indiscretions.",
    "Goat": "Charming and graceful, this pair of artistic, creative people can have the world eating out of their hands. The Goat’s inherent beauty and seductive appeal, when combined with the Snake’s elegance and sensuality, form an enviably synergistic couple. Theirs will be a delicious complicity. Unfortunately, neither of these gloriously attractive people is very adept with a calculator. They are both equally improvident, luxury-loving, and even extravagant with spending. Unpaid bills will accumulate, and each will accuse the other of being a spendthrift, leading to a stalemate. Do not expect the Goat to find solutions. Snakes may overspend, but they also provide. Goats are determined to be dependent and provided for. The Snake will only tolerate so much of the Goat’s indolence and will soon find the poor Goat a high-paying job and compel it to arrive at the office on time and perform its duties well until death do them part. Once again, the Snake’s incurable infidelity enters the equation. Goats tend to be fickle too. But, even though the Snake understands the Goat’s occasional need for a fling, the more stubborn Goat dislikes sharing its possessions and will react strongly to the Snake's infidelity. But never mind; arguments are a part of these people’s lives: both are addicted to passionate drama. Romantically, this couple is sound. But when the harsh, overhead light of reality penetrates the veneer of their relationship, the cracks and flaws may prove too numerous for its survival.",
    "Monkey": "Auspicious beginnings encourage these individuals to unite and operate as a team. The versatile Monkey finds wisdom and consideration in the Snake’s personality. The Snake enjoys the Monkey’s charm and energetic spirit. They are truly a complementary pair. After a time, however, they will realize that all they have in common is a desire to help others, a charitable inclination that binds them ever so loosely together. The Snake, of course, always embarks on extramarital adventures. The Monkey? Well, the Monkey could not care less: if affairs arise, so much the better. If not, it can take them or leave them alone. Snakes value elegance and desire their lives to be carefully accessorized. Monkeys are bored by the very idea of accessorizing anything and prefer casual attire to dressing up. Monkeys are spontaneous; Snakes are deliberate. The Snake is romantic, the Monkey logical. The Snake is sophisticated, the Monkey bohemian and carefree. Monkeys love to converse, but dialogue becomes difficult because Snakes find it hard to reveal their inner feelings. A breakdown in communication might be the demise of this relationship. Their sex life usually compensates for much of the strife between them. Although sexual intimacy is not always the Monkey’s strongest suit, Snakes succeed in exciting them greatly. The complicity of elaborate sexual games may provide a foundation for this pair to strengthen their union—despite their essential differences.",
    "Rooster": "A perfect love match, if ever there was one! The Rooster is rather conventional and traditional. Snakes are aesthetic and desire to appear attractive at all times. Although, at first glance, it may seem that the Snake is too sophisticated and elegant for the plain-living Rooster, the opposite is true. Roosters and Snakes form some of the best couples. They are both quite secretive and prefer to keep to themselves. Yet, when together, they are constantly engaged in intense discussion and consideration of every detail, from the quality of light inside their refrigerator to the leather on the soles of their expensive shoes. Roosters are mostly forgiving, indulgent people whose loyalty knows no bounds. Snakes may engage in some casual social and sexual dalliances, but they are careful never to become deeply involved with their conquests and hardly ever betray or leave their Rooster mates. Why? Because they truly love them. In this marriage, the Rooster should manage the finances. Snakes often waste money; Roosters keep closer tabs on their pennies. The cultural side can be handled equally well by both. Sexual intimacy should definitely be left to the seductive Snake. Snakes know how to arouse hesitant Roosters and make their bodies sing. Roosters are basically reserved about sensual matters. The Rooster who finds a Snake as a mate will have much to boast about.",
    "Dog": "This partnership is imbalanced. We are dealing with two disparate types of people. Dogs are pessimistic, prone to depression and worry. Snakes are naturally relaxed, less anxious, and certainly less sarcastic. Sometimes the doubting Dog even mistrusts a companion Snake’s charm and will whine and snap about it, criticizing the Snake for both frivolity and an easygoing nature. Basic personality differences do not have to destroy relationships. But the Dog dislikes society, has few friends, and stays at home a lot. Snakes are just the opposite, yet they need a home to return to after their numerous forays into the wider world. Returning to the comfortable Dog home after experiencing society's greed can be refreshing for the sociable Snake. Even though they snarl and threaten, Dogs always forgive, are loyal to a fault, and never waver in their devotion to their loved ones. Both parties are sensitive to causes, feel strongly about combating injustice, and believe in right over might. This similarity of purpose can serve to harmonize their relationship and smooth out some potential rough edges. The problem is, their sexual selves are very different. Dogs are physically conventional and direct. Snakes are highly adventurous in bed and enjoy intricate sexual play. The two may not clash over this issue, but the Snake may eventually grow bored, resume a natural inclination for flirting, and irrevocably damage the Dog’s tender-hearted soul.",
    "Pig": "This is the Pig’s nemesis. Chinese sages always advise against this relationship. They say that the rapacious Snake will eventually strangle the unsuspecting Pig. It is interesting because Pigs are earthy, warm-hearted individuals who are easily swayed by beauty and cultural sophistication. So, inevitably, the first gorgeous, sex-loving Snake to come along completely captivates the Pig, who cannot resist. Superficially, the luxury-loving Pig has much to offer a Snake lover. Pigs are scrupulous and mostly honest. They usually know how to earn a lot of money, which the Snake loves to lavish on their joint lifestyle. They both adore traditional things like antiques, vintage wines, and castles in Spain. The problem here revolves around a shared weakness: neither the Snake nor the Pig is a world-record decision-maker. The Pig changes its mind as readily as the Snake changes its outfit. The Snake procrastinates. The Pig wallows and wonders. They are sexually compatible to a fault, but little is accomplished in life by lying about intertwined in each other’s limbs. Pigs do not care much about appearances, making rude noises and smacking their lips when they eat. Eventually, a fastidious Snake grows critical of a Pig’s sloppy habits. The Snake’s sarcastic remarks bring out the worst in the Pig, who whimpers, which only makes the Snake more impatient and even cruel. The gracious Pig can never please the demanding Snake enough. It finally just sadly withers away and leaves all its money to the voracious beauty it could not resist marrying."
    },
    futures: {
        "2025": {"year": "Snake", "element": "Yin Wood", "prediction": `As you will be in the driver’s seat this year, you can expect to be supercharged and cheerful most of the time—except when events accelerate and too many demands are made on your time. You prefer to live your life at your own pace. This year, you will be compelled to follow the hectic rhythm of the world and its drastic politics. In Snake years, the planet’s geopolitical climate generally intensifies to full throttle by about July and does not calm down until well after the following January. I know that being a member of the ruling class sounds terrific in theory, but in practice, it is an entirely different matter, with everyone vying for top status. You will need ample rest and relaxation this year if you want to remain in good health. Ideally, you would take one day off a week, but of course, almost nobody—not even you relaxed Snake people—can do that with a clear conscience. Instead, tune out. Wear earphones and blinders. Turn off the house phone, the cell phone, the TV, and your computer so you can take a few short naps here and there. If you are still without a life partner (rare for the irresistible Snake), this year will present you with a couple of serious options. Stick to Roosters and Oxen if you can. If not, dare to marry a Tiger. OR... why not hitch your wagon to a Dragon?`},
        "2026": {"year": "Horse", "element": "Yang Fire", "prediction": `Many people believe Horses and Snakes do not harmonize. Many people are correct. This year will be challenging at best for Snakes, as the Horse is not even-tempered and does not particularly care about its subjects’ well-being. Horses are intensely pragmatic; they simply want to do things their way. They are talented and shrewd, and they are artistic, but not necessarily altruistic. You Snakes are motivated by compassion and philanthropy; you sincerely believe in your ability to contribute to the betterment of humankind. So, Snake dissatisfaction is common in the ego-centered Horse year environment. You will feel as though you just cannot make progress on any project and maintain it without obstacle after obstacle being thrown up and roadblocks appearing at every turn. You might, moreover, become entangled in a legal battle over a contract or real property. As the climate in Horse years is unfavorable to a positive outcome for Snakes, you will not have much chance of winning. It would be better to try some cunning tactic to delay the lawsuit until next year when the gentle Goat will rule—a more lenient climate for Snakes involved in legal disputes. Obviously, this year will not be your favorite. Take your frustration on a long holiday somewhere warm and tropical with your significant other in tow. Should your significant other be (for some strange reason) a Horse, I advise that you leave him or her at home. Perhaps you should consider seducing someone more philosophically inclined.`},
        "2027": {"year": "Goat", "element": "Yin Fire", "prediction": `Goats usually find you Snakes alluring, but in another way, they cannot stand to be near you. Why? Because you are so quietly strong, capable, and attractive, and Goats are so dependent and pessimistic. Deep inside, they sincerely wish that you would take care of them. You, of course, are not very willing to take care of anybody except your good looks, your favorite charities, and your beloved family. So the atmosphere in this Goat year is lukewarm for Snakes, and if there is anything Snake people dislike, it is tepid affection. Snakes prefer it hot; Goats prefer it comfortable. So, watch out for the possibility of someone younger or weaker than you who will try to crawl into your life, eat from your fridge, soak up your central heating, and generally just settle there until you force them out. It might be a relative or an ex, a niece, or just a nice person you feel sorry for. You invite them to stay until they get back on their feet. After only a few months, they now live with you and your family, and the entanglements are many. Take advice from your significant other or a wise close friend who will show you how (diplomatically) to get rid of the intruding guest without having to either create scenes or witness a very unpleasant houseguest tantrum unfold.`},
        "2028": {"year": "Monkey", "element": "Yang Earth", "prediction": `You will need your indomitable strength this year to withstand the onslaught of the Monkey’s intricate antics. Monkeys crave attention and will perform almost any type of outrageous act to get it. Perhaps you will not be drawn in by the Monkey’s neurotic charm, but if you are—beware! You provide an excellent audience because you simply love spectacle. This characteristic puts you in considerable danger in Monkey years. Because you find entertainment so attractive, you can be deceived. Monkeys are tricksters who do not care much whom they are performing for, as long as the public rewards them. So, in this year of the Monkey, Snakes must guard their finances, secure their purse strings tightly, and avoid temptation. Do not even think about entering a casino or going near a card game. Remain aloof by undertaking a major creative project that keeps you grounded and in one place. Your romantic life may also provide a safe haven—provided, of course, that you are not married to a Monkey. Should this be the case, consult a Dog or Ox psychiatrist, or else—move to Tibet—alone!`},
        "2029": {"year": "Rooster", "element": "Yin Earth", "prediction": `Snakes and Roosters make excellent companions. You appreciate each other’s energies and can both easily understand the other’s point of view. Being naturally able to glimpse into almost anyone’s private life, you Snakes do have a distinct advantage over us mere mortals. Roosters live their lives and play their cards very discreetly. Hence, being capable of subtly understanding them (as all self-respecting Snakes can) constitutes a huge advantage for you in Rooster years. As the Rooster is so comfortable in your presence, you can also count on this year to provide you with the financial security you so long for and deserve. What’s more, this Rooster year gives you the opportunity to ascend to new and more prestigious heights in your professional life. All doors seem to open at once. Executives who until now refused to receive you suddenly call you to inquire if they can make an appointment. Promotions come your way when you least expect them. It’s a great year for Snakes to make progress in every area of their existence. The ups and downs created by this new commotion will surely land you at the doctor’s office once or twice during this twelve-month period. But never mind; the rewards will be worth any anxieties or upsets you may suffer because of the Rooster’s demanding pace.`},
        "2030": {"year": "Dog", "element": "Yang Metal", "prediction": `The Dog protects its charming Snake companion and, like all dogs, loves you unconditionally. Both Snake and Dog individuals have humanitarian goals. The Dog is more spirited and vocal about desiring justice for all, but you do see eye-to-eye when it comes to believing that something can and ought to be done about the innumerable examples of human cruelty prevalent in the world today. You may not form a perfect team, however, as you and the Dog both prefer to be in charge. But each in his or her own way is constantly vigilant for signs of bias and unfairness. The Dog is slightly more paranoid about evil being perpetrated against its own person. You are cool-headed and confident in your ability to rectify wrongs. But no matter; you will be appreciated for who you are and, of course, admired and adored for your natural beauty. In this favorable climate, you should dare to undertake new projects, establish your own business, or build yourself a dream house. Whatever you create will be solid and well-received. Dogs emanate anxiety vibes. As the year progresses, this fretfulness will most likely affect you, as it is contagious and can undermine your peace of mind. Take time out; practice yoga, tai chi, or meditate to quell the unease.`},
        "2031": {"year": "Pig", "element": "Yin Metal", "prediction": `Take advantage of the Pig’s profound adoration of you to make progress this year. Nothing is more attractive to a plump, trusting Pig individual than a slender, worldly-wise Snake who (to Pigs) seems to possess all the answers. Pigs are sweet, innocent, and tough. Snakes are not so sweet, never innocent, and… they are far tougher than Pigs. Pigs, however, possess something that all Snakes desire: money. For some peculiar reason, Pigs attract wealth. They moreover covet and acquire everything authentic in sight—from rococo antique tables to old masters’ paintings and gilded Louis XV sconces, and castles and palaces and gold. Snakes certainly do not disdain that sort of asset and will sometimes vigorously pursue and even conquer the poor, unsuspecting, vulnerable Pig. But that’s another story. This year, Snakes thrive. You can count on everything from passion to a reprieve from your allergies and skin ailments. The only dark aspect of this year’s forecast will reveal itself if you try to make rapid decisions. Stay away from people who ask you to participate in their schemes. Adhere to your own work ethic and do not partner with anyone except your good self.`},
        "2032": {"year": "Rat", "element": "Yang Water", "prediction": `Your health and well-being are in excellent condition this year. All the ailments you were suffering last year will dissipate in the beneficial atmosphere of the protective Rat. Trouble may be brewing, however, in your financial sector. Although you will begin the year with a sense of abundance and continue it with ample sufficiency, you may encounter some unexpected financial difficulties towards the end of the year. You should start saving money for the future and curb your buying sprees. Shopping may be calming for you while it is happening, but when those alarming credit card bills and excessive mortgage payments start flooding your mailbox, it will be goodbye to serenity and hello to stress and late-night anxiety. Much emphasis has been placed on your family situation for the past twelve months. Now it is time to pursue career goals and achieve them for your and your family’s benefit. The Rat is a nervous type, and that intense atmosphere emanating from the very core of this year causes you anxiety. Secure your finances more tightly and accumulate security. Invest only in what you can genuinely afford. Otherwise, you will be struggling against the current for twelve long, frazzled months.`},
        "2033": {"year": "Ox", "element": "Yin Water", "prediction": `Snakes are the Ox’s best friends, and vice versa. You are both deliberate and slow-paced, and your energies are similar in character. So, this coming Ox year for Snakes will be beneficial, productive, and personally valuable. You will return to your natural rhythm and enjoy the kind of relaxed mood in which you always devise your best schemes and are able to complete projects that needed finishing or enhancing. Last year truly slowed your progress to a subtle crawl, but the Ox appreciates your quiet sense of aesthetics and is always there to help you realize your dreams. Love is also back. You will be feeling more romantically intense than you have been in a while. The reason? Your financial and health troubles are behind you. Do remember, though, that the Ox is a demanding individual and does not tolerate idleness. One must demonstrate a willingness and ability to labor under pressure in Ox years, and even though the Ox favors you and considers you its companion, you will still have to apply yourself diligently and begin working on projects and problems left undone in previous (less benevolent) years.`},
        "2034": {"year": "Tiger", "element": "Yang Wood", "prediction": `The Tiger wishes you only the best. Its influence, however, is an entirely different matter. Tigers have a reputation for stealthily prowling the world's jungles late at night, stalking their prey. This animal portrait does not quite fit the profile of the restless Tiger individual. Tiger people are extremely active; they leap and bound and rush about searching for new and different experiences. They adore change and prefer it to happen quickly. You Snakes prefer to recline in silken repose on chaises longues, reading novels with intricate, winding plots, expansive detailed geographies, and complex characters. Let’s just say your styles are different, and your goals are not the same either. You wish to reflect and philosophize; Tigers act first and think second. Because of their immense charm, Tigers are frequently chosen to lead, but they rarely lead far without the wise counsel of someone like you. How could they? They have change for brains—loose change at that. So this Tiger year will be a challenge for Snakes. You will be called upon to advise friends and foes alike. You will be in charge of wisdom. Minor accidents and small setbacks will annoy you, but you are not in danger. In the hands of a Tiger, a Snake can feel a certain thrill. But do not look for security this year, because there isn't any to spare.`},
        "2035": {"year": "Rabbit", "element": "Yin Wood", "prediction": `You Snakes will need all your cunning skills this year because the Cat/Rabbit and you are traditionally at odds. You are not inclined to conceal your feelings and almost never spare us the details of your moods. The Cat/Rabbit is a master of secretive and covert behavior. He or she never wishes to attract much attention or confront conflict. The prevailing mood of Cat/Rabbit years is anything but direct. Instead, it is quiet, effective, and exceedingly calm. You are constantly moving and scurrying about in an attempt to control and manage things your way. Your very restlessness irritates the Cat/Rabbit. This will be an excellent year for investment. Make it your priority to conduct business, but keep your sharp little eyes peeled for trickery and theft. If you are not in a committed relationship, you could very well fall deeply in love this year. If you do, then whisk your new beloved away to a secluded island where the two of you can daydream about next year, which promises to bring far more favorable vibes your way.`},
        "2036": {"year": "Dragon", "element": "Yang Fire", "prediction": `Relax, my little Rat friend. The Dragon and you are long-standing allies. You respect the flamboyant Dragon’s need for attention and never threaten to overshadow its brilliance. Your intelligent handling of Dragons is, in fact, legendary. You understand how to let it shine while quietly building your own empire in the background. The mood of the Dragon year is celebratory. These magnificent creatures enjoy hosting large gatherings for thousands at numerous festivals and events of all kinds. Any excuse for a grand commemoration is welcomed. It is the Dragon’s way—the more ceremonial the event, the more it enjoys watching people have fun. You do not mind playing the charming guest among the Dragon’s countless friends, all the while planning your own networking strategies. Play hard this year and make the most of opportunities while the Dragon’s brilliant sun is shining on your life. Enjoy this hectic but fortunate year; it is guaranteed to be one of your most memorable and best.`}
    }
};

  

    