/**
 * @fileOverview Verbatim Enemy Year Dynamics for Personal Years 4 and 7.
 */
export const CONVERGENCE_CARDS = [
  {
    year: 4,
    title: "Personal Year 4 × Enemy Year Dynamics",
    sub: "The Fortress Year — When Structure Becomes a Prison",
    intro: `Personal Year 4 is governed by Rahu — the North Node of the Moon, shadow planet of karmic compulsion, disruption within structure, and the hunger for material security that can never be fully satisfied. Year 4 demands building: financial foundations, organizational systems, disciplined habits, long-term plans. The danger is not failure to build but building the wrong structure — or mistaking the cage for the cathedral. In the Lo Shu system, Year 4 occupies the Southeast (wealth/prosperity sector), governed by Xun (Gentle Wind, Wood element). The annual flying star interacting with this placement determines whether Year 4's building energy encounters support or resistance. Years when the 5 Yellow Star visits the Southeast create the most challenging foundation-building conditions in the entire Lo Shu cycle.`,
    chips: [
      { t: "Life Path 5 in PY 4", p: "The freedom-seeker imprisoned in structure. LP 5 individuals — Mercury-ruled, restless, transformative — experience PY 4 as suffocation. Career locks feel permanent. Routines feel like chains. The resolution: 4's foundations enable future freedom. Build now; fly in Year 5. Suppressing 4's demands creates karmic debt carried into 5." },
      { t: "Life Path 3 in PY 4", p: "Creative expression meets bureaucratic resistance. LP 3's natural overflow of ideas meets Year 4's demand for systematic execution. The shadow: abandoning creative visions at the 4-year mark repeatedly, never building anything lasting. Year 4 is specifically when the artist must learn the administrator's discipline — or find one who can do it for them." },
      { t: "Life Path 1 in PY 4", p: "The pioneer in a year that demands consolidation. LP 1's natural initiating energy conflicts with Year 4's requirement to deepen what was already started. The temptation: beginning new ventures to escape Year 4's consolidation requirement. The invitation: apply your pioneer courage to the unglamorous but essential foundational work." },
      { t: "PY 4 + Universal Year 1 (2026)", p: "Particularly tense convergence: collective initiation energy (UY 1) pulls toward new ventures while PY 4 demands consolidation of existing structures. Caught between the world's call to begin and the soul's requirement to finish. Resolution: stabilize foundations before launching. Use the UY 1 energy to initiate the specific foundational disciplines Year 4 requires." },
      { t: "Rahu's Karmic Shadow", p: "Rahu governs obsessive seeking without satisfaction. In Year 4, this manifests as workaholic patterns, hoarding behaviors, or building structures driven by fear rather than vision. Rahu's Year 4 lesson: security is never found in accumulation. The foundation must be built on trust in the cycle's wisdom, not on fear of the void between completion and new beginning." },
      { t: "Lo Shu: The 5 Yellow Center", p: "In Chinese numerology, the annual 5 Yellow Star visiting the center during Year 4 creates maximum obstruction: all directions carry resistance, financial decisions carry heightened risk, structural projects encounter unexpected delays. Metal element cures (brass wind chimes, metallic objects) suppress the 5 Yellow's disruptive influence wherever it visits your home." },
      { t: "The Chaldean 13/4 Warning", p: "When Year 4 reduces from compound 13, karmic weight intensifies dramatically. 13/4 is Regeneration through Upheaval — transformation forced by structural collapse. Buildings literal and metaphorical may fall before new ones rise. The invitation: release attachment to forms that have outlived their purpose before the collapse makes the choice for you." },
      { t: "Health Architecture in PY 4", p: "Rahu's compulsive energy combined with Year 4's structural demands creates the highest workaholism risk in the cycle. Physical grounding practices are essential protective measures: barefoot earth contact daily, root chakra yoga, regular sleep regardless of deadlines, and the deliberate scheduling of genuine rest as a non-negotiable structural commitment." }
    ],
    warning: "<strong>Navigating PY 4 Enemy Dynamics:</strong> Build deliberately. Choose one primary foundation (career, financial, health, or creative) and commit to it with complete consistency. Reject Rahu's compulsion to secure everything simultaneously. The Lo Shu teaches: water finds its level — true security emerges through patient accumulation, not anxious grasping. What you build in Year 4 with genuine patience and discernment outlasts anything built with frantic urgency."
  },
  {
    year: 7,
    title: "Personal Year 7 × Enemy Year Dynamics",
    sub: "The Hermit Year — When Solitude Becomes Exile",
    intro: `Personal Year 7 is governed by Ketu — the South Node, the shadow of past lives, mysticism, detachment, and the dissolution of ego-identity. Where Rahu in Year 4 hungers for more, Ketu in Year 7 seeks the subtraction of everything inessential. The individual is pulled inward toward study, contemplation, and the terrifying question of who they are when stripped of social roles and material achievement. Year 7 is the most spiritually demanding year in the cycle and the one most consistently misunderstood by the world. Chinese numerology maps Year 7 to the West — Dui trigram (Joyous Lake, Metal element), the direction of harvest completion and autumn's refining intelligence. Forcing Year 7 into social or commercial productivity violates Metal's mandate to refine, cut away, and reveal the essential.`,
    chips: [
      { t: "Life Path 6 in PY 7", p: "LP 6 — Venus-ruled, home-centered, relationally responsible — meets Year 7's withdrawal demand with profound conflict. Loved ones need presence; Year 7 requires retreat. The guilt compounds the isolation. Hidden invitation: Year 7 teaches LP 6 that genuine love cannot come from depletion. The hermit who fills their well returns with real sustenance rather than performed giving." },
      { t: "Life Path 1 in PY 7", p: "LP 1's pioneer identity — built on visible action, leadership, and initiating — dissolves in Year 7's interior fog. The self that knew how to begin find no path to begin. This is not failure but preparation: Year 7 strips the warrior to the mystic, dismantling ego-scaffolding so Year 8's true authority can emerge from inner knowing rather than outer performance." },
      { t: "Life Path 3 in PY 7", p: "LP 3's creative and communicative nature meets Year 7's requirement for silence and contemplation. The expressive self that flourished in Year 3's bloom finds Year 7's quiet disorienting. The invitation: discover what creative depths become available only through the discipline of silence. Some of the cycle's most important creative insights arrive in Year 7's stillness rather than Year 3's exuberance." },
      { t: "Ketu's Past-Life Trigger", p: "Year 7 is when ancestral and past-life material rises most urgently. Ketu rules what was mastered in previous incarnations and what must now be released. Recurring dreams, inexplicable fears, sudden spiritual openings, encounters with teachings that feel like profound remembering — all are Ketu's hallmarks. This material cannot be rationalized away; it must be witnessed with presence and allowed to complete its surfacing." },
      { t: "The Ajna Crisis: Third Eye Opening", p: "Ketu activates the Ajna chakra in Year 7, bringing heightened intuition, psychic sensitivity, and occasionally disturbing perceptions. Some individuals experience depersonalization — reality feels thin, the self feels porous. This is not pathology but spiritual transition. Without grounding practices (earth contact, physical exercise, regular meals, consistent sleep), the Ajna opening becomes destabilizing rather than illuminating." },
      { t: "PY 7 + Universal Year 1 (2026)", p: "Extreme tension: a collective year of new beginnings presses against the soul's requirement for stillness and dissolution. The individual in PY 7 during UY 1 faces maximum social pressure to launch and begin while deepest wisdom counsels silence and integration. The mature response: honor Year 7's requirement privately while engaging selectively with collective energy, preparing inner foundations for Year 8's emergence." },
      { t: "7 Red Star Volatility", p: "The annual 7 Red Star's volatility — arguments, theft risk, controversy — combined with Year 7's contemplative requirement creates double Metal intensity. This combination is prone to extreme isolation when the 7 Red Star's conflict energy makes social engagement feel dangerous, further enforcing Year 7's withdrawal. Water element remedies balance excessive Metal: fountain, black objects, flowing forms in key spaces." },
      { t: "The 16/7 Shattered Citadel", p: "In Chaldean practice, the 16/7 compound indicates that Year 7 may dismantle structures built for security before revealing the eternal beneath. Those who have built their lives on genuine values experience this as liberating; those who have built on fear or performance experience it as devastating loss. Year 7 from 16 tests the authenticity of every structure in your life." }
    ],
    warning: "<strong>Navigating PY 7 Enemy Dynamics:</strong> Year 7's greatest enemy is refusing to go inward. Mistaking Ketu's calling for depression, failure, or abnormality — and attempting to medicate or social-activity away the contemplative pull — creates the actual crisis. Those who surrender to Year 7's mandate for retreat, study, and inner work emerge in Year 8 with unprecedented practical wisdom and genuine authority. Ketu's gift is only received in the silence that Year 7 creates whether you choose it or not."
  }
];
