/**
 * @fileOverview Verbatim Animal/Zodiac metadata and relationship descriptions from Chunks 02-04.
 */
export const ZOO: Record<string, any> = {
  Rat: {
    e: '🐀', i: 0, n: 'Rat', el: 'Water', pol: 'Yang', br: 'Zi',
    organ: 'kidneys, ears', dir: 'North',
    trait: 'intelligent, adaptable, resourceful, quick-witted',
    clashDesc: "The Zi-Wu clash is Water-Fire mutual extinction at maximum intensity. Your Rat's yin Water intelligence and adaptability confronts Horse's explosive yang Fire energy head-on. 2026 (Bingwu Fire Horse) is the peak expression — Fire stem doubling Fire branch against your Water nature. Expect forced movement: career disruptions, relationship volatility, geographic shifts. The classical teaching — use movement to respond to movement — means proactive transformation beats reactive resistance. Those who initiate change in Horse years fare dramatically better than those who resist it.",
    harmDesc: "The Zi-Wei harm operates through concealed depletion. Goat's Earth appears to stabilize your Water, but gradually absorbs and depletes your vitality. Unlike direct clash confrontation, harm year damage is invisible until cumulative — trusted associates with hidden agendas, authority miscommunication that builds quietly, financial drain through seemingly minor ongoing expenses. Your characteristic Rat intelligence becomes a liability when excessive trust is placed in relationships containing concealed adversaries. Verification, documentation, and independent information sources are essential protections.",
    destructionDesc: "Rooster's Metal appears productive to Water (Metal generates Water) but becomes corrosive when excessive — fragmenting your fluid Rat adaptability into scattered pieces. Partnership dissolution through accumulated incompatibility, unexpected expenses emerging from overlooked structural weaknesses, projects failing near completion from details that weren't tracked. The Rooster year brings the precision and standards that expose what the Rat's fluid nature has left insufficiently structured.",
    benDesc: "Your Ben Ming Nian intensifies all Rat qualities to maximum expression — a double-edged amplification. Your intelligence becomes hypersensitivity, your adaptability becomes volatility, your resourcefulness becomes anxious over-preparation. Health vulnerabilities center on kidneys, urinary system, and ears. Career recognition tends to be delayed despite genuine effort. Financial instability from unexpected expenses. Yet this year also brings extraordinary perceptive gifts: heightened intuition, accelerated learning capacity, and the ability to see systemic patterns others miss. Strategic practice: structured self-assessment using heightened awareness for deliberate life architecture. Wear red undergarments and accessories received as gifts from elders. Perform An Tai Sui at a temple in the first lunar month.",
    allianceDesc: "Dragon and Monkey years form your San He Water triangle, providing multi-directional support: Dragon combines imperial vision with your Water wealth capacity for major career advancement; Monkey's cleverness allies with your adaptability for creative problem-solving and negotiation. Ox years offer Liu He alliance — conjugal intimacy energy where your Water intelligence finds grounded expression through Ox's Earth manifestation capacity. These alliance windows reward advance preparation: have your proposals, projects, and relationship investments ready to deploy when the environmental support opens."
  },
  Ox: {
    e: '🐂', i: 1, n: 'Ox', el: 'Earth', pol: 'Yin', br: 'Chou',
    organ: 'digestive system, muscles, spleen', dir: 'Northeast',
    trait: 'diligent, reliable, methodical, persistent',
    clashDesc: "The Chou-Wei same-element Earth clash is unusually intractable because neither party can absorb or transform the other — Ox's dense yin Earth and Goat's dispersed yang Earth claim identical territory through fundamentally incompatible approaches. Goat years create rivalry without resolution: partnership strain from different resource priorities, directional instability in shared ventures, decision paralysis from competing Earth-element values. The 2027 Goat year brings Fire Goat (Ding fire generating Wei Earth) intensifying this tension. Advance partnership assessment and explicit governance protocols are essential preparation.",
    harmDesc: "Horse's Fire generates Ox's Earth productively — but demands recognition that Ox's reticent nature fails to provide. The healthy generative relationship curdles into smothering when appreciation is withheld. In 2026 (Fire Horse), the Fire element is maximally heated against your Earth, making authority relationships the central challenge. Superiors who feel unappreciated, colleagues whose visible contributions are absorbed without credit, evaluation processes that measure Earth's steady contribution against Fire's visible performance. Your natural reliability becomes a vulnerability when others exploit Ox's authority-deference. Maintain independent professional networks and document all significant contributions.",
    destructionDesc: "Dragon's yang Earth and Ox's yin Earth create structural redundancy — two containing Earth forces occupying identical organizational territory. Long-term institutional arrangements that seemed compatible reveal fundamental incompatibility in Dragon years. Property challenges, authority legitimacy contests within organizations where both Dragon and Ox types have established claims, property arrangements that seemed secure proving vulnerable to Earth-element internal conflict.",
    benDesc: "Your Ben Ming Nian amplifies characteristic stubbornness into potential rigidity. Persistence becomes refusal-to-adapt, reliability becomes predictability that others take for granted, diligence becomes invisible contribution. Digestive system, joints, and metabolic processes are health vulnerability areas. Career stagnation risk from being reliable without being visible. Financial risk from accumulated obligations. Yet Ben Ming Nian also intensifies Ox's extraordinary strengths: sustainability, practical wisdom, and the capacity for sustained effort that outlasts everyone else's intensity. Practice deliberate flexibility — expose yourself to perspectives that challenge established patterns. Red accessories worn throughout the lunar year, particularly received as gifts from elders.",
    allianceDesc: "Snake and Rooster form your San He Metal triangle: Snake's strategic yin Fire containing Metal allied with Rooster's precision, creating exceptional conditions for systematic achievement and quality recognition. Ox years are also the Liu He ally of Rat, making you a key alliance partner in Water-type years. Your own Liu He ally is Rat — Rat years bring conjugal-intimacy energy where Water's intelligence grounds through your Earth manifestation capacity, ideal for relationship deepening and practical implementation of complex plans."
  },
  Tiger: {
    e: '🐯', i: 2, n: 'Tiger', el: 'Wood', pol: 'Yang', br: 'Yin',
    organ: 'liver, nervous system, gallbladder', dir: 'East-Northeast',
    trait: 'bold, charismatic, competitive, independent',
    clashDesc: "Yin-Shen Metal-Wood combat: your Yang Wood's expansive vision and bold initiative confronts Monkey's analytical precision and technological capability directly — Metal cuts Wood. Monkey years bring the systematic challenges that expose Tiger's big-picture orientation: legal disputes from insufficient contract detail, competitive losses to more methodical operators, technological disruptions to Tiger's intuitive approaches. 2028 (Earth Monkey) amplifies with Earth generating additional Metal. Legal preparation, technical skill development, and systematic contingency planning before Monkey years significantly reduce exposure.",
    harmDesc: "Snake's yin Fire appears to be nourished by your yang Wood (Wood generates Fire) but becomes excessive and uncontrolled — burning through Tiger's resources rather than productively transforming them. Snake harm years bring concealed competitive threat: rivals patiently cultivating advantage while Tiger is distracted by Snake's demands for confrontation, strategic position erosion from premature commitment forced by Snake-energy individuals, inflammatory physical conditions from the excessive Fire dynamic. Tiger's characteristic boldness becomes its vulnerability when impulsive Snake-influenced forces disrupt the timing that success requires.",
    destructionDesc: "Tiger-Pig Wood-Water overnourishment: Pig's generous Water nourishes Tiger's Wood to excess, producing unrooted, unsustainable expansion. Pig years bring the over-commitment challenge: projects launched beyond sustainable capacity, financial obligations from optimistic over-assessment, energy deadline from simultaneously pursuing too many Wood-growth initiatives. The destruction comes not from opposition but from too much of a good thing — Pig's generosity enabling Tiger's inherent tendency to overextend.",
    benDesc: "Your Ben Ming Nian amplifies Tiger's boldness toward recklessness, competition toward destructive conflict, independence toward isolation. Liver and nervous system are health vulnerability areas — physical fire conditions, inflammatory complaints, stress-related nervous disorders. Career challenges from authority conflicts triggered by Tiger's amplified assertiveness. Financial risk from impulsive decisions made with Ben Ming Nian's intensified confidence. Yet Tiger's Ben Ming Nian is also the most magnetically charismatic personal year of any sign — leadership capacity, inspirational power, and the ability to mobilize others toward meaningful action reaches its peak. Direct this intensity toward genuinely important initiatives rather than reactive assertion.",
    allianceDesc: "Horse and Dog form your San He Fire triangle, creating exceptional conditions for inspired action and community building. Horse years provide passionate momentum; Dog years provide loyal protective support. Your Liu He ally is Pig — Pig years offer deeply harmonious conditions for Tiger's initiatives, with Pig's generous Water nourishing Tiger's Wood growth (at sustainable levels). Tiger-Pig years are particularly favorable for relationship formation and collaborative venture launches."
  },
  Rabbit: {
    e: '🐰', i: 3, n: 'Rabbit', el: 'Wood', pol: 'Yin', br: 'Mao',
    organ: 'liver, gallbladder, eyes', dir: 'East',
    trait: 'gentle, diplomatic, aesthetic, empathetic, conflict-averse',
    clashDesc: "Mao-You Metal-Wood: Rabbit's gentle yin Wood refinement and relationship sensitivity confronts Rooster's critical precision and appearance standards directly. Both signs care deeply about beauty and quality — but through incompatible frameworks. Rooster years bring critical evaluation that Rabbit's conflict-averse nature finds profoundly destabilizing: romantic disruption from aesthetic incompatibility, professional standards enforcement that feels like personal criticism, social environments where Rabbit's diplomatic nuance is overridden by Rooster's blunt precision. 2029 (Earth Rooster) exemplifies. Developing capacity for direct communication before Rooster years significantly reduces exposure.",
    harmDesc: "Rabbit-Dragon Earth subjugates Wood: Dragon's yang Earth appears stable and supportive but gradually absorbs Rabbit's Wood vitality without reciprocal nourishment. The harm operates through hidden power imbalance in close relationships — Dragon's magnificent energy unconsciously overwhelming Rabbit's gentle nature, creative contributions absorbed by larger entities without appropriate credit, authority relationships where Rabbit's diplomatic sensitivity is exploited by Dragon's imperial demands. Rabbit's characteristic conflict avoidance makes this particularly dangerous — problems accumulate without direct confrontation until the imbalance becomes critical.",
    destructionDesc: "Rabbit-Horse Wood-Fire consumption: Horse's yang Fire consumes Rabbit's yin Wood in a destructive rather than generative relationship. Horse years bring relationships and projects that deplete Rabbit's gentle energy without replenishment — romantic partnerships where Rabbit's emotional resources are consumed by Horse's passionate demands, creative collaborations where Rabbit's contributions fuel another's visibility, work environments where Rabbit's diplomatic capacity is endlessly deployed in service of Horse-type leaders without sustainable reciprocity.",
    benDesc: "Rabbit's Ben Ming Nian amplifies empathy toward enmeshment, conflict avoidance toward paralysis, aesthetic sensitivity toward anxiety. Liver and gallbladder are health vulnerability areas, alongside eye strain and optical sensitivity. Relationship challenges from excessive accommodation — Rabbit's amplified sensitivity making boundaries feel like cruelty. Financial risk from inability to assert appropriate terms. Yet Rabbit's Ben Ming Nian also intensifies extraordinary perceptive gifts: the ability to read emotional environments with unprecedented accuracy, aesthetic intelligence that touches the sublime, and diplomatic capacity that can heal community fractures others cannot even perceive. Practice deliberate boundary cultivation — the development of firm-but-kind \"no\" as spiritual practice.",
    allianceDesc: "Pig and Goat form your San He Wood triangle (the most creatively abundant triad), creating exceptional conditions for artistic expression, relationship building, and community flourishing. Dog years offer Liu He alliance — Rabbit-Dog pairing brings harmonious loyal support for Rabbit's sensitive initiatives. Your presence in others' alliance networks (you are part of the Wood trio with Pig and Goat) means your years are sought-after alliance periods for your partners."
  },
  Dragon: {
    e: '🐉', i: 4, n: 'Dragon', el: 'Earth', pol: 'Yang', br: 'Chen',
    organ: 'stomach, immune system, skin', dir: 'East-Southeast',
    trait: 'visionary, imperial, transformative, charismatic, perfectionist',
    clashDesc: "Chen-Xu same-element Earth polarization: Dragon's wet, transformative, visionary Earth confronts Dog's dry, loyal, protective Earth — neither can establish hierarchy, neither can absorb the other. Dog years bring the loyalty challenges that test Dragon's transformative leadership: long-term supporters questioning whether Dragon's vision serves the community, institutional stakeholders defending existing structures against Dragon's disruptive innovation, authority legitimacy contested by those who claim equal Earth-grounded moral standing. Dragon's imperial nature finds its deepest humbling in those who refuse to recognize the imperial claim.",
    harmDesc: "Dragon's yang Earth unconsciously subjugates Rabbit's yin Wood — not through malice but through magnitude. In Rabbit years, Dragon must practice deliberate restraint in close relationships, conscious space-creation for partners whose scale is more intuitive than Dragon's imperial nature, and recognition that Dragon's contributions absorb others' energy without this being anyone's intention. Creative collaborators feeling consumed rather than partnered, relationship partners feeling overshadowed rather than cherished — these are Dragon's Rabbit year challenges.",
    destructionDesc: "Dragon-Ox structural Earth competition: two containing, transformative Earth forces create institutional redundancy. Ox years bring challenges where Dragon's visionary institutions conflict with Ox's practical implementations — the same Earth territory claimed through incompatible means. Long-term structural arrangements revealed as fundamentally incompatible, authority legitimacy contests within organizations where both Dragon and Ox types have established claims, property arrangements that seemed secure proving vulnerable to Earth-element internal conflict.",
    benDesc: "Dragon's Ben Ming Nian — occurring every 12 years — is simultaneously the most powerful and most dangerous personal year of any sign. Imperial charisma amplified: vision becomes ego-driven distortion, perfectionism becomes tyranny, transformation becomes disruption for its own sake. Immune system and digestive vulnerabilities. Authority conflicts at maximum intensity — Dragon's amplified imperial energy provoking challenges from all quadrants. Financial risk from overreach. Yet Dragon's Ben Ming Nian is genuinely the most powerful manifestation year in the zodiac — those who have done the preparatory work of the preceding 11 years find this year capable of producing truly extraordinary outcomes. Direct the amplified energy toward genuinely meaningful transformation.",
    allianceDesc: "Rat and Monkey form your San He Water triangle — most auspicious for wealth, strategic intelligence, and large-scale achievement. Rooster years offer Liu He alliance — Dragon-Rooster pairing combines Dragon's visionary magnitude with Rooster's precision execution, exceptional for translating grand vision into quality reality. Dragon years are the most sought-after alliance years in Chinese astrology — you are the centerpiece of multiple triangular alliances, making your support enormously valuable to those who cultivate it."
  },
  Snake: {
    e: '🐍', i: 5, n: 'Snake', el: 'Fire', pol: 'Yin', br: 'Si',
    organ: 'heart, small intestine, cardiovascular', dir: 'South-Southeast',
    trait: 'perceptive, strategic, mysterious, patient, transformative',
    clashDesc: "Si-Hai Fire-Water extinction: Snake's yin Fire strategic intensity confronts Pig's yin Water generous abundance — mutual extinction where neither element can fully dominate. Pig years bring the emotional flooding challenge: Pig's generous Water extinguishes Snake's strategic Fire clarity, financial resources depleted through emotional generosity, boundary dissolution from Pig's overwhelming abundance. The strategic control that defines Snake's nature is its most vulnerable quality in Pig years — careful preparations overwhelmed by Pig's expansive, unconditional giving that disrupts Snake's carefully managed information environment.",
    harmDesc: "Tiger's yang Wood appears to support Snake's yin Fire (Wood generates Fire), but generates excessive, uncontrolled burning that exhausts Snake's resources rather than sustaining them. Tiger harm years bring impulsive external forces that disrupt Snake's patient timing: premature exposure of strategic preparations, competitive pressure forcing action before Snake is ready, partner's bold initiative revealing Snake's private strategy to unintended audiences. Snake's characteristic patience — its most powerful strategic asset — is precisely what Tiger-energy forces undermine.",
    destructionDesc: "Snake-Monkey Fire-Metal corrosion: both elements degrade through excessive interaction — Metal corrodes Fire, Fire exhausts Metal's precision. Monkey years bring implementation challenges: technical over-analysis paralysing Snake's intuitive strategy, systematic scrutiny revealing preparation gaps in Snake's carefully cultivated plans, public criticism of Snake's private methods from Monkey's transparent analytical approach. 2028 Earth Monkey is particularly challenging for Snake-born individuals.",
    benDesc: "Snake's Ben Ming Nian amplifies strategic depth toward obsessive secrecy, perceptiveness toward paranoid vigilance, patience toward strategic paralysis. Cardiovascular system is the primary health vulnerability — sustained internal tension from heightened vigilance creates measurable cardiac stress. Reputation risk from perceived manipulation. Relationship isolation from excessive privacy in a year when all relationships are under magnified scrutiny. Yet Snake's Ben Ming Nian also intensifies its most extraordinary gifts: the strategic intelligence that can see seven moves ahead, the transformative capacity that produces genuine metamorphosis, and the perceptive depth that touches the hidden nature of reality. Transparency balance — sufficient disclosure to build trust, sufficient privacy to protect strategic advantage — is the year's central practice.",
    allianceDesc: "Rooster and Ox form your San He Metal triangle — exceptional for precision achievement, quality recognition, and systematic implementation. Rooster years reward quality demonstration; Ox years reward practical implementation. Your Liu He ally is Monkey — Snake-Monkey pairing combines Snake's strategic yin Fire with Monkey's technical Metal in a Water-transforming relationship, creating exceptional problem-solving and innovation partnership. Monkey years (including the destructive 2028) offer paradoxical alliance potential for those who consciously navigate the Fire-Metal interaction."
  },
  Horse: {
    e: '🐎', i: 6, n: 'Horse', el: 'Fire', pol: 'Yang', br: 'Wu',
    organ: 'heart, small intestine, circulatory system', dir: 'South',
    trait: 'passionate, free-spirited, energetic, charismatic, restless',
    clashDesc: "Wu-Zi Fire-Water conflict: your yang Fire's passionate intensity confronts Rat's yin Water strategic intelligence directly. Rat years bring the grounding challenge — Water's patient depth opposing Fire's expansive immediacy, strategic long-term thinking confronting Horse's impulse toward visible action. Career disruptions from those with greater strategic depth, relationship challenges from partners who plan while Horse acts, financial volatility from Water's tendency to contain and redirect Fire's spending momentum.",
    harmDesc: "Horse-Ox (Wu-Chou) harm: your Fire generates Ox's Earth productively — but Ox's reticent nature fails to provide the recognition that Horse's yang energy requires. Horse's visible contribution is absorbed without acknowledgment, generating the smothering dynamic. In 2026 — also Horse's own Ben Ming Nian — this harm with Ox-born individuals and Ox-type authority figures is particularly intense: the Fire generates Earth maximally while receiving minimal Fire-sustaining recognition.",
    destructionDesc: "Horse-Rabbit destruction: Horse's yang Fire consumes Rabbit's yin Wood — the generous Wood that should fuel Fire instead burns away without productive transformation. Horse years bring relationships and projects where Rabbit-type individuals' gentle energy is depleted rather than channeled productively, creative partnerships exhausting Rabbit-energy collaborators, romantic relationships where Horse's intensity overwhelms Rabbit's gentleness.",
    benDesc: "2026 is Horse's Ben Ming Nian — the year of maximum yang Fire amplification. Passion becomes volatility, restlessness becomes instability, charisma becomes manipulation of those who are mesmerized by Fire's light. Cardiovascular system is the critical health vulnerability — the most active fire year in the cycle creates maximum cardiac stress. Yet Horse's Ben Ming Nian is the most energetically powerful year of any sign's cycle — pure yang Fire at full expression. This is the year when Horse's authentic nature must be fully honored: wear red continuously, perform An Tai Sui rituals, and consciously direct the amplified Fire toward genuinely meaningful expression rather than reactive combustion.",
    allianceDesc: "Tiger and Dog form your San He Fire triangle — exceptional for passionate leadership, community mobilization, and inspired action. Your Liu He ally is Goat — Horse-Goat pairing is the most harmonious single-animal alliance in the zodiac, combining yang and yin Earth in complementary unity. Goat years offer Horse the grounded aesthetic support that tempers Fire's volatility without extinguishing its brilliance."
  },
  Goat: {
    e: '🐏', i: 7, n: 'Goat', el: 'Earth', pol: 'Yin', br: 'Wei',
    organ: 'spleen, stomach, digestive system', dir: 'South-Southwest',
    trait: 'artistic, gentle, empathetic, creative, sensitive',
    clashDesc: "Wei-Chou same-element Earth polarization: Goat's yang Earth (dispersed, nurturing, aesthetic) confronts Ox's yin Earth (dense, practical, structural) in irresolvable competition for Earth-element territory. Ox years bring the values conflict: resource allocation disputes between Goat's relationship-maintenance spending and Ox's security-accumulation priorities, pace incompatibility between Goat's responsive generosity and Ox's methodical deliberation, aesthetic conflicts in shared environments between Goat's beauty-oriented standards and Ox's functional requirements.",
    harmDesc: "Goat-Rat Earth absorbs Water: Goat's Earth element inadvertently depletes Rat's Water vitality — not through malice but through the absorptive quality of Earth receiving Water without productive return. Goat must practice deliberate reciprocity in Rat years: conscious attention to whether relationships are genuinely nourishing all parties, awareness of the unconscious tendency for Goat's Earth to absorb Water-type individuals' energy without adequate return, and structured practices for ensuring that Goat's considerable empathic resources are matched by genuine reciprocal exchange.",
    destructionDesc: "Goat-Dog dry Earth competition: both Goat and Dog are caregiving Earth-element signs, but their Earth expressions are fundamentally incompatible — Goat's aesthetic nurturing versus Dog's protective vigilance create competition for identical caregiving territory. Dog years bring community conflicts, social network fragmentation from competing relational priorities, resource disputes between Goat's generosity and Dog's protective hoarding.",
    benDesc: "2027 is Goat's Ben Ming Nian — artistic sensitivity amplified to potentially destabilizing intensity. Empathy becomes emotional absorption of others' distress, creativity becomes indecision from excessive aesthetic possibilities, dependence on others' support becomes crisis when support is unavailable. Digestive system and spleen are health vulnerability areas. Financial instability from generosity exceeding sustainable capacity. Yet Goat's Ben Ming Nian also intensifies its most extraordinary gifts: artistic expression reaching its most sublime level, empathic capacity touching the genuinely transcendent, and creative output that carries unusual emotional resonance and lasting impact.",
    allianceDesc: "Pig and Rabbit form your San He Wood triangle — most creatively abundant alliance, exceptional for artistic expression, relationship building, and community flourishing. Your Liu He ally is Horse — Goat-Horse is the zodiac's most harmonious pairing, combining in Earth transformation where each completes what the other lacks. Horse years provide the passionate yang momentum that grounds and energizes Goat's yin Earth creativity."
  },
  Monkey: {
    e: '🐒', i: 8, n: 'Monkey', el: 'Metal', pol: 'Yang', br: 'Shen',
    organ: 'lungs, large intestine, respiratory system', dir: 'West-Southwest',
    trait: 'clever, innovative, adaptable, strategic, restless',
    clashDesc: "Shen-Yin Metal-Wood combat: Monkey's yang Metal analytical precision confronts Tiger's yang Wood expansive vision — Metal cuts Wood, but Wood's growth endurance exhausts Metal's cutting edge. Tiger years bring challenges from bold, visionary forces that operate outside Monkey's systematic frameworks: impulsive decisions that disrupt careful preparations, creative disruptions that invalidate Monkey's analytical conclusions, competitive losses to those who move faster than Monkey's verification systems allow. Tiger years require Monkey to develop genuine appreciation for intuitive leaps that cannot be fully systematized.",
    harmDesc: "Monkey-Pig Metal corrodes Water: Monkey's analytical precision gradually drains Pig's generous Water vitality through over-analysis. Pig years bring the emotional intelligence challenge — environments where Monkey's systematic approach creates distance in contexts requiring authentic warmth, relationships where technical precision substitutes for genuine connection, partnerships where Monkey's cleverness exploits Pig's generosity without conscious awareness. Monkey must practice deliberate emotional presence in Pig years: setting aside analytical frameworks in relational contexts.",
    destructionDesc: "Snake-Monkey destruction from Monkey's perspective: both Fire and Metal degrade through excessive interaction. Snake years bring strategic conflict: Snake's patient hidden preparation confronts Monkey's transparent analytical process — Snake's secrecy and Monkey's systematic exposure create fundamental operating incompatibility. Collaboration failures with strategic-type partners, intellectual property disputes, implementation paralysis from competing analytical and strategic frameworks.",
    benDesc: "2028 is Monkey's Ben Ming Nian — cleverness amplified toward potential manipulation, innovation toward instability, strategic thinking toward paralysis by analysis. Respiratory system and large intestine are health vulnerability areas. Trust challenges from perceived over-cleverness. Financial risk from complex strategies that backfire. Yet Monkey's Ben Ming Nian intensifies its most extraordinary gifts: the innovative intelligence that generates genuinely novel solutions, the adaptive capacity that thrives in chaos that defeats others, and the strategic creativity that finds unexpected paths through impossible situations. Direct this year's peak mental energy toward genuinely valuable innovation.",
    allianceDesc: "Rat and Dragon form your San He Water triangle — exceptional for wealth accumulation, strategic achievement, and large-scale problem-solving. Your Liu He ally is Snake — Monkey-Snake pairing combines Metal's analytical precision with Fire's strategic depth in a Water-transforming relationship that produces exceptional problem-solving and innovation. Snake-Monkey alliance years are particularly powerful for intellectual and strategic partnership formation."
  },
  Rooster: {
    e: '🐓', i: 9, n: 'Rooster', el: 'Metal', pol: 'Yin', br: 'You',
    organ: 'lungs, large intestine, skin', dir: 'West',
    trait: 'precise, observant, critical, organized, perfectionist',
    clashDesc: "You-Mao Metal-Wood confrontation: Rooster's yin Metal critical precision confronts Rabbit's yin Wood diplomatic harmony — the most aesthetically charged clash in the zodiac. Rabbit years bring environments where Rooster's critical standards seem harsh, where diplomatic harmony overrides quality requirements, where aesthetic judgments based on feeling override Rooster's standards-based analysis. Romantic disruption from aesthetic incompatibility, professional conflict from precision standards perceived as perfectionism, social environments where Rooster's honest criticism disrupts Rabbit's carefully maintained harmony.",
    harmDesc: "Dog's Earth buries Rooster's Metal — not through active destruction but through passive absorption that renders Rooster's precision invisible. Dog years bring the invisible contribution challenge: systematic efforts going unacknowledged, critical analytical work disappearing into organizational Earth structures without credit, careful execution absorbed by loyal but metrics-averse Dog-type leadership. Rooster's best work becoming invisible is the Dog year's defining harm dynamic.",
    destructionDesc: "Rooster-Rat Metal-Water: Metal appears to generate Water (productive elemental cycle) but becomes corrosive when excessive — Rooster's analytical precision fragmenting Rat's fluid adaptability. Rat years bring adaptive-type challenges: flexible individuals whose Water-nature adaptation violates Rooster's systematized structures, creative improvisations that undermine established quality frameworks, organizational adaptations that sacrifice Rooster's carefully maintained standards for short-term flexibility.",
    benDesc: "2029 is Rooster's Ben Ming Nian — critical precision amplified toward hypercriticism, organization toward rigid inflexibility, observational accuracy toward relentless fault-finding. Respiratory and skin vulnerabilities from Metal element intensification. Professional isolation from excessive critical standards that others experience as impossible to satisfy. Yet Rooster's Ben Ming Nian also represents the peak of analytical and organizational power — this is the year to produce genuinely masterwork-quality output, to establish the systematic frameworks that will serve for years, to demonstrate the quality standards that define Rooster's highest expression.",
    allianceDesc: "Snake and Ox form your San He Metal triangle — exceptional for systematic quality achievement, credential recognition, and precision-based professional success. Your Liu He ally is Dragon — Rooster-Dragon pairing combines Rooster's precision execution with Dragon's visionary magnitude, exceptional for translating grand vision into quality reality. Dragon years offer Rooster the imperial scale that gives Rooster's precision-based work its most meaningful context."
  },
  Dog: {
    e: '🐕', i: 10, n: 'Dog', el: 'Earth', pol: 'Yang', br: 'Xu',
    organ: 'stomach, spleen, digestive system', dir: 'West-Northwest',
    trait: 'loyal, protective, honest, anxious, moralistic',
    clashDesc: "Xu-Chen same-element Earth polarization: Dog's dry, loyal, protective Earth confronts Dragon's wet, transformative, visionary Earth in irresolvable competition. Dragon years bring the loyalty-versus-transformation challenge: Dragon's imperial vision disrupts the protective structures Dog has built, transformative initiatives threatening the loyalties and traditions Dog has carefully maintained. Dog's deepest anxiety — that loyalty will not be honored, that protective structures will be dismantled — is precisely what Dragon's disruptive energy triggers.",
    harmDesc: "Dog-Rooster: Rooster's Metal is gradually buried in Dog's Earth — Dog's Earth absorbs Rooster's analytical precision without recognition, creating the invisible contribution dynamic from Dog's perspective. In Rooster years, Dog experiences environments where loyalty and trustworthiness are less valued than technical precision, where Dog's authentic moral commitment is evaluated against Rooster's standards rather than accepted as intrinsically valuable. Dog's anxiety intensifies when evaluation metrics replace trust as the basis for relationship.",
    destructionDesc: "Dog-Goat dry Earth competition: Dog's protective conservatism and Goat's aesthetic generosity compete for identical caregiving territory. Goat years bring community disputes, resource allocation conflicts between Dog's protection-oriented hoarding and Goat's relationship-maintenance generosity, social network fragmentation from competing Earth-element values in shared communities.",
    benDesc: "2030 is Dog's Ben Ming Nian — loyalty amplified toward possessiveness, protectiveness toward controlling anxiety, moral clarity toward self-righteous rigidity. Digestive vulnerability from intensified anxiety — Dog's characteristic worry patterns become physically manifested during the amplification of Ben Ming Nian. Career challenges from inflexibility. Relationship difficulties from excessive vigilance. Yet Dog's Ben Ming Nian also represents the peak of genuine integrity — this is the year when Dog's authentic trustworthiness reaches its clearest expression, when loyalty is most powerfully demonstrated, when moral clarity can genuinely guide others through complexity.",
    allianceDesc: "Tiger and Horse form your San He Fire triangle — exceptional for inspired action, community leadership, and passionate defense of meaningful causes. Your Liu He ally is Rabbit — Dog-Rabbit pairing combines Dog's loyal Earth protection with Rabbit's diplomatic Wood sensitivity, exceptional for creating environments where both safety and beauty can flourish. Rabbit years offer Dog the aesthetic refinement that softens protective vigilance into welcoming warmth."
  },
  Pig: {
    e: '🐖', i: 11, n: 'Pig', el: 'Water', pol: 'Yin', br: 'Hai',
    organ: 'kidneys, reproductive system, ears', dir: 'North-Northwest',
    trait: 'generous, sincere, sensual, compassionate, naive',
    clashDesc: "Hai-Si Water-Fire extinction: Pig's yin Water generous abundance confronts Snake's yin Fire strategic intensity — Pig's greatest elemental challenge. Snake years bring strategic environments that exploit Pig's openness: careful calculation meeting genuine generosity, hidden agendas operating within Pig's trust-based world, strategic information management by Snake-type individuals whose concealment disrupts Pig's authentic relationship approach. Pig's generous Water is precisely what Snake's strategic Fire needs — and precisely what it consumes without adequate reciprocation.",
    harmDesc: "Pig-Monkey Water-Metal: Monkey's analytical precision gradually drains Pig's generous Water vitality. Monkey years bring over-analytical environments that exhaust Pig's spontaneous generosity: technical demands exceeding Pig's systematic capacity, analytical scrutiny destroying the authentic spontaneity that Pig's best contributions require, partnership environments where clever strategy replaces genuine warmth as the operating currency.",
    destructionDesc: "Pig-Tiger Wood-Water overnourishment: Pig's generous Water enables Tiger's Wood overextension, creating unsustainable expansion that ultimately collapses. Tiger years bring enabling dynamics: Pig's generosity funding Tiger's risky initiatives, Pig's emotional support sustaining Tiger's reckless confidence, Pig's resources depleted in service of Tiger's overreach. Pig must develop appropriate discernment about which Tigers to support and to what degree during Tiger years.",
    benDesc: "2031 is Pig's Ben Ming Nian — generosity amplified toward dangerous naivety, openness toward exploitation vulnerability, sincerity toward inability to perceive deception. Kidney and reproductive system vulnerabilities from yin Water amplification. Financial depletion from excessive generosity without discernment. Relationship exploitation from misplaced trust in a year when all relationships are under maximum energetic pressure. Yet Pig's Ben Ming Nian is the most spiritually abundant year in the zodiac — the deep Water qualities of compassion, intuitive wisdom, and genuine abundance reach their fullest expression. This is the year to channel extraordinary generosity toward deliberately chosen recipients rather than dissipating it indiscriminately.",
    allianceDesc: "Rabbit and Goat form your San He Wood triangle — most creatively abundant and relationally harmonious alliance, exceptional for artistic collaboration, community building, and compassionate service. Your Liu He ally is Tiger — Pig-Tiger is one of the zodiac's most dynamic pairings, combining Pig's generous yin Water with Tiger's bold yang Wood in genuine mutual nourishment (at sustainable levels). Tiger years are Pig's most supported annual environment for meaningful initiative."
  }
};
