
export const goat = {
    introduction: `Oh, Gracious Goat, your sign is the most creative. You are truly gifted, possess a flair for the aesthetic, and enjoy being in tune with nature. You are artless, hardworking, and intuitive. When you’re relaxed, you could teach "take it easy" courses. But before you do anything, you must be provided with security. You need to feel loved, protected, and be grazing safely in a fertile field. Without structure, you're uncomfortable.

You are an eccentric, and something of a winner, too. You don't mind struggling and striving in an effort to reach a noble or tangible goal, but you hate adhering to schedules or performing repetitive, routine chores. You need lots of ready cash, yet you scorn budgets.

A formidable ambivalence divides your basic need for security and your longing for total freedom from stressful limits. Goats are generally very delicate. Your good manners, wiles, and charm will go a long way towards finding that person, group, or profession that offers you maximum protection and allows your talent to thrive. Try your hand at poetry, research, or, better still, just lie back, relax, and embrace a bohemian lifestyle. You would make a perfect hippie.

Try courting an eloquent Horse. Horses know how to work hard for others. Bat your eyelashes at a refined, home-loving Cat or—better still—grab yourself a scrupulous, competent (and often rich) Pig to lean on and love for life. Avoid Tigers and Oxen; they don't approve of your capriciousness.

You don't mind the role of dependent, so you'll probably enjoy a peaceful childhood. As an amorous and fanciful young adult, you may experience some devastating romantic disappointments. But luck shines in the third part of your life, bringing love and security to coddle your tender soul. A bit of practical advice: find your "fertile field" at a young age and force yourself to graze patiently. Your fortune can often be found in somebody else's bank account.`,
    elements: {
        Wood: `The influence of Wood on the Goat's whimsical behavior is definitely beneficial. Here we see a strengthened and supported Goat individual. Instead of indulging in frivolous caprice, this Goat manages to maintain a healthy balance between lightheartedness and stability. Of all Goats, this type is most likely to be able to overcome harsh setbacks and carry on valiantly as though nothing untoward had occurred. This Goat is exorbitantly creative, yet more ambitious than many of its counterparts.

The necessity for security and moral support from its immediate circle is still very much present in this Goat's life. Take just a few of the above-mentioned famous men as examples. Arthur Murray, the celebrated dance instructor who gave his name to thousands of ballroom dance studios throughout the world, was typically Goat-like: tall, graceful, and slender. Dancing is a perfect career for a Goat; and Arthur Murray was an excellent, innovative teacher. He was not, however, a manager. He always said that his wife Katherine was the brains behind the expansion and management of the Arthur Murray operation. Without her, he claimed, "I would still be swirling around a summer pavilion dance floor looking gorgeous." Knowing his Chinese sign, I believe him.

Wood Goats are indeed so talented and innovative that marriage and a stable home life often serve as the necessary springboard for them to dare to venture out into the challenging world and make their fortunes. They need to know that they can always come home and feel safe where they live.

The Wood Goat is young at heart. Even under pressure, he manages to keep a smile or a joke on his lips. Because of this gift for optimism (exceptional in Goats), he confronts adversity more readily and extricates himself more gracefully than most Goats who are likely, in their frustration, either to crumble or surrender.

Given to mood swings, the Wood Goat gets depressed from time to time. These sinking spells or periods of gloom are often caused by the hormonal fluctuations common to all Goats, but particularly severe in this Goat. Careful monitoring of endocrine gland function is advised.

The Wood Goat lives in a permanent state of moral dilemma. He is, like all his Goat counterparts, a hedonist, a potential lifelong pleasure-seeker. However, the Wood Goat wants to achieve. He does not choose to remain in the herd, and he knows that to reach the lofty goals he imagines, he might have to commit himself to a life of both hard work and protracted routine effort. This prospect, for any Goat, is daunting. The Wood Goat can handle it.

To satisfy his desire for success, the Wood Goat, in his inimitable resourcefulness, learns young how to choose effective friends and associates. First, he cultivates their affections, then trusts them implicitly to assist him in getting where he wants to go. I would not go so far as to call this Goat a "taker." He doesn’t use people to his own ends. Rather, the Wood Goat is a jolly parasite. He is easy to have around—a joy and an inspiration to those who will generously surround him with essential comforts, calm, and sustenance. And hard work delights him, so influential people willingly give him a hand to get almost anywhere he wants to go.`,
        Fire: `The Fire Goat is a walking emotional maelstrom. Passion governs its existence. No matter how it tries, it cannot react calmly to stimuli, remain composed in the face of insult, or appear aloof when provoked. Mind you, this Goat is no pouncing Tiger who devours its adversaries before they have a chance to finish their sentences. Its methods are more akin to theatrics. It is prone to dramatic displays and erupts into rages or succumbs to nervous collapse. The Fire Goat is excessively sensitive and requires a stronger emotional restraint than most to keep its volcanic sentiments in check. A steady partner can make all the difference to the success or failure of the Fire Goat's life.

This individual is renowned for its charm and ability to influence others through a quality we might call refinement. Its sensitivity is almost palpable, causing the very hairs on forearms to rise. People are drawn to it and instantly admire its uplifting style. The Fire Goat's ability to reach masses of people with its words or to touch their emotions with its talent for seizing the moment or interpreting a role is legendary. It is exceptionally talented but requires top-notch guidance to ensure its perseverance.

This individual must not be compelled to manage its own finances. The mere thought of balancing a checkbook is enough to trigger one of the Fire Goat's fainting spells. If success comes knocking, it is well advised not to open the door until it has summoned its resident accountant to stand by. The Fire Goat is a reckless squanderer of money—its own and other people's. If you know and love one of these ethereal creatures, you are hereby warned to maintain strict control over joint accounts and impose limits on credit cards. The Fire Goat is not dishonest, but it is both thoughtless and inconsequential about spending. Fortunately, it is also incredibly lucky. I certainly do not advise gambling, but the occasional raffle ticket couldn't hurt, could it?

This Goat can enjoy some degree of superiority in a hierarchy but must not assume too grand a role. An excess of responsibility can lead to the onset of chronic ailments such as migraines or ulcers. A Fire Goat has a short fuse. When angered, it does not know how to keep its antagonistic feelings suppressed. Leadership demands self-control; the Fire Goat is deficient in that commodity.

Charisma is the Fire Goat's strong suit. Its gentle manner and aura of mystery attract others. The best professions this person can choose will involve theater, movies, music, mysticism, philosophy, the subconscious, occult science, or perhaps physics or other mind-liberating sciences.

It follows, then, that the Fire Goat is drawn to causes that seek to improve the quality of our inner as well as our outer lives. Fire Goats can take the lead in such areas as acting, directing, singing, ecology, health professions, nutrition, or alternative medicines. A smart Fire Goat can make a handsome fortune in these and other New Age pursuits. But it must surround itself with honorable and sympathetic associates who will never give it the key to the safe.`,
        Earth: `There is genius in the Earth Goat's makeup. Given the proper circumstances, skill and business may combine to help this Goat create a superlative and luxurious (just the way it likes it) lifestyle.

But the Earth Goat is perpetually erratic. Half the time it cannot decide what it wants to do, and the other half it suddenly becomes determined and pursues a difficult-to-achieve goal. Sometimes it succeeds, and things go swimmingly, provided it is well protected and insured against its own worst enemy—itself.

The Earth Goat tends to be argumentative. Its talent for talking things through is more pronounced than that of other, less naturally verbal Goats. But it often bases its arguments on illogical premises or fleeting dreams that happen to be circulating in its psyche and catch its fancy. As it does not always think things through to their logical conclusion, the tone of these discussions is often chaotic. If it is not careful, people eventually grow to mistrust its judgment, and it becomes the subject of some ridicule among its peers. Studying logic in college and participating in school debating teams would provide a sound basis for the Earth Goat to spare itself disrespect in later life.

Despite its tendency to bicker over trivialities at every turn, the Earth Goat has one of the most manageable Goat natures. It knows very well that its survival depends on the goodwill it can generate among those who surround it. It hardly ever pushes its disputes too far, causing rifts or break-ups. In fact, it displays almost no follow-through urge to assert its rights, demand its due, or seek reparations. However, if it feels it has been wronged, it will resort to lawyers. The image of a lawyer "standing up" for it where it cannot and will not do so for itself is tempting to this kind of Goat. Life with the Earth Goat is usually suffused with a spirit of cooperation and gentility—unless it feels betrayed; then, it loses its temper.

Its lack of objectivity gets it into scrapes, however, particularly in the work hierarchy. Because of its inherent passivity and gift for concession and compromise, the Earth Goat is sometimes blamed for wrongs it did not commit. More ambitious, ruthless colleagues will happily take advantage of its laid-back, semi-unresponsive nature to leap over its desk in pursuit of their own selfish ends.

Ultimately, the biggest challenge to the Earth Goat is simply to endure, but not necessarily to prevail. More than anything, it wishes to be left to its own devices to follow its lucky stars and dream its impossible dreams without interference from more down-to-earth folk who feel that they are doing it a favor by bringing truth into its life.

It's a tricky and perilous management challenge both to remain dependent on the support of others and still maintain intact one's integrity and dreams. The tightrope it walks may cause a feeling of imbalance in the Earth Goat's inner self. Physical symptoms may result that are solely manifestations of this lack of equilibrium. Epileptic seizures, spells of weakness, and dark, gloomy depressions may crop up. When this happens, a good lover or lifelong companion or caring boss needs to be right there for its Earth Goat. Nothing short of sitting it down with some old-fashioned straight talk and reassurance about its security will clear up the messy muddles into which this Goat's elusive psyche can lead it. When properly handled, the Earth Goat's startling talents can afford it the highest accolades. Its imagination knows no bounds. It is sympathetic and understands even the most incomprehensible human behavior. It is often a brilliant, sympathetic soul. But it has to watch out for its own scatterbrained tendencies. If not, it may well tarnish its image in the eyes of those who respect it.`,
        Metal: `Goats appear in the most unexpected places! I tell you that they are dependent and sometimes frail and super artistically creative, and then someone major and powerful like Gorbachev or Rupert Murdoch turns out to be a Goat. The Metal Goat seems, to the uninformed outsider, a gentle pushover. Its unassuming, disheveled, casual style suggests only simplicity and innocence. But beware: although the influence of Metal does enhance the gentle Goat's resolve, it also hardens its heart, causing it to become unnecessarily combative when dealing with others.

Goats are generally non-confrontational and are known to have to depend on the kindness of strangers for their survival. At all costs, they must appear to be compromising and easy-going. This is true of the Metal Goat: it cannot and does not risk open conflict. Yet, as it is temperamental, it often feels interfered with and imposed upon. To avoid being visible and therefore doubly vulnerable, the combativeness in this individual goes underground. Metal Goats delight in secret manipulation and subterfuge, and perform their most skillful string-pulling from behind the scenes.

For this reason, the Metal Goat makes an easy-going friend but is a daunting adversary. It will never speak its mind in any controversy. It categorically refuses to deal one-to-one in open conflict. It will not take stands on any controversial subject, nor will it brave danger for the sake of a good cause. The Metal Goat favors underhanded means and is quite capable of lying and justifying even the most amoral behavior to itself if it does not get its way. The wronged Metal Goat is consumed by the need for revenge and will stop at nothing to gain ground against its (real or imagined) enemies.

At home in the hidden depths of the collective unconscious, the Metal Goat can readily pursue careers where knowledge of the inner workings of the human mind is a prerequisite. It will make an excellent forecaster and interpreter of human behavior: a soothsayer or psychiatrist, an incisively charismatic actor or film director, a politician, a brilliant writer or singer, or, more simply, a willing courtesan. Alternatively, it might choose to stay at home and become an inventor, trying to concoct a gourmet elixir of youth, to make gold from aluminum foil, or improve on some secret eavesdropping device.

Of all the Goat types, this one is perhaps the most elementally lacking in a sense of urgency. It will not hurry. It insists on moving ahead in a leisurely way and hasn't got a clue how its lackadaisical behavior affects others.

This Goat can rise to great heights by advancing steadily at its own unhurried pace. But because the subconscious is always pulling at it, it often falls victim to self-deceiving bad habits, such as drug, alcohol, or diabolical religious addictions.

A well-nurtured Metal Goat's talent can bring it enormous rewards, but it must watch out for a dangerous tendency to self-congratulatory boasting. Metal Goats suffer from an excess of pride. Sometimes their vanity gets in the way of their common sense and thwarts the possibility of reaching a desirable goal.

The remedy? Lots of tough love and no-nonsense nurturing may help to bring reality out of the basement of the Metal Goat's mind and put its thoughts into better perspective.`,
        Water: `The Water Goat's claim to fame is its skill at using its intuition. Of course, all Goats are sensitive and easily pick up on feelings—but Water bestows a special talent for intuiting the flavor and tone of even the most subtle of life's situations on this fluid variety of Goat. Where hints of danger, twinges of fear, or suggestions of sexuality or extraterrestrial activity may pass unnoticed by less perceptive folk, every nuance is picked up by the supremely impressionable Water Goat. It seems able to understand without learning and to know certain things instinctively without necessarily having first comprehended them.

Although compassion is the emotion that can be most profoundly felt by it, the Water Goat is oddly egocentric and quite unable to escape from its golden bubble of preoccupation with itself long enough to relate to those it might feel sorry for. It is neither a natural care provider nor is it very altruistic. Rather, the Water Goat senses the way things are moving, then zigzags through the loaded minefields of life, relying solely on its inner radar to guide it. It seeks more to stave off danger and predict events for itself than to warn others of potential harm.

Water Goats are intensely charming and sensual. They love being needed and adore having an audience. Adulation and applause provide approval and help to keep them moving. Appreciation serves to push them to heights they might not aspire to without external urging. Their inner emotional structure is somewhat shaky, so being encouraged, cheered, and inspired by friends and family is of great assistance to them in making decisions, accomplishing tasks on time, and overcoming hurdles without the usual Goat-like pessimism or hesitation.

There is a kinky side to this Water Goat's sexual character. The male of the species is amorous and romantic and requires abundant physical attention from females. In her geisha-like way, the sensuous woman Water Goat also comes on very strong. Although quiet and unassuming, the Water Goat lady is a true siren whose amiable sexual prowess is never a well-kept secret. In fact, hardly a day goes by that this Goat does not engage in sexual activity or fantasy. There is a strong propensity among Water Goats to engage in group sex and other forms of unconventional and promiscuous activity.

When you get to know this Goat well, you rapidly understand why this has often been known as the sign of the hippie or Bohemian. Water Goats don't care to heed the rules and regulations of the standard social system. They prefer to remain outside, looking in, enjoying a certain detachment from the mainstream, and managing to hover about three feet above their own and others' heads.

Water Goats, like their brothers and sisters of the other Goat signs, frequently possess genius. When they put this to practical use, the road ahead may quickly lead to stardom because, of all Goats, this one knows best how to use its influence to make contacts, open doors with its sexual charms, and eagerly seize opportunities. It knows instinctively how to move in the "right" circles, get itself known to the "right" people, and find ways to be noticed by influential types who can get it where it wants to be. This Goat is never too pushy or boastful but, rather, plays its hand deftly by maintaining tight relations with influential people who can put it where it thinks it ought to be.

Although it doesn't usually assert its will aggressively, the Water Goat does not like being thwarted or interfered with. If it doesn't get its way, or feels it has been shunted aside, its well-developed sense of martyrdom rises straight to the surface. Its whining can be heard for miles. The "Poor me" side of the ultra-sensitive Water Goat is absolutely its worst fault. If it can control this tendency, it will be a true charmer, a delightful, well-mannered individual, and a terrifically amusing friend. But when that "Why me?" refrain rises from the depths of the silken chaise longue, I advise you to head for the hills and hide under an anonymous rock until the sniveling is over. And don't feel guilty. If you don't take care of poor little Water Goat in his deepest chagrin, he will make it his business to see that somebody else does.`,
    },
    compatibilities: {
        "Rat": "This is a tricky one. The Goat enjoys the loving Rat’s company but finds his nervousness unappealing. The Goat’s peaceful nature appeals to the snuggly Rat, but the Goatly lack of interest in the menial tasks of everyday life will cause the Rat to fret and worry. The Goat’s fey, lackadaisical nature will strike the industrious Rat as rank laziness. The Goat will spend too much money on unnecessary items. The Rat will suffer anxiety about debt, fiscal responsibility and pervasive insecurity. This household is in a constant state of cold war. The Rat worries quietly and the Goat lacks the necessary initiative to loosen up his troubled mate. All their battles will be fought with underhand tactics and vicious stares. The Rat will long for a partner with more oomph. The gracious Goat, not courageous enough to confront the Rat, will resist lethargically—but not emphatically enough to suit the Rat’s need for challenge. Their mutual feelings of inadequacy will be put to rest when they have sex. The Goat is ultra sensual and can exert an almost magical power over the Rat. Thrilled by such intense sexual excitement, the Rat (for once) will be happy to surrender power. The Goat may gain confidence from the Rat’s submissiveness and see an opportunity to discuss some of their differences. If the physical union is strong, this couple may eventually iron out their discord on the pillow.",
        "Ox": "In the beginning, the delicate Goat seems like a great catch for a domineering Ox. But we must never judge a Goat by appearances! Although gentle, Goats are not easily bossed. I caution all Oxen against this union. First, you’ll feel a surge of power next to this dainty mountain creature. But after several shared hikes, your puffed-up ego will flop like a tired soufflé. The Goat complains endlessly and you (slowly but surely) lose interest. The patient Ox puts up with the Goat’s lackadaisical attitude for a while, but soon comes to believe that the Goat is not only lazy, but directionless. A hard-working Ox simply can’t understand the Goat’s inertia. Happy to be dependent on others, the Goat just doesn’t feel the need to work himself to death. Doesn’t the dedicated Bull bring home more than enough bacon? After a while, as the Ox is so tame and responsible, the Goat finds him just plain dreary. The Goat likes to sleep on different sides of the bed every night just for the fun of it, which exasperates the rigid Ox, who can’t bear the thought of breaking routine. Even in bed, the stodgy Ox has trouble keeping up with all the different Goat positions. This is a clumsy couple. Each will be better off without the other.",
        "Tiger": "This union is among the worst possible known to Chinese astrologers. Although the couple may make a fabulous start (in bed), from there on it's all downhill. The practicalities just don't work out. Goat is charming, beautifully seductive and loving. Tiger is passion and mettle. But who will bring home the bacon? In this family, nobody wants the job. No concessions are made. The Goat remains laid back while the ambitious Tiger bombasts a hole in the kitchen ceiling. What was a great passion ends in lifelong misunderstanding and acrimony. Affairs? Yes. Marriage? Abstinence is advised.",
        "Rabbit": "Although initially they may seem ill suited, this pair will undoubtedly develop a solid love relationship. Cats and Goats are complementary. The Cat provides the dependent, creative Goat with just the right amount of down-home security, and the hypersensitive, capricious Goat amuses and keeps the Cat interested. Cats are serious and steady. Goats hardly ever follow the rules. Although normally disconcerted by such nonchalance, the Cat finds it disarming in a love partner. The Goat respects the Cat’s sound judgment and takes solace in Kitty’s ability to cope in a routine fashion. The Goat’s capacity for total surrender in love situations melts the sexually resistant Cat’s little heart. Their romantic life is dense with passion. Tenderness and marathon caressing sessions are the order of the day. The fewer children this couple has, the better. The Goat requires so much personal attention and caring from a Cat spouse that a brood of children who distract the Cat might make the Goat cranky and jealous.",
        "Dragon": "In Chinese astrological circles, this is said to be a sound marriage. Goats are essentially dependent. They are easily swayed and don’t mind being bamboozled and manipulated by their loved ones. Dragons need to command direct operations and dominate. Goat’s good-natured passivity. The acquiescent Goat inspires the Dragon to protect and be chivalrous and thrives in the security provided by Dragon’s authority. Their sexual life together will be as near to an erotic dream as you can get. Dragons like to take charge and Goats like to lie there and be loved. Being two very sentimental as well as sensual beings, these two will know instinctively how to blend sex with affection. Their intimacies will be satisfying and frequent.",
        "Snake": "Charming and gracious, this pair of artistic, creative people can have the world eating out of their hands. The Goat’s inherent beauty and seductive appeal, when combined with the Snake’s elegance and sensuality, forms an enviably synergistic couple. Theirs will be a delicious complicity. Unfortunately, neither of these gloriously attractive people is very handy with a calculator. They are both equally improvident, luxury-loving, even profligate about spending. Unpaid bills will pile up and each will call the other a spendthrift. Stalemate. Don’t expect the Goat to find solutions. Snakes may overspend but they also provide. Goats are determined to depend and be provided for. The Snake will only take so much of the Goat’s indolence, will soon find the poor Goat a high-paying job and force him to get to the office on time and perform his job well till death do them part. Once again, the Snake’s incurable infidelity slithers into the equation. Goats tend to be fickle too. But, even though the Snake understands the Goat’s occasional need for a fling, the more stubborn Goat hates to share his goodies and will freak out at the Snakey’s infidelity. But, never mind. Rows are the stuff of these people’s lives: both are addicted to passionate drama. Romantically, this couple is sound. But when the harsh, overhead light of reality pierces the veneer of their relationship, the cracks and flaws may prove too numerous for its survival.",
        "Horse": "This apparently odd combination sometimes works extremely well. Horses are strong-minded hard workers. Goats are languorous, creative and oh-so-dependent. The Horse in this pair will always feel protective of the Goat mate. Horses like to feel superior and Goats know exactly how to inflate their egos. When decisions are to be made or actions taken, the Goat goes all flabby and swoons, “Honey, you’re so clever. I just know you’re better at this than I am,” and the Horse rides off into the night to play hero. The Goat’s romantic side appeals to the stodgy Horse’s need to learn about love. Even though their sensitivities are not too similar, Horses find ethereal Goats decidedly sexy. They complement each other. Goats are pessimistic; Horses are not. Goats are flaky. Horses are solid conservatives. Goats depend and Horses willingly provide. Horses like things their way and, as long as there’s money in the bank, Goats are supremely flexible. These two are so different that they will never be bored together. Of course, friction might occur, because the Goat can be jealous and possessive and the Horse needs to feel free. But usually, the Goat’s sense of what is most practical for the future will win out and, aside from some mild disapproval, he or she will not tax their partner sufficiently to cause the Horse to bolt.",
        "Goat": "Immediate synergy! In bed, this couple performs well. They are so alike that everything flows naturally. Romance flourishes as they are both loving, sensitive and unusually in touch with and open about their emotions. At first glance, it would seem that these two might be able to live on love alone. Later on, however, when they have settled into a routine, a pair of Goats will cause each other much mutual pain. Being alike in temperament, their sins and grievances will be similar. Each will learn quickly how to push the other’s panic buttons. The immaturity and pessimism of dual Goats could be their undoing. Neither wants responsibility for the finances, for the future of their emotional bonding or for the workaday continuity of the household. Neither is able to depend on the other. When things go wrong, each will dream of having a stronger partner. The best way for this union to work well would be if one party (or better still, both) had a private income. Then, they could hire a “take-charge” domestic staff and have all the time in the world for creative joint projects. Infidelity is another Goat trait. Imagine two randy Goats running loose in the same marriage. Awful rows, pouting and shrieking occur. Moreover, Goats are possessive and jealous. Each, in his turn, will be devastated by the other’s betrayal. An “iffy” marriage at best.",
        "Monkey": "A mutual lightheartedness will draw these two creatures into a joyous relationship. The Monkey’s energy alone can carry the couple and, as the Monkey is very generous, he or she will not mind being the sole provider. If Monkey is doing well, their whole existence can consist of fun and games. The sex will be less than wonderful, though, because Monkey isn’t the same sort of sensitive lover as the Goat. Goats need constant caresses, are romantic and sentimental, while Monkeys are practical lovers whose lovemaking resembles a healthful gymnastic more than a swooning match. The Goat’s moral dependence may become irritating to the Monkey, who longs to move about freely without undue constraint. Having to stay at home, coaxing a grumpy Goat out of pessimistic moods and rousing him from inertia may be more than the independent Monkey can bear. If this couple has a family, it may help to hold them together. Goat can stay securely at home while Monkey wanders free. It’s a sound combination, providing the Monkey can eventually support Goat in leisurely style.",
        "Rooster": "This is a dicey combination. Roosters are conservative and individualistic. They deplore laziness and cannot tolerate lackadaisical attitudes in others. Goats like to take it easy. They don’t believe in work for its own sake, would rather sit still than move about, and are ever ready to get someone else to take care of their basic needs. As the Rooster often had great difficulty scratching out a living, he or she will be impatient with the idea of anyone living off the fat of the land and will wish the Goat would find a “real” job, like a normal person. Goat’s feelings are readily hurt. Tensions can mount in this household and very little will be talked through, because the Rooster hates discussing his emotions. The fickle Goat may wander sexually, causing the staid and faithful Rooster untold pain. Trouble is, the Goat needs more than just the Rooster’s perfunctory affections. Knowing this fact creates feelings of inadequacy and a lack of self-confidence in the Rooster. If Goat could be persuaded to stick around all the time and teach the willing Rooster how to be more sensual, their relationship might have a good chance at success. At least it would give more purpose to the otherwise idle Goat’s home life. Goat with Rooster is far from an ideal marriage.",
        "Dog": "Not much love is lost between these two. The Dog is all moral standard and high-mindedness. Very often, the Goat’s ideals begin and end with where the next meal is coming from. Goats are on the side of the person carrying the wallet. Dogs deplore pandering. Goats know no other way of life. As a couple, unless the Dog decides, uncharacteristically, to shoulder the burden of changing a poor misunderstood Goat whom he or she believes to be a hidden genius, they will be two very different people going in opposite directions. The Dog likes things to be clear, just and fair. The Goat doesn’t even know what those terms mean. Goats are dreamers whose ephemeral plans often go up in smoke. Dogs dream too, but their dreams are founded in concrete and seek real solutions to real problems. Goats, of course, love sex and favor open relationships wherein they have full freedom. Dogs wouldn’t think of being disloyal. They may stray—but only for a minute or two. To a Dog, devotion and loyalty come first. To a Goat, blind devotion and loyalty are for fools who don’t know which side their bread is buttered. It would be too optimistic to expect harmony from this essentially unbalanced romantic equation.",
        "Pig": "In this pairing we find one of the happiest possible combinations. The atmosphere between Goat and Pig is mellow and smooth. They may have minor differences of opinion over small things, like taste in furniture or which sort of friends to frequent most, but the Goat likes the security he finds with Piggy and Piggy, in turn, enjoys the creative nuttiness of the charming Goat. Pig is lucky in money matters so he can support the gentle Goat, allow him free rein to dream, aimlessly inventing and reinventing his daily life. Pigs have endless patience and seem to be composed of goodwill and indulgence for the capricious Goat mate. Goat could not be better matched where emotional stability is concerned. The Pig usually stays in the country, away from madding city life, where the Goat can safely cavort, unhindered, in fertile fields. The sexual side of this affair is also enviably harmonious. The parties have similar sensitivities. Noble Piggy will undoubtedly be jealous of the Goat’s incessant dalliances and disapprove of his unfortunate tendency to try to take up with almost every attractive person who comes to call (the flirtatious Goat lacks tact). But, never mind. Once Piggy’s pain has passed, the darling Goat will be forgiven and both will return to their familiar devil-may-care, bucolic existence.",
    },
    futures: {
        "2025": { "year": "Snake", "element": "Yin Wood", "prediction": `Still moving along in a completely free-spirited way, you will discover a fresh sense of luxury and social acceptance by the conclusion of this Snake year. While Snake individuals aren't known for being the most outgoing people, they frequently seek out the gentle, artistic companionship of Goats. You are currently operating on your own unique wavelength, approaching your activities at a notably unhurried pace. This calm and deliberate manner of yours appeals greatly to the Snake, who prefers to navigate life smoothly and without haste. Your easygoing company provides warmth and comfort to the otherwise reserved Snake. You can anticipate being invited to a great number of elegant dinner parties and various events in exotic locations, possibly even on yachts or at chateaux in France or Spain. Take time to prepare your most sophisticated car, update your wardrobe, and certainly remember to use your finest French colognes and other appealing cosmetics. Naturally, all this personal grooming and socializing will lead to an abundance of romantic adventures. You'll find yourself courted by so many new and diverse individuals that keeping track will become quite a challenge. Enjoy these romantic experiences while they last, as by the end of the year, amorous pursuits will come to an abrupt halt. If you're considering marrying one of your recent conquests, I suggest you reconsider. Marriage is not currently foreseen in your immediate future.` },
        "2026": { "year": "Horse", "element": "Yang Fire", "prediction": `Goats generally feel quite comfortable during Horse years, because the diligent atmosphere created by the Horse provides a comforting sense of security and safety. This year, it would be beneficial for you to solidify your position within any organizational structure where you currently find yourself established. Now, you might argue that you don't belong to any such structure, perhaps identifying as a freelance magician, a self-employed dog walker, or a renowned plastic surgeon who practices independently. However, if you do work on your own, I would wager that you are either deeply married to a stable, responsible individual who handles the finances—or perhaps both! If you aren't married, then it's likely you live at home, where you can depend on regular meals and a warm bed. Goats rarely operate entirely alone. This brings us back to the Horse year: you will appreciate the general mood of this year because it supports your need for dependability. You can truly rely on the Horse. Indeed, we can all rely on Horses; they are consistent, reliable, and practical beings. Therefore, this year, you will continue to progress smoothly with good fortune on your side. Consider investing some money in real estate this year. Perhaps acquire a cottage or a bungalow to renovate. You are very skilled with your hands, and this year, hands-on projects are on everyone's agenda.` },
        "2027": { "year": "Goat", "element": "Yin Fire", "prediction": `Finally, you are in charge! Although this isn't exactly your preferred style, as you'd likely feel more comfortable being named chancellor of the exchequer or serving as the King's or Queen's jester. You typically feel more secure when you are stably employed and protected by the society in which you reside. But never mind; you hold the position of power this year, and you will manage it—your way. As fate is on your side, this year will grant you everything you've ever envisioned in terms of freedom and the resources to create, accomplish, invent, and bring into production all the wonderful ideas you've conceived over the past three years. This is also the crucial year when you must formulate a plan for the next twelve years. It should outline something like: "2027, Innovate. Be the leader. 2028, Get the production line moving. Hire new people. Make changes, but avoid public attention. 2029, Economize," and so on, until you reach 2039 when your own year cycles back. The Chinese organize time into sixty-year cycles, each comprising twelve-year periods, and this marks the beginning of your current cycle. By 2031, you should have decided whether to get married or remain so. Make a clear decision now about where you want to be in twelve years, what you wish to be doing, and with whom. Beyond leading the world this year, you must actively begin drafting this twelve-year plan.` },
        "2028": { "year": "Monkey", "element": "Yang Earth", "prediction": `This year promises to be a bit too chaotic for your personal liking. Monkeys are constantly bustling about, devising intricate schemes and planning ways to entertain the world while simultaneously resolving all its issues. The truth is, Monkeys are rather disorganized individuals who present themselves as orderly. You won't find that crucial sense of security from Monkeys, and for good reason. They are incredibly neurotic and frequently imagine that others might be plotting against them. They devise strategies and manipulate situations, neither of which you are typically guilty of. You prefer to confront problems directly—even if you don't succeed in resolving them. The Monkey's deliberate chaos will unnerve you and cause you to doubt yourself. Since you don't possess an abundance of self-confidence to begin with, this perplexing year will make you extra anxious, highlight your pessimistic tendencies, and more than once leave you feeling foolish and cornered. Why? Because you insist on being direct and transparent about your intentions. Monkeys don't grasp that; they prefer complex mazes to straightforward paths. If I were you during this Monkey year, I would seriously consider a complete change of profession. Perhaps ask a wealthy friend to purchase a restaurant for you, or seek bank sponsorship for a career as an opera singer. Remember, your priority is security. Do not fund ventures yourself. If you fail, let someone else bear the consequences.` },
        "2029": { "year": "Rooster", "element": "Yin Earth", "prediction": `In this period, you will find yourself in a year where you get the distinct impression that opportunities are tightly restricted, and progress is not flowing smoothly. Roosters are demanding individuals who are almost never as adaptable as one might wish. This lack of flexibility, however, is only part of the challenge. Roosters do not appreciate sacrificing their own independence for the benefit of another. They enjoy being in control of their own lives and the lives of those important to them, but their generosity extends no further. Furthermore, they cannot tolerate anyone who is not fully contributing their share. You, as a Goat, need to be nurtured and understood; you long to feel secure. This year, you might have to set aside all those desires and aspirations. Perhaps you should consider taking a sabbatical or finding passage on a wealthy lover’s yacht. Your health outlook is positive; those symptoms you experienced last year have subsided. They might have been related to stress and anxiety, as the chaotic influence of the Monkey year can affect Goats in that way. Romantic prospects will be uncertain in the Rooster year. While there won’t be an abundance of serious commitment available, there should be plenty of passion on the agenda. However, ample sexual activity offers little compensation for the fact that you won’t be accumulating gold either. The Rooster is cautious about spending and does not encourage extravagance or waste. Since your favorite pastime is acquiring lavish, often unnecessary items, you may experience disappointment. This year does not promise any designer gowns or luxury watches for gentle Goat individuals.` },
        "2030": { "year": "Dog", "element": "Yang Metal", "prediction": `The Dog tends to guide Goats, yet Goats do not appreciate being directed or compelled to participate in activities that are not of their own choosing. Nevertheless, in Dog years, we are all more or less obligated to join the fight for universal justice, to work diligently for the common good, and to voice our objections against all that is cruel and inhumane in our complex world. Fortunately for you, Dogs have a soft spot in their hearts for Goat individuals. Why? Because Dogs are fond of all forms of companionship. Goat people make excellent companions. When they are not working excessively long hours without eating or napping, Goats are very present and engaged. You can always count on a Goat friend to call for a chat, spend an evening watching television with you, or accompany you to a movie or a bistro. Consequently, this will be a good year for your social life. You will be asked to go on dates and attend community functions. You may even be invited to take an active role in the local political scene. What might appeal to you least about this Dog year is the Dog’s tendency to criticize your methods and sometimes even say hurtful things. At times, you will feel closely scrutinized. Try not to take these observations too seriously. The Dog cares deeply for you and worries that you cannot take care of yourself. Be patient; you are loved.` },
        "2031": { "year": "Pig", "element": "Yin Metal", "prediction": `You can finally relax. Goats are among the Pig’s most favored individuals across all types of people. This year, you will be pampered, cared for, and made to feel exceptionally comfortable in your own skin. You desired security? You have it. A full calendar year of safety and admiration is available for Goats during the Pig year. What should you do with this sudden sense of well-being? Get out there and perform. Make your voice heard. Showcase your numerous talents to the world. Create movies, write books or poetry, sculpt, invent, act, or dance… but DO something significant for your career and your future NOW. In this benevolent year, you can make enormous strides towards success in your chosen field. Do not hesitate to present your innovative ideas to superiors, exhibit your work in galleries, or submit multiple manuscripts. You will be making all sorts of deals and contracts and signing agreements within the generous atmosphere prevalent in this Pig year. You may also get married. Yes. And/or you may indeed have a baby (or even two!) because this is the year in which things simply work out for Goats. Take full advantage. Next year is not quite as promising.` },
        "2032": { "year": "Rat", "element": "Yang Water", "prediction": `As the Rat seeks power and desires to protect and influence people, Goats find it difficult to express much of a personal statement this year. Being pressured or crowded does not have the desired effect on you carefree individuals. You are always willing to cooperate and be pleasant when asked to perform. However, when someone literally pushes you and orders you to get moving, you instinctively retreat in fear and aversion. You may feel misunderstood and sulk, but you certainly won’t feel inspired to paint the Mona Lisa or reinvent pizza. Furthermore, when you feel unwell, you often spend money as if there were no tomorrow—which is not a healthy way to react, but a typical Goat-like method of "dealing" with discomfort. You can still be creative this year. Work diligently on your personal projects in a protected environment where you feel safe and cared for. However, Rat years are not the time for building up your reputation as the genius you often are. Love will emerge to spare you from excessive misery this year. Someone sweet and strong (perhaps a Pig) will appear who will love and admire you. This person will genuinely appreciate how exceptional you are and will encourage you in your artistic and inventive endeavors. This romantic interest will materialize unexpectedly… perhaps at a restaurant, a public beach, or even on an escalator going in the opposite direction. Do not miss this opportunity. When the initial glance proves intriguing—seize the chance to connect with this charming individual.` },
        "2033": { "year": "Ox", "element": "Yin Water", "prediction": `While the Rat previously tried to motivate you to perform under the guise of offering protection, the Ox takes a distinctly different approach. The Ox dictates directly, with no pretense necessary. You will either work alongside him and complete tasks his way, or you will find yourself excluded. Goats typically voice their loudest complaints in Ox years, feeling misunderstood by those in authority, and indeed, they often are. Goats dislike being told what to do no less than anyone else, but they might willingly comply if the Ox were to say, "Go frolic over there and graze on the fresh green grass, and I’ll call you when we’re finished working here." Ox years signify a period of diligent effort, and that work can manifest in many forms. It might involve manual labor like ditch digging, or it could necessitate significant changes in the Goat’s personal plans, such as: "You are going to buckle down and complete university, achieving straight A’s this year." Alternatively, the Goat might be called upon to serve in his or her country’s armed forces, or be ordered to assist in disaster relief after a tsunami. The bottom line is that demanding work awaits Goats wherever they look this year, and no matter where they attempt to hide, they will be discovered and pressed into service. Fortunately, despite all this pressure, your romantic life is progressing splendidly. You have either found someone (or they have discovered you) on whom you can depend for defense and protection, without any bossiness or tyranny. Hold onto this person; you require security to sustain your actively inventive existence.` },
        "2034": { "year": "Tiger", "element": "Yang Wood", "prediction": `Keeping pace with Tigers is a challenge few enjoy. Tigers leap and bound, pounce, and roam about like hyperactive grasshoppers—and they consistently emerge looking triumphant. If the only issue were the pace that the Goat cannot maintain, that would be one thing. However, the truth is, the Tiger also possesses outlandish ambition and an intense drive to succeed. Goats are simply unable—and unwilling—to keep up. So, when it’s the Tiger’s turn to dominate the world, the Goat mostly retreats into hibernation or else feigns admiration for the chaotic energy, applauding the countless curtain calls without genuine conviction. In either scenario, Goats and Tigers frequently clash. Not only do they have different approaches to tasks, but they also disagree on the desired outcomes. These disagreements do not imply that the Tiger doesn't want you to succeed. Fundamentally, Tigers are indifferent to your success or failure—as long as you are not hindering their progress. Therefore, in Tiger years, I suggest that Goats work and engage in leisure activities as much as possible independently. Take solitary walks. Paint pictures. Write a book or sculpt a piece of art. But stay out of the intense Tiger fray. You were not designed for coexistence with this impulsive creature. Use this year to build your own career or your own house, or to learn to cook, sew, knit, crochet, practice judo, or yoga. However, do not attempt to compete in the challenging wider world during the Tiger year.` },
        "2035": { "year": "Rabbit", "element": "Yin Wood", "prediction": `Having endured two rather challenging years, you can finally relax and lighten up in the benevolent, refined atmosphere of the Cat/Rabbit year. Not only will you feel more vibrant and open to meeting new people, but your social life will also significantly improve. You might only be invited to tea or an intimate cocktail party, but these are precisely the types of gatherings that appeal to you. There, you can confidently express yourself and display some of that famous Goat-like charm. This year is particularly favorable for you to meet an important new individual. Perhaps a romantic interest, though not definitively. It could be someone you will collaborate with on a new project, or someone who knows a person capable of providing precisely what you need (whether it's money or influence) to launch your business or acquire a country residence. If you have tasks to accomplish and prefer to do them at your own speed, this Cat/Rabbit year is the one you have been anticipating. There will be no external pressures forcing you to intensify your efforts or criticizing you about how long it takes to thread a needle. You are not comfortable with other people’s deadlines. A project might take you a few days, or it could require weeks of concentrated effort. And for most of that time, you will likely get no sleep, not eat regularly, or converse with many people. But the job will be completed correctly. You have no inherent sense of time; it’s simply your way. The Cat/Rabbit will not interfere.` },
        "2036": { "year": "Dragon", "element": "Yang Fire", "prediction": `Before I neglect to remind you: begin now to save up a few months’ salary during this Dragon year. You will find it necessary. In Dragon years, the pace intensifies, but the favorable disposition towards Goats continues steadily. You will not only feel liberated and unburdened by intrusive influences, but you will also be entertained by the pervasive sense of celebration and festivity that permeates every aspect of our lives in Dragon years. You Goats often require that extra spark of energy (or a push) to navigate the challenges of daily life. You can be prone to both pessimism and defeatism. The Dragon desires no part of your negative attitude and will exert all its power to keep your spirits high. Throughout the year, you will be able to claim minor victories over adversity. You won’t contract the prevalent flu, and you will win the lottery and successfully find the exact drapes you wanted for your TV room. Nothing earth-shattering, but the triumphs will be frequent enough to keep you prancing towards the future with your head held high. Towards the end of the year, you will likely experience a financial setback. Take care not to panic. Instead, find comfort in knowing that you have set aside enough money to see you through until next year, when your fortunes will definitely improve.` }
    }
};

  

    