
export const rooster = {
    introduction: `Jaunty Rooster, you were born to bounce back. Your life is a roller-coaster ride, a chaotic mix of successes and setbacks, periods of prosperity and hardship, trials, tribulations, and other emotionally draining or gut-wrenching experiences, yet you remain an irrepressibly steadfast and courageous spirit. Resilience is your defining characteristic. Regardless of the depth of despair, you simply pick yourself up, smooth your feathers, and confidently stride forward once more. You radiate enthusiasm. Your joy in experiencing new thrills is infectious. People eagerly seek your company, wishing to visit your places, see your sights, and share your exciting way of life. You will frequently hold positions of authority. You are naturally inclined to lead and excel at setting a positive example. You work exceptionally hard.

Despite a sometimes arrogant demeanor and a tendency towards conceit, you cannot be accused of being either overly aggressive or pedantic. You are a multi-talented, open-minded, yet curiously conservative individual. In matters of love, you are captivated by elegance and sophistication. Consider pursuing a glamorous Snake, or engage with an encouraging Dog. Even better, for the sake of a challenge, allow yourself to be charmed by a steady Ox. All of these pairings are capable of easing the difficulties and alleviating the strain of your exhaustingly busy life.

Listen closely. Heed my advice: you are too direct for your own benefit. Make an effort to be less candid. Your bluntness can be your downfall. Feel free to promote yourself, but try not to expose your own weaknesses in the process. Remember, a Rooster in trouble is nothing more than chicken soup.`,
    elements: {
        Wood: `This Rooster possesses a unique ability to persevere in areas where significant effort is crucial for achieving results. Its inherent vigor, conscientiousness, and meticulousness empower it to execute complex tasks that might intimidate less organized or "picky" individuals. However, do not ask the Wood Rooster to agree to spend a lifetime poring over yellowed texts in a dark attic room to produce an encyclopedic volume at the end of its life. Wood Roosters are only capable of exerting enormous effort for short-term undertakings. This individual is best suited for roles such as an efficiency expert, troubleshooter, or project manager, whose primary objective is to "get the job done well—now."

It is a sociable creature and enjoys being in friendly company where it can express itself, share some of its best stories, recount its travels, or listen attentively to the tales spun by its companions. Parties and festivals delight this naturally hospitable type, who will often host, do the cooking, purchase the wine, and (although it is far from wasteful with money) indulge its beloved guests with luxuries for the pleasure of ensuring they have a good time.

Some consider the Wood Rooster a superficial person because appearance holds paramount importance for him. It is important to understand that, on a personal level, he is preoccupied—even obsessed—with youth and fascinated by the "look" of things. Wood Roosters sincerely believe that one's appearance reflects one's essence. They cannot tolerate the idea of being old, irritable, wrinkled, or excluded from mainstream ideas. Even after middle age, the Wood Rooster is likely to continue dressing in youthful, form-fitting clothing and exert every effort to remain slender, agile, and self-assured. He seeks the company and intimacy of people younger than himself in an attempt to maintain his vitality. He often behaves in a manner not entirely consistent with his age—taking up roller-skating at forty, purchasing rock music at sixty, and dancing at seventy in noisy discos where no one else has yet reached their twentieth birthday.

As talkative and sociable as this creature is, the Wood Rooster has a significant emotional block when it comes to expressing his feelings. He can converse extensively about anything he considers polite conversation. In private, however, on subjects deeply personal to one’s heart and soul, he remains completely uncommunicative. If you love one of these emotionally reserved individuals, you will face a considerable challenge trying to encourage him to articulate what is on his mind. Whether this Rooster is angry or sorry, sad, glad, or madly, passionately in love, his exterior remains cool, sleek, well-groomed, nervous, and rather too serious. The Wood Rooster is the type of emotionally constrained person to whom it is necessary to ask a hundred times a day, "Do you love me, darling?" or "Honey, are you angry with me?" They require profound emotional events and insistent, heartfelt lovers to help them open up. Unless the Wood Rooster learns to directly address his feelings, an unhealthy accumulation of anger and resentment will almost certainly remain with him and his intimates for the rest of his days.`,
        Fire: `Complexity! And passion. Fire illuminates the Rooster in peculiar, exaggerated ways, causing him to be born tormented, difficult, and fiery! Fire Roosters are volatile, craving confrontation and confidently rushing from one head-on collision to another without sustaining so much as a tiny scratch.

This Rooster seems to thrive on exhilaration. He is enthusiastic about and involved in everything. Monotony and a lack of challenge bore and depress him. He desires to be right in the midst of the action, on the front lines. Regardless of how tough the dare, he will gladly undertake it. His capacity for work is monumental. His endurance is legendary. His cutting-edge brilliance at absorbing information is staggering. And, finally, his ability to organize others at work while still retaining their respect and affection is top-tier. Fire Roosters were born to be world-beaters, but, unfortunately for them, Fate simultaneously cursed them with a built-in emotional instability.

Fire Roosters should be more successful than they typically are. They are relentlessly ambitious, intelligent, and competent individuals. They make excellent lawyers, caring doctors, innovative scientists, and capable business people. However, because emotions play a primary role in how these individuals conduct business, they often create confusion. Whether they are deeply involved in a conference, eloquently presenting facts in a court case, or reciting crucial figures at a bankruptcy hearing, Fire Roosters remain vulnerable to emotional involvement. They can be swayed into submission if the boss’s wife has had a miscarriage, feel sympathetic because the accountant is overweight, or distort their plea because the other lawyer’s husband just lost his job—anything emotional that enters the Fire Rooster’s mind during business hours poses a potential danger to the outcome of his efforts. Objectivity eludes him.

This person is impulsive, headstrong, and cannot be easily reasoned with. Conjugal life with a Fire Rooster is a testament to friction and very often becomes explosive to the point of being unbearable. He can be tyrannical and despotic, too, especially if his pride is offended. The Fire Rooster believes strongly in absolute rightness and earnestly desires the truth to be revealed. But if voicing the truth involves revealing his own vulnerability or letting down his guard, the Fire Rooster may simply refuse and miss the point entirely: his promises are often little more than promises. He’s emotionally fragile, needing to be liked as well as to enjoy the thrill of victory. He fails because he's conflicted. He doesn't want to apply the rules of ruthlessness to his own advancement, yet because he is so intellectually gifted for clarity, he can perfectly well discern what is necessary to succeed.

On the positive side, the Fire Rooster is a fabulous friend, an amusing companion, and an honest, truthful colleague. In social settings, he enjoys his role as a non-conformist and is sometimes even exhibitionistically bohemian to make a point. He possesses a sound sense of morality, but will not go out of his way unless you go out of yours to champion causes or perform good deeds. He is a tit-for-tat person whose love of honesty and talent for being brutally frank carries him cheerfully along on the crest of his own enthusiasm. He falters when he confronts emotional imperatives with which he cannot reason. But, because he is a Rooster, even repeated failures and torrential setbacks do not deter his courage or dampen his spirit. He was born to bounce back.

As he is easily labeled puritanical in his approach to sex, this deeply troubled Rooster might be better off living in a cloister, adopting some ascetic course of action that does not demand emotional involvement. When effectively utilized, the Fire Rooster’s richly nuanced emotional capacity can produce excellent creative results. But if he chooses to become an artist, he will require both isolation and protection from the outside world.`,
        Earth: `A powerful intellect combined with a flair for the aesthetic, feminine side of life bestows upon this Rooster a talent for nuance and creativity that surpasses that of his more conventional Rooster brothers and sisters. Because of his gift for conversation, some find the Earth Rooster exasperatingly vague and accuse him of not sticking to the point when he delivers rambling speeches. His ability to engage with abstract concepts allows him great verbal freedom, but for those who value concrete facts, his mental meanderings can seem incomprehensible. There's no need to worry, however: this Rooster also has a firm grasp on factual information.

His thought processes can best be described as "penetrating," and his critical abilities as "dead accurate." When he needs to be precise, an Earth Rooster always gets straight to the point, recalling every single detail and date of what occurred previously. He will never allow his interlocutor to get away with fudging even a single detail. It's almost as if, to counteract his own tendency towards vagueness, he feels compelled to be ruthlessly factual in his recollections. Earth Roosters possess elephantine memories, minds like steel traps, and enough common sense to manage both Hungary and Yugoslavia single-handedly.

This is an uncommonly elegant person of regal bearing whose sense of humor—a twinkle, a wink, or a swift, ambiguous glance—always shines through his slightly forbidding facade. It is his great fortune to possess excellent health and frequently to live to a great age. Not only does he live a long time in good condition, the Earth Rooster ages gracefully, retains his agile, quick wit, and rarely suffers symptoms of senility. I know three 1909 Roosters and am certain that today any one of them could tackle a battery of the demanding exams we set our eighteen-year-olds. Earth Roosters grow old with poise, remaining steadfast and individualistic, but shedding the anxiety of their troubled youth to become serene and accepting.

The Earth Rooster only reaches his optimal performance once he has found true love. As he is somewhat timid in youth, he doesn’t always dare to be forward with the opposite sex. An air of naive embarrassment may deter others from attempting to seduce this reserved, conservative creature. He is unlikely to bring home some fleeting lover picked up at a singles bar, usually becoming involved with someone met through a cousin or at a family gathering or wedding. They often marry later than their peers, and because they choose carefully and wait for the right person, they rarely get divorced.

Sexual passion is not the strong suit of this deeply loving person. No tender pats on the head, overt signs of affection, poetic love letters, or exotic love potions for this no-nonsense individual. The Earth Rooster prefers to keep love pure and sensible, never allowing his pristine image to become muddled with sentimental scenes or sticky with emotion.

To succeed professionally, Earth Roosters require a support network. Working for a family business or a large corporation suits them, as they always enjoy playing an integral part in a communal effort. These individuals make excellent accountants, bankers, doctors, architects, and designers. They are meticulous with details and non-impulsive. Although they may experience some tough financial patches, Earth Roosters do not usually go bankrupt or lose their fortunes through foolish investments.`,
        Metal: `Here is a creature born to be on the stage, in the movies, or simply in the middle of his own living room, putting on a show for his family. The Metal Rooster is a performer, the life and soul of the party. People either like this fervent person immensely or find it difficult to tolerate him. Metal Roosters are sometimes boastful: they enjoy promoting themselves, sharing their success stories and those of their family, and generally letting you know how wonderful they are. Although this trait can be tiresome, the Metal Rooster’s purpose is neither egotistical nor greedy. He doesn’t want to impress anyone because he needs or wants something from them. Rather, it is part of his flamboyant nature. Although some find it irritating, others, because this person is usually funny and imaginative, adore being invited to witness the daily spectacle and manage to live happily ever after with this incorrigible entertainer.

If he doesn’t learn to temper it while young, this brash, confident person’s tongue can get him into trouble throughout his life. He is incapable of diplomacy and has a way of blurting out indelicate truths at the most inopportune moments, encountering failure and rejection where he might have found success and approval. When criticized for being too candid, the Metal Rooster may erupt into a short-lived fit of defensive rage. He isn’t the type to bear a grudge. But, given his inclination for speechmaking, his verbose outbursts of bad temper can be impressive enough to cloud an otherwise sunny afternoon.

The Metal Rooster loves organization: he needs to keep things neat and tidy—a place for everything and everything in its place. He doesn’t like to be interrupted when devising new tricks or engaged in his favorite hobby. He cannot tolerate having too much improvisation imposed upon him.

All of the above somewhat fastidious traits may cause a Metal Rooster to spend his adult life alone, without a full-time partner, children, or pets to disrupt the life he has so meticulously planned.

Roosters hold conservative political opinions. They make excellent policemen and, as they crave movement, thrive on travel, and enjoy being expatriates, may find lucrative, secure positions with organizations such as the FBI or Interpol. Of course, their inherent indiscretion might hinder their progress in jobs requiring top-secret classifications. But the Metal Rooster is intelligent and, with a little help from his friends, can certainly learn how to keep quiet in life-or-death circumstances.

The Metal Rooster is perfectly suited for jobs in theater, cinema, and TV. If he does not choose to perform, he should try to become involved in production. When he succeeds in this challenging profession, he will certainly have many fans and followers who will cheer him on and keep his career advancing. He is a natural for stand-up comedy routines, as a talk-show host, and might make a superb newscaster, roving reporter, and even war correspondent.`,
        Water: `Here we encounter the exceptionally multi-talented Rooster. Possessing all the most significant Rooster strengths and weaknesses combined, the Water Rooster might be considered the quintessential model for all other Roosters. He is serious. He is resolute and meticulous. He talks about himself quite a bit. He meticulously cares for his appearance as well as his wardrobe. He is a willing traveler and adores adventure. He knows how to work diligently and persistently to achieve a goal. He endures many setbacks, yet no matter how far he falls behind financially, this Rooster can always discover a new way to earn a living from nothing.

There are, however, a few distinct characteristics about the Water Rooster that set him apart. He is exceptionally adaptable. He’s not rigid but does hold conservative views on almost everything—except his rather inconsistent pattern of fidelity—which he accepts as his inherent right and privilege. Ironically, the Water Rooster is also jealous and possessive of his lovers and mistresses. For him, a double standard applies. Why? Because he says so. Water Roosters either get to be the boss, or they pack their bags and go home.

The Water Rooster loves to be surrounded by people. The more individuals who contact him on any given day, the happier he becomes. He actively seeks out the company of friends and family and will go to great lengths to succeed. He entertains frequently and is often an excellent cook and host. Possibly because he is so eager for companionship, he may, at times, lend assistance to someone less scrupulous than himself. If he is not careful, he may be exploited by ruthless individuals who profit from his goodwill and offer nothing in return.

The Water Rooster is thin-skinned. He cannot tolerate being advised, interfered with, or—heaven forbid—reprimanded. Even if he knows he has made mistakes or is about to encounter significant trouble, he does not wish to be reminded or warned of it. His reactions are not positive to even the mildest suggestion on how he might alter his approach or modify his thinking. If you don’t want to lose his friendship, do not attempt to play truth games with the Water Rooster. If you dare to utter one piercingly true statement in his presence, he’ll become unpleasant and hostile. He may only sulk for a period, but he might never call you again.

Essentially, the Water Rooster suffers from an inferiority complex. He often wishes that he were someone more fortunate whose parents had left him a fortune, a network of influential contacts in the world, or, even better, a chain of supermarkets to call his own. This Rooster often carries a chip on his shoulder about the injustices he feels society has committed against him, but, as he will not listen to the truth about himself nor squarely face his real place in the world, he often has to confront failure, which exacerbates his inferiority complex. As he grows older, this cycle of events becomes increasingly detrimental. If he cannot lower his guard and learn to accept advice, he may become so disgruntled that, by middle age, he may be permanently embittered, withdrawing from society and life as a cheerful hippie or a homeless person.

Despite his unflagging energy and industriousness, the Water Rooster secretly desires to be wealthy. He often envisions himself in a luxurious environment where satin sheets are commonplace and silk pajamas are essential. He even dreams of ample leisure time to recline and read novels and philosophical texts. Roosters are not adept at being idle, as they become bored when they have too much free time. Therefore, this period of idleness usually remains merely a dream.

It is not the Water Rooster’s destiny to become rich overnight. If he marries a wealthy woman whose father owns the biggest construction business in town, the old man will almost certainly go bankrupt the week after the wedding or die and leave all his money to some charity. If he enters into some get-rich-quick business deal where he feels certain to make a fortune in a week, the Better Business Bureau may shut him down or someone will report on TV that his products are defective. The Water Rooster is born to labor. He is both talented for and fated to earn a living from the most barren ground and, above all, to persist day after day, building a solid financial foundation until he has amassed a fortune. His lot may be demanding, but it is nothing to be ashamed of.

Water Roosters possess a seductive quality. Not only are they excellent conversationalists, but they also have a charming way with words that makes them irresistible as salespeople, lovers, advertisers, politicians, and teachers. Loving one of these masterful Water Roosters is a full-time commitment. They do not like to be left alone and cannot tolerate idleness. They require adoration and praise—but even if they receive more than their fair share of compliments, they still may not always be faithful to their partner.`,
    },
    compatibilities: {
        "Rat": "The Rat and the Rooster incessantly peck away at each other. They are equally jealous and possessive, as well as anxious about their combined future. One would expect this alliance to devote long hours to mutual accounts, carefully monitoring each debit. Nervous and impatient to pin down every detail, they’ve surely planned ahead, booking their flights to London and their trips to Morocco months in advance. Not so! Each considers that the other should be the adult in the relationship. Indeed, each wants freedom from burdensome responsibility. Rooster and Rat are forever arguing over money. Each deems the other too extravagant on the wrong items. The showy Rooster desires a shimmering new Jaguar. The Rat wants a crumbling stone house in the countryside. They will never agree. A lively Rat with an active social calendar makes a possessive Rooster turn green with envy. A socially active Rat paired with a conservative Rooster feels stifled. The rebellious Rat accepts prestigious invitations and leaves the jilted Rooster at home alone. Crushed by the Rat's frequent absences, the Rooster grows insecure and seeks new ways to confine the Rat. Using sex as a weapon, each deprives the other when they quarrel. Although fundamentally capable of enjoying each other, their mundane conflicts surface in the bedroom. This allows for only intermittent pleasure on the occasional peaceful Tuesday. The union is unstable, at best.",
        "Ox": "Should you be fortunate enough to have found each other, remain together. People consistently notice an Ox/Rooster couple. 'Look how content they are!' they remark. Astrologers in China recommend this as one of the most favorable unions ever! Together, your lives will be enriched by a blend of effortless sociability and unwavering security. Individually, the Ox and the Rooster can be equally meticulous, anxious, and perfectionistic. One might expect this pairing to come together and then self-destruct. But, for some reason, they discover peace. This traditional couple lives strictly by the rules. The Ox performs everything correctly, and the Rooster follows suit. They purchase their first home at the appropriate stage of life, have children when expected, and retire to their beautiful country residence when they become wealthy—which often happens very quickly. Both are keen, capable workers. They are not particularly fond of social outings, preferring to remain close to home. Children will be more than welcome here. This stable pair provides great security for a family. Not known for passion or recklessness, their sexual intimacy reflects their practical lifestyle. No embellishments, just basic, normal lovemaking. Two naturally harmonious signs should ensure this happy marriage is long-lived and successful.",
        "Tiger": "I don’t recommend this pair for marriage. Both parties are aggressive and opinionated; neither will back down easily. The atmosphere will be taut and most arguments one-sided. Conflicts and collisions are guaranteed to hinder the harmonious progress of this couple. Tigers bounce back and forget every nasty word that was said. But Roosters carry grudges and cannot forget how badly they were treated by a Tiger last time they had a row. Impasses are common. In bed, there may be some fairly exciting fireworks, as the Rooster is imaginative and energetic enough to keep the demanding Tiger interested. They are both impetuous and uninhibited lovers capable of grand gestures and profound intensity. Unless the disagreements of the day carry over into the bedroom, this couple is well aspected for a long, healthy sex life—without marriage.",
        "Rabbit": "This couple should think twice before taking the lifelong plunge into matrimony. The sex is mediocre at best. Although Cats are initially attracted by the haughty Rooster’s natural nobility and aura of reserve, they may be misinterpreting the Rooster’s real methods and motives. Basically, Roosters want to be free to roam and race about following the peripatetic bent of their roller-coaster existence. Cats like to stay at home, work long and hard at quiet jobs, get and stay rich. Lifestyle would quickly become a problem for this pair. With their individual approaches being so gapingly different, who, I ask you, would take out the garbage? Certainly not the refined Cat, who is too busy reading philosophical tomes and decorating magazines on a Louis XV chaise longue. As for the Rooster—he’s hardly ever home long enough to create any garbage, or babies. If the pair has the means (and nothing prevents them from earning money, as they are both hardworking, serious types) to hire help for the baser human chores, they can establish a solid, functional family life.",
        "Dragon": "Both passion and glamour are missing from this otherwise well-balanced relationship. It is workable. Dragon protects with gusto and Rooster obeys with serious intent to do the right thing. Neither is ecstatic in this arrangement but, then, neither is blatantly unhappy. Roosters recognize and respect the Dragon’s need to shine, to assert superiority over others and go out and beat the world at its game. Despite sometimes flamboyant outward appearances, the Rooster is a rank conservative. Roosters do want to voice their truths and implement their ideals. But they don’t show off. With a brave and daring Dragon partner, the Rooster can carry on being quietly cocky while the Dragon plays the conspicuous role. I’m afraid the Dragon’s exorbitant sexual needs may prove overwhelming to the less sensual Rooster. Rooster’s rebuffs may destroy Dragon’s ego. The solution will only be found in frank discussion with an objective third party. A therapist? A clergyman? A family friend?",
        "Snake": "A love match if ever I saw one! The Rooster is rather bourgeois and conventional. Snakes are esthetic and long to appear attractive at all times. Although, at first glance, it may seem that the Snake is too sophisticated and elegant for the plain-living Rooster, the opposite is true. Roosters and Snakes form some of the best couples. They are both quite secretive and like to keep to themselves. Yet, when together, they are forever locked in intense discussion and consideration of every detail, from the quality of light inside their fridge to the leather on the soles of their expensive shoes. Roosters are mostly forgiving, indulgent people whose loyalty knows no frontiers. Snakes may run around a bit, both socially and sexually, but they are careful never to get deeply involved with their conquests and hardly ever betray or leave their Rooster mates. Why? Because they truly love them. In this marriage, the Rooster should look after the finances. Snakes often waste money. Roosters keep closer tabs on their pennies. The cultural side can be handled equally well by both. Sex should definitely be left up to the seductive Snake. Snakes know how to turn on hesitant Roosters, to make their bodies sing. Roosters are basically reserved about sensual matters. The Rooster who lands a Snake for a mate will have much to crow about.",
        "Horse": "Unless stimulated by the right partner, both Roosters and Horses become stodgy and work-obsessed. This couple would need a professional or family connection in order to be thrown together in the first place. There is not much charisma on either side at the outset. But, with some work, the relationship can grow and endure. Once together, the Horse will be flattered by the Rooster’s possessive streak, but in time will resent it and dissension will set in. Horse wants to go out and play and Rooster wants them both safely at home – even if it’s only to share the Sunday crossword puzzle. For this relationship to succeed, the Horse must learn to be less outgoing and the Rooster more tolerant of the Horse’s need for social interaction. Roosters are so conservative that, although Horse’s occasional outrageousness appeals to their rebellious side, they will worry nonstop about the negative outcome of their mate’s follies. A Rooster’s best bet is to give the Horse a longer and longer rein, and wait sanely by the fireside till Horsey comes cantering back for dinner. At first, their sex life may be limited by Rooster’s excessive conservatism. The practical Horse will rise to the occasion and prod Rooster to be more innovative. In time, when they learn to satisfy each other’s needs, their sexual rapport can become nigh unto perfect.",
        "Goat": "This is a dicey combination. Roosters are conservative and individualistic. They deplore laziness and cannot tolerate lackadaisical attitudes in others. Goats like to take it easy. They don’t believe in work for its own sake, would rather sit still than move about, and are ever ready to get someone else to take care of their basic needs. As the Rooster often had great difficulty scratching out a living, he or she will be impatient with the idea of anyone living off the fat of the land and will wish the Goat would find a “real” job, like a normal person. Goat’s feelings are readily hurt. Tensions can mount in this household and very little will be talked through, because the Rooster hates discussing his emotions. The fickle Goat may wander sexually, causing the staid and faithful Rooster untold pain. Trouble is, the Goat needs more than just the Rooster’s perfunctory affections. Knowing this fact creates feelings of inadequacy and a lack of self-confidence in the Rooster. If Goat could be persuaded to stick around all the time and teach the willing Rooster how to be more sensual, their relationship might have a good chance at success. At least it would give more purpose to the otherwise idle Goat’s home life. Goat with Rooster is far from an ideal marriage.",
        "Monkey": "Not much is going on sexually between these two characters. Roosters are possessive and anxious about their position in relationships. Their instinct is to anchor their prey. Monkeys need miles of rope to feel good about themselves. They have to roam amid people, jabber with others and find solutions to ever more important problems. Roosters are conservative thinkers. Monkeys are all for liberation, gentler laws and personal liberty. This couple may be constantly at odds over policy. Decisions become difficult. Tensions rise and Rooster suffers—because Rooster makes the untenable scenes that send the Monkey packing. Roosters must accept Monkey’s devil-may-care side to enjoy the benefit of his or her humor. It’s up to the Rooster to be more flexible. And that is a tall order. So these two are not exactly Romeo and Juliet. Monkey is interested in sex, but he’s also fascinated by life’s other aspects—above all its practicalities. Rooster is also practical and appreciates Monkey’s delight in solving concrete issues. But Rooster needs softening, romancing, loving and cuddling to appreciate the joys of sex. Now it’s Monkey’s turn to adapt, to become more languorous and spend time petting and nuzzling. Or Rooster (God forbid!) might begin scratching around in another barnyard for sexual understanding.",
        "Rooster": "Difficult at best, this couple’s inevitable clashes over everything from money to styles of clothing and which schools to send the children to are practically never worth sorting out. What we face here are two opinionated, ego-centered people. They are, first of all, victims of themselves and require jollier, more acquiescent partners than either can be for the other. Roosters need to be cushioned and coaxed. I hardly see any Rooster accepting to do the coaxing for another—unless in a war where the other Rooster was a fallen buddy. The war metaphor is suitable. Each Rooster engaged in a Rooster/Rooster couple wants to be the General. Each needs to feel superior to the other. Each is conservative and shy, unsure of his image and feisty beyond feistiness. Battles royal rage daily, viciously tearing harmony to shreds. Roosters often befriend each other. They think alike and have similar views. They can even work together—providing one takes a backseat. But romantic love between Roosters rarely produces equilibrium. The sex is lukewarm: neither is able to express passion without help from a more vigorously self-assured partner.",
        "Dog": "Incompatibility reigns supreme in this couple. Dogs and Roosters are equally flinty and raw-nerved. Dogs are forever blurting criticism and bruising the egos of those around them. Roosters are cocky but deeply unsure of themselves. One yelp from the Dog’s storehouse of biting blatancies can put the Rooster under for days, depress him and undo his hard-earned image. Do these people fight? They never stop. Backbiting, carping, bickering over details. They don’t agree on anything. Dogs are classically left wing, kindly and trustworthy. Roosters are born conservatives who believe in the system, adhere to society’s basic tenets and cleave to traditional ways. This couple’s home life is a constant push-me pull-you of political unrest. Dog wants revolution. Rooster devoutly wishes for status quo. Dog thinks mismatched china and a pallet on the floor will do nicely. Rooster wants Spode or Limoges set with crystal grasses on an heirloom table. Dog wants to spend money on causes. Rooster wants to keep his money in the bank. Rooster demands more and varied sex than Dog has to give. Rooster needs to puff up his ego and preen his feathers. Dog couldn’t care less what he looks like in bed. He feels sex rather than performing it. Besides, Dogs are slightly puritanical. They don’t believe one should overindulge in pleasure. Leave the Rooster/Dog love relationship alone.",
        "Pig": "This partnership can succeed brilliantly. Roosters who find themselves in bed with willing, sensual Pigs are truly in luck. My advice to this lucky Rooster is to hang on tight: you will not find such amiability, charm and easygoing service anywhere else in the zodiac. Pigs are willing to adapt and change, modify their personalities and lifestyles to suit the one they love. With all of your ups and downs, resounding successes and failures, you will definitely benefit from the presence of a kindly, nurturing, understanding Pig. As for the Pig in this relationship, you will gain much from the pure rigor and frank style of a Rooster partner. Roosters like things as they are. They are not revolutionaries. Pigs, too, enjoy tradition and respect the basic tenets of a good society. Your common interests will flourish and after the first few years will take you very far towards achieving dreams and goals you only dreamed of before meeting. Sex, too, is favored in this couple. The Rooster can take charge in lovemaking. Pigs appreciate being moved to exotic heights in bed, adore almost anything sensual and make excellent cuddlers for roughshod Rooster to learn to snuggle with. If I were a Rooster, I think I might seek a Pig mate. Your lifetime happiness and financial security (Pigs attract money) would be assured.",
    },
    futures: {
        "2025": { "year": "Snake", "element": "Wood", "prediction": "This year is a good one for you. Snakes and Roosters are allies. You can anticipate making good progress in your career and enjoying a stable love life. The Snake's philosophical nature will appeal to your own intellectual side. You will find much to discuss and may even embark on a joint project together. Financially, it’s a time of security. The Snake’s wisdom and your own diligence will ensure that you have more than enough. It's a good year for investing, particularly in areas related to art and culture. Romantically, you will be captivated by the Snake’s charm and sensuality. Your loyalty will be deeply appreciated, and you will find a profound connection with your partner. This is a year of harmony, intellectual stimulation, and personal growth." },
        "2026": { "year": "Horse", "element": "Fire", "prediction": "This is a year of action and hard work. The Horse’s energy and your own diligent nature are a good combination for productivity. However, you may find the Horse’s pace a bit frantic. You prefer a more methodical approach. Professionally, your hard work will be rewarded, but you may have to adapt to new and faster ways of doing things. Financially, it’s a good year for earning money, but be careful not to get caught up in the Horse’s extravagant spending habits. Your natural conservatism will serve you well. In your love life, you may find the Horse’s need for constant excitement a bit tiring. You prefer a more settled existence. However, the Horse’s passion can also be invigorating. This is a year for adapting to a faster pace and reaping the rewards of your labor." },
        "2027": { "year": "Goat", "element": "Fire", "prediction": "This will be a frustrating year for you. The Goat’s whimsical, and sometimes lazy, nature will clash with your own disciplined and hardworking personality. You will feel that no one is taking things seriously, and your efforts to impose order will be met with artistic temperament and emotional displays. It’s a time to be patient and to focus on your own tasks. Don't expect much from others. Financially, this is not a year for major gains. The Goat’s influence is not conducive to practical matters. It’s a time for conserving your resources. Romantically, you may find the Goat’s need for constant reassurance and its emotional volatility to be draining. Your straightforward nature may not be appreciated. It’s a year to practice tolerance and to lower your expectations." },
        "2028": { "year": "Monkey", "element": "Earth", "prediction": "This is a year of intellectual stimulation and strategic maneuvering. The Monkey’s cleverness will impress you, and you will enjoy the challenge of a good debate. However, be wary of the Monkey’s tendency to play games. You are a straightforward person and may not appreciate the Monkey’s love of intrigue. Professionally, this is a good year for problem-solving and for using your analytical skills. You may find yourself in a position where you have to outsmart the competition. Financially, it’s a time for caution. The Monkey’s influence can lead to risky schemes. Trust your own judgment and avoid anything that seems too good to be true. Romantically, the Monkey’s wit can be very attractive, but its lack of seriousness may be a source of frustration. This is a year for keeping your wits about you and for enjoying a good mental workout." },
        "2029": { "year": "Rooster", "element": "Earth", "prediction": "This is your year to take charge and to put your own house in order. You will feel a strong urge to organize, to budget, and to make plans for the future. Your natural leadership abilities will be in demand. However, be careful not to become too dictatorial. Your tendency to criticize can be off-putting to others. Professionally, this is an excellent year for management and for any work that requires precision and attention to detail. Financially, your conservative nature will serve you well. It’s a time for saving and for making sensible investments. Romantically, if you are with another Rooster, you will find a shared sense of purpose and a mutual understanding. However, the lack of spontaneity can be a bit dull. Make an effort to inject some fun and romance into your life. This is a year for being in control and for building a solid foundation." },
        "2030": { "year": "Dog", "element": "Metal", "prediction": "This will be a difficult year for you. The Dog’s idealism and your own conservatism are at odds. You will find yourself in constant disagreement over matters of principle. The Dog will want to fight for justice, while you will want to maintain the status quo. This can lead to heated arguments and a general sense of unease. Professionally, you may find that your practical approach is not valued in a climate of social change. It’s a time to keep your head down and to avoid controversy. Financially, the Dog’s generosity will conflict with your own frugality. Don’t let yourself be guilt-tripped into supporting causes you don’t believe in. Romantically, your need for order will clash with the Dog’s more chaotic and emotional nature. It’s a year of conflict and frustration. Patience and tolerance are essential for survival." },
        "2031": { "year": "Pig", "element": "Metal", "prediction": "This is a very favorable year for you. The Pig’s good nature and your own sense of duty make for a harmonious combination. You will find that your hard work is appreciated and that your efforts are rewarded. Professionally, it’s a time for steady progress. Your diligence will lead to success. Financially, this is a very prosperous year. The Pig’s luck with money and your own sound judgment will bring you wealth. It’s a good time for enjoying the fruits of your labor. Romantically, the Pig’s sensuality and your own loyalty are a perfect match. You will find great contentment and security in your relationship. This is a year of peace, prosperity, and happiness. Enjoy it." },
        "2032": { "year": "Rat", "element": "Water", "prediction": "This year will be a period of conflict and stress for you. The Rat’s ambition and your own desire for control will lead to a power struggle. You will both want to be in charge, and neither of you will be willing to back down. This can lead to bitter arguments and a breakdown in communication. Professionally, you will find yourself in a competitive environment. It’s a time for being assertive and for defending your territory. Financially, there will be disputes over money. The Rat’s extravagance will clash with your own conservative approach. Be prepared for arguments over spending. In your love life, possessiveness and jealousy will be major issues. This is a year of tension and conflict. It will require all your skills of diplomacy to navigate." },
        "2033": { "year": "Ox", "element": "Water", "prediction": "This is an excellent year for you. The Ox is your most powerful ally. You share a common work ethic, a love of order, and a conservative outlook. You will find great harmony and mutual support in this relationship. Professionally, your diligence and the Ox’s strength will lead to great success. It’s a time for building, for consolidating, and for achieving your long-term goals. Financially, this is a very secure year. Your combined efforts will lead to prosperity. Romantically, you will find a deep and lasting bond with your partner. Your shared values will create a stable and happy home life. This is a year of achievement, security, and contentment." },
        "2034": { "year": "Tiger", "element": "Wood", "prediction": "This will be a challenging year. The Tiger’s impulsiveness and your own need for order are a difficult combination. You will find the Tiger’s constant need for excitement and its disregard for rules to be very stressful. It’s a time for being flexible and for adapting to change. Professionally, you may find that your careful plans are disrupted by unforeseen events. You will need to be quick on your feet to respond. Financially, it’s a volatile year. The Tiger’s risk-taking can lead to both great gains and great losses. Be cautious. Romantically, the Tiger’s passion is exciting, but its temper can be frightening. This is a year for courage and for learning to go with the flow." },
        "2035": { "year": "Rabbit", "element": "Wood", "prediction": "This year, you will feel at odds with the prevailing atmosphere. The Rabbit’s refined and gentle nature will seem frivolous to your practical mind. You may also find that your directness is not appreciated in a climate that values diplomacy and subtlety. Professionally, you may feel that your hard work is not being properly valued. It’s a time for patience and for not taking things personally. Financially, it’s a stable but uninspiring year. The Rabbit’s influence is not conducive to major financial undertakings. Romantically, you may find the Rabbit’s indirectness and emotional sensitivity to be frustrating. Your own conservative nature in love may not be enough to keep the peace. This is a year for practicing tolerance and for trying to understand a different point of view." },
        "2036": { "year": "Dragon", "element": "Fire", "prediction": "This is a year of opportunity and expansion. The Dragon’s energy and your own ambition can lead to great success. However, you will have to share the spotlight, which may not come easily to you. The Dragon’s flamboyance can also be a bit much for your conservative tastes. Professionally, this is a time for being bold and for taking on new challenges. The Dragon’s influence will help you to achieve your goals. Financially, it’s a year of extravagance. You will be tempted to spend lavishly. Enjoy yourself, but try to keep a rein on your spending. Romantically, the Dragon’s passion is intoxicating, but its ego can be overwhelming. This is a year for being confident and for enjoying the fruits of your ambition." }
    }
};
