/**
 * MYSTIQUE COMPASS — Karmic Lessons (Missing Numbers 1-9)
 *
 * Each digit 1-9 that is absent from the birth date + full name chart
 * represents a Karmic Lesson the soul chose to learn in this lifetime.
 * From the birth date alone, we analyze which digits are absent.
 *
 * ALL TEXT IS VERBATIM.
 */
export interface KarmicLesson {
  number: number;
  title: string;
  present: boolean;
  count: number;
  interpretation: string;
}
export interface KarmicLessonResult {
  lessons: KarmicLesson[];
  summary: string;
  /** Optional long-form synthesis used by PDF/EPUB exporters when present. */
  synthesis?: string;
}
const LESSON_MEANINGS: Record<
  number,
  { title: string; interpretation: string }
> = {
  1: {
    title: "The Lesson of Selfhood",
    interpretation: `KARMIC LESSON 1 — The Lesson of Selfhood\n\nThe number 1 represents independence, initiative, and the courage to stand alone. When the 1 is absent or under-represented in the birth chart, the soul has chosen the Karmic Lesson of SELFHOOD — learning to develop a strong, independent sense of self in a lifetime where the natural tendency is toward dependence on others.\n\nTHE MANIFESTATION: The individual with a Karmic Lesson 1 often struggles with indecision, self-doubt, and a persistent sense that they need someone else's approval or permission before acting. They may gravitate toward strong personalities who make decisions for them, then resent the very dependence they seek. The lesson is not merely to "be more independent" but to DISCOVER that the self they have been seeking outside themselves has been within them all along.\n\nTHE CURRICULUM: Life will present situations that demand independent action — circumstances where no one else can decide, lead, or initiate on your behalf. These situations are not punishments but classrooms. Each time you act from your own authority (however tentatively), the muscle of selfhood strengthens. The goal is not to never need others but to stand beside them as an autonomous being rather than leaning on them as a dependent one.\n\nTHE RESOLUTION: The Lesson of Selfhood is learned when the individual can say "I decide" without needing to justify the decision to anyone. It is learned when aloneness ceases to feel like abandonment and begins to feel like freedom.`,
  },
  2: {
    title: "The Lesson of Connection",
    interpretation: `KARMIC LESSON 2 — The Lesson of Connection\n\nThe number 2 represents partnership, sensitivity, and the capacity for genuine emotional attunement. When the 2 is absent or under-represented in the birth chart, the soul has chosen the Karmic Lesson of CONNECTION — learning to relate to others with patience, empathy, and the willingness to prioritize relationship over independence.\n\nTHE MANIFESTATION: The individual with a Karmic Lesson 2 often struggles with impatience, insensitivity to others' feelings, and a tendency to dominate relationships rather than collaborate within them. They may find themselves repeatedly in conflicts they do not understand — saying things that wound others without intending to, pushing forward when waiting would be wiser, and wondering why relationships keep breaking despite their best efforts.\n\nTHE CURRICULUM: Life will present situations that demand patience, listening, and emotional attunement — circumstances where force and independence are not the solution. Relationships will be the primary classroom, and the lesson will repeat in different forms until it is learned. The key is to recognize that genuine connection requires a different set of muscles than independence — muscles of patience, receptivity, and the willingness to be affected by another.\n\nTHE RESOLUTION: The Lesson of Connection is learned when the individual can sit in silence with another without needing to fill it, when they can receive criticism without immediately counterattacking, and when partnership ceases to feel like limitation and begins to feel like expansion.`,
  },
  3: {
    title: "The Lesson of Expression",
    interpretation: `KARMIC LESSON 3 — The Lesson of Expression\n\nThe number 3 represents creative self-expression, joy, and the capacity to communicate in ways that uplift and inspire. When the 3 is absent or under-represented in the birth chart, the soul has chosen the Karmic Lesson of EXPRESSION — learning to give voice to the inner world in a lifetime where the natural tendency is toward silence, suppression, or the fear of being seen.\n\nTHE MANIFESTATION: The individual with a Karmic Lesson 3 often struggles with expressing their authentic self. They may have rich inner worlds that remain locked inside, creative impulses that are stifled by self-criticism before they can emerge, and a persistent sense that what they have to say is not worth hearing. The joy that other people seem to access naturally feels foreign or even threatening.\n\nTHE CURRICULUM: Life will present situations that demand expression — moments when silence is not an option, when the creative impulse becomes so urgent that it overrides the fear. These are the soul's interventions, creating pressure that ensures the lesson cannot be permanently avoided. Creative practices, public speaking, and any form of self-expression are the laboratories where this lesson is learned.\n\nTHE RESOLUTION: The Lesson of Expression is learned when the individual creates for the pure joy of creating — not for approval, not for perfection, but because expression has become as natural as breathing. It is learned when the fear of judgment diminishes to the point where it no longer prevents action.`,
  },
  4: {
    title: "The Lesson of Discipline",
    interpretation: `KARMIC LESSON 4 — The Lesson of Discipline\n\nThe number 4 represents structure, discipline, and the capacity for sustained, methodical effort toward long-term goals. When the 4 is absent or under-represented in the birth chart, the soul has chosen the Karmic Lesson of DISCIPLINE — learning to build foundations and maintain consistency in a lifetime where the natural tendency is toward chaos, impulsiveness, and the abandonment of projects when initial excitement fades.\n\nTHE MANIFESTATION: The individual with a Karmic Lesson 4 often struggles with follow-through. They begin projects with genuine enthusiasm but abandon them when the work becomes routine. Their lives may be characterized by a series of promising starts and disappointing incompletions. Practical responsibilities — finances, organization, maintenance — feel burdensome in a way that is disproportionate to their actual difficulty.\n\nTHE CURRICULUM: Life will present situations that demand sustained effort — projects that cannot be completed in a burst of inspiration, commitments that must be honored day after day regardless of mood. The universe will systematically remove the short-term gratification options that the individual has relied upon, forcing engagement with the slower, deeper rewards of disciplined effort.\n\nTHE RESOLUTION: The Lesson of Discipline is learned when the individual discovers that structure is not the enemy of freedom but its foundation. It is learned when the satisfaction of completing a long-term project surpasses the pleasure of starting a new one. It is learned when discipline ceases to feel like imprisonment and begins to feel like self-respect.`,
  },
  5: {
    title: "The Lesson of Freedom",
    interpretation: `KARMIC LESSON 5 — The Lesson of Freedom\n\nThe number 5 represents freedom, adaptability, and the courage to embrace change and uncertainty. When the 5 is absent or under-represented in the birth chart, the soul has chosen the Karmic Lesson of FREEDOM — learning to release control, embrace change, and trust life's unfolding in a lifetime where the natural tendency is toward rigidity, fear of the unknown, and excessive attachment to stability.\n\nTHE MANIFESTATION: The individual with a Karmic Lesson 5 often struggles with change. They may cling to situations, relationships, and identities long after they have served their purpose, not from genuine attachment but from terror of the unknown. Their lives may become increasingly constricted as they avoid risks, decline opportunities, and build walls that were meant to provide safety but have become a prison.\n\nTHE CURRICULUM: Life will present situations that cannot be controlled — changes that arrive regardless of resistance, disruptions that shatter the carefully maintained stability. These are the soul's interventions, ensuring that the individual cannot permanently avoid the lesson of surrender. The curriculum is not to become reckless but to develop the capacity to move WITH change rather than against it.\n\nTHE RESOLUTION: The Lesson of Freedom is learned when the individual discovers that genuine security is internal — that no external stability can substitute for the inner capacity to adapt and thrive in changing circumstances. It is learned when change ceases to feel like threat and begins to feel like adventure.`,
  },
  6: {
    title: "The Lesson of Love",
    interpretation: `KARMIC LESSON 6 — The Lesson of Love\n\nThe number 6 represents love, responsibility, and the capacity for genuine care and service to others. When the 6 is absent or under-represented in the birth chart, the soul has chosen the Karmic Lesson of LOVE — learning to open the heart, to care for others beyond self-interest, and to accept the responsibilities that genuine love entails.\n\nTHE MANIFESTATION: The individual with a Karmic Lesson 6 often struggles with intimacy and commitment. They may avoid the responsibilities of close relationships, prioritize personal freedom over the needs of others, and find themselves increasingly isolated despite (or because of) their insistence on independence. There may be a pattern of leaving relationships when they demand genuine care or sacrifice.\n\nTHE CURRICULUM: Life will present situations that demand care — circumstances where the individual is the only one who can provide what is needed, where walking away would cause genuine harm. Relationships, family obligations, and opportunities for service are the classrooms. The lesson is not to become a martyr but to discover that caring for others is not a subtraction from the self but an expansion of it.\n\nTHE RESOLUTION: The Lesson of Love is learned when the individual experiences the genuine satisfaction of having helped another — not for recognition but for the quiet knowledge that their presence made someone's life better. It is learned when commitment ceases to feel like trap and begins to feel like the structure within which love can genuinely flourish.`,
  },
  7: {
    title: "The Lesson of Depth",
    interpretation: `KARMIC LESSON 7 — The Lesson of Depth\n\nThe number 7 represents spiritual depth, introspection, and the pursuit of wisdom and understanding. When the 7 is absent or under-represented in the birth chart, the soul has chosen the Karmic Lesson of DEPTH — learning to move beyond surfaces, to seek understanding rather than mere information, and to develop a spiritual dimension of existence.\n\nTHE MANIFESTATION: The individual with a Karmic Lesson 7 often struggles with superficiality — not from lack of intelligence but from a habit of skimming surfaces rather than diving deep. They may accumulate experiences without integrating them, collect information without transforming it into wisdom, and avoid the solitude that genuine depth requires. There may be a persistent sense that something important is missing, without clarity about what it is.\n\nTHE CURRICULUM: Life will present situations that cannot be navigated at the surface level — crises that demand deeper understanding, losses that require spiritual resources, questions that cannot be answered by conventional wisdom. Solitude will be imposed when it is not chosen, creating the conditions in which depth can develop. The curriculum is not to abandon the world but to develop an inner dimension that enriches engagement with it.\n\nTHE RESOLUTION: The Lesson of Depth is learned when the individual discovers the satisfaction of genuine understanding — the moment when a question that has been pursued patiently finally yields its answer. It is learned when solitude ceases to feel like loneliness and begins to feel like the condition of spiritual growth.`,
  },
  8: {
    title: "The Lesson of Power",
    interpretation: `KARMIC LESSON 8 — The Lesson of Power\n\nThe number 8 represents power, authority, and the capacity to direct material resources toward meaningful ends. When the 8 is absent or under-represented in the birth chart, the soul has chosen the Karmic Lesson of POWER — learning to claim authority, to manage resources effectively, and to wield influence without being corrupted by it.\n\nTHE MANIFESTATION: The individual with a Karmic Lesson 8 often struggles with financial management, professional authority, and the exercise of power in any form. They may avoid positions of responsibility, underearn relative to their capacity, or repeatedly find themselves in financial difficulty that seems disproportionate to their effort. There may be a pattern of giving away power to others and then resenting the inequality.\n\nTHE CURRICULUM: Life will present situations that demand the exercise of authority — circumstances where refusal to lead would cause harm, where avoidance of financial responsibility would have serious consequences. The curriculum is not to become obsessed with power and money but to develop a HEALTHY relationship with them — to claim what you have earned and to direct resources with wisdom and integrity.\n\nTHE RESOLUTION: The Lesson of Power is learned when the individual can hold authority without being corrupted by it and manage resources without being defined by them. It is learned when financial stability ceases to feel like selling out and begins to feel like the foundation from which genuine generosity becomes possible.`,
  },
  9: {
    title: "The Lesson of Release",
    interpretation: `KARMIC LESSON 9 — The Lesson of Release\n\nThe number 9 represents completion, universal compassion, and the capacity to release what has finished its cycle. When the 9 is absent or under-represented in the birth chart, the soul has chosen the Karmic Lesson of RELEASE — learning to let go, to forgive, and to complete cycles gracefully rather than clinging to what has ended.\n\nTHE MANIFESTATION: The individual with a Karmic Lesson 9 often struggles with endings. They may hold onto relationships long after they have died, remain in careers that have completed their purpose, and accumulate possessions, grievances, and identities that no longer serve them. There may be a pattern of refusing to grieve and thereby remaining permanently tethered to what has been lost.\n\nTHE CURRICULUM: Life will present situations that demand release — endings that arrive regardless of resistance, losses that cannot be prevented, closures that must be accepted. The curriculum is not to become indifferent but to develop the capacity to love without clinging, to grieve and then to continue, to complete one chapter before beginning the next.\n\nTHE RESOLUTION: The Lesson of Release is learned when the individual discovers that letting go is not loss but liberation — that what is genuinely yours cannot be taken, and what can be taken was never yours. It is learned when forgiveness ceases to feel like surrender and begins to feel like the ultimate act of self-liberation.`,
  },
};
export function getKarmicLessons(
  numberCounts: Record<number, number>,
): KarmicLessonResult {
  const lessons: KarmicLesson[] = [];
  for (let n = 1; n <= 9; n++) {
    const count = numberCounts[n] || 0;
    const present = count > 0;
    lessons.push({
      number: n,
      present,
      count,
      title: LESSON_MEANINGS[n]!.title,
      interpretation: present
        ? `${LESSON_MEANINGS[n]!.title}\n\nThis number (${n}) is PRESENT in your birth chart (${count} occurrence${count !== 1 ? "s" : ""}), indicating that this lesson has been addressed in previous incarnations or is being actively developed in this lifetime. The qualities associated with the number ${n} are accessible to you, though they may require conscious cultivation to reach their fullest expression.\n\nHaving this number present means that the corresponding Karmic Lesson is not a PRIMARY curriculum for this lifetime — though it may serve as a supporting theme, particularly if the number appears only once. The soul chose to include this vibration as part of its current incarnation's toolkit.`
        : `KARMIC LESSON ${n} — ${LESSON_MEANINGS[n]!.title}\n\nThe number ${n} is ABSENT from your birth chart. This absence is not a deficiency but a DELIBERATE CHOICE made by your soul before this incarnation. The soul chose to enter this lifetime WITHOUT the ${n} vibration, creating a curriculum in which the qualities associated with the ${n} must be consciously developed through experience rather than accessed as innate gifts.\n\n${LESSON_MEANINGS[n]!.interpretation}\n\nRECOGNIZING THE LESSON IN YOUR LIFE: Pay attention to recurring patterns that involve the themes of this missing number. These patterns are not random misfortunes but the soul's curriculum making itself known — the same lesson appearing in different forms until it is consciously engaged. The absence of a number in your chart is the universe's way of ensuring you cannot avoid its corresponding lesson.`,
    });
  }
  const missing = lessons.filter((l) => !l.present);
  const missingNumbers = missing.map((l) => l.number);
  const presentLesson = lessons.every((l) => l.present);
  const summary = presentLesson
    ? `ALL NUMBERS PRESENT: Your birth chart contains all nine single-digit vibrations (1-9). This is relatively rare and indicates a soul that has completed significant karmic work across many lifetimes. Rather than specific Karmic Lessons (missing numbers), your curriculum in this lifetime is one of INTEGRATION — learning to harmonize all nine vibrations into a coherent, balanced expression. The challenge of having all numbers is not absence but OVERLOAD — the risk of scattering across too many expressions without depth in any. Your task is to choose which vibrations to develop most fully while maintaining access to all.`
    : `KARMIC LESSON SUMMARY: Your birth chart reveals ${missing.length > 5 ? "significant" : missing.length > 2 ? "several" : "key"} Karmic Lesson${missing.length > 1 ? "s" : ""} — ${missing.length === 1 ? "the number" : "the numbers"} ${missingNumbers.join(", ")} ${missing.length === 1 ? "is" : "are"} absent or under-represented. This absence is not a flaw but a DELIBERATE SOUL CHOICE. Before incarnation, your soul selected the specific vibrations it would carry into this lifetime and those it would leave behind — creating a precise curriculum of experiences designed to develop qualities that require conscious cultivation.\n\nThe absent number${missing.length > 1 ? "s represent" : " represents"} the territory your soul most needs to explore in this lifetime. The patterns and challenges that recur in your life are not random — they are the classroom in which these lessons are taught. When you encounter difficulty in the areas governed by your missing number${missing.length > 1 ? "s" : ""}, you are not being punished. You are being EDUCATED.\n\nThe goal is not to become perfect in these areas but to develop FUNCTIONAL COMPETENCE — enough mastery that the absence no longer creates suffering. A lifetime is long enough for this work.`;
  return { lessons, summary };
}