/**
 * Birth-date ledger for the historical personal-year cases.
 *
 * The historical examples are only useful when their arithmetic is reproducible.
 * The main famous-birthday bank covers most records; this supplemental ledger
 * covers people who are deliberately used in the historical-event bank but are
 * not in that general-purpose list. Dates are public biographical facts and
 * are kept here so that a case's Direct and Classic compounds can be checked
 * from the same source data as a user's chart.
 */

export interface HistoricalBirthDate {
  day: number;
  month: number;
  year: number;
  source?: string;
}

export function normaliseHistoricalPersonName(value: string): string {
  return value
    .toLowerCase()
    .replace(/[†’‘’“”.,'()]/g, '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

const WIKIPEDIA = 'https://en.wikipedia.org/wiki/';

/** Supplemental dates not already present in famous-birthdays.ts. */
export const HISTORICAL_BIRTH_DATES: Record<string, HistoricalBirthDate> = {
  'aamir khan': { day: 14, month: 3, year: 1965, source: `${WIKIPEDIA}Aamir_Khan` },
  'aitana bonmati': { day: 18, month: 1, year: 1998, source: `${WIKIPEDIA}Aitana_Bonmatí` },
  'al gore': { day: 31, month: 3, year: 1948, source: `${WIKIPEDIA}Al_Gore` },
  'alex morgan': { day: 2, month: 7, year: 1989, source: `${WIKIPEDIA}Alex_Morgan` },
  'alexandria ocasio cortez': { day: 13, month: 10, year: 1989, source: `${WIKIPEDIA}Alexandria_Ocasio-Cortez` },
  'alexei navalny': { day: 4, month: 6, year: 1976, source: `${WIKIPEDIA}Alexei_Navalny` },
  'alexia putellas': { day: 4, month: 2, year: 1994, source: `${WIKIPEDIA}Alexia_Putellas` },
  'alfred hitchcock': { day: 13, month: 8, year: 1899, source: `${WIKIPEDIA}Alfred_Hitchcock` },
  'amber heard': { day: 22, month: 4, year: 1986, source: `${WIKIPEDIA}Amber_Heard` },
  'amelia earhart': { day: 24, month: 7, year: 1897, source: `${WIKIPEDIA}Amelia_Earhart` },
  'amitabh bachchan': { day: 11, month: 10, year: 1942, source: `${WIKIPEDIA}Amitabh_Bachchan` },
  'andrew yang': { day: 13, month: 1, year: 1975, source: `${WIKIPEDIA}Andrew_Yang` },
  'ang lee': { day: 23, month: 10, year: 1954, source: `${WIKIPEDIA}Ang_Lee` },
  'angela davis': { day: 26, month: 1, year: 1944, source: `${WIKIPEDIA}Angela_Davis` },
  'anita hill': { day: 30, month: 7, year: 1956, source: `${WIKIPEDIA}Anita_Hill` },
  'anthony fauci': { day: 24, month: 12, year: 1940, source: `${WIKIPEDIA}Anthony_Fauci` },
  'ariana grande': { day: 26, month: 6, year: 1993, source: `${WIKIPEDIA}Ariana_Grande` },
  'arianna huffington': { day: 15, month: 7, year: 1950, source: `${WIKIPEDIA}Arianna_Huffington` },
  'avicii': { day: 8, month: 9, year: 1989, source: `${WIKIPEDIA}Avicii` },
  'bernie sanders': { day: 8, month: 9, year: 1941, source: `${WIKIPEDIA}Bernie_Sanders` },
  'beyonce knowles carter': { day: 4, month: 9, year: 1981, source: `${WIKIPEDIA}Beyoncé` },
  'bill gates': { day: 28, month: 10, year: 1955, source: `${WIKIPEDIA}Bill_Gates` },
  'billie eilish': { day: 18, month: 12, year: 2001, source: `${WIKIPEDIA}Billie_Eilish` },
  'bong joon ho': { day: 14, month: 9, year: 1969, source: `${WIKIPEDIA}Bong_Joon-ho` },
  'boris johnson': { day: 19, month: 6, year: 1964, source: `${WIKIPEDIA}Boris_Johnson` },
  'brian chesky': { day: 29, month: 8, year: 1981, source: `${WIKIPEDIA}Brian_Chesky` },
  'brittney griner': { day: 18, month: 10, year: 1990, source: `${WIKIPEDIA}Brittney_Griner` },
  'bruno mars': { day: 8, month: 10, year: 1985, source: `${WIKIPEDIA}Bruno_Mars` },
  'buzz aldrin': { day: 20, month: 1, year: 1930, source: `${WIKIPEDIA}Buzz_Aldrin` },
  'caitlin clark': { day: 22, month: 9, year: 2002, source: `${WIKIPEDIA}Caitlin_Clark` },
  'cardi b': { day: 11, month: 10, year: 1992, source: `${WIKIPEDIA}Cardi_B` },
  'carl sagan': { day: 9, month: 11, year: 1934, source: `${WIKIPEDIA}Carl_Sagan` },
  'charles iii': { day: 14, month: 11, year: 1948, source: `${WIKIPEDIA}Charles_III` },
  'chester bennington': { day: 20, month: 3, year: 1976, source: `${WIKIPEDIA}Chester_Bennington` },
  'chimamanda ngozi adichie': { day: 15, month: 9, year: 1977, source: `${WIKIPEDIA}Chimamanda_Ngozi_Adichie` },
  'chris rock': { day: 7, month: 2, year: 1965, source: `${WIKIPEDIA}Chris_Rock` },
  'christopher nolan': { day: 30, month: 7, year: 1970, source: `${WIKIPEDIA}Christopher_Nolan` },
  'clarence thomas': { day: 23, month: 6, year: 1948, source: `${WIKIPEDIA}Clarence_Thomas` },
  'coco chanel': { day: 19, month: 8, year: 1883, source: `${WIKIPEDIA}Coco_Chanel` },
  'coco gauff': { day: 13, month: 3, year: 2004, source: `${WIKIPEDIA}Coco_Gauff` },
  'colin kaepernick': { day: 3, month: 11, year: 1987, source: `${WIKIPEDIA}Colin_Kaepernick` },
  'conor mcgregor': { day: 14, month: 7, year: 1988, source: `${WIKIPEDIA}Conor_McGregor` },
  'dave chappelle': { day: 24, month: 8, year: 1973, source: `${WIKIPEDIA}Dave_Chappelle` },
  'david attenborough': { day: 8, month: 5, year: 1926, source: `${WIKIPEDIA}David_Attenborough` },
  'david beckham': { day: 2, month: 5, year: 1975, source: `${WIKIPEDIA}David_Beckham` },
  'david cameron': { day: 9, month: 10, year: 1966, source: `${WIKIPEDIA}David_Cameron` },
  'deepika padukone': { day: 5, month: 1, year: 1986, source: `${WIKIPEDIA}Deepika_Padukone` },
  'derek chauvin': { day: 19, month: 3, year: 1976, source: `${WIKIPEDIA}Derek_Chauvin` },
  'dian fossey': { day: 16, month: 1, year: 1932, source: `${WIKIPEDIA}Dian_Fossey` },
  'drew weissman': { day: 7, month: 9, year: 1959, source: `${WIKIPEDIA}Drew_Weissman` },
  'edward snowden': { day: 21, month: 6, year: 1983, source: `${WIKIPEDIA}Edward_Snowden` },
  'elizabeth holmes': { day: 3, month: 2, year: 1984, source: `${WIKIPEDIA}Elizabeth_Holmes` },
  'elizabeth ii': { day: 21, month: 4, year: 1926, source: `${WIKIPEDIA}Elizabeth_II` },
  'elizabeth warren': { day: 22, month: 6, year: 1949, source: `${WIKIPEDIA}Elizabeth_Warren` },
  'ellen degeneres': { day: 26, month: 1, year: 1958, source: `${WIKIPEDIA}Ellen_DeGeneres` },
  'emilia clarke': { day: 23, month: 10, year: 1986, source: `${WIKIPEDIA}Emilia_Clarke` },
  'emma raducanu': { day: 13, month: 11, year: 2002, source: `${WIKIPEDIA}Emma_Raducanu` },
  'emmanuelle charpentier': { day: 11, month: 12, year: 1968, source: `${WIKIPEDIA}Emmanuelle_Charpentier` },
  'florence nightingale': { day: 12, month: 5, year: 1820, source: `${WIKIPEDIA}Florence_Nightingale` },
  'george floyd': { day: 14, month: 10, year: 1973, source: `${WIKIPEDIA}George_Floyd` },
  'george michael': { day: 25, month: 6, year: 1963, source: `${WIKIPEDIA}George_Michael` },
  'george w bush': { day: 6, month: 7, year: 1946, source: `${WIKIPEDIA}George_W._Bush` },
  'giannis antetokounmpo': { day: 6, month: 12, year: 1994, source: `${WIKIPEDIA}Giannis_Antetokounmpo` },
  'golda meir': { day: 3, month: 5, year: 1898, source: `${WIKIPEDIA}Golda_Meir` },
  'greta garbo': { day: 18, month: 9, year: 1905, source: `${WIKIPEDIA}Greta_Garbo` },
  'greta gerwig': { day: 4, month: 8, year: 1983, source: `${WIKIPEDIA}Greta_Gerwig` },
  'greta thunberg': { day: 3, month: 1, year: 2003, source: `${WIKIPEDIA}Greta_Thunberg` },
  'guillermo del toro': { day: 9, month: 10, year: 1964, source: `${WIKIPEDIA}Guillermo_del_Toro` },
  'harvey weinstein': { day: 19, month: 3, year: 1952, source: `${WIKIPEDIA}Harvey_Weinstein` },
  'helen keller': { day: 27, month: 6, year: 1880, source: `${WIKIPEDIA}Helen_Keller` },
  'j robert oppenheimer': { day: 22, month: 4, year: 1904, source: `${WIKIPEDIA}J._Robert_Oppenheimer` },
  'jack dorsey': { day: 19, month: 11, year: 1976, source: `${WIKIPEDIA}Jack_Dorsey` },
  'jair bolsonaro': { day: 21, month: 3, year: 1955, source: `${WIKIPEDIA}Jair_Bolsonaro` },
  'james cameron': { day: 16, month: 8, year: 1954, source: `${WIKIPEDIA}James_Cameron` },
  'jane goodall': { day: 3, month: 4, year: 1934, source: `${WIKIPEDIA}Jane_Goodall` },
  'jeff bezos': { day: 12, month: 1, year: 1964, source: `${WIKIPEDIA}Jeff_Bezos` },
  'jeff buckley': { day: 17, month: 11, year: 1966, source: `${WIKIPEDIA}Jeff_Buckley` },
  'jennifer doudna': { day: 19, month: 2, year: 1964, source: `${WIKIPEDIA}Jennifer_Doudna` },
  'jennifer lopez': { day: 24, month: 7, year: 1969, source: `${WIKIPEDIA}Jennifer_Lopez` },
  'jensen huang': { day: 17, month: 2, year: 1963, source: `${WIKIPEDIA}Jensen_Huang` },
  'jerry seinfeld': { day: 29, month: 4, year: 1954, source: `${WIKIPEDIA}Jerry_Seinfeld` },
  'john glenn': { day: 18, month: 7, year: 1921, source: `${WIKIPEDIA}John_Glenn` },
  'jon stewart': { day: 28, month: 11, year: 1962, source: `${WIKIPEDIA}Jon_Stewart` },
  'jonas salk': { day: 28, month: 10, year: 1914, source: `${WIKIPEDIA}Jonas_Salk` },
  'julian assange': { day: 3, month: 7, year: 1971, source: `${WIKIPEDIA}Julian_Assange` },
  'justin bieber': { day: 1, month: 3, year: 1994, source: `${WIKIPEDIA}Justin_Bieber` },
  'kamala harris': { day: 20, month: 10, year: 1964, source: `${WIKIPEDIA}Kamala_Harris` },
  'katalin kariko': { day: 17, month: 1, year: 1955, source: `${WIKIPEDIA}Katalin_Kariko` },
  'katherine johnson': { day: 26, month: 8, year: 1918, source: `${WIKIPEDIA}Katherine_Johnson` },
  'kathryn bigelow': { day: 27, month: 11, year: 1951, source: `${WIKIPEDIA}Kathryn_Bigelow` },
  'kendrick lamar': { day: 17, month: 6, year: 1987, source: `${WIKIPEDIA}Kendrick_Lamar` },
  'kim kardashian': { day: 21, month: 10, year: 1980, source: `${WIKIPEDIA}Kim_Kardashian` },
  'kit harington': { day: 26, month: 12, year: 1986, source: `${WIKIPEDIA}Kit_Harington` },
  'kobe bryant': { day: 23, month: 8, year: 1978, source: `${WIKIPEDIA}Kobe_Bryant` },
  'lady gaga': { day: 28, month: 3, year: 1986, source: `${WIKIPEDIA}Lady_Gaga` },
  'lance armstrong': { day: 18, month: 9, year: 1971, source: `${WIKIPEDIA}Lance_Armstrong` },
  'larry david': { day: 2, month: 7, year: 1947, source: `${WIKIPEDIA}Larry_David` },
  'larry ellison': { day: 17, month: 8, year: 1944, source: `${WIKIPEDIA}Larry_Ellison` },
  'larry page': { day: 26, month: 3, year: 1973, source: `${WIKIPEDIA}Larry_Page` },
  'lech walesa': { day: 29, month: 9, year: 1943, source: `${WIKIPEDIA}Lech_Wałęsa` },
  'lewis hamilton': { day: 7, month: 1, year: 1985, source: `${WIKIPEDIA}Lewis_Hamilton` },
  'lisa su': { day: 7, month: 11, year: 1969, source: `${WIKIPEDIA}Lisa_Su` },
  'liz truss': { day: 26, month: 7, year: 1975, source: `${WIKIPEDIA}Liz_Truss` },
  'mac miller': { day: 19, month: 1, year: 1992, source: `${WIKIPEDIA}Mac_Miller` },
  'mae jemison': { day: 17, month: 10, year: 1956, source: `${WIKIPEDIA}Mae_Jemison` },
  'margaret atwood': { day: 18, month: 11, year: 1939, source: `${WIKIPEDIA}Margaret_Atwood` },
  'margot robbie': { day: 2, month: 7, year: 1990, source: `${WIKIPEDIA}Margot_Robbie` },
  'maria sharapova': { day: 19, month: 4, year: 1987, source: `${WIKIPEDIA}Maria_Sharapova` },
  'marion jones': { day: 12, month: 10, year: 1975, source: `${WIKIPEDIA}Marion_Jones` },
  'mark cuban': { day: 31, month: 7, year: 1958, source: `${WIKIPEDIA}Mark_Cuban` },
  'mark hamill': { day: 25, month: 9, year: 1951, source: `${WIKIPEDIA}Mark_Hamill` },
  'mark zuckerberg': { day: 14, month: 5, year: 1984, source: `${WIKIPEDIA}Mark_Zuckerberg` },
  'marta': { day: 19, month: 2, year: 1986, source: `${WIKIPEDIA}Marta_(footballer)` },
  'martha stewart': { day: 3, month: 8, year: 1941, source: `${WIKIPEDIA}Martha_Stewart` },
  'martin scorsese': { day: 17, month: 11, year: 1942, source: `${WIKIPEDIA}Martin_Scorsese` },
  'max verstappen': { day: 30, month: 9, year: 1997, source: `${WIKIPEDIA}Max_Verstappen` },
  'megan rapinoe': { day: 5, month: 7, year: 1985, source: `${WIKIPEDIA}Megan_Rapinoe` },
  'meghan markle': { day: 4, month: 8, year: 1981, source: `${WIKIPEDIA}Meghan_Markle` },
  'melania trump': { day: 26, month: 4, year: 1970, source: `${WIKIPEDIA}Melania_Trump` },
  'melinda french gates': { day: 15, month: 8, year: 1964, source: `${WIKIPEDIA}Melinda_French_Gates` },
  'michael dell': { day: 23, month: 2, year: 1965, source: `${WIKIPEDIA}Michael_Dell` },
  'michelle obama': { day: 17, month: 1, year: 1964, source: `${WIKIPEDIA}Michelle_Obama` },
  'muhammad yunus': { day: 28, month: 6, year: 1940, source: `${WIKIPEDIA}Muhammad_Yunus` },
  'miley cyrus': { day: 23, month: 11, year: 1992, source: `${WIKIPEDIA}Miley_Cyrus` },
  'nancy pelosi': { day: 26, month: 3, year: 1940, source: `${WIKIPEDIA}Nancy_Pelosi` },
  'naomi osaka': { day: 16, month: 10, year: 1997, source: `${WIKIPEDIA}Naomi_Osaka` },
  'neil armstrong': { day: 5, month: 8, year: 1930, source: `${WIKIPEDIA}Neil_Armstrong` },
  'nipsey hussle': { day: 15, month: 8, year: 1985, source: `${WIKIPEDIA}Nipsey_Hussle` },
  'novak djokovic': { day: 22, month: 5, year: 1987, source: `${WIKIPEDIA}Novak_Djokovic` },
  'olivia rodrigo': { day: 20, month: 2, year: 2003, source: `${WIKIPEDIA}Olivia_Rodrigo` },
  'oprah winfrey': { day: 29, month: 1, year: 1954, source: `${WIKIPEDIA}Oprah_Winfrey` },
  'oscar pistorius': { day: 22, month: 11, year: 1986, source: `${WIKIPEDIA}Oscar_Pistorius` },
  'paul pogba': { day: 15, month: 3, year: 1993, source: `${WIKIPEDIA}Paul_Pogba` },
  'peter dinklage': { day: 11, month: 6, year: 1969, source: `${WIKIPEDIA}Peter_Dinklage` },
  'peter higgs': { day: 29, month: 5, year: 1929, source: `${WIKIPEDIA}Peter_Higgs` },
  'peter jackson': { day: 31, month: 10, year: 1961, source: `${WIKIPEDIA}Peter_Jackson` },
  'phil knight': { day: 24, month: 2, year: 1938, source: `${WIKIPEDIA}Phil_Knight` },
  'priyanka chopra jonas': { day: 18, month: 7, year: 1982, source: `${WIKIPEDIA}Priyanka_Chopra_Jonas` },
  'pierre omidyar': { day: 21, month: 6, year: 1967, source: `${WIKIPEDIA}Pierre_Omidyar` },
  'psy': { day: 31, month: 12, year: 1977, source: `${WIKIPEDIA}Psy` },
  'quentin tarantino': { day: 27, month: 3, year: 1963, source: `${WIKIPEDIA}Quentin_Tarantino` },
  'rachel carson': { day: 27, month: 5, year: 1907, source: `${WIKIPEDIA}Rachel_Carson` },
  'rafael nadal': { day: 3, month: 6, year: 1986, source: `${WIKIPEDIA}Rafael_Nadal` },
  'reed hastings': { day: 8, month: 10, year: 1960, source: `${WIKIPEDIA}Reed_Hastings` },
  'richard branson': { day: 18, month: 7, year: 1950, source: `${WIKIPEDIA}Richard_Branson` },
  'rishi sunak': { day: 12, month: 5, year: 1980, source: `${WIKIPEDIA}Rishi_Sunak` },
  'roger federer': { day: 8, month: 8, year: 1981, source: `${WIKIPEDIA}Roger_Federer` },
  'ronald reagan': { day: 6, month: 2, year: 1911, source: `${WIKIPEDIA}Ronald_Reagan` },
  'rosalind franklin': { day: 25, month: 7, year: 1920, source: `${WIKIPEDIA}Rosalind_Franklin` },
  'rupert murdoch': { day: 11, month: 3, year: 1931, source: `${WIKIPEDIA}Rupert_Murdoch` },
  'ruth bader ginsburg': { day: 15, month: 3, year: 1933, source: `${WIKIPEDIA}Ruth_Bader_Ginsburg` },
  'ryan gosling': { day: 12, month: 11, year: 1980, source: `${WIKIPEDIA}Ryan_Gosling` },
  'ryan murphy': { day: 30, month: 11, year: 1965, source: `${WIKIPEDIA}Ryan_Murphy` },
  'sally ride': { day: 26, month: 5, year: 1951, source: `${WIKIPEDIA}Sally_Ride` },
  'salman rushdie': { day: 19, month: 6, year: 1947, source: `${WIKIPEDIA}Salman_Rushdie` },
  'sam altman': { day: 22, month: 4, year: 1985, source: `${WIKIPEDIA}Sam_Altman` },
  'sam bankman fried': { day: 6, month: 3, year: 1992, source: `${WIKIPEDIA}Sam_Bankman-Fried` },
  'sandra day o connor': { day: 26, month: 3, year: 1930, source: `${WIKIPEDIA}Sandra_Day_O'Connor` },
  'sanna marin': { day: 16, month: 11, year: 1985, source: `${WIKIPEDIA}Sanna_Marin` },
  'satya nadella': { day: 19, month: 8, year: 1967, source: `${WIKIPEDIA}Satya_Nadella` },
  'selena quintanilla': { day: 16, month: 4, year: 1971, source: `${WIKIPEDIA}Selena` },
  'sergey brin': { day: 21, month: 8, year: 1973, source: `${WIKIPEDIA}Sergey_Brin` },
  'shah rukh khan': { day: 2, month: 11, year: 1965, source: `${WIKIPEDIA}Shah_Rukh_Khan` },
  'shaquille o neal': { day: 6, month: 3, year: 1972, source: `${WIKIPEDIA}Shaquille_O'Neal` },
  'sha carri richardson': { day: 25, month: 3, year: 2000, source: `${WIKIPEDIA}Sha'Carri_Richardson` },
  'sheryl sandberg': { day: 28, month: 8, year: 1969, source: `${WIKIPEDIA}Sheryl_Sandberg` },
  'shonda rhimes': { day: 13, month: 1, year: 1970, source: `${WIKIPEDIA}Shonda_Rhimes` },
  'stacey abrams': { day: 9, month: 12, year: 1973, source: `${WIKIPEDIA}Stacey_Abrams` },
  'stephen curry': { day: 14, month: 3, year: 1988, source: `${WIKIPEDIA}Stephen_Curry` },
  'steve irwin': { day: 22, month: 2, year: 1962, source: `${WIKIPEDIA}Steve_Irwin` },
  'steve jobs': { day: 24, month: 2, year: 1955, source: `${WIKIPEDIA}Steve_Jobs` },
  'steve wozniak': { day: 11, month: 8, year: 1950, source: `${WIKIPEDIA}Steve_Wozniak` },
  'steven spielberg': { day: 18, month: 12, year: 1946, source: `${WIKIPEDIA}Steven_Spielberg` },
  'sundar pichai': { day: 12, month: 7, year: 1972, source: `${WIKIPEDIA}Sundar_Pichai` },
  'tarana burke': { day: 12, month: 9, year: 1973, source: `${WIKIPEDIA}Tarana_Burke` },
  'tedros adhanom ghebreyesus': { day: 3, month: 3, year: 1965, source: `${WIKIPEDIA}Tedros_Adhanom_Ghebreyesus` },
  'temple grandin': { day: 29, month: 8, year: 1947, source: `${WIKIPEDIA}Temple_Grandin` },
  'the notorious big': { day: 21, month: 5, year: 1972, source: `${WIKIPEDIA}The_Notorious_B.I.G.` },
  'tim cook': { day: 1, month: 11, year: 1960, source: `${WIKIPEDIA}Tim_Cook` },
  'tina turner': { day: 26, month: 11, year: 1939, source: `${WIKIPEDIA}Tina_Turner` },
  'tony blair': { day: 6, month: 5, year: 1953, source: `${WIKIPEDIA}Tony_Blair` },
  'travis kalanick': { day: 6, month: 8, year: 1976, source: `${WIKIPEDIA}Travis_Kalanick` },
  'travis scott': { day: 30, month: 4, year: 1991, source: `${WIKIPEDIA}Travis_Scott` },
  'trevor noah': { day: 20, month: 2, year: 1984, source: `${WIKIPEDIA}Trevor_Noah` },
  'vince gilligan': { day: 10, month: 2, year: 1967, source: `${WIKIPEDIA}Vince_Gilligan` },
  'walt disney': { day: 5, month: 12, year: 1901, source: `${WIKIPEDIA}Walt_Disney` },
  'warren buffett': { day: 30, month: 8, year: 1930, source: `${WIKIPEDIA}Warren_Buffett` },
  'whitney wolfe herd': { day: 1, month: 7, year: 1989, source: `${WIKIPEDIA}Whitney_Wolfe_Herd` },
  'yasser arafat': { day: 24, month: 8, year: 1929, source: `${WIKIPEDIA}Yasser_Arafat` },
  'yitzhak rabin': { day: 1, month: 3, year: 1922, source: `${WIKIPEDIA}Yitzhak_Rabin` },
  'yuri gagarin': { day: 9, month: 3, year: 1934, source: `${WIKIPEDIA}Yuri_Gagarin` },
  'zelda fitzgerald': { day: 24, month: 7, year: 1900, source: `${WIKIPEDIA}Zelda_Fitzgerald` },
  'diana princess of wales': { day: 1, month: 7, year: 1961, source: `${WIKIPEDIA}Diana,_Princess_of_Wales` },
  'prince harry': { day: 15, month: 9, year: 1984, source: `${WIKIPEDIA}Prince_Harry` },
  'queen camilla': { day: 17, month: 7, year: 1947, source: `${WIKIPEDIA}Queen_Camilla` },
  'malcolm x': { day: 19, month: 5, year: 1925, source: `${WIKIPEDIA}Malcolm_X` },
  'heath ledger': { day: 4, month: 4, year: 1979, source: `${WIKIPEDIA}Heath_Ledger` },
  'cristiano ronaldo': { day: 5, month: 2, year: 1985, source: `${WIKIPEDIA}Cristiano_Ronaldo` },
  'lionel messi': { day: 24, month: 6, year: 1987, source: `${WIKIPEDIA}Lionel_Messi` },
  'michael jackson': { day: 29, month: 8, year: 1958, source: `${WIKIPEDIA}Michael_Jackson` },
  'chadwick boseman': { day: 29, month: 11, year: 1976, source: `${WIKIPEDIA}Chadwick_Boseman` },
  'elton john': { day: 25, month: 3, year: 1947, source: `${WIKIPEDIA}Elton_John` },
};

export function supplementalBirthDateFor(name: string): HistoricalBirthDate | null {
  return HISTORICAL_BIRTH_DATES[normaliseHistoricalPersonName(name)] ?? null;
}
