/**
 * MYSTIQUE COMPASS — Personal Month Meanings & Birth Month Numerolog
 *
 * Personal Month 1-9 verbatim meanings for the current month cycle,
 * plus birth month numerological significance (1-12).
 *
 * ALL TEXT IS VERBATIM.
 */

import { getPersonalYearAnalysis } from '@/lib/numerology/personal-year-full';

export interface PersonalMonthResult {
  personalYear: number;
  personalMonth: number;
  title: string;
  interpretation: string;
}

export interface BirthMonthResult {
  month: number;
  monthName: string;
  number: number;
  title: string;
  interpretation: string;
}

function reduceNum(n: number): number {
  let val = Math.abs(n);
  // Master-number-safe: stop reducing once an intermediate value lands on
  // 11, 22, or 33, instead of collapsing straight through it.
  while (val > 9 && val !== 11 && val !== 22 && val !== 33) {
    val = String(val).split('').reduce((a: number, d: string) => a + +d, 0);
  }
  return val;
}

const PM_MEANINGS: Record<number, { title: string; interpretation: string }> = {
  1: { title: 'Personal Month 1 — The Initiatory Gate', interpretation: `PERSONAL MONTH 1 — The Initiatory Gate\n\nA Personal Month 1 opens a nine-month mini-cycle of new beginnings. This is the month to START — new projects, new habits, new directions. The energy supports initiative, independence, and bold first steps. Hesitation is the only real obstacle; the cosmic current is flowing toward action. Plant seeds now that will grow over the coming eight months. The shadow: impulsiveness, starting too many things, neglecting existing commitments in the excitement of the new. The practice: choose ONE initiative as this month's primary focus and give it your full attention.` },
  2: { title: 'Personal Month 2 — The Relational Field', interpretation: `PERSONAL MONTH 2 — The Relational Field\n\nA Personal Month 2 slows the pace and turns attention toward partnership, patience, and emotional attunement. This is the month to CONNECT — to deepen relationships, to listen more than speak, to allow situations to unfold rather than forcing outcomes. The energy supports diplomacy, intuition, and the gentle resolution of conflicts. The shadow: passivity, over-accommodation, losing oneself in others' needs. The practice: practice receiving — let someone help you, accept a compliment without deflecting, allow yourself to be supported.` },
  3: { title: 'Personal Month 3 — Creative Bloom', interpretation: `PERSONAL MONTH 3 — Creative Bloom\n\nA Personal Month 3 opens the floodgates of creative expression and social connection. This is the month to EXPRESS — to create, communicate, socialize, and share your joy with others. The energy supports artistic work, public speaking, writing, and any form of self-expression. The shadow: scattering energy across too many social engagements, superficial communication, using busyness to avoid depth. The practice: dedicate time each day to creative expression — not for an audience, but for the pure pleasure of creation.` },
  4: { title: 'Personal Month 4 — Foundation Cycle', interpretation: `PERSONAL MONTH 4 — Foundation Cycle\n\nA Personal Month 4 brings the energy of discipline, structure, and hard work. This is the month to BUILD — to lay foundations, to organize, to do the unglamorous work that makes later success possible. The energy supports systems, routines, and sustained effort. This may feel constricting after the freedom of other months, but what is built now will support you for months to come. The shadow: rigidity, workaholism, neglect of joy and spontaneity. The practice: identify one area of life that needs structure and create a sustainable system for it.` },
  5: { title: 'Personal Month 5 — Freedom & Flux', interpretation: `PERSONAL MONTH 5 — Freedom & Flux\n\nA Personal Month 5 brings unexpected change, adventure, and the impulse toward freedom. This is the month to EXPLORE — to travel, to experiment, to break routines and discover what lies beyond the familiar. The energy supports risk-taking, adaptability, and the embrace of uncertainty. Expect the unexpected; plans may shift rapidly. The shadow: chaos, recklessness, abandoning commitments that still have value. The practice: say yes to one thing you would normally decline, and notice what happens.` },
  6: { title: 'Personal Month 6 — Heart & Hearth', interpretation: `PERSONAL MONTH 6 — Heart & Hearth\n\nA Personal Month 6 turns attention toward home, family, and matters of the heart. This is the month to NURTURE — to tend relationships, to beautify your environment, to serve those you love. The energy supports domestic harmony, caregiving, and the deepening of emotional bonds. The shadow: martyrdom, over-giving, neglecting personal needs in service of others. The practice: perform one act of service for someone without expectation of return, and receive one act of care from someone without immediately reciprocating.` },
  7: { title: 'Personal Month 7 — Spiritual Retreat', interpretation: `PERSONAL MONTH 7 — Spiritual Retreat\n\nA Personal Month 7 withdraws energy from the external world and redirects it inward. This is the month to REFLECT — to study, meditate, and seek deeper understanding. The energy supports solitude, spiritual practice, and the integration of recent experiences. Social demands may feel draining; honor the need for quiet. The shadow: isolation, intellectual arrogance, using spirituality to avoid practical responsibilities. The practice: dedicate 15 minutes daily to unstructured silence — no phone, no book, no agenda.` },
  8: { title: 'Personal Month 8 — Power & Harvest', interpretation: `PERSONAL MONTH 8 — Power & Harvest\n\nA Personal Month 8 brings the energy of material achievement, authority, and karmic return. This is the month to REAP — to collect the harvest of seeds planted in previous months, to exercise authority with integrity, to make financial decisions with clarity. The energy supports career advancement, financial planning, and the responsible exercise of power. What you have earned — both positive and negative — tends to arrive now. The shadow: greed, domination, measuring all value in material terms. The practice: review your relationship with money and power — where are you avoiding responsibility, and where are you over-identifying with material success?` },
  9: { title: 'Personal Month 9 — Great Completion', interpretation: `PERSONAL MONTH 9 — Great Completion\n\nA Personal Month 9 closes the nine-month cycle that began with Month 1. This is the month to RELEASE — to let go of what has completed its purpose, to forgive, to clear the slate for the next cycle. The energy supports endings, completions, and the emotional processing that makes genuine release possible. What you cling to now will be taken anyway; voluntary release is gentler than forced removal. The shadow: premature endings, avoidance of necessary grief, using "letting go" as an excuse to flee difficulty. The practice: identify one thing — a belief, a grudge, a possession, a commitment — that has completed its cycle, and consciously release it.` },
};

const BIRTH_MONTH_DATA: Record<number, BirthMonthResult> = {
  1: { month: 1, monthName: 'January', number: 1, title: 'The Origin Month', interpretation: `BIRTH MONTH 1 — January — The Origin Month\n\nBorn in the first month, you carry the vibration of beginnings, initiation, and the raw potential of the unformed. January's children are natural pioneers — they start things, they break ground, they are not afraid of the blank page. The number 1 confers independence, leadership capacity, and a certain solitude that is not loneliness but the necessary condition of the originator. January births often produce individuals who are comfortable being first — first to arrive, first to speak, first to act — and who may struggle with the collaborative phases that follow initiation. The winter birth adds a quality of resilience — these souls entered the world when the earth was dormant, and they carry that capacity for patient germination into all their endeavors.` },
  2: { month: 2, monthName: 'February', number: 2, title: 'The Intuitive Month', interpretation: `BIRTH MONTH 2 — February — The Intuitive Month\n\nBorn in the second month, you carry the vibration of partnership, sensitivity, and the bridge between winter's end and spring's beginning. February's children are natural diplomats — they sense the unspoken, mediate the conflicted, and create harmony through their mere presence. The number 2 confers emotional intelligence, intuitive accuracy, and a relational orientation that values connection above independence. February births often produce individuals with pronounced psychic sensitivity, perhaps because they arrived when the veil between seasons (and, some say, between worlds) is thinnest. The shadow is the loss of self in relationship; the gift is the capacity to create genuine partnership.` },
  3: { month: 3, monthName: 'March', number: 3, title: 'The Creative Month', interpretation: `BIRTH MONTH 3 — March — The Creative Month\n\nBorn in the third month, you carry the vibration of creativity, expression, and the explosive energy of spring's arrival. March's children are natural communicators — they speak, write, perform, and create with an ease that others must labor to achieve. The number 3 confers joy, optimism, and a generative quality that brings ideas into form. March births arrive as the natural world is waking, and these individuals often carry that awakening energy throughout their lives — they are the ones who rouse others from complacency, who bring color to grey situations, who remind us that life is meant to be expressed, not merely endured.` },
  4: { month: 4, monthName: 'April', number: 4, title: 'The Builder Month', interpretation: `BIRTH MONTH 4 — April — The Builder Month\n\nBorn in the fourth month, you carry the vibration of structure, discipline, and the patient work of spring's full expression. April's children are natural builders — they create systems, establish foundations, and do the methodical work upon which later achievements depend. The number 4 confers reliability, persistence, and a relationship with time that understands the value of slow, steady progress. April births, poised between the explosion of March and the flowering of May, carry a distinctive energy of TRANSITION — they are the ones who translate vision into blueprint, who take the raw inspiration of others and give it form.` },
  5: { month: 5, monthName: 'May', number: 5, title: 'The Freedom Month', interpretation: `BIRTH MONTH 5 — May — The Freedom Month\n\nBorn in the fifth month, you carry the vibration of freedom, sensuality, and the full flowering of spring. May's children are natural adventurers — they crave variety, embrace change, and resist anything that feels like confinement. The number 5 confers versatility, charisma, and a love of experience in all its sensory richness. May births arrive when the world is at its most beautiful, and these individuals often carry an expectation of beauty and pleasure throughout their lives — not as entitlement but as a kind of birthright, a memory of their first encounter with a world in full bloom. The shadow is restlessness; the gift is the capacity to find joy in change.` },
  6: { month: 6, monthName: 'June', number: 6, title: 'The Nurturing Month', interpretation: `BIRTH MONTH 6 — June — The Nurturing Month\n\nBorn in the sixth month, you carry the vibration of love, responsibility, and the summer's turn toward warmth and care. June's children are natural nurturers — they create homes, tend relationships, and provide the emotional sustenance upon which others depend. The number 6 confers a deep capacity for love, a pronounced aesthetic sense, and a responsibility toward others that is felt as privilege rather than burden. June births arrive when the year's light is at its maximum, and these individuals often carry that luminosity throughout their lives — they are the ones others turn to for warmth, for comfort, for the reassurance that someone cares.` },
  7: { month: 7, monthName: 'July', number: 7, title: 'The Mystical Month', interpretation: `BIRTH MONTH 7 — July — The Mystical Month\n\nBorn in the seventh month, you carry the vibration of spiritual depth, introspection, and the summer's invitation to inner reflection. July's children are natural seekers — they question, they study, they are not satisfied with surfaces. The number 7 confers analytical acuity, spiritual sensitivity, and a quality of depth that others may find mysterious or intimidating. July births arrive at the year's peak, and there is something of the zenith in these individuals — they see from a height that others must climb to reach. The shadow is isolation; the gift is the capacity to perceive what others overlook.` },
  8: { month: 8, monthName: 'August', number: 8, title: 'The Power Month', interpretation: `BIRTH MONTH 8 — August — The Power Month\n\nBorn in the eighth month, you carry the vibration of power, authority, and the material harvest of summer's labors. August's children are natural executives — they organize, they direct, they command resources with an instinctive understanding of how power flows. The number 8 confers ambition, financial acumen, and a karmic relationship with authority that demands its ethical exercise. August births arrive when the year is at its most powerful, and these individuals often carry that power throughout their lives — for good or ill, depending on how consciously they wield it. The shadow is corruption; the gift is the capacity to direct resources toward worthy ends.` },
  9: { month: 9, monthName: 'September', number: 9, title: 'The Wisdom Month', interpretation: `BIRTH MONTH 9 — September — The Wisdom Month\n\nBorn in the ninth month, you carry the vibration of completion, wisdom, and the harvest not just of crops but of understanding. September's children are natural humanitarians — they see the big picture, they care about causes beyond personal benefit, they possess a maturity that often exceeds their years. The number 9 confers compassion, artistic sensitivity, and a relationship with endings that, properly understood, is the foundation of all genuine wisdom. September births arrive as the year begins its turn toward autumn, and these individuals carry that liminal quality — they are comfortable with transitions, with completions, with the melancholy beauty of things that are ending because they know that every ending presages a beginning.` },
  10: { month: 10, monthName: 'October', number: 1, title: 'The Cycle Month', interpretation: `BIRTH MONTH 10 — October — The Cycle Month\n\nBorn in the tenth month, you carry the vibration of the 1 filtered through the 0 — independence emerging from the void, initiative tempered by the wisdom of the wheel. October's children possess the 1's leadership and originality, but with a depth that the pure 1 does not access. There is something of the autumnal mystery in these individuals — they understand cycles, they sense the turning of seasons (literal and metaphorical), and they carry a certain gravitas that belies the 1's typical brightness. The 0 behind the 1 gives them access to renewal that others lack — they can begin again, and again, without bitterness.` },
  11: { month: 11, monthName: 'November', number: 11, title: 'The Master Month', interpretation: `BIRTH MONTH 11 — November — The Master Month\n\nBorn in the eleventh month, you carry the Master Number 11 vibration — the most intuitive of all numbers, the number of the spiritual messenger. November's children possess a nervous system tuned to a higher frequency. They perceive what others miss, feel what others suppress, and know what others must study. There is something of the late autumn in these souls — a quality of having witnessed the full cycle, of carrying the memory of summer's brightness and winter's darkness simultaneously. The 11 confers inspiration, vision, and sensitivity — gifts that require grounding to be sustainable.` },
  12: { month: 12, monthName: 'December', number: 3, title: 'The Completion Month', interpretation: `BIRTH MONTH 12 — December — The Completion Month\n\nBorn in the twelfth month, you carry the 3 vibration (1+2=3) through the portal of completion and return. December's children are natural communicators and creators, but with a depth that the pure 3 does not access. The 1 (self) and 2 (other) combine to produce a 3 (expression) that has cycled through the full calendar and emerged with something to say. December births arrive in the darkest time of the year, and there is something of that darkness in these individuals — not as gloom but as the fertile void from which new light is born. They are the ones who bring warmth to winter, who remind us that the light returns.` },
};

export function getPersonalMonth(birthDay: number, birthMonth: number): PersonalMonthResult {
  // Reuse the shared, corrected Personal Year calculation (unreduced compound
  // total, THEN reduced) rather than re-deriving it here with the old
  // pre-reduce-each-component formula — keeps this in sync with the
  // Personal Year section instead of silently drifting from it.
  const py = getPersonalYearAnalysis(birthDay, birthMonth).year;
  const pm = reduceNum(py + (new Date().getMonth() + 1));
  return { personalYear: py, personalMonth: pm, ...(PM_MEANINGS[pm] || { title: `Personal Month ${pm}`, interpretation: `Personal Month ${pm} carries its own unique energy within the Personal Year ${py} cycle.` }) };
}

export function getBirthMonthAnalysis(month: number): BirthMonthResult {
  return BIRTH_MONTH_DATA[month] || { month, monthName: `Month ${month}`, number: reduceNum(month), title: `Birth Month ${month}`, interpretation: `The ${month}${['','st','nd','rd','th','th','th','th','th','th','th','th','th'][month] || 'th'} month of the year carries its own numerological vibration, coloring the life path with the qualities of its number.` };
}